package org.cangnova.cangjie.cfir.analysis.tests.CfirAnalysisLLTTest.llt.function

import com.intellij.testFramework.TestDataPath
import org.cangnova.cangjie.ObsoleteTestInfrastructure
import org.cangnova.cangjie.cfir.analysis.tests.runners.AbstractCfirLightTreeLlTDiagnosticsTest
import org.cangnova.cangjie.test.TestMetadata
import org.junit.jupiter.api.Test
import java.io.File
import org.cangnova.cangjie.cfir.analysis.tests.assertAllFilesPresentByMetadata

/** AUTO-GENERATED by TestGeneratorForCfirAnalysisTests. DO NOT EDIT MANUALLY. */
@TestMetadata("cfir/analysis-tests/testData/llt/function")
@TestDataPath("${'$'}PROJECT_ROOT")
@OptIn(ObsoleteTestInfrastructure::class)
@ObsoleteTestInfrastructure
class FunctionGenerated : AbstractCfirLightTreeLlTDiagnosticsTest() {
    @Test
    fun testAllFilesPresent() {
        assertAllFilesPresentByMetadata(this, "cfir/analysis-tests/testData/llt/function")
    }

    @TestMetadata("abstract_named_00.cj")
    @Test
    fun testAbstractNamed00() {
        runTest("cfir/analysis-tests/testData/llt/function/abstract_named_00.cj")
    }

    @TestMetadata("composition_00.cj")
    @Test
    fun testComposition00() {
        runTest("cfir/analysis-tests/testData/llt/function/composition_00.cj")
    }

    @TestMetadata("defaultParameter1.cj")
    @Test
    fun testDefaultParameter1() {
        runTest("cfir/analysis-tests/testData/llt/function/defaultParameter1.cj")
    }

    @TestMetadata("defaultParameter2.cj")
    @Test
    fun testDefaultParameter2() {
        runTest("cfir/analysis-tests/testData/llt/function/defaultParameter2.cj")
    }

    @TestMetadata("defaultParameter3.cj")
    @Test
    fun testDefaultParameter3() {
        runTest("cfir/analysis-tests/testData/llt/function/defaultParameter3.cj")
    }

    @TestMetadata("defaultParameter4_0.cj")
    @Test
    fun testDefaultParameter40() {
        runTest("cfir/analysis-tests/testData/llt/function/defaultParameter4_0.cj")
    }

    @TestMetadata("defaultParameter4_1.cj")
    @Test
    fun testDefaultParameter41() {
        runTest("cfir/analysis-tests/testData/llt/function/defaultParameter4_1.cj")
    }

    @TestMetadata("defaultParameter4_2.cj")
    @Test
    fun testDefaultParameter42() {
        runTest("cfir/analysis-tests/testData/llt/function/defaultParameter4_2.cj")
    }

    @TestMetadata("defaultParameter4_3.cj")
    @Test
    fun testDefaultParameter43() {
        runTest("cfir/analysis-tests/testData/llt/function/defaultParameter4_3.cj")
    }

    @TestMetadata("defaultParameter4_4.cj")
    @Test
    fun testDefaultParameter44() {
        runTest("cfir/analysis-tests/testData/llt/function/defaultParameter4_4.cj")
    }

    @TestMetadata("defaultParameter4_5.cj")
    @Test
    fun testDefaultParameter45() {
        runTest("cfir/analysis-tests/testData/llt/function/defaultParameter4_5.cj")
    }

    @TestMetadata("defaultParameter5.cj")
    @Test
    fun testDefaultParameter5() {
        runTest("cfir/analysis-tests/testData/llt/function/defaultParameter5.cj")
    }

    @TestMetadata("defaultParameter6.cj")
    @Test
    fun testDefaultParameter6() {
        runTest("cfir/analysis-tests/testData/llt/function/defaultParameter6.cj")
    }

    @TestMetadata("defaultParameter7.cj")
    @Test
    fun testDefaultParameter7() {
        runTest("cfir/analysis-tests/testData/llt/function/defaultParameter7.cj")
    }

    @TestMetadata("defaultParamter.cj")
    @Test
    fun testDefaultParamter() {
        runTest("cfir/analysis-tests/testData/llt/function/defaultParamter.cj")
    }

    @TestMetadata("defaultParamterGeneric.cj")
    @Test
    fun testDefaultParamterGeneric() {
        runTest("cfir/analysis-tests/testData/llt/function/defaultParamterGeneric.cj")
    }

    @TestMetadata("default_param_generic_desugar.cj")
    @Test
    fun testDefaultParamGenericDesugar() {
        runTest("cfir/analysis-tests/testData/llt/function/default_param_generic_desugar.cj")
    }

    @TestMetadata("depth_call.cj")
    @Test
    fun testDepthCall() {
        runTest("cfir/analysis-tests/testData/llt/function/depth_call.cj")
    }

    @TestMetadata("err_default_param.cj")
    @Test
    fun testErrDefaultParam() {
        runTest("cfir/analysis-tests/testData/llt/function/err_default_param.cj")
    }

    @TestMetadata("funcDecl2.cj")
    @Test
    fun testFuncDecl2() {
        runTest("cfir/analysis-tests/testData/llt/function/funcDecl2.cj")
    }

    @TestMetadata("funcDecl3.cj")
    @Test
    fun testFuncDecl3() {
        runTest("cfir/analysis-tests/testData/llt/function/funcDecl3.cj")
    }

    @TestMetadata("funcDecl4.cj")
    @Test
    fun testFuncDecl4() {
        runTest("cfir/analysis-tests/testData/llt/function/funcDecl4.cj")
    }

    @TestMetadata("func_assign_var.cj")
    @Test
    fun testFuncAssignVar() {
        runTest("cfir/analysis-tests/testData/llt/function/func_assign_var.cj")
    }

    @TestMetadata("func_assign_var_02.cj")
    @Test
    fun testFuncAssignVar02() {
        runTest("cfir/analysis-tests/testData/llt/function/func_assign_var_02.cj")
    }

    @TestMetadata("func_param_error.cj")
    @Test
    fun testFuncParamError() {
        runTest("cfir/analysis-tests/testData/llt/function/func_param_error.cj")
    }

    @TestMetadata("func_param_match.cj")
    @Test
    fun testFuncParamMatch() {
        runTest("cfir/analysis-tests/testData/llt/function/func_param_match.cj")
    }

    @TestMetadata("function_access.cj")
    @Test
    fun testFunctionAccess() {
        runTest("cfir/analysis-tests/testData/llt/function/function_access.cj")
    }

    @TestMetadata("function_capture1.cj")
    @Test
    fun testFunctionCapture1() {
        runTest("cfir/analysis-tests/testData/llt/function/function_capture1.cj")
    }

    @TestMetadata("function_capture2.cj")
    @Test
    fun testFunctionCapture2() {
        runTest("cfir/analysis-tests/testData/llt/function/function_capture2.cj")
    }

    @TestMetadata("function_capture3.cj")
    @Test
    fun testFunctionCapture3() {
        runTest("cfir/analysis-tests/testData/llt/function/function_capture3.cj")
    }

    @TestMetadata("function_shadow_01.cj")
    @Test
    fun testFunctionShadow01() {
        runTest("cfir/analysis-tests/testData/llt/function/function_shadow_01.cj")
    }

    @TestMetadata("function_shadow_02.cj")
    @Test
    fun testFunctionShadow02() {
        runTest("cfir/analysis-tests/testData/llt/function/function_shadow_02.cj")
    }

    @TestMetadata("generci_class.cj")
    @Test
    fun testGenerciClass() {
        runTest("cfir/analysis-tests/testData/llt/function/generci_class.cj")
    }

    @TestMetadata("generci_defval.cj")
    @Test
    fun testGenerciDefval() {
        runTest("cfir/analysis-tests/testData/llt/function/generci_defval.cj")
    }

    @TestMetadata("insertUnit.cj")
    @Test
    fun testInsertUnit() {
        runTest("cfir/analysis-tests/testData/llt/function/insertUnit.cj")
    }

    @TestMetadata("interface_def_val.cj")
    @Test
    fun testInterfaceDefVal() {
        runTest("cfir/analysis-tests/testData/llt/function/interface_def_val.cj")
    }

    @TestMetadata("internal_type_func_return_01.cj")
    @Test
    fun testInternalTypeFuncReturn01() {
        runTest("cfir/analysis-tests/testData/llt/function/internal_type_func_return_01.cj")
    }

    @TestMetadata("member_func_overload_0.cj")
    @Test
    fun testMemberFuncOverload0() {
        runTest("cfir/analysis-tests/testData/llt/function/member_func_overload_0.cj")
    }

    @TestMetadata("member_func_overload_1.cj")
    @Test
    fun testMemberFuncOverload1() {
        runTest("cfir/analysis-tests/testData/llt/function/member_func_overload_1.cj")
    }

    @TestMetadata("member_func_overload_2.cj")
    @Test
    fun testMemberFuncOverload2() {
        runTest("cfir/analysis-tests/testData/llt/function/member_func_overload_2.cj")
    }

    @TestMetadata("mut_err_op.cj")
    @Test
    fun testMutErrOp() {
        runTest("cfir/analysis-tests/testData/llt/function/mut_err_op.cj")
    }

    @TestMetadata("mut_err_paren.cj")
    @Test
    fun testMutErrParen() {
        runTest("cfir/analysis-tests/testData/llt/function/mut_err_paren.cj")
    }

    @TestMetadata("mut_err_ret_struct.cj")
    @Test
    fun testMutErrRetStruct() {
        runTest("cfir/analysis-tests/testData/llt/function/mut_err_ret_struct.cj")
    }

    @TestMetadata("mut_function_00.cj")
    @Test
    fun testMutFunction00() {
        runTest("cfir/analysis-tests/testData/llt/function/mut_function_00.cj")
    }

    @TestMetadata("mut_function_01.cj")
    @Test
    fun testMutFunction01() {
        runTest("cfir/analysis-tests/testData/llt/function/mut_function_01.cj")
    }

    @TestMetadata("mut_function_02.cj")
    @Test
    fun testMutFunction02() {
        runTest("cfir/analysis-tests/testData/llt/function/mut_function_02.cj")
    }

    @TestMetadata("mut_function_03.cj")
    @Test
    fun testMutFunction03() {
        runTest("cfir/analysis-tests/testData/llt/function/mut_function_03.cj")
    }

    @TestMetadata("mut_function_04.cj")
    @Test
    fun testMutFunction04() {
        runTest("cfir/analysis-tests/testData/llt/function/mut_function_04.cj")
    }

    @TestMetadata("mut_function_05.cj")
    @Test
    fun testMutFunction05() {
        runTest("cfir/analysis-tests/testData/llt/function/mut_function_05.cj")
    }

    @TestMetadata("mut_function_06.cj")
    @Test
    fun testMutFunction06() {
        runTest("cfir/analysis-tests/testData/llt/function/mut_function_06.cj")
    }

    @TestMetadata("mut_function_07.cj")
    @Test
    fun testMutFunction07() {
        runTest("cfir/analysis-tests/testData/llt/function/mut_function_07.cj")
    }

    @TestMetadata("mut_function_08.cj")
    @Test
    fun testMutFunction08() {
        runTest("cfir/analysis-tests/testData/llt/function/mut_function_08.cj")
    }

    @TestMetadata("mut_function_09.cj")
    @Test
    fun testMutFunction09() {
        runTest("cfir/analysis-tests/testData/llt/function/mut_function_09.cj")
    }

    @TestMetadata("mut_function_10.cj")
    @Test
    fun testMutFunction10() {
        runTest("cfir/analysis-tests/testData/llt/function/mut_function_10.cj")
    }

    @TestMetadata("mut_function_11.cj")
    @Test
    fun testMutFunction11() {
        runTest("cfir/analysis-tests/testData/llt/function/mut_function_11.cj")
    }

    @TestMetadata("mut_function_12.cj")
    @Test
    fun testMutFunction12() {
        runTest("cfir/analysis-tests/testData/llt/function/mut_function_12.cj")
    }

    @TestMetadata("mut_ret_class.cj")
    @Test
    fun testMutRetClass() {
        runTest("cfir/analysis-tests/testData/llt/function/mut_ret_class.cj")
    }

    @TestMetadata("nest_function_call.cj")
    @Test
    fun testNestFunctionCall() {
        runTest("cfir/analysis-tests/testData/llt/function/nest_function_call.cj")
    }

    @TestMetadata("nest_function_use_01.cj")
    @Test
    fun testNestFunctionUse01() {
        runTest("cfir/analysis-tests/testData/llt/function/nest_function_use_01.cj")
    }

    @TestMetadata("nest_function_use_02.cj")
    @Test
    fun testNestFunctionUse02() {
        runTest("cfir/analysis-tests/testData/llt/function/nest_function_use_02.cj")
    }

    @TestMetadata("nest_function_use_03.cj")
    @Test
    fun testNestFunctionUse03() {
        runTest("cfir/analysis-tests/testData/llt/function/nest_function_use_03.cj")
    }

    @TestMetadata("nest_function_use_04.cj")
    @Test
    fun testNestFunctionUse04() {
        runTest("cfir/analysis-tests/testData/llt/function/nest_function_use_04.cj")
    }

    @TestMetadata("nest_function_use_05.cj")
    @Test
    fun testNestFunctionUse05() {
        runTest("cfir/analysis-tests/testData/llt/function/nest_function_use_05.cj")
    }

    @TestMetadata("nest_function_use_06.cj")
    @Test
    fun testNestFunctionUse06() {
        runTest("cfir/analysis-tests/testData/llt/function/nest_function_use_06.cj")
    }

    @TestMetadata("nest_function_use_07.cj")
    @Test
    fun testNestFunctionUse07() {
        runTest("cfir/analysis-tests/testData/llt/function/nest_function_use_07.cj")
    }

    @TestMetadata("nest_function_use_08.cj")
    @Test
    fun testNestFunctionUse08() {
        runTest("cfir/analysis-tests/testData/llt/function/nest_function_use_08.cj")
    }

    @TestMetadata("nest_function_use_09.cj")
    @Test
    fun testNestFunctionUse09() {
        runTest("cfir/analysis-tests/testData/llt/function/nest_function_use_09.cj")
    }

    @TestMetadata("nestedDefaultParameter1.cj")
    @Test
    fun testNestedDefaultParameter1() {
        runTest("cfir/analysis-tests/testData/llt/function/nestedDefaultParameter1.cj")
    }

    @TestMetadata("nestedDefaultParameter2.cj")
    @Test
    fun testNestedDefaultParameter2() {
        runTest("cfir/analysis-tests/testData/llt/function/nestedDefaultParameter2.cj")
    }

    @TestMetadata("nestedDefaultParameter2_1.cj")
    @Test
    fun testNestedDefaultParameter21() {
        runTest("cfir/analysis-tests/testData/llt/function/nestedDefaultParameter2_1.cj")
    }

    @TestMetadata("nestedDefaultParameter3.cj")
    @Test
    fun testNestedDefaultParameter3() {
        runTest("cfir/analysis-tests/testData/llt/function/nestedDefaultParameter3.cj")
    }

    @TestMetadata("nestedDefaultParameter4.cj")
    @Test
    fun testNestedDefaultParameter4() {
        runTest("cfir/analysis-tests/testData/llt/function/nestedDefaultParameter4.cj")
    }

    @TestMetadata("no_insert_unit_00.cj")
    @Test
    fun testNoInsertUnit00() {
        runTest("cfir/analysis-tests/testData/llt/function/no_insert_unit_00.cj")
    }

    @TestMetadata("no_insert_unit_01.cj")
    @Test
    fun testNoInsertUnit01() {
        runTest("cfir/analysis-tests/testData/llt/function/no_insert_unit_01.cj")
    }

    @TestMetadata("ok_overload_00.cj")
    @Test
    fun testOkOverload00() {
        runTest("cfir/analysis-tests/testData/llt/function/ok_overload_00.cj")
    }

    @TestMetadata("overloaded_func_01.cj")
    @Test
    fun testOverloadedFunc01() {
        runTest("cfir/analysis-tests/testData/llt/function/overloaded_func_01.cj")
    }

    @TestMetadata("overloaded_func_alone1.cj")
    @Test
    fun testOverloadedFuncAlone1() {
        runTest("cfir/analysis-tests/testData/llt/function/overloaded_func_alone1.cj")
    }

    @TestMetadata("overloaded_func_alone2.cj")
    @Test
    fun testOverloadedFuncAlone2() {
        runTest("cfir/analysis-tests/testData/llt/function/overloaded_func_alone2.cj")
    }

    @TestMetadata("overloaded_func_alone3.cj")
    @Test
    fun testOverloadedFuncAlone3() {
        runTest("cfir/analysis-tests/testData/llt/function/overloaded_func_alone3.cj")
    }

    @TestMetadata("overloaded_int_literal_00.cj")
    @Test
    fun testOverloadedIntLiteral00() {
        runTest("cfir/analysis-tests/testData/llt/function/overloaded_int_literal_00.cj")
    }

    @TestMetadata("override_named_00.cj")
    @Test
    fun testOverrideNamed00() {
        runTest("cfir/analysis-tests/testData/llt/function/override_named_00.cj")
    }

    @TestMetadata("override_named_01.cj")
    @Test
    fun testOverrideNamed01() {
        runTest("cfir/analysis-tests/testData/llt/function/override_named_01.cj")
    }

    @TestMetadata("override_named_02.cj")
    @Test
    fun testOverrideNamed02() {
        runTest("cfir/analysis-tests/testData/llt/function/override_named_02.cj")
    }

    @TestMetadata("override_named_03.cj")
    @Test
    fun testOverrideNamed03() {
        runTest("cfir/analysis-tests/testData/llt/function/override_named_03.cj")
    }

    @TestMetadata("raw_init_main.cj")
    @Test
    fun testRawInitMain() {
        runTest("cfir/analysis-tests/testData/llt/function/raw_init_main.cj")
    }

    @TestMetadata("raw_init_main02.cj")
    @Test
    fun testRawInitMain02() {
        runTest("cfir/analysis-tests/testData/llt/function/raw_init_main02.cj")
    }

    @TestMetadata("raw_init_main03.cj")
    @Test
    fun testRawInitMain03() {
        runTest("cfir/analysis-tests/testData/llt/function/raw_init_main03.cj")
    }

    @TestMetadata("raw_init_main04.cj")
    @Test
    fun testRawInitMain04() {
        runTest("cfir/analysis-tests/testData/llt/function/raw_init_main04.cj")
    }

    @TestMetadata("recursive_ctor_00.cj")
    @Test
    fun testRecursiveCtor00() {
        runTest("cfir/analysis-tests/testData/llt/function/recursive_ctor_00.cj")
    }

    @TestMetadata("recursive_ctor_01.cj")
    @Test
    fun testRecursiveCtor01() {
        runTest("cfir/analysis-tests/testData/llt/function/recursive_ctor_01.cj")
    }

    @TestMetadata("recursive_ctor_02.cj")
    @Test
    fun testRecursiveCtor02() {
        runTest("cfir/analysis-tests/testData/llt/function/recursive_ctor_02.cj")
    }

    @TestMetadata("recursive_ctor_03.cj")
    @Test
    fun testRecursiveCtor03() {
        runTest("cfir/analysis-tests/testData/llt/function/recursive_ctor_03.cj")
    }

    @TestMetadata("recursive_ctor_04.cj")
    @Test
    fun testRecursiveCtor04() {
        runTest("cfir/analysis-tests/testData/llt/function/recursive_ctor_04.cj")
    }

    @TestMetadata("recursive_ctor_05.cj")
    @Test
    fun testRecursiveCtor05() {
        runTest("cfir/analysis-tests/testData/llt/function/recursive_ctor_05.cj")
    }

    @TestMetadata("recursive_ctor_06.cj")
    @Test
    fun testRecursiveCtor06() {
        runTest("cfir/analysis-tests/testData/llt/function/recursive_ctor_06.cj")
    }

    @TestMetadata("recursive_ctor_07.cj")
    @Test
    fun testRecursiveCtor07() {
        runTest("cfir/analysis-tests/testData/llt/function/recursive_ctor_07.cj")
    }

    @TestMetadata("recursive_ctor_08.cj")
    @Test
    fun testRecursiveCtor08() {
        runTest("cfir/analysis-tests/testData/llt/function/recursive_ctor_08.cj")
    }

    @TestMetadata("throwable_00.cj")
    @Test
    fun testThrowable00() {
        runTest("cfir/analysis-tests/testData/llt/function/throwable_00.cj")
    }

    @TestMetadata("try_with_resource.cj")
    @Test
    fun testTryWithResource() {
        runTest("cfir/analysis-tests/testData/llt/function/try_with_resource.cj")
    }

    @TestMetadata("unsafe_func_can_only_be_called.cj")
    @Test
    fun testUnsafeFuncCanOnlyBeCalled() {
        runTest("cfir/analysis-tests/testData/llt/function/unsafe_func_can_only_be_called.cj")
    }
}

