package org.cangnova.cangjie.cfir.analysis.tests.CfirAnalysisLLTTest.llt.Extend.overload

import com.intellij.testFramework.TestDataPath
import org.cangnova.cangjie.ObsoleteTestInfrastructure
import org.cangnova.cangjie.cfir.analysis.tests.runners.AbstractCfirLightTreeLlTDiagnosticsTest
import org.cangnova.cangjie.test.TestMetadata
import org.junit.jupiter.api.Test
import java.io.File
import org.cangnova.cangjie.cfir.analysis.tests.assertAllFilesPresentByMetadata

/** AUTO-GENERATED by TestGeneratorForCfirAnalysisTests. DO NOT EDIT MANUALLY. */
@TestMetadata("cfir/analysis-tests/testData/llt/Extend/overload")
@TestDataPath("${'$'}PROJECT_ROOT")
@OptIn(ObsoleteTestInfrastructure::class)
@ObsoleteTestInfrastructure
class OverloadGenerated : AbstractCfirLightTreeLlTDiagnosticsTest() {
    @Test
    fun testAllFilesPresent() {
        assertAllFilesPresentByMetadata(this, "cfir/analysis-tests/testData/llt/Extend/overload")
    }

    @TestMetadata("overload_with_extended_type.cj")
    @Test
    fun testOverloadWithExtendedType() {
        runTest("cfir/analysis-tests/testData/llt/Extend/overload/overload_with_extended_type.cj")
    }

    @TestMetadata("private_visible01.cj")
    @Test
    fun testPrivateVisible01() {
        runTest("cfir/analysis-tests/testData/llt/Extend/overload/private_visible01.cj")
    }

    @TestMetadata("private_visible02.cj")
    @Test
    fun testPrivateVisible02() {
        runTest("cfir/analysis-tests/testData/llt/Extend/overload/private_visible02.cj")
    }

    @TestMetadata("subtype_overload_with_extended_type.cj")
    @Test
    fun testSubtypeOverloadWithExtendedType() {
        runTest("cfir/analysis-tests/testData/llt/Extend/overload/subtype_overload_with_extended_type.cj")
    }
}

