package org.cangnova.cangjie.cfir.analysis.tests.CfirAnalysisLLTPsiTest.llt.range

import com.intellij.testFramework.TestDataPath
import org.cangnova.cangjie.ObsoleteTestInfrastructure
import org.cangnova.cangjie.cfir.analysis.tests.runners.AbstractCfirPsiLlTDiagnosticsTest
import org.cangnova.cangjie.test.TestMetadata
import org.junit.jupiter.api.Test
import java.io.File
import org.cangnova.cangjie.cfir.analysis.tests.assertAllFilesPresentByMetadata

/** AUTO-GENERATED by TestGeneratorForCfirAnalysisTests. DO NOT EDIT MANUALLY. */
@TestMetadata("cfir/analysis-tests/testData/llt/range")
@TestDataPath("${'$'}PROJECT_ROOT")
@OptIn(ObsoleteTestInfrastructure::class)
@ObsoleteTestInfrastructure
class RangeGenerated : AbstractCfirPsiLlTDiagnosticsTest() {
    @Test
    fun testAllFilesPresent() {
        assertAllFilesPresentByMetadata(this, "cfir/analysis-tests/testData/llt/range")
    }

    @TestMetadata("range2.cj")
    @Test
    fun testRange2() {
        runTest("cfir/analysis-tests/testData/llt/range/range2.cj")
    }

    @TestMetadata("range4.cj")
    @Test
    fun testRange4() {
        runTest("cfir/analysis-tests/testData/llt/range/range4.cj")
    }

    @TestMetadata("range5.cj")
    @Test
    fun testRange5() {
        runTest("cfir/analysis-tests/testData/llt/range/range5.cj")
    }

    @TestMetadata("range7.cj")
    @Test
    fun testRange7() {
        runTest("cfir/analysis-tests/testData/llt/range/range7.cj")
    }

    @TestMetadata("range8.cj")
    @Test
    fun testRange8() {
        runTest("cfir/analysis-tests/testData/llt/range/range8.cj")
    }

    @TestMetadata("range_001.cj")
    @Test
    fun testRange001() {
        runTest("cfir/analysis-tests/testData/llt/range/range_001.cj")
    }

    @TestMetadata("range_big_int_001.cj")
    @Test
    fun testRangeBigInt001() {
        runTest("cfir/analysis-tests/testData/llt/range/range_big_int_001.cj")
    }

    @TestMetadata("range_class_02.cj")
    @Test
    fun testRangeClass02() {
        runTest("cfir/analysis-tests/testData/llt/range/range_class_02.cj")
    }

    @TestMetadata("range_class_03.cj")
    @Test
    fun testRangeClass03() {
        runTest("cfir/analysis-tests/testData/llt/range/range_class_03.cj")
    }

    @TestMetadata("range_record_001.cj")
    @Test
    fun testRangeRecord001() {
        runTest("cfir/analysis-tests/testData/llt/range/range_record_001.cj")
    }
}

