package org.cangnova.cangjie.cfir.analysis.tests.CfirAnalysisLLTPsiTest.llt.redefinition

import com.intellij.testFramework.TestDataPath
import org.cangnova.cangjie.ObsoleteTestInfrastructure
import org.cangnova.cangjie.cfir.analysis.tests.runners.AbstractCfirPsiLlTDiagnosticsTest
import org.cangnova.cangjie.test.TestMetadata
import org.junit.jupiter.api.Test
import java.io.File
import org.cangnova.cangjie.cfir.analysis.tests.assertAllFilesPresentByMetadata

/** AUTO-GENERATED by TestGeneratorForCfirAnalysisTests. DO NOT EDIT MANUALLY. */
@TestMetadata("cfir/analysis-tests/testData/llt/redefinition")
@TestDataPath("${'$'}PROJECT_ROOT")
@OptIn(ObsoleteTestInfrastructure::class)
@ObsoleteTestInfrastructure
class RedefinitionGenerated : AbstractCfirPsiLlTDiagnosticsTest() {
    @Test
    fun testAllFilesPresent() {
        assertAllFilesPresentByMetadata(this, "cfir/analysis-tests/testData/llt/redefinition")
    }

    @TestMetadata("for_in_00.cj")
    @Test
    fun testForIn00() {
        runTest("cfir/analysis-tests/testData/llt/redefinition/for_in_00.cj")
    }

    @TestMetadata("func_00.cj")
    @Test
    fun testFunc00() {
        runTest("cfir/analysis-tests/testData/llt/redefinition/func_00.cj")
    }

    @TestMetadata("redefinition1.cj")
    @Test
    fun testRedefinition1() {
        runTest("cfir/analysis-tests/testData/llt/redefinition/redefinition1.cj")
    }

    @TestMetadata("redefinition2.cj")
    @Test
    fun testRedefinition2() {
        runTest("cfir/analysis-tests/testData/llt/redefinition/redefinition2.cj")
    }
}

