package org.cangnova.cangjie.cfir.analysis.tests.CfirAnalysisDiagnostics2PsiTest.diagnostics2.interop

import com.intellij.testFramework.TestDataPath
import org.cangnova.cangjie.ObsoleteTestInfrastructure
import org.cangnova.cangjie.cfir.analysis.tests.runners.AbstractCfirPsiDiagnosticTest
import org.cangnova.cangjie.test.TestMetadata
import org.junit.jupiter.api.Test
import java.io.File
import org.cangnova.cangjie.cfir.analysis.tests.assertAllFilesPresentByMetadata

/** AUTO-GENERATED by TestGeneratorForCfirAnalysisTests. DO NOT EDIT MANUALLY. */
@TestMetadata("cfir/analysis-tests/testData/diagnostics2/interop")
@TestDataPath("${'$'}PROJECT_ROOT")
@OptIn(ObsoleteTestInfrastructure::class)
@ObsoleteTestInfrastructure
class InteropGenerated : AbstractCfirPsiDiagnosticTest() {
    @Test
    fun testAllFilesPresent() {
        assertAllFilesPresentByMetadata(this, "cfir/analysis-tests/testData/diagnostics2/interop")
    }

    @TestMetadata("foreignFunctionCFuncLegalityPlaceholder.cj")
    @Test
    fun testForeignFunctionCFuncLegalityPlaceholder() {
        runTest("cfir/analysis-tests/testData/diagnostics2/interop/foreignFunctionCFuncLegalityPlaceholder.cj")
    }

    @TestMetadata("foreignFunctionMixedSignatureLegality.cj")
    @Test
    fun testForeignFunctionMixedSignatureLegality() {
        runTest("cfir/analysis-tests/testData/diagnostics2/interop/foreignFunctionMixedSignatureLegality.cj")
    }

    @TestMetadata("foreignFunctionParameterTypePlaceholder.cj")
    @Test
    fun testForeignFunctionParameterTypePlaceholder() {
        runTest("cfir/analysis-tests/testData/diagnostics2/interop/foreignFunctionParameterTypePlaceholder.cj")
    }

    @TestMetadata("foreignFunctionReturnType.cj")
    @Test
    fun testForeignFunctionReturnType() {
        runTest("cfir/analysis-tests/testData/diagnostics2/interop/foreignFunctionReturnType.cj")
    }

    @TestMetadata("foreignFunctionTypeAliasExpansion.cj")
    @Test
    fun testForeignFunctionTypeAliasExpansion() {
        runTest("cfir/analysis-tests/testData/diagnostics2/interop/foreignFunctionTypeAliasExpansion.cj")
    }
}

