<!sema_missing_entry!>/<!>/ Copyright (c) Huawei Technologies Co., Ltd. 2025. All rights reserved.
// This source file is part of the Cangjie project, licensed under Apache-2.0
// with Runtime Library Exception.
//
// See https://cangjie-lang.cn/pages/LICENSE for license information.


extend <!sema_undeclared_type_name!>B<!> {
    public func foo() {
        return this;
    }
}

extend <!sema_undeclared_type_name!>A<!> {
    public func foo() {
        return this;
    }
}
