package org.cangnova.cangjie.cfir.lightTree

import java.io.File

/**
 * 生成 LightTree2Cfir 测试套件（对齐 TestGeneratorForPsi2Cfir 风格）。
 *
 * 扫描 psi2cfir/testData/rawBuilder 目录，为每个 .cj 文件生成一个测试方法，
 * 通过 LightTree 路径构建 CFIR 并与 .txt Golden 文件对比。
 */
object TestGeneratorForLightTree2Cfir {
    @JvmStatic
    fun main(args: Array<String>) {
        val projectRoot = if (args.isNotEmpty()) File(args[0]) else File(System.getProperty("user.dir"))

        // Golden 文件测试：LightTree → CFIR → 与 .txt 对比
        generateSuite(
            projectRoot = projectRoot,
            modelRelativePath = "cfir/raw-cfir/psi2cfir/testData/rawBuilder",
            generatedClassName = "LightTree2CfirConverterTestGenerated",
            baseClassName = "AbstractLightTree2CfirConverterTestCase",
            outputRelativePath = "cfir/raw-cfir/light-tree2cfir/tests-gen/org/cangnova/cangjie/cfir/lightTree",
            packageName = "org.cangnova.cangjie.cfir.lightTree",
        )
    }

    private fun generateSuite(
        projectRoot: File,
        modelRelativePath: String,
        generatedClassName: String,
        baseClassName: String,
        outputRelativePath: String,
        packageName: String,
    ) {
        val testDataRoot = projectRoot.resolve(modelRelativePath)
        require(testDataRoot.exists()) { "testData root not found: ${testDataRoot.path}" }

        val outputFile = projectRoot.resolve("$outputRelativePath/$generatedClassName.kt")
        outputFile.parentFile.mkdirs()
        outputFile.writeText(
            render(testDataRoot, projectRoot, generatedClassName, baseClassName, packageName),
            Charsets.UTF_8,
        )
        println("Generated: ${outputFile.path}")
    }

    private fun render(
        testDataRoot: File,
        projectRoot: File,
        generatedClassName: String,
        baseClassName: String,
        packageName: String,
    ): String {
        val sb = StringBuilder()
        sb.appendLine("package $packageName")
        sb.appendLine()
        sb.appendLine("import com.intellij.testFramework.TestDataPath")
        sb.appendLine("import org.cangnova.cangjie.ObsoleteTestInfrastructure")
        sb.appendLine("import org.cangnova.cangjie.test.TestMetadata")
        sb.appendLine("import org.cangnova.cangjie.test.JUnit3RunnerWithInners")
        sb.appendLine("import org.junit.runner.RunWith")
        sb.appendLine()
        sb.appendLine("/** AUTO-GENERATED by TestGeneratorForLightTree2Cfir. DO NOT EDIT MANUALLY. */")
        val rootRel = projectRoot.toPath().relativize(testDataRoot.toPath()).toString().replace('\\', '/')
        sb.appendLine("@TestMetadata(\"$rootRel\")")
        sb.appendLine("@TestDataPath(\"\\\$PROJECT_ROOT\")")
        sb.appendLine("@RunWith(JUnit3RunnerWithInners::class)")
        sb.appendLine("@OptIn(ObsoleteTestInfrastructure::class)")
        sb.appendLine("@ObsoleteTestInfrastructure")
        sb.appendLine("class $generatedClassName : $baseClassName() {")
        sb.appendLine("    fun testSmoke() {")
        sb.appendLine("        // Container class for nested generated suites.")
        sb.appendLine("    }")
        sb.appendLine()

        val children = testDataRoot.listFiles().orEmpty().sortedBy { it.name }
        children.filter { it.isDirectory }.forEach { dir ->
            renderDirectoryClass(sb, dir, projectRoot, baseClassName, 1)
        }

        val filesInRoot = testDataRoot.listFiles().orEmpty()
            .filter { it.isFile && it.extension == "cj" }.sortedBy { it.name }
        filesInRoot.forEach { file ->
            renderTestMethod(sb, file, projectRoot, 1)
        }

        sb.appendLine("}")
        return sb.toString()
    }

    private fun renderDirectoryClass(
        sb: StringBuilder,
        dir: File,
        projectRoot: File,
        baseClassName: String,
        level: Int,
    ) {
        val indent = "    ".repeat(level)
        val className = toClassName(dir.name)
        val relDir = projectRoot.toPath().relativize(dir.toPath()).toString().replace('\\', '/')

        sb.appendLine("${indent}@TestMetadata(\"$relDir\")")
        sb.appendLine("${indent}@TestDataPath(\"\\\$PROJECT_ROOT\")")
        sb.appendLine("${indent}@RunWith(JUnit3RunnerWithInners::class)")
        sb.appendLine("${indent}class $className : $baseClassName() {")
        sb.appendLine("${indent}    fun testSmoke() {}")
        sb.appendLine()

        val files = dir.listFiles().orEmpty()
            .filter { it.isFile && it.extension == "cj" }.sortedBy { it.name }
        files.forEach { file ->
            renderTestMethod(sb, file, projectRoot, level + 1)
        }

        val subdirs = dir.listFiles().orEmpty().filter { it.isDirectory }.sortedBy { it.name }
        subdirs.forEach { child ->
            renderDirectoryClass(sb, child, projectRoot, baseClassName, level + 1)
        }

        sb.appendLine("${indent}}")
        sb.appendLine()
    }

    private fun renderTestMethod(
        sb: StringBuilder,
        file: File,
        projectRoot: File,
        level: Int,
    ) {
        val indent = "    ".repeat(level)
        val testName = toTestMethodName(file.nameWithoutExtension)
        val rel = projectRoot.toPath().relativize(file.toPath()).toString().replace('\\', '/')
        sb.appendLine("${indent}@TestMetadata(\"${file.name}\")")
        sb.appendLine("${indent}fun $testName() {")
        sb.appendLine("${indent}    doLightTree2CfirTest(\"$rel\")")
        sb.appendLine("${indent}}")
        sb.appendLine()
    }

    private fun toClassName(name: String): String {
        return name
            .split(Regex("[^A-Za-z0-9]+"))
            .filter { it.isNotBlank() }
            .joinToString("") { it.replaceFirstChar { ch -> ch.uppercaseChar() } }
    }

    private fun toTestMethodName(base: String): String {
        val raw = toClassName(base)
        return "test$raw"
    }
}
