// DEPENDENCE: fileUseArrayList.cj
// EXEC-PIPE: %compiler %cmp_opt --no-sub-pkg %f fileUseArrayList.cj -o %output 2>&1 | compare %f

internal import std.collection.*
main() {}

/* SCAN
*/

// Copyright (c) Huawei Technologies Co., Ltd. 2025. All rights reserved.
// This source file is part of the Cangjie project, licensed under Apache-2.0
// with Runtime Library Exception.
//
// See https://cangjie-lang.cn/pages/LICENSE for license information.
