package org.cangnova.cangjie.cfir.analysis.tests.CfirAnalysisLLTPsiTest.llt._class.static_call_non_static

import com.intellij.testFramework.TestDataPath
import org.cangnova.cangjie.ObsoleteTestInfrastructure
import org.cangnova.cangjie.cfir.analysis.tests.runners.AbstractCfirPsiLlTDiagnosticsTest
import org.cangnova.cangjie.test.TestMetadata
import org.junit.jupiter.api.Test
import java.io.File
import org.cangnova.cangjie.cfir.analysis.tests.assertAllFilesPresentByMetadata

/** AUTO-GENERATED by TestGeneratorForCfirAnalysisTests. DO NOT EDIT MANUALLY. */
@TestMetadata("cfir/analysis-tests/testData/llt/class/static_call_non_static")
@TestDataPath("${'$'}PROJECT_ROOT")
@OptIn(ObsoleteTestInfrastructure::class)
@ObsoleteTestInfrastructure
class StaticCallNonStaticGenerated : AbstractCfirPsiLlTDiagnosticsTest() {
    @Test
    fun testAllFilesPresent() {
        assertAllFilesPresentByMetadata(this, "cfir/analysis-tests/testData/llt/class/static_call_non_static")
    }

    @TestMetadata("class_static_call_non_static1.cj")
    @Test
    fun testClassStaticCallNonStatic1() {
        runTest("cfir/analysis-tests/testData/llt/class/static_call_non_static/class_static_call_non_static1.cj")
    }

    @TestMetadata("class_static_call_non_static2.cj")
    @Test
    fun testClassStaticCallNonStatic2() {
        runTest("cfir/analysis-tests/testData/llt/class/static_call_non_static/class_static_call_non_static2.cj")
    }

    @TestMetadata("class_static_call_non_static3.cj")
    @Test
    fun testClassStaticCallNonStatic3() {
        runTest("cfir/analysis-tests/testData/llt/class/static_call_non_static/class_static_call_non_static3.cj")
    }

    @TestMetadata("class_static_call_non_static4.cj")
    @Test
    fun testClassStaticCallNonStatic4() {
        runTest("cfir/analysis-tests/testData/llt/class/static_call_non_static/class_static_call_non_static4.cj")
    }

    @TestMetadata("class_static_call_non_static5.cj")
    @Test
    fun testClassStaticCallNonStatic5() {
        runTest("cfir/analysis-tests/testData/llt/class/static_call_non_static/class_static_call_non_static5.cj")
    }
}

