package org.cangnova.cangjie.cfir.analysis.tests.CfirAnalysisDiagnostics2Test.diagnostics2.visibility

import com.intellij.testFramework.TestDataPath
import org.cangnova.cangjie.ObsoleteTestInfrastructure
import org.cangnova.cangjie.cfir.analysis.tests.runners.AbstractCfirLightTreeDiagnosticsTest
import org.cangnova.cangjie.test.TestMetadata
import org.junit.jupiter.api.Test
import java.io.File
import org.cangnova.cangjie.cfir.analysis.tests.assertAllFilesPresentByMetadata

/** AUTO-GENERATED by TestGeneratorForCfirAnalysisTests. DO NOT EDIT MANUALLY. */
@TestMetadata("cfir/analysis-tests/testData/diagnostics2/visibility")
@TestDataPath("${'$'}PROJECT_ROOT")
@OptIn(ObsoleteTestInfrastructure::class)
@ObsoleteTestInfrastructure
class VisibilityGenerated : AbstractCfirLightTreeDiagnosticsTest() {
    @Test
    fun testAllFilesPresent() {
        assertAllFilesPresentByMetadata(this, "cfir/analysis-tests/testData/diagnostics2/visibility")
    }

    @TestMetadata("inheritedMemberAccess.cj")
    @Test
    fun testInheritedMemberAccess() {
        runTest("cfir/analysis-tests/testData/diagnostics2/visibility/inheritedMemberAccess.cj")
    }

    @TestMetadata("invisibleReferenceAndMember.cj")
    @Test
    fun testInvisibleReferenceAndMember() {
        runTest("cfir/analysis-tests/testData/diagnostics2/visibility/invisibleReferenceAndMember.cj")
    }

    @TestMetadata("privateMemberAccess.cj")
    @Test
    fun testPrivateMemberAccess() {
        runTest("cfir/analysis-tests/testData/diagnostics2/visibility/privateMemberAccess.cj")
    }

    @TestMetadata("privateMemberAccessExplicitThis.cj")
    @Test
    fun testPrivateMemberAccessExplicitThis() {
        runTest("cfir/analysis-tests/testData/diagnostics2/visibility/privateMemberAccessExplicitThis.cj")
    }

    @TestMetadata("privateMemberAndPropertyAccess.cj")
    @Test
    fun testPrivateMemberAndPropertyAccess() {
        runTest("cfir/analysis-tests/testData/diagnostics2/visibility/privateMemberAndPropertyAccess.cj")
    }

    @TestMetadata("privatePropertyAccess.cj")
    @Test
    fun testPrivatePropertyAccess() {
        runTest("cfir/analysis-tests/testData/diagnostics2/visibility/privatePropertyAccess.cj")
    }

    @TestMetadata("protectedAndInternalMatrix.cj")
    @Test
    fun testProtectedAndInternalMatrix() {
        runTest("cfir/analysis-tests/testData/diagnostics2/visibility/protectedAndInternalMatrix.cj")
    }
}

