package org.cangnova.cangjie.cfir.analysis.tests.CfirAnalysisLLTPsiTest.llt.desugar_error_report

import com.intellij.testFramework.TestDataPath
import org.cangnova.cangjie.ObsoleteTestInfrastructure
import org.cangnova.cangjie.cfir.analysis.tests.runners.AbstractCfirPsiLlTDiagnosticsTest
import org.cangnova.cangjie.test.TestMetadata
import org.junit.jupiter.api.Test
import java.io.File
import org.cangnova.cangjie.cfir.analysis.tests.assertAllFilesPresentByMetadata

/** AUTO-GENERATED by TestGeneratorForCfirAnalysisTests. DO NOT EDIT MANUALLY. */
@TestMetadata("cfir/analysis-tests/testData/llt/desugar_error_report")
@TestDataPath("${'$'}PROJECT_ROOT")
@OptIn(ObsoleteTestInfrastructure::class)
@ObsoleteTestInfrastructure
class DesugarErrorReportGenerated : AbstractCfirPsiLlTDiagnosticsTest() {
    @Test
    fun testAllFilesPresent() {
        assertAllFilesPresentByMetadata(this, "cfir/analysis-tests/testData/llt/desugar_error_report")
    }

    @TestMetadata("operator_overload.cj")
    @Test
    fun testOperatorOverload() {
        runTest("cfir/analysis-tests/testData/llt/desugar_error_report/operator_overload.cj")
    }

    @TestMetadata("primary_ctor.cj")
    @Test
    fun testPrimaryCtor() {
        runTest("cfir/analysis-tests/testData/llt/desugar_error_report/primary_ctor.cj")
    }

    @TestMetadata("subscribe_in_binary.cj")
    @Test
    fun testSubscribeInBinary() {
        runTest("cfir/analysis-tests/testData/llt/desugar_error_report/subscribe_in_binary.cj")
    }
}

