package org.cangnova.cangjie.cfir.analysis.tests.CfirAnalysisLLTTest.llt.PatternMatching.Sealed

import com.intellij.testFramework.TestDataPath
import org.cangnova.cangjie.ObsoleteTestInfrastructure
import org.cangnova.cangjie.cfir.analysis.tests.runners.AbstractCfirLightTreeLlTDiagnosticsTest
import org.cangnova.cangjie.test.TestMetadata
import org.junit.jupiter.api.Test
import java.io.File
import org.cangnova.cangjie.cfir.analysis.tests.assertAllFilesPresentByMetadata

/** AUTO-GENERATED by TestGeneratorForCfirAnalysisTests. DO NOT EDIT MANUALLY. */
@TestMetadata("cfir/analysis-tests/testData/llt/PatternMatching/Sealed")
@TestDataPath("${'$'}PROJECT_ROOT")
@OptIn(ObsoleteTestInfrastructure::class)
@ObsoleteTestInfrastructure
class SealedGenerated : AbstractCfirLightTreeLlTDiagnosticsTest() {
    @Test
    fun testAllFilesPresent() {
        assertAllFilesPresentByMetadata(this, "cfir/analysis-tests/testData/llt/PatternMatching/Sealed")
    }

    @TestMetadata("exhaustive_gadt.cj")
    @Test
    fun testExhaustiveGadt() {
        runTest("cfir/analysis-tests/testData/llt/PatternMatching/Sealed/exhaustive_gadt.cj")
    }

    @TestMetadata("exhaustive_interface.cj")
    @Test
    fun testExhaustiveInterface() {
        runTest("cfir/analysis-tests/testData/llt/PatternMatching/Sealed/exhaustive_interface.cj")
    }

    @TestMetadata("non_exhaustive_extend_00.cj")
    @Test
    fun testNonExhaustiveExtend00() {
        runTest("cfir/analysis-tests/testData/llt/PatternMatching/Sealed/non_exhaustive_extend_00.cj")
    }

    @TestMetadata("ok_visibility.cj")
    @Test
    fun testOkVisibility() {
        runTest("cfir/analysis-tests/testData/llt/PatternMatching/Sealed/ok_visibility.cj")
    }

    @TestMetadata("sealed_imported.cj")
    @Test
    fun testSealedImported() {
        runTest("cfir/analysis-tests/testData/llt/PatternMatching/Sealed/sealed_imported.cj")
    }

    @TestMetadata("sealed_open_exhaustive.cj")
    @Test
    fun testSealedOpenExhaustive() {
        runTest("cfir/analysis-tests/testData/llt/PatternMatching/Sealed/sealed_open_exhaustive.cj")
    }

    @TestMetadata("sealed_open_non_exhaustive.cj")
    @Test
    fun testSealedOpenNonExhaustive() {
        runTest("cfir/analysis-tests/testData/llt/PatternMatching/Sealed/sealed_open_non_exhaustive.cj")
    }

    @TestMetadata("sealed_open_unreachable.cj")
    @Test
    fun testSealedOpenUnreachable() {
        runTest("cfir/analysis-tests/testData/llt/PatternMatching/Sealed/sealed_open_unreachable.cj")
    }

    @TestMetadata("sealed_sealed_exhaustive.cj")
    @Test
    fun testSealedSealedExhaustive() {
        runTest("cfir/analysis-tests/testData/llt/PatternMatching/Sealed/sealed_sealed_exhaustive.cj")
    }

    @TestMetadata("simple_exhaustive.cj")
    @Test
    fun testSimpleExhaustive() {
        runTest("cfir/analysis-tests/testData/llt/PatternMatching/Sealed/simple_exhaustive.cj")
    }

    @TestMetadata("simple_non_exhaustive.cj")
    @Test
    fun testSimpleNonExhaustive() {
        runTest("cfir/analysis-tests/testData/llt/PatternMatching/Sealed/simple_non_exhaustive.cj")
    }

    @TestMetadata("simple_unreachable.cj")
    @Test
    fun testSimpleUnreachable() {
        runTest("cfir/analysis-tests/testData/llt/PatternMatching/Sealed/simple_unreachable.cj")
    }
}

