<!MISSING_ENTRY!>/<!>/ Copyright (c) Huawei Technologies Co., Ltd. 2025. All rights reserved.
// CHECK_PROGRAM_ENTRY
// This source file is part of the Cangjie project, licensed under Apache-2.0
// with Runtime Library Exception.
//
// See https://cangjie-lang.cn/pages/LICENSE for license information.


foreign func foo(<!CFUNC_CANNOT_HAVE_UNIT_ARGS!>a: Unit<!>): Unit

foreign func bar(<!CFUNC_CANNOT_HAVE_UNIT_ARGS!>a: Unit<!>): Unit
