package org.cangnova.cangjie.cfir.analysis.tests.CfirAnalysisLLTPsiTest.llt.Extend.Extend_Refactor

import com.intellij.testFramework.TestDataPath
import org.cangnova.cangjie.ObsoleteTestInfrastructure
import org.cangnova.cangjie.cfir.analysis.tests.runners.AbstractCfirPsiLlTDiagnosticsTest
import org.cangnova.cangjie.test.TestMetadata
import org.junit.jupiter.api.Test
import java.io.File
import org.cangnova.cangjie.cfir.analysis.tests.assertAllFilesPresentByMetadata

/** AUTO-GENERATED by TestGeneratorForCfirAnalysisTests. DO NOT EDIT MANUALLY. */
@TestMetadata("cfir/analysis-tests/testData/llt/Extend/Extend_Refactor")
@TestDataPath("${'$'}PROJECT_ROOT")
@OptIn(ObsoleteTestInfrastructure::class)
@ObsoleteTestInfrastructure
class ExtendRefactorGenerated : AbstractCfirPsiLlTDiagnosticsTest() {
    @Test
    fun testAllFilesPresent() {
        assertAllFilesPresentByMetadata(this, "cfir/analysis-tests/testData/llt/Extend/Extend_Refactor")
    }

    @TestMetadata("extend_function_conflict_invalid_1.cj")
    @Test
    fun testExtendFunctionConflictInvalid1() {
        runTest("cfir/analysis-tests/testData/llt/Extend/Extend_Refactor/extend_function_conflict_invalid_1.cj")
    }

    @TestMetadata("extend_function_conflict_invalid_2.cj")
    @Test
    fun testExtendFunctionConflictInvalid2() {
        runTest("cfir/analysis-tests/testData/llt/Extend/Extend_Refactor/extend_function_conflict_invalid_2.cj")
    }

    @TestMetadata("extend_function_conflict_invalid_3.cj")
    @Test
    fun testExtendFunctionConflictInvalid3() {
        runTest("cfir/analysis-tests/testData/llt/Extend/Extend_Refactor/extend_function_conflict_invalid_3.cj")
    }

    @TestMetadata("extend_function_conflict_invalid_4.cj")
    @Test
    fun testExtendFunctionConflictInvalid4() {
        runTest("cfir/analysis-tests/testData/llt/Extend/Extend_Refactor/extend_function_conflict_invalid_4.cj")
    }

    @TestMetadata("extend_function_conflict_invalid_5.cj")
    @Test
    fun testExtendFunctionConflictInvalid5() {
        runTest("cfir/analysis-tests/testData/llt/Extend/Extend_Refactor/extend_function_conflict_invalid_5.cj")
    }

    @TestMetadata("extend_function_conflict_invalid_6.cj")
    @Test
    fun testExtendFunctionConflictInvalid6() {
        runTest("cfir/analysis-tests/testData/llt/Extend/Extend_Refactor/extend_function_conflict_invalid_6.cj")
    }

    @TestMetadata("extend_function_ok_1.cj")
    @Test
    fun testExtendFunctionOk1() {
        runTest("cfir/analysis-tests/testData/llt/Extend/Extend_Refactor/extend_function_ok_1.cj")
    }

    @TestMetadata("extend_function_ok_2.cj")
    @Test
    fun testExtendFunctionOk2() {
        runTest("cfir/analysis-tests/testData/llt/Extend/Extend_Refactor/extend_function_ok_2.cj")
    }

    @TestMetadata("extend_function_ok_3.cj")
    @Test
    fun testExtendFunctionOk3() {
        runTest("cfir/analysis-tests/testData/llt/Extend/Extend_Refactor/extend_function_ok_3.cj")
    }

    @TestMetadata("extend_function_ok_4.cj")
    @Test
    fun testExtendFunctionOk4() {
        runTest("cfir/analysis-tests/testData/llt/Extend/Extend_Refactor/extend_function_ok_4.cj")
    }

    @TestMetadata("extend_function_override_invalid_1.cj")
    @Test
    fun testExtendFunctionOverrideInvalid1() {
        runTest("cfir/analysis-tests/testData/llt/Extend/Extend_Refactor/extend_function_override_invalid_1.cj")
    }

    @TestMetadata("extend_function_shadow_invalid.cj")
    @Test
    fun testExtendFunctionShadowInvalid() {
        runTest("cfir/analysis-tests/testData/llt/Extend/Extend_Refactor/extend_function_shadow_invalid.cj")
    }

    @TestMetadata("extend_mutable_function_invalid_1.cj")
    @Test
    fun testExtendMutableFunctionInvalid1() {
        runTest("cfir/analysis-tests/testData/llt/Extend/Extend_Refactor/extend_mutable_function_invalid_1.cj")
    }

    @TestMetadata("extend_property_conflict_invalid_1.cj")
    @Test
    fun testExtendPropertyConflictInvalid1() {
        runTest("cfir/analysis-tests/testData/llt/Extend/Extend_Refactor/extend_property_conflict_invalid_1.cj")
    }

    @TestMetadata("extend_property_conflict_invalid_2.cj")
    @Test
    fun testExtendPropertyConflictInvalid2() {
        runTest("cfir/analysis-tests/testData/llt/Extend/Extend_Refactor/extend_property_conflict_invalid_2.cj")
    }

    @TestMetadata("extend_property_conflict_invalid_3.cj")
    @Test
    fun testExtendPropertyConflictInvalid3() {
        runTest("cfir/analysis-tests/testData/llt/Extend/Extend_Refactor/extend_property_conflict_invalid_3.cj")
    }

    @TestMetadata("extend_property_conflict_invalid_4.cj")
    @Test
    fun testExtendPropertyConflictInvalid4() {
        runTest("cfir/analysis-tests/testData/llt/Extend/Extend_Refactor/extend_property_conflict_invalid_4.cj")
    }

    @TestMetadata("extend_property_conflict_invalid_5.cj")
    @Test
    fun testExtendPropertyConflictInvalid5() {
        runTest("cfir/analysis-tests/testData/llt/Extend/Extend_Refactor/extend_property_conflict_invalid_5.cj")
    }

    @TestMetadata("extend_property_conflict_invalid_6.cj")
    @Test
    fun testExtendPropertyConflictInvalid6() {
        runTest("cfir/analysis-tests/testData/llt/Extend/Extend_Refactor/extend_property_conflict_invalid_6.cj")
    }

    @TestMetadata("extend_property_ok_1.cj")
    @Test
    fun testExtendPropertyOk1() {
        runTest("cfir/analysis-tests/testData/llt/Extend/Extend_Refactor/extend_property_ok_1.cj")
    }

    @TestMetadata("extend_property_ok_2.cj")
    @Test
    fun testExtendPropertyOk2() {
        runTest("cfir/analysis-tests/testData/llt/Extend/Extend_Refactor/extend_property_ok_2.cj")
    }

    @TestMetadata("extend_property_ok_3.cj")
    @Test
    fun testExtendPropertyOk3() {
        runTest("cfir/analysis-tests/testData/llt/Extend/Extend_Refactor/extend_property_ok_3.cj")
    }

    @TestMetadata("extend_property_ok_4.cj")
    @Test
    fun testExtendPropertyOk4() {
        runTest("cfir/analysis-tests/testData/llt/Extend/Extend_Refactor/extend_property_ok_4.cj")
    }

    @TestMetadata("extend_property_override_invalid_1.cj")
    @Test
    fun testExtendPropertyOverrideInvalid1() {
        runTest("cfir/analysis-tests/testData/llt/Extend/Extend_Refactor/extend_property_override_invalid_1.cj")
    }
}

