package org.cangnova.cangjie.cfir.analysis.tests.CfirAnalysisLLTPsiTest.llt.fuzz_invalid_parse

import com.intellij.testFramework.TestDataPath
import org.cangnova.cangjie.ObsoleteTestInfrastructure
import org.cangnova.cangjie.cfir.analysis.tests.runners.AbstractCfirPsiLlTDiagnosticsTest
import org.cangnova.cangjie.test.TestMetadata
import org.junit.jupiter.api.Test
import java.io.File
import org.cangnova.cangjie.cfir.analysis.tests.assertAllFilesPresentByMetadata

/** AUTO-GENERATED by TestGeneratorForCfirAnalysisTests. DO NOT EDIT MANUALLY. */
@TestMetadata("cfir/analysis-tests/testData/llt/fuzz_invalid_parse")
@TestDataPath("${'$'}PROJECT_ROOT")
@OptIn(ObsoleteTestInfrastructure::class)
@ObsoleteTestInfrastructure
class FuzzInvalidParseGenerated : AbstractCfirPsiLlTDiagnosticsTest() {
    @Test
    fun testAllFilesPresent() {
        assertAllFilesPresentByMetadata(this, "cfir/analysis-tests/testData/llt/fuzz_invalid_parse")
    }

    @TestMetadata("invalid_struct_inheritance.cj")
    @Test
    fun testInvalidStructInheritance() {
        runTest("cfir/analysis-tests/testData/llt/fuzz_invalid_parse/invalid_struct_inheritance.cj")
    }

    @TestMetadata("invalid_try_with_resource2.cj")
    @Test
    fun testInvalidTryWithResource2() {
        runTest("cfir/analysis-tests/testData/llt/fuzz_invalid_parse/invalid_try_with_resource2.cj")
    }
}

