

package org.cangnova.cangjie.analysis.low.level.api.cfir.file.structure;

import com.intellij.testFramework.TestDataPath;
import org.cangnova.cangjie.test.util.CjTestUtil;
import org.cangnova.cangjie.test.TestMetadata;
import org.junit.jupiter.api.Test;

import java.io.File;
import java.util.regex.Pattern;

/** This class is generated by {@link org.cangnova.cangjie.analysis.low.level.api.cfir.TestGeneratorKt}. DO NOT MODIFY MANUALLY */
@SuppressWarnings("all")
@TestMetadata("analysis/low-level-api-cfir/testData/inBlockModification")
@TestDataPath("$PROJECT_ROOT")
public class InBlockModificationTestGenerated extends AbstractInBlockModificationTest {
  private void run(String fileName) {
    runTest("analysis/low-level-api-cfir/testData/inBlockModification/" + fileName);
  }

  @Test
  public void testAllFilesPresentInInBlockModification() {
    CjTestUtil.assertAllTestsPresentByMetadataWithExcluded(this.getClass(), new File("analysis/low-level-api-cfir/testData/inBlockModification"), Pattern.compile("^(.+)\\.cj$"), null, true);
  }

  @Test
  @TestMetadata("functionBody.cj")
  public void testFunctionBody() {
    run("functionBody.cj");
  }
}
