

package org.cangnova.cangjie.analysis.low.level.api.cfir.file.structure;

import com.intellij.testFramework.TestDataPath;
import org.cangnova.cangjie.test.util.CjTestUtil;
import org.cangnova.cangjie.test.TestMetadata;
import org.junit.jupiter.api.Test;

import java.io.File;
import java.util.regex.Pattern;

/** This class is generated by {@link org.cangnova.cangjie.analysis.low.level.api.cfir.TestGeneratorKt}. DO NOT MODIFY MANUALLY */
@SuppressWarnings("all")
@TestMetadata("analysis/low-level-api-cfir/testData/fileStructure")
@TestDataPath("$PROJECT_ROOT")
public class SourceFileStructureTestGenerated extends AbstractSourceFileStructureTest {
  private void run(String fileName) {
    runTest("analysis/low-level-api-cfir/testData/fileStructure/" + fileName);
  }

  @Test
  public void testAllFilesPresentInFileStructure() {
    CjTestUtil.assertAllTestsPresentByMetadataWithExcluded(this.getClass(), new File("analysis/low-level-api-cfir/testData/fileStructure"), Pattern.compile("^(.+)\\.cj$"), null, true);
  }

  @Test
  @TestMetadata("interfaceStatus.cj")
  public void testInterfaceStatus() {
    run("interfaceStatus.cj");
  }
}
