package org.cangnova.cangjie.cfir.analysis.tests.CfirAnalysisDiagnostics2PsiTest.diagnostics2.common_specific

import com.intellij.testFramework.TestDataPath
import org.cangnova.cangjie.ObsoleteTestInfrastructure
import org.cangnova.cangjie.cfir.analysis.tests.runners.AbstractCfirPsiDiagnosticTest
import org.cangnova.cangjie.test.TestMetadata
import org.junit.jupiter.api.Test
import java.io.File
import org.cangnova.cangjie.cfir.analysis.tests.assertAllFilesPresentByMetadata

/** AUTO-GENERATED by TestGeneratorForCfirAnalysisTests. DO NOT EDIT MANUALLY. */
@TestMetadata("cfir/analysis-tests/testData/diagnostics2/common-specific")
@TestDataPath("${'$'}PROJECT_ROOT")
@OptIn(ObsoleteTestInfrastructure::class)
@ObsoleteTestInfrastructure
class CommonSpecificGenerated : AbstractCfirPsiDiagnosticTest() {
    @Test
    fun testAllFilesPresent() {
        assertAllFilesPresentByMetadata(this, "cfir/analysis-tests/testData/diagnostics2/common-specific")
    }

    @TestMetadata("commonSpecificClassBoundaryPlaceholder.cj")
    @Test
    fun testCommonSpecificClassBoundaryPlaceholder() {
        runTest("cfir/analysis-tests/testData/diagnostics2/common-specific/commonSpecificClassBoundaryPlaceholder.cj")
    }

    @TestMetadata("commonSpecificClassKindMismatchPlaceholder.cj")
    @Test
    fun testCommonSpecificClassKindMismatchPlaceholder() {
        runTest("cfir/analysis-tests/testData/diagnostics2/common-specific/commonSpecificClassKindMismatchPlaceholder.cj")
    }

    @TestMetadata("commonSpecificInterfaceKindMismatchPlaceholder.cj")
    @Test
    fun testCommonSpecificInterfaceKindMismatchPlaceholder() {
        runTest("cfir/analysis-tests/testData/diagnostics2/common-specific/commonSpecificInterfaceKindMismatchPlaceholder.cj")
    }

    @TestMetadata("commonSpecificNotMatchedPlaceholder.cj")
    @Test
    fun testCommonSpecificNotMatchedPlaceholder() {
        runTest("cfir/analysis-tests/testData/diagnostics2/common-specific/commonSpecificNotMatchedPlaceholder.cj")
    }

    @TestMetadata("commonSpecificOpenClassNoInitPlaceholder.cj")
    @Test
    fun testCommonSpecificOpenClassNoInitPlaceholder() {
        runTest("cfir/analysis-tests/testData/diagnostics2/common-specific/commonSpecificOpenClassNoInitPlaceholder.cj")
    }

    @TestMetadata("commonSpecificOpenTypeMismatchPlaceholder.cj")
    @Test
    fun testCommonSpecificOpenTypeMismatchPlaceholder() {
        runTest("cfir/analysis-tests/testData/diagnostics2/common-specific/commonSpecificOpenTypeMismatchPlaceholder.cj")
    }

    @TestMetadata("commonSpecificPairMismatchPlaceholder.cj")
    @Test
    fun testCommonSpecificPairMismatchPlaceholder() {
        runTest("cfir/analysis-tests/testData/diagnostics2/common-specific/commonSpecificPairMismatchPlaceholder.cj")
    }
}

