

enum E {
    A
}

main() {
    let x = ((((((((((((((((((((1 <!INVALID_BINARY_OPERATOR!>+<!> true) + 1) + true) + 1) + true) + 1) + true) + 1) + true) + 1) + true) + 1) + true) +
        1) + true) + 1) + true) + 1) + true) + 1) + (A + A * A + A * A + A * A + A * A + A * A + A * A + A * A + A * A +
        A * A + A * A + A * A + A * A + A * A + A * A + A * A + A * A + A * A + A * A + A * A + A * A + A * A + A * A +
        A * A + A * A + A * A + A * A + A * A + A * A + A * A + A * A + A * A + A * A + A * A + A * A + A * A + A * A +
        A * A + A * A + A * A + A * A + A * A + A) + true + 1 + true + 1 + true + 1 + true + 1 + true + 1 + true + 1 +
        true + 1 + true + 1 + true + 1 + true + 1 + true + 1 + true + 1 + true + 1 + true + 1 + true + 1 + true + 1 +
        true + 1 + true + 1 + true + 1 + true + 1 + true + 1 + true + 1 + true + 1 + true + 1 + true + 1 + true + 1 +
        true + 1 + true + 1 + true + 1 + true + 1 + true + 1 + true + 1 + true + 1 + true + 1 + true + 1 + true + 1 +
        true + 1 + true + 1 + true + 1 + true + 1 + true + 1 + true + 1 + true + 1 + true + 1 + true + 1 + true + 1 +
        true + 1 + true + 1 + true + 1 + true + 1 + true + 1 + true + 1 + true + 1 + true + 1 + true + 1 + (true + (1 + (true +
        (1 + (true + (1 + (true + (1 + (true + (1 + (true + (1 + (true + (1 + (true + (1 + (true + (1 + (true + (1 + (true +
        (1 + (true + (1 + (true + (1 + (true + (1 + (true + (1 + (true + (1 + (true + (1 + true))))))))))))))))))))))))))))))))))
}
