package org.cangnova.cangjie.cfir.analysis.tests.CfirAnalysisLLTTest.llt._class.call_private_ctor_in_other_package

import com.intellij.testFramework.TestDataPath
import org.cangnova.cangjie.ObsoleteTestInfrastructure
import org.cangnova.cangjie.cfir.analysis.tests.runners.AbstractCfirLightTreeLlTDiagnosticsTest
import org.cangnova.cangjie.test.TestMetadata
import org.junit.jupiter.api.Test
import java.io.File
import org.cangnova.cangjie.cfir.analysis.tests.assertAllFilesPresentByMetadata

/** AUTO-GENERATED by TestGeneratorForCfirAnalysisTests. DO NOT EDIT MANUALLY. */
@TestMetadata("cfir/analysis-tests/testData/llt/class/call_private_ctor_in_other_package")
@TestDataPath("${'$'}PROJECT_ROOT")
@OptIn(ObsoleteTestInfrastructure::class)
@ObsoleteTestInfrastructure
class CallPrivateCtorInOtherPackageGenerated : AbstractCfirLightTreeLlTDiagnosticsTest() {
    @Test
    fun testAllFilesPresent() {
        assertAllFilesPresentByMetadata(this, "cfir/analysis-tests/testData/llt/class/call_private_ctor_in_other_package")
    }

    @TestMetadata("main.cj")
    @Test
    fun testMain() {
        runTest("cfir/analysis-tests/testData/llt/class/call_private_ctor_in_other_package/main.cj")
    }
}

