package org.cangnova.cangjie.cfir.analysis.tests.CfirAnalysisLLTPsiTest.llt.box

import com.intellij.testFramework.TestDataPath
import org.cangnova.cangjie.ObsoleteTestInfrastructure
import org.cangnova.cangjie.cfir.analysis.tests.runners.AbstractCfirPsiLlTDiagnosticsTest
import org.cangnova.cangjie.test.TestMetadata
import org.junit.jupiter.api.Test
import java.io.File
import org.cangnova.cangjie.cfir.analysis.tests.assertAllFilesPresentByMetadata

/** AUTO-GENERATED by TestGeneratorForCfirAnalysisTests. DO NOT EDIT MANUALLY. */
@TestMetadata("cfir/analysis-tests/testData/llt/box")
@TestDataPath("${'$'}PROJECT_ROOT")
@OptIn(ObsoleteTestInfrastructure::class)
@ObsoleteTestInfrastructure
class BoxGenerated : AbstractCfirPsiLlTDiagnosticsTest() {
    @Test
    fun testAllFilesPresent() {
        assertAllFilesPresentByMetadata(this, "cfir/analysis-tests/testData/llt/box")
    }

    @TestMetadata("array_expr_00.cj")
    @Test
    fun testArrayExpr00() {
        runTest("cfir/analysis-tests/testData/llt/box/array_expr_00.cj")
    }

    @TestMetadata("auto_box_block.cj")
    @Test
    fun testAutoBoxBlock() {
        runTest("cfir/analysis-tests/testData/llt/box/auto_box_block.cj")
    }

    @TestMetadata("box_in_array.cj")
    @Test
    fun testBoxInArray() {
        runTest("cfir/analysis-tests/testData/llt/box/box_in_array.cj")
    }

    @TestMetadata("box_in_array_01.cj")
    @Test
    fun testBoxInArray01() {
        runTest("cfir/analysis-tests/testData/llt/box/box_in_array_01.cj")
    }

    @TestMetadata("box_in_generic.cj")
    @Test
    fun testBoxInGeneric() {
        runTest("cfir/analysis-tests/testData/llt/box/box_in_generic.cj")
    }

    @TestMetadata("box_in_multi_matchcase.cj")
    @Test
    fun testBoxInMultiMatchcase() {
        runTest("cfir/analysis-tests/testData/llt/box/box_in_multi_matchcase.cj")
    }

    @TestMetadata("box_in_try_01.cj")
    @Test
    fun testBoxInTry01() {
        runTest("cfir/analysis-tests/testData/llt/box/box_in_try_01.cj")
    }

    @TestMetadata("box_interface_multi_conversion.cj")
    @Test
    fun testBoxInterfaceMultiConversion() {
        runTest("cfir/analysis-tests/testData/llt/box/box_interface_multi_conversion.cj")
    }

    @TestMetadata("call_boxed_super_01.cj")
    @Test
    fun testCallBoxedSuper01() {
        runTest("cfir/analysis-tests/testData/llt/box/call_boxed_super_01.cj")
    }

    @TestMetadata("call_boxed_super_02.cj")
    @Test
    fun testCallBoxedSuper02() {
        runTest("cfir/analysis-tests/testData/llt/box/call_boxed_super_02.cj")
    }

    @TestMetadata("check_super_box_01.cj")
    @Test
    fun testCheckSuperBox01() {
        runTest("cfir/analysis-tests/testData/llt/box/check_super_box_01.cj")
    }

    @TestMetadata("check_super_box_02.cj")
    @Test
    fun testCheckSuperBox02() {
        runTest("cfir/analysis-tests/testData/llt/box/check_super_box_02.cj")
    }

    @TestMetadata("check_super_box_03.cj")
    @Test
    fun testCheckSuperBox03() {
        runTest("cfir/analysis-tests/testData/llt/box/check_super_box_03.cj")
    }

    @TestMetadata("check_super_box_05.cj")
    @Test
    fun testCheckSuperBox05() {
        runTest("cfir/analysis-tests/testData/llt/box/check_super_box_05.cj")
    }

    @TestMetadata("check_super_box_06.cj")
    @Test
    fun testCheckSuperBox06() {
        runTest("cfir/analysis-tests/testData/llt/box/check_super_box_06.cj")
    }

    @TestMetadata("option_box_array.cj")
    @Test
    fun testOptionBoxArray() {
        runTest("cfir/analysis-tests/testData/llt/box/option_box_array.cj")
    }

    @TestMetadata("option_box_assign_00.cj")
    @Test
    fun testOptionBoxAssign00() {
        runTest("cfir/analysis-tests/testData/llt/box/option_box_assign_00.cj")
    }

    @TestMetadata("option_box_assign_01.cj")
    @Test
    fun testOptionBoxAssign01() {
        runTest("cfir/analysis-tests/testData/llt/box/option_box_assign_01.cj")
    }

    @TestMetadata("option_box_ifexpr.cj")
    @Test
    fun testOptionBoxIfexpr() {
        runTest("cfir/analysis-tests/testData/llt/box/option_box_ifexpr.cj")
    }

    @TestMetadata("option_box_this_type.cj")
    @Test
    fun testOptionBoxThisType() {
        runTest("cfir/analysis-tests/testData/llt/box/option_box_this_type.cj")
    }

    @TestMetadata("option_box_try.cj")
    @Test
    fun testOptionBoxTry() {
        runTest("cfir/analysis-tests/testData/llt/box/option_box_try.cj")
    }

    @TestMetadata("option_box_unary_01.cj")
    @Test
    fun testOptionBoxUnary01() {
        runTest("cfir/analysis-tests/testData/llt/box/option_box_unary_01.cj")
    }

    @TestMetadata("option_box_unary_02.cj")
    @Test
    fun testOptionBoxUnary02() {
        runTest("cfir/analysis-tests/testData/llt/box/option_box_unary_02.cj")
    }

    @TestMetadata("option_box_with_extend_box_01.cj")
    @Test
    fun testOptionBoxWithExtendBox01() {
        runTest("cfir/analysis-tests/testData/llt/box/option_box_with_extend_box_01.cj")
    }

    @TestMetadata("option_box_with_extend_box_02.cj")
    @Test
    fun testOptionBoxWithExtendBox02() {
        runTest("cfir/analysis-tests/testData/llt/box/option_box_with_extend_box_02.cj")
    }

    @TestMetadata("tuple_literal_00.cj")
    @Test
    fun testTupleLiteral00() {
        runTest("cfir/analysis-tests/testData/llt/box/tuple_literal_00.cj")
    }
}

