package org.cangnova.cangjie.cfir.analysis.tests.CfirAnalysisLLTPsiTest.llt.generics.pkgs004

import com.intellij.testFramework.TestDataPath
import org.cangnova.cangjie.ObsoleteTestInfrastructure
import org.cangnova.cangjie.cfir.analysis.tests.runners.AbstractCfirPsiLlTDiagnosticsTest
import org.cangnova.cangjie.test.TestMetadata
import org.junit.jupiter.api.Test
import java.io.File
import org.cangnova.cangjie.cfir.analysis.tests.assertAllFilesPresentByMetadata

/** AUTO-GENERATED by TestGeneratorForCfirAnalysisTests. DO NOT EDIT MANUALLY. */
@TestMetadata("cfir/analysis-tests/testData/llt/generics/pkgs004")
@TestDataPath("${'$'}PROJECT_ROOT")
@OptIn(ObsoleteTestInfrastructure::class)
@ObsoleteTestInfrastructure
class Pkgs004Generated : AbstractCfirPsiLlTDiagnosticsTest() {
    @Test
    fun testAllFilesPresent() {
        assertAllFilesPresentByMetadata(this, "cfir/analysis-tests/testData/llt/generics/pkgs004")
    }

    @TestMetadata("pkgs004001.cj")
    @Test
    fun testPkgs004001() {
        runTest("cfir/analysis-tests/testData/llt/generics/pkgs004/pkgs004001.cj")
    }
}

