$ErrorActionPreference = "Stop"

$mapping = @{
    "sema_missing_entry" = "MISSING_ENTRY"
    "sema_type_incompatible" = "TYPE_INCOMPATIBLE"
    "sema_ref_not_be_type" = "REF_NOT_BE_TYPE"
    "sema_no_matching_constructor" = "NO_CONSTRUCTOR"
    "sema_undeclared_identifier" = "UNRESOLVED_REFERENCE"
    "sema_no_matching_function" = "INVISIBLE_MEMBER"
    "sema_class_not_open_for_inheritance" = "CLASS_NOT_OPEN_FOR_INHERITANCE"
    "sema_explicit_super_call_required" = "EXPLICIT_SUPER_CALL_REQUIRED"
    "sema_ambiguous_call" = "AMBIGUOUS_FUNCTION_CALL"
    "sema_ambiguous_constructor_call" = "AMBIGUOUS_CONSTRUCTOR_CALL"
    "sema_ambiguous_arg_type" = "AMBIGUOUS_ARG_TYPE"
    "sema_ambiguous_function_reference" = "AMBIGUOUS_FUNCTION_REFERENCE"
    "sema_no_matching_operator_invoke" = "NO_MATCHING_OPERATOR_INVOKE"
    "sema_enum_type_cannot_be_used_as_constructor" = "ENUM_TYPE_CANNOT_BE_USED_AS_CONSTRUCTOR"
    "sema_cannot_override_invisible_member" = "CANNOT_OVERRIDE_INVISIBLE_MEMBER"
    "sema_cannot_override" = "CANNOT_OVERRIDE"
    "sema_throw_expr_with_wrong_type" = "THROW_EXPR_WITH_WRONG_TYPE"
    "sema_except_catch_type_error" = "CATCH_TYPE_MUST_EXTEND_EXCEPTION"
    "sema_duplicate_catch_block" = "DUPLICATE_CATCH_BLOCK"
    "sema_unreachable_catch_block" = "UNREACHABLE_CATCH_BLOCK"
    "sema_try_resource_must_implement_resource" = "TRY_RESOURCE_MUST_IMPLEMENT_RESOURCE"
    "sema_static_cannot_be_open_abstract_override" = "STATIC_CANNOT_BE_OPEN_ABSTRACT_OVERRIDE"
    "sema_missing_func_body" = "MISSING_FUNC_BODY"
    "sema_mut_only_on_function" = "MUT_ONLY_ON_FUNCTION"
    "sema_nothing_to_override" = "NOTHING_TO_OVERRIDE"
    "sema_incompatible_modifiers" = "INCOMPATIBLE_MODIFIERS"
    "sema_wrong_modifier_target" = "WRONG_MODIFIER_TARGET"
    "sema_deprecated_modifier_for_target" = "DEPRECATED_MODIFIER_FOR_TARGET"
    "sema_deprecated_modifier_pair" = "DEPRECATED_MODIFIER_PAIR"
    "sema_deprecated_modifier_containing_declaration" = "DEPRECATED_MODIFIER_CONTAINING_DECLARATION"
    "sema_redeclaration" = "REDECLARATION"
    "sema_conflicting_overloads" = "CONFLICTING_OVERLOADS"
    "sema_interface_cannot_inherit_class" = "INTERFACE_CANNOT_INHERIT_CLASS"
    "sema_multiple_class_inheritance" = "MULTIPLE_CLASS_SUPER_TYPES"
    "sema_override_static_error" = "OVERRIDE_STATIC_ERROR"
    "sema_super_types_duplicate" = "SUPER_TYPES_DUPLICATE"
    "sema_super_types_self_reference" = "SUPER_TYPES_SELF_REFERENCE"
    "sema_enum_super_not_allowed" = "ENUM_SUPER_NOT_ALLOWED"
    "sema_struct_super_not_allowed" = "STRUCT_SUPER_NOT_ALLOWED"
    "sema_interface_super_not_allowed" = "INTERFACE_SUPER_NOT_ALLOWED"
    "sema_invalid_member_visibility_in_class" = "INVALID_MEMBER_VISIBILITY_IN_CLASS"
    "sema_illegal_this_or_super_call" = "ILLEGAL_THIS_OR_SUPER_CALL"
    "sema_recursive_constructor_call" = "RECURSIVE_CONSTRUCTOR_CALL"
    "sema_too_many_arguments" = "TOO_MANY_ARGUMENTS"
    "sema_no_value_for_parameter" = "NO_VALUE_FOR_PARAMETER"
    "sema_argument_passed_twice" = "ARGUMENT_PASSED_TWICE"
    "sema_named_arguments_not_allowed" = "NAMED_ARGUMENTS_NOT_ALLOWED"
    "sema_named_parameter_not_found" = "NAMED_PARAMETER_NOT_FOUND"
    "sema_mixing_named_and_positional_arguments" = "MIXING_NAMED_AND_POSITIONAL_ARGUMENTS"
    "sema_need_named_argument" = "NEED_NAMED_ARGUMENT"
    "sema_new_inference_error" = "NEW_INFERENCE_ERROR"
    "sema_cannot_infer_parameter_type" = "CANNOT_INFER_PARAMETER_TYPE"
    "sema_empty_arrayLit_type_undefined" = "ARRAY_LITERAL_TYPE_CANNOT_BE_INFERRED"
    "sema_builder_inference_multi_lambda_restriction" = "BUILDER_INFERENCE_MULTI_LAMBDA_RESTRICTION"
    "sema_inferred_type_variable_into_empty_intersection" = "INFERRED_TYPE_VARIABLE_INTO_EMPTY_INTERSECTION"
    "sema_inferred_type_variable_into_possible_empty_intersection" = "INFERRED_TYPE_VARIABLE_INTO_POSSIBLE_EMPTY_INTERSECTION"
    "sema_generic_type_without_type_argument" = "GENERIC_TYPE_SHOULD_BE_USED_WITH_TYPE_ARGUMENT"
    "sema_generic_type_argument_not_match_constraint" = "GENERIC_TYPE_ARGUMENT_NOT_MATCH_CONSTRAINT"
    "sema_generic_no_member_match_in_upper_bounds" = "GENERIC_NO_MEMBER_MATCH_IN_UPPER_BOUNDS"
    "sema_generic_no_method_match_in_upper_bounds" = "GENERIC_NO_METHOD_MATCH_IN_UPPER_BOUNDS"
    "sema_conflicting_upper_bounds" = "CONFLICTING_UPPER_BOUNDS"
    "sema_name_in_constraint_is_not_a_type_parameter" = "NAME_IN_CONSTRAINT_IS_NOT_A_TYPE_PARAMETER"
    "sema_only_one_class_bound_allowed" = "ONLY_ONE_CLASS_BOUND_ALLOWED"
    "sema_repeated_bound" = "REPEATED_BOUND"
    "sema_cannot_currying" = "CANNOT_CURRYING"
    "sema_cannot_have_parameter" = "CANNOT_HAVE_PARAMETER"
    "sema_forbid_generic_finalizer" = "FORBID_GENERIC_FINALIZER"
    "sema_finalizer_forbidden_in_class" = "FINALIZER_FORBIDDEN_IN_CLASS"
    "sema_invalid_loop_control" = "INVALID_LOOP_CONTROL"
    "sema_immutable_function_cannot_access_mutable_function" = "IMMUTABLE_FUNCTION_CANNOT_ACCESS_MUTABLE_FUNCTION"
    "sema_cannot_modify_var" = "CANNOT_MODIFY_VAR"
    "sema_used_before_initialization" = "USED_BEFORE_INITIALIZATION"
    "sema_match_case_has_no_type" = "MATCH_CASE_HAS_NO_TYPE"
    "sema_not_overload_in_match" = "NOT_OVERLOAD_IN_MATCH"
    "sema_not_matched" = "NOT_MATCHED"
    "sema_non_exhaustive_match" = "NON_EXHAUSTIVE_MATCH"
    "sema_enum_pattern_param_size_error" = "ENUM_PATTERN_PARAM_SIZE_ERROR"
    "sema_tuple_pattern_not_match" = "TUPLE_PATTERN_NOT_MATCH"
    "sema_pattern_not_match" = "PATTERN_NOT_MATCH"
    "sema_const_eval_arithmetic_overflow" = "CONST_EVAL_ARITHMETIC_OVERFLOW"
    "sema_const_eval_divide_by_zero" = "CONST_EVAL_DIVIDE_BY_ZERO"
    "sema_const_eval_negative_shift_count" = "CONST_EVAL_NEGATIVE_SHIFT_COUNT"
    "sema_const_eval_shift_count_overflow" = "CONST_EVAL_SHIFT_COUNT_OVERFLOW"
    "sema_literal_numeric_overflow" = "LITERAL_NUMERIC_OVERFLOW"
    "sema_invalid_binary_expr" = "INVALID_BINARY_OPERATOR"
    "sema_property_override_implement_type_diff" = "PROPERTY_OVERRIDE_IMPLEMENT_TYPE_DIFF"
    "sema_range_step_not_int" = "RANGE_STEP_NOT_INT"
    "sema_range_step_cannot_be_zero" = "RANGE_STEP_CANNOT_BE_ZERO"
    "sema_range_direction_step_mismatch" = "RANGE_DIRECTION_STEP_MISMATCH"
    "sema_inconsistency_range_element_type" = "INCONSISTENCY_RANGE_ELEMENT_TYPE"
    "sema_invalid_cfunc_return_type" = "INVALID_CFUNC_RETURN_TYPE"
    "sema_invalid_cfunc_parameter_type" = "INVALID_CFUNC_PARAMETER_TYPE"
    "sema_invalid_calling_convention_target" = "INVALID_CALLING_CONVENTION_TARGET"
    "sema_extend_a_java_type" = "EXTEND_JAVA_TYPE_NOT_ALLOWED"
    "sema_objc_method_must_have_foreign_name" = "OBJC_METHOD_MUST_HAVE_FOREIGN_NAME"
    "sema_objc_impl_must_have_objc_mirror_super_class" = "OBJC_IMPL_MUST_INHERIT_MIRROR"
    "sema_objc_cj_mapping_must_be_class" = "OBJC_CJ_MAPPING_MUST_BE_CLASS"
    "sema_mock_disabled" = "MOCK_DISABLED"
    "sema_mock_not_in_test_mode" = "MOCK_NOT_IN_TEST_MODE"
    "sema_mock_unsupported_type" = "MOCK_UNSUPPORTED_TYPE"
    "sema_annotation_no_const_init" = "ANNOTATION_NO_CONST_INIT"
    "sema_varray_size_mismatch" = "VARRAY_SIZE_MISMATCH"
    "sema_varray_subscript_num" = "VARRAY_SUBSCRIPT_NUM"
    "sema_varray_args_number_mismatch" = "VARRAY_ARGS_NUMBER_MISMATCH"
    "sema_varray_arg_type_with_reftype" = "VARRAY_ARG_TYPE_WITH_REFTYPE"
    "sema_builtin_index_in_bound" = "BUILTIN_INDEX_IN_BOUND"
    "sema_specific_has_different_kind" = "SPECIFIC_HAS_DIFFERENT_TYPE"
    "sema_param_named_mismatched" = "PARAM_NAMED_MISMATCHED"
    "sema_finally_block_must_not_produce_result" = "FINALLY_BLOCK_MUST_NOT_PRODUCE_RESULT"
    "sema_core_object_not_found_when_no_prelude" = "CORE_OBJECT_NOT_FOUND_WHEN_NO_PRELUDE"
    "typealias_unused_type_parameters" = "TYPEALIAS_UNUSED_TYPE_PARAMETERS"
    "sema_inout_must_be_var_variable" = "INOUT_MUST_BE_VAR_VARIABLE"
    "sema_duplicate_inout_argument" = "DUPLICATE_INOUT_ARGUMENT"
    "sema_invalid_inout_argument" = "INVALID_INOUT_ARGUMENT"
    "sema_mismatching_handle_block" = "MISMATCHING_HANDLE_BLOCK"
    "sema_command_handle_type_error" = "COMMAND_HANDLE_TYPE_ERROR"
    "sema_resume_no_with" = "RESUME_NO_WITH"
    "sema_resume_throwing_mismatch_type" = "RESUME_THROWING_MISMATCH_TYPE"
    "sema_implicit_resume_outside_handler" = "IMPLICIT_RESUME_OUTSIDE_HANDLER"
    "sema_return_in_try_handle_block" = "RETURN_IN_HANDLE_BLOCK"
    "sema_mismatched_types" = "TYPE_MISMATCH"
    "sema_nonexhuastive_patterns" = "NON_EXHAUSTIVE_MATCH"
    "sema_accessibility" = "ACCESSIBILITY_ERROR"
    "sema_ambiguous_func_ref" = "AMBIGUOUS_FUNCTION_REFERENCE"
    "sema_ambiguous_use" = "AMBIGUOUS_USE"
    "sema_assignment_of_member_variable_cannot_use_this_or_super" = "ASSIGNMENT_OF_MEMBER_VARIABLE_CANNOT_USE_THIS_OR_SUPER"
    "sema_cannot_assign_to_immutable" = "CANNOT_ASSIGN_TO_IMMUTABLE"
    "sema_cannot_assign_to_subscript" = "CANNOT_ASSIGN_TO_SUBSCRIPT"
    "sema_cannot_convert_literal" = "CANNOT_CONVERT_LITERAL"
    "sema_cannot_have_default_param" = "CANNOT_HAVE_DEFAULT_PARAM"
    "sema_cannot_instantiated_by_incomplete_type" = "CANNOT_INSTANTIATED_BY_INCOMPLETE_TYPE"
    "sema_capture_before_initialization" = "CAPTURE_BEFORE_INITIALIZATION"
    "sema_capture_has_shadow_variable" = "CAPTURE_HAS_SHADOW_VARIABLE"
    "sema_capture_this_or_instance_field_in_func" = "CAPTURE_THIS_OR_INSTANCE_FIELD_IN_FUNC"
    "sema_cfunc_cannot_have_unit_args" = "CFUNC_CANNOT_HAVE_UNIT_ARGS"
    "sema_class_uninitialized_field" = "CLASS_UNINITIALIZED_FIELD"
    "sema_deprecated_warning" = "DEPRECATED_WARNING"
    "sema_diag_report_error_message" = "DIAG_REPORT_ERROR_MESSAGE"
    "sema_expr_in_forin_must_has_iterator" = "EXPR_IN_FORIN_MUST_HAS_ITERATOR"
    "sema_extend_function_cannot_overridden" = "EXTEND_FUNCTION_CANNOT_OVERRIDDEN"
    "sema_extend_member_cannot_shadow" = "EXTEND_MEMBER_CANNOT_SHADOW"
    "sema_extend_not_interface" = "EXTEND_NOT_INTERFACE"
    "sema_extend_use_super" = "EXTEND_USE_SUPER"
    "sema_forin_pattern_must_be_irrefutable" = "FORIN_PATTERN_MUST_BE_IRREFUTABLE"
    "sema_func_capture_var_cannot_assign" = "FUNC_CAPTURE_VAR_CANNOT_ASSIGN"
    "sema_generic_argument_no_match" = "GENERIC_ARGUMENT_NO_MATCH"
    "sema_generic_infinite_instantiation" = "GENERIC_INFINITE_INSTANTIATION"
    "sema_generic_instantiation_causes_ambiguous_functions" = "GENERIC_INSTANTIATION_CAUSES_AMBIGUOUS_FUNCTIONS"
    "sema_generic_param_directly_recursive" = "GENERIC_PARAM_DIRECTLY_RECURSIVE"
    "sema_illegal_access_non_static_member" = "ILLEGAL_ACCESS_NON_STATIC_MEMBER"
    "sema_illegal_capture_this" = "ILLEGAL_CAPTURE_THIS"
    "sema_illegal_extended_type" = "ILLEGAL_EXTENDED_TYPE"
    "sema_illegal_multi_inheritance" = "ILLEGAL_MULTI_INHERITANCE"
    "sema_illegal_place_of_calling_this_or_super" = "ILLEGAL_PLACE_OF_CALLING_THIS_OR_SUPER"
    "sema_illegal_super_alone" = "ILLEGAL_SUPER_ALONE"
    "sema_illegal_usage_of_member" = "ILLEGAL_USAGE_OF_MEMBER"
    "sema_incompatible_func_body_and_return_type" = "INCOMPATIBLE_FUNC_BODY_AND_RETURN_TYPE"
    "sema_inherit_duplicate_interface" = "EXTEND_DUPLICATE_INTERFACE"
    "sema_inherit_member_type_inconsistent" = "INHERIT_MEMBER_TYPE_INCONSISTENT"
    "sema_inheritance_cycle" = "INHERITANCE_CYCLE"
    "sema_interface_member_must_be_implemented" = "INTERFACE_MEMBER_MUST_BE_IMPLEMENTED"
    "sema_invalid_access_control" = "INVALID_ACCESS_CONTROL"
    "sema_invalid_override_member_in_class" = "INVALID_OVERRIDE_MEMBER_IN_CLASS"
    "sema_invalid_override_or_redefine_member_in_interface" = "INVALID_OVERRIDE_OR_REDEFINE_MEMBER_IN_INTERFACE"
    "sema_invalid_string_implementation" = "INVALID_STRING_IMPLEMENTATION"
    "sema_invalid_subscript_assign_parameter" = "INVALID_SUBSCRIPT_ASSIGN_PARAMETER"
    "sema_invalid_this_call_outside_ctor" = "INVALID_THIS_CALL_OUTSIDE_CTOR"
    "sema_invalid_type_param_of_enum_member_access" = "INVALID_TYPE_PARAM_OF_ENUM_MEMBER_ACCESS"
    "sema_lambdaExpr_must_have_type_annotation" = "LAMBDA_MUST_HAVE_TYPE_ANNOTATION"
    "sema_match_case_must_have_default" = "MATCH_CASE_MUST_HAVE_DEFAULT"
    "sema_member_variable_can_not_shadow" = "MEMBER_VARIABLE_CAN_NOT_SHADOW"
    "sema_multiple_named_argument" = "MULTIPLE_NAMED_ARGUMENT"
    "sema_need_member_implementation" = "NEED_MEMBER_IMPLEMENTATION"
    "sema_no_match_function_declaration_for_call" = "NO_MATCH_FUNCTION_DECLARATION_FOR_CALL"
    "sema_no_match_function_declaration_for_ref" = "NO_MATCH_FUNCTION_DECLARATION_FOR_REF"
    "sema_no_match_operator_function_call" = "NO_MATCH_OPERATOR_FUNCTION_CALL"
    "sema_non_generic_function_with_type_argument" = "NON_GENERIC_FUNCTION_WITH_TYPE_ARGUMENT"
    "sema_non_inheritable_super_class" = "NON_INHERITABLE_SUPER_CLASS"
    "sema_not_a_type" = "NOT_A_TYPE"
    "sema_not_member_of" = "NOT_MEMBER_OF"
    "sema_object_cannot_access_static_member" = "OBJECT_CANNOT_ACCESS_STATIC_MEMBER"
    "sema_operator_overload_built_in_binary_operator" = "OPERATOR_OVERLOAD_BUILT_IN_BINARY_OPERATOR"
    "sema_operator_overload_built_in_unary_operator" = "OPERATOR_OVERLOAD_BUILT_IN_UNARY_OPERATOR"
    "sema_parameters_and_arguments_mismatch" = "PARAMETERS_AND_ARGUMENTS_MISMATCH"
    "sema_return_type_incompatible" = "RETURN_TYPE_INCOMPATIBLE"
    "sema_return_type_invariance" = "RETURN_TYPE_INVARIANCE"
    "sema_static_and_non_static_member_cannot_have_same_name" = "STATIC_AND_NON_STATIC_MEMBER_CANNOT_HAVE_SAME_NAME"
    "sema_static_function_cannot_access_non_static_member" = "STATIC_FUNCTION_CANNOT_ACCESS_NON_STATIC_MEMBER"
    "sema_static_function_overload_conflicts" = "STATIC_FUNCTION_OVERLOAD_CONFLICTS"
    "sema_static_lambdaExpr_cannot_access_non_static" = "STATIC_LAMBDA_CANNOT_ACCESS_NON_STATIC"
    "sema_static_members_cannot_call_members" = "STATIC_MEMBERS_CANNOT_CALL_MEMBERS"
    "sema_static_variable_cannot_access_non_static_member" = "STATIC_VARIABLE_CANNOT_ACCESS_NON_STATIC_MEMBER"
    "sema_superclass_must_be_placed_at_first" = "SUPERCLASS_MUST_BE_PLACED_AT_FIRST"
    "sema_this_super_use_error_outside_class" = "THIS_SUPER_USE_ERROR_OUTSIDE_CLASS"
    "sema_type_implement_non_interface" = "TYPE_IMPLEMENT_NON_INTERFACE"
    "sema_typealias_cycle" = "TYPEALIAS_CYCLE"
    "sema_unable_to_infer_generic_func" = "UNABLE_TO_INFER_GENERIC_FUNC"
    "sema_unable_to_infer_return_type" = "UNABLE_TO_INFER_RETURN_TYPE"
    "sema_undeclared_type_name" = "UNDECLARED_TYPE_NAME"
    "sema_unexpected_param_for_entry" = "UNEXPECTED_PARAM_FOR_ENTRY"
    "sema_unordered_arguments" = "UNORDERED_ARGUMENTS"
    "sema_upper_bound_must_be_class_or_interface" = "UPPER_BOUND_MUST_BE_CLASS_OR_INTERFACE"
    "sema_use_func_capture_var_alone" = "USE_FUNC_CAPTURE_VAR_ALONE"
    "sema_value_type_recursive" = "VALUE_TYPE_RECURSIVE"
    "sema_weak_visibility" = "WEAK_VISIBILITY"
    "sema_wrong_number_of_arguments" = "WRONG_NUMBER_OF_ARGUMENTS"
    "sema_overload_conflicts" = "OVERLOAD_CONFLICTS"
    "sema_multiple_class_upperbounds" = "MULTIPLE_CLASS_UPPER_BOUNDS"
}

# Use -Recurse to find ALL files in subdirectories
$allFiles = Get-ChildItem -Path "cfir\analysis-tests\testData\llt" -Recurse -Filter "*.cj"

$modified = 0
foreach ($f in $allFiles) {
    $content = Get-Content $f.FullName -Raw
    $original = $content
    foreach ($old in $mapping.Keys) {
        $new = $mapping[$old]
        $content = $content -replace [regex]::Escape("<!$old!>"), "<!$new!>"
    }
    if ($content -ne $original) {
        Set-Content $f.FullName -Value $content -NoNewline
        $modified++
        Write-Output "Fixed: $($f.FullName)"
    }
}

Write-Output "`nTotal files modified: $modified"

# Verify no sema_ remain
$remaining = Get-ChildItem -Path "cfir\analysis-tests\testData\llt" -Recurse -Filter "*.cj" | Select-String -Pattern '<!sema_' -SimpleMatch -List
if ($remaining.Count -eq 0) {
    Write-Output "All sema_ markers cleaned up!"
} else {
    Write-Output "WARNING: $($remaining.Count) files still have sema_ markers:"
    $remaining | ForEach-Object { Write-Output "  $($_.Path)" }
}
