package org.cangnova.cangjie.cfir.analysis.tests.CfirAnalysisDiagnosticsPsiTest.diagnostics.effects

import com.intellij.testFramework.TestDataPath
import org.cangnova.cangjie.ObsoleteTestInfrastructure
import org.cangnova.cangjie.cfir.analysis.tests.runners.AbstractCfirPsiDiagnosticTest
import org.cangnova.cangjie.test.TestMetadata
import org.junit.jupiter.api.Test
import java.io.File
import org.cangnova.cangjie.cfir.analysis.tests.assertAllFilesPresentByMetadata

/** AUTO-GENERATED by TestGeneratorForCfirAnalysisTests. DO NOT EDIT MANUALLY. */
@TestMetadata("cfir/analysis-tests/testData/diagnostics/effects")
@TestDataPath("${'$'}PROJECT_ROOT")
@OptIn(ObsoleteTestInfrastructure::class)
@ObsoleteTestInfrastructure
class EffectsGenerated : AbstractCfirPsiDiagnosticTest() {
    @Test
    fun testAllFilesPresent() {
        assertAllFilesPresentByMetadata(this, "cfir/analysis-tests/testData/diagnostics/effects")
    }

    @TestMetadata("effectsFeatureDisabledRich.cj")
    @Test
    fun testEffectsFeatureDisabledRich() {
        runTest("cfir/analysis-tests/testData/diagnostics/effects/effectsFeatureDisabledRich.cj")
    }

    @TestMetadata("effectsSemanticsRich.cj")
    @Test
    fun testEffectsSemanticsRich() {
        runTest("cfir/analysis-tests/testData/diagnostics/effects/effectsSemanticsRich.cj")
    }

    @TestMetadata("handleBlockMismatchRich.cj")
    @Test
    fun testHandleBlockMismatchRich() {
        runTest("cfir/analysis-tests/testData/diagnostics/effects/handleBlockMismatchRich.cj")
    }
}

