package pkg

public interface IA<T0> {
    static func foo(_: (Int8, Range<Int32>)) {
        false
    }
}

public open class CA<T0> <: IA<Float32> {}


// Copyright (c) Huawei Technologies Co., Ltd. 2025. All rights reserved.
// This source file is part of the Cangjie project, licensed under Apache-2.0
// with Runtime Library Exception.
//
// See https://cangjie-lang.cn/pages/LICENSE for license information.
