package org.cangnova.cangjie.cfir.analysis.tests.CfirAnalysisDiagnostics2PsiTest.diagnostics2._typealias

import com.intellij.testFramework.TestDataPath
import org.cangnova.cangjie.ObsoleteTestInfrastructure
import org.cangnova.cangjie.cfir.analysis.tests.runners.AbstractCfirPsiDiagnosticTest
import org.cangnova.cangjie.test.TestMetadata
import org.junit.jupiter.api.Test
import java.io.File
import org.cangnova.cangjie.cfir.analysis.tests.assertAllFilesPresentByMetadata

/** AUTO-GENERATED by TestGeneratorForCfirAnalysisTests. DO NOT EDIT MANUALLY. */
@TestMetadata("cfir/analysis-tests/testData/diagnostics2/typealias")
@TestDataPath("${'$'}PROJECT_ROOT")
@OptIn(ObsoleteTestInfrastructure::class)
@ObsoleteTestInfrastructure
class TypealiasGenerated : AbstractCfirPsiDiagnosticTest() {
    @Test
    fun testAllFilesPresent() {
        assertAllFilesPresentByMetadata(this, "cfir/analysis-tests/testData/diagnostics2/typealias")
    }

    @TestMetadata("a.cj")
    @Test
    fun testA() {
        runTest("cfir/analysis-tests/testData/diagnostics2/typealias/a.cj")
    }

    @TestMetadata("crossPackageImportedAliasInFunctionSignature.cj")
    @Test
    fun testCrossPackageImportedAliasInFunctionSignature() {
        runTest("cfir/analysis-tests/testData/diagnostics2/typealias/crossPackageImportedAliasInFunctionSignature.cj")
    }
}

