package org.cangnova.cangjie.cfir.analysis.tests.CfirAnalysisLLTPsiTest.llt.PatternMatching.Sealed.pkg_visibility

import com.intellij.testFramework.TestDataPath
import org.cangnova.cangjie.ObsoleteTestInfrastructure
import org.cangnova.cangjie.cfir.analysis.tests.runners.AbstractCfirPsiLlTDiagnosticsTest
import org.cangnova.cangjie.test.TestMetadata
import org.junit.jupiter.api.Test
import java.io.File
import org.cangnova.cangjie.cfir.analysis.tests.assertAllFilesPresentByMetadata

/** AUTO-GENERATED by TestGeneratorForCfirAnalysisTests. DO NOT EDIT MANUALLY. */
@TestMetadata("cfir/analysis-tests/testData/llt/PatternMatching/Sealed/pkg_visibility")
@TestDataPath("${'$'}PROJECT_ROOT")
@OptIn(ObsoleteTestInfrastructure::class)
@ObsoleteTestInfrastructure
class PkgVisibilityGenerated : AbstractCfirPsiLlTDiagnosticsTest() {
    @Test
    fun testAllFilesPresent() {
        assertAllFilesPresentByMetadata(this, "cfir/analysis-tests/testData/llt/PatternMatching/Sealed/pkg_visibility")
    }

    @TestMetadata("failed.cj")
    @Test
    fun testFailed() {
        runTest("cfir/analysis-tests/testData/llt/PatternMatching/Sealed/pkg_visibility/failed.cj")
    }

    @TestMetadata("pass.cj")
    @Test
    fun testPass() {
        runTest("cfir/analysis-tests/testData/llt/PatternMatching/Sealed/pkg_visibility/pass.cj")
    }
}

