package org.cangnova.cangjie.cfir.analysis.tests.CfirAnalysisLLTTest.llt._interface.use_interface_default_impl_02

import com.intellij.testFramework.TestDataPath
import org.cangnova.cangjie.ObsoleteTestInfrastructure
import org.cangnova.cangjie.cfir.analysis.tests.runners.AbstractCfirLightTreeLlTDiagnosticsTest
import org.cangnova.cangjie.test.TestMetadata
import org.junit.jupiter.api.Test
import java.io.File
import org.cangnova.cangjie.cfir.analysis.tests.assertAllFilesPresentByMetadata

/** AUTO-GENERATED by TestGeneratorForCfirAnalysisTests. DO NOT EDIT MANUALLY. */
@TestMetadata("cfir/analysis-tests/testData/llt/interface/use_interface_default_impl_02")
@TestDataPath("${'$'}PROJECT_ROOT")
@OptIn(ObsoleteTestInfrastructure::class)
@ObsoleteTestInfrastructure
class UseInterfaceDefaultImpl02Generated : AbstractCfirLightTreeLlTDiagnosticsTest() {
    @Test
    fun testAllFilesPresent() {
        assertAllFilesPresentByMetadata(this, "cfir/analysis-tests/testData/llt/interface/use_interface_default_impl_02")
    }

    @TestMetadata("use_interface_def_imple_024.cj")
    @Test
    fun testUseInterfaceDefImple024() {
        runTest("cfir/analysis-tests/testData/llt/interface/use_interface_default_impl_02/use_interface_def_imple_024.cj")
    }
}

