package org.cangnova.cangjie.cfir.analysis.tests.CfirAnalysisDiagnosticsWithoutAliasExpansionTest.diagnostics.override

import com.intellij.testFramework.TestDataPath
import org.cangnova.cangjie.ObsoleteTestInfrastructure
import org.cangnova.cangjie.cfir.analysis.tests.runners.AbstractCfirLightTreeDiagnosticsWithoutAliasExpansionTest
import org.cangnova.cangjie.test.TestMetadata
import org.junit.jupiter.api.Test
import java.io.File
import org.cangnova.cangjie.cfir.analysis.tests.assertAllFilesPresentByMetadata

/** AUTO-GENERATED by TestGeneratorForCfirAnalysisTests. DO NOT EDIT MANUALLY. */
@TestMetadata("cfir/analysis-tests/testData/diagnostics/override")
@TestDataPath("${'$'}PROJECT_ROOT")
@OptIn(ObsoleteTestInfrastructure::class)
@ObsoleteTestInfrastructure
class OverrideGenerated : AbstractCfirLightTreeDiagnosticsWithoutAliasExpansionTest() {
    @Test
    fun testAllFilesPresent() {
        assertAllFilesPresentByMetadata(this, "cfir/analysis-tests/testData/diagnostics/override")
    }

    @TestMetadata("implemented.cj")
    @Test
    fun testImplemented() {
        runTest("cfir/analysis-tests/testData/diagnostics/override/implemented.cj")
    }
}

