package org.cangnova.cangjie.cfir.analysis.tests

import com.intellij.testFramework.TestDataPath
import org.cangnova.cangjie.ObsoleteTestInfrastructure
import org.cangnova.cangjie.cfir.analysis.tests.runners.AbstractCfirLightTreeLlTDiagnosticsTest
import org.cangnova.cangjie.test.TestMetadata
import org.junit.jupiter.api.Test
import java.io.File
import org.cangnova.cangjie.cfir.analysis.tests.assertAllFilesPresentByMetadata

/** AUTO-GENERATED by TestGeneratorForCfirAnalysisTests. DO NOT EDIT MANUALLY. */
@TestMetadata("cfir/analysis-tests/testData/llt")
@TestDataPath("${'$'}PROJECT_ROOT")
@OptIn(ObsoleteTestInfrastructure::class)
@ObsoleteTestInfrastructure
class CfirAnalysisLLTTestGenerated : AbstractCfirLightTreeLlTDiagnosticsTest() {
    @Test
    fun testAllFilesPresent() {
        assertAllFilesPresentByMetadata(this, "cfir/analysis-tests/testData/llt")
    }

    // Package: CompoundAssign -> CompoundAssignGenerated

    // Package: ErrMsgs -> ErrMsgsGenerated

    // Package: Extend -> ExtendGenerated

    // Package: Extend_Positive -> ExtendPositiveGenerated

    // Package: Extend_import -> ExtendImportGenerated

    // Package: InitializationCheck -> InitializationCheckGenerated

    // Package: IsOrAsExpr -> IsOrAsExprGenerated

    // Package: Loops -> LoopsGenerated

    // Package: OptionalModifiers -> OptionalModifiersGenerated

    // Package: OverlappedInstances -> OverlappedInstancesGenerated

    // Package: PatternMatching -> PatternMatchingGenerated

    // Package: accessibility -> AccessibilityGenerated

    // Package: array -> ArrayGenerated

    // Package: assign -> AssignGenerated

    // Package: binary -> BinaryGenerated

    // Package: blockexpr -> BlockexprGenerated

    // Package: bottomType -> BottomTypeGenerated

    // Package: box -> BoxGenerated

    // Package: call -> CallGenerated

    // Package: capture -> CaptureGenerated

    // Package: class -> ClassGenerated

    // Package: concurrency -> ConcurrencyGenerated

    // Package: const -> ConstGenerated

    // Package: const_evaluation -> ConstEvaluationGenerated

    // Package: constraint_check -> ConstraintCheckGenerated

    // Package: desugar_error_report -> DesugarErrorReportGenerated

    // Package: effect -> EffectGenerated

    // Package: enum -> EnumGenerated

    // Package: exception -> ExceptionGenerated

    // Package: extends_implements_interface_duplicated -> ExtendsImplementsInterfaceDuplicatedGenerated

    // Package: ffi -> FfiGenerated

    // Package: flow_expr -> FlowExprGenerated

    // Package: forin -> ForinGenerated

    // Package: function -> FunctionGenerated

    // Package: functionlinkage -> FunctionlinkageGenerated

    // Package: future -> FutureGenerated

    // Package: fuzz_invalid_parse -> FuzzInvalidParseGenerated

    // Package: generics -> GenericsGenerated

    // Package: if -> IfGenerated

    // Package: if-let-expr -> IfLetExprGenerated

    // Package: incordec -> IncordecGenerated

    // Package: interface -> InterfaceGenerated

    // Package: intrinsics -> IntrinsicsGenerated

    // Package: join_meet -> JoinMeetGenerated

    // Package: lambda -> LambdaGenerated

    // Package: let -> LetGenerated

    // Package: linkage -> LinkageGenerated

    // Package: lookup -> LookupGenerated

    // Package: main -> MainGenerated

    // Package: match -> MatchGenerated

    // Package: mut -> MutGenerated

    // Package: native -> NativeGenerated

    // Package: nonExhaustiveEnum -> NonExhaustiveEnumGenerated

    // Package: operator -> OperatorGenerated

    // Package: operator_overload -> OperatorOverloadGenerated

    // Package: optimization -> OptimizationGenerated

    // Package: optional_chain -> OptionalChainGenerated

    // Package: overflow_check -> OverflowCheckGenerated

    // Package: overload -> OverloadGenerated

    // Package: postfixAdd -> PostfixAddGenerated

    // Package: property -> PropertyGenerated

    // Package: range -> RangeGenerated

    // Package: record -> RecordGenerated

    // Package: redefinition -> RedefinitionGenerated

    // Package: return -> ReturnGenerated

    // Package: solveTypeArgs -> SolveTypeArgsGenerated

    // Package: string -> StringGenerated

    // Package: synchronized -> SynchronizedGenerated

    // Package: this -> ThisGenerated

    // Package: throw -> ThrowGenerated

    // Package: toplevel -> ToplevelGenerated

    // Package: tuple -> TupleGenerated

    // Package: type -> TypeGenerated

    // Package: type_infer -> TypeInferGenerated

    // Package: typealias -> TypealiasGenerated

    // Package: unusedImport -> UnusedImportGenerated

    // Package: users -> UsersGenerated

    // Package: var -> VarGenerated

    // Package: varray -> VarrayGenerated

    // Package: while-let-expr -> WhileLetExprGenerated
}

