package org.cangnova.cangjie.cfir.analysis.tests

import com.intellij.testFramework.TestDataPath
import org.cangnova.cangjie.ObsoleteTestInfrastructure
import org.cangnova.cangjie.cfir.analysis.tests.runners.AbstractCfirLightTreeDiagnosticsTest
import org.cangnova.cangjie.test.TestMetadata
import org.junit.jupiter.api.Nested
import org.junit.jupiter.api.Test
import java.io.File

/** AUTO-GENERATED by TestGeneratorForCfirAnalysisTests. DO NOT EDIT MANUALLY. */
@TestMetadata("cfir/analysis-tests/testData/diagnostics")
@TestDataPath("\$PROJECT_ROOT")
@OptIn(ObsoleteTestInfrastructure::class)
@ObsoleteTestInfrastructure
class CfirAnalysisDiagnosticsTestGenerated : AbstractCfirLightTreeDiagnosticsTest() {
    @Test
    fun testAllFilesPresent() {
        assertAllFilesPresentByMetadata(this, "cfir/analysis-tests/testData/diagnostics")
    }

    @TestMetadata(".cache")
    @TestDataPath("\$PROJECT_ROOT")
    @Nested
    inner class Cache : AbstractCfirLightTreeDiagnosticsTest() {
        @Test
        fun testAllFilesPresent() {
            assertAllFilesPresentByMetadata(this, "cfir/analysis-tests/testData/diagnostics/.cache")
        }
    }

    @TestMetadata("const-eval")
    @TestDataPath("\$PROJECT_ROOT")
    @Nested
    inner class ConstEval : AbstractCfirLightTreeDiagnosticsTest() {
        @Test
        fun testAllFilesPresent() {
            assertAllFilesPresentByMetadata(this, "cfir/analysis-tests/testData/diagnostics/const-eval")
        }

        @TestMetadata("constEvalArithmeticOverflow.cj")
        @Test
        fun testConstEvalArithmeticOverflow() {
            runTest("cfir/analysis-tests/testData/diagnostics/const-eval/constEvalArithmeticOverflow.cj")
        }

        @TestMetadata("constEvalDivideByZero.cj")
        @Test
        fun testConstEvalDivideByZero() {
            runTest("cfir/analysis-tests/testData/diagnostics/const-eval/constEvalDivideByZero.cj")
        }
    }

    @TestMetadata("constraints")
    @TestDataPath("\$PROJECT_ROOT")
    @Nested
    inner class Constraints : AbstractCfirLightTreeDiagnosticsTest() {
        @Test
        fun testAllFilesPresent() {
            assertAllFilesPresentByMetadata(this, "cfir/analysis-tests/testData/diagnostics/constraints")
        }

        @TestMetadata("conflictingUpperBounds.cj")
        @Test
        fun testConflictingUpperBounds() {
            runTest("cfir/analysis-tests/testData/diagnostics/constraints/conflictingUpperBounds.cj")
        }

        @TestMetadata("nameInConstraintIsNotTypeParameter.cj")
        @Test
        fun testNameInConstraintIsNotTypeParameter() {
            runTest("cfir/analysis-tests/testData/diagnostics/constraints/nameInConstraintIsNotTypeParameter.cj")
        }

        @TestMetadata("nameInConstraintIsNotTypeParameterExtend.cj")
        @Test
        fun testNameInConstraintIsNotTypeParameterExtend() {
            runTest("cfir/analysis-tests/testData/diagnostics/constraints/nameInConstraintIsNotTypeParameterExtend.cj")
        }

        @TestMetadata("onlyOneClassBoundAllowed.cj")
        @Test
        fun testOnlyOneClassBoundAllowed() {
            runTest("cfir/analysis-tests/testData/diagnostics/constraints/onlyOneClassBoundAllowed.cj")
        }

        @TestMetadata("repeatedBound.cj")
        @Test
        fun testRepeatedBound() {
            runTest("cfir/analysis-tests/testData/diagnostics/constraints/repeatedBound.cj")
        }

        @TestMetadata("repeatedBoundTypeParameter.cj")
        @Test
        fun testRepeatedBoundTypeParameter() {
            runTest("cfir/analysis-tests/testData/diagnostics/constraints/repeatedBoundTypeParameter.cj")
        }
    }

    @TestMetadata("coverage")
    @TestDataPath("\$PROJECT_ROOT")
    @Nested
    inner class Coverage : AbstractCfirLightTreeDiagnosticsTest() {
        @Test
        fun testAllFilesPresent() {
            assertAllFilesPresentByMetadata(this, "cfir/analysis-tests/testData/diagnostics/coverage")
        }

        @TestMetadata("declaration-status")
        @TestDataPath("\$PROJECT_ROOT")
        @Nested
        inner class DeclarationStatus : AbstractCfirLightTreeDiagnosticsTest() {
            @Test
            fun testAllFilesPresent() {
                assertAllFilesPresentByMetadata(this, "cfir/analysis-tests/testData/diagnostics/coverage/declaration-status")
            }

            @TestMetadata("modifierCheckerRich.cj")
            @Test
            fun testModifierCheckerRich() {
                runTest("cfir/analysis-tests/testData/diagnostics/coverage/declaration-status/modifierCheckerRich.cj")
            }

            @TestMetadata("mutOnlyOnFunctionRich.cj")
            @Test
            fun testMutOnlyOnFunctionRich() {
                runTest("cfir/analysis-tests/testData/diagnostics/coverage/declaration-status/mutOnlyOnFunctionRich.cj")
            }

            @TestMetadata("operatorParameterCountRich.cj")
            @Test
            fun testOperatorParameterCountRich() {
                runTest("cfir/analysis-tests/testData/diagnostics/coverage/declaration-status/operatorParameterCountRich.cj")
            }

            @TestMetadata("staticIncompatibleModifiersRich.cj")
            @Test
            fun testStaticIncompatibleModifiersRich() {
                runTest("cfir/analysis-tests/testData/diagnostics/coverage/declaration-status/staticIncompatibleModifiersRich.cj")
            }
        }

        @TestMetadata("extensions")
        @TestDataPath("\$PROJECT_ROOT")
        @Nested
        inner class Extensions : AbstractCfirLightTreeDiagnosticsTest() {
            @Test
            fun testAllFilesPresent() {
                assertAllFilesPresentByMetadata(this, "cfir/analysis-tests/testData/diagnostics/coverage/extensions")
            }

            @TestMetadata("extendDefaultImplementationConflictRich.cj")
            @Test
            fun testExtendDefaultImplementationConflictRich() {
                runTest("cfir/analysis-tests/testData/diagnostics/coverage/extensions/extendDefaultImplementationConflictRich.cj")
            }

            @TestMetadata("extendDuplicateInterfaceRich.cj")
            @Test
            fun testExtendDuplicateInterfaceRich() {
                runTest("cfir/analysis-tests/testData/diagnostics/coverage/extensions/extendDuplicateInterfaceRich.cj")
            }

            @TestMetadata("extendNotInterfaceRich.cj")
            @Test
            fun testExtendNotInterfaceRich() {
                runTest("cfir/analysis-tests/testData/diagnostics/coverage/extensions/extendNotInterfaceRich.cj")
            }

            @TestMetadata("illegalExtendedTypeRich.cj")
            @Test
            fun testIllegalExtendedTypeRich() {
                runTest("cfir/analysis-tests/testData/diagnostics/coverage/extensions/illegalExtendedTypeRich.cj")
            }
        }

        @TestMetadata("imports")
        @TestDataPath("\$PROJECT_ROOT")
        @Nested
        inner class Imports : AbstractCfirLightTreeDiagnosticsTest() {
            @Test
            fun testAllFilesPresent() {
                assertAllFilesPresentByMetadata(this, "cfir/analysis-tests/testData/diagnostics/coverage/imports")
            }

            @TestMetadata("importAliasConflictRich.cj")
            @Test
            fun testImportAliasConflictRich() {
                runTest("cfir/analysis-tests/testData/diagnostics/coverage/imports/importAliasConflictRich.cj")
            }

            @TestMetadata("importConflictRich.cj")
            @Test
            fun testImportConflictRich() {
                runTest("cfir/analysis-tests/testData/diagnostics/coverage/imports/importConflictRich.cj")
            }

            @TestMetadata("importTargetNotFoundRich.cj")
            @Test
            fun testImportTargetNotFoundRich() {
                runTest("cfir/analysis-tests/testData/diagnostics/coverage/imports/importTargetNotFoundRich.cj")
            }
        }

        @TestMetadata("inheritance")
        @TestDataPath("\$PROJECT_ROOT")
        @Nested
        inner class Inheritance : AbstractCfirLightTreeDiagnosticsTest() {
            @Test
            fun testAllFilesPresent() {
                assertAllFilesPresentByMetadata(this, "cfir/analysis-tests/testData/diagnostics/coverage/inheritance")
            }

            @TestMetadata("inheritedMemberAccess.cj")
            @Test
            fun testInheritedMemberAccess() {
                runTest("cfir/analysis-tests/testData/diagnostics/coverage/inheritance/inheritedMemberAccess.cj")
            }

            @TestMetadata("overrideReturnType.cj")
            @Test
            fun testOverrideReturnType() {
                runTest("cfir/analysis-tests/testData/diagnostics/coverage/inheritance/overrideReturnType.cj")
            }
        }

        @TestMetadata("match")
        @TestDataPath("\$PROJECT_ROOT")
        @Nested
        inner class Match : AbstractCfirLightTreeDiagnosticsTest() {
            @Test
            fun testAllFilesPresent() {
                assertAllFilesPresentByMetadata(this, "cfir/analysis-tests/testData/diagnostics/coverage/match")
            }

            @TestMetadata("booleanExhaustiveness.cj")
            @Test
            fun testBooleanExhaustiveness() {
                runTest("cfir/analysis-tests/testData/diagnostics/coverage/match/booleanExhaustiveness.cj")
            }

            @TestMetadata("nonExhaustiveMatchRich.cj")
            @Test
            fun testNonExhaustiveMatchRich() {
                runTest("cfir/analysis-tests/testData/diagnostics/coverage/match/nonExhaustiveMatchRich.cj")
            }
        }

        @TestMetadata("supertypes")
        @TestDataPath("\$PROJECT_ROOT")
        @Nested
        inner class Supertypes : AbstractCfirLightTreeDiagnosticsTest() {
            @Test
            fun testAllFilesPresent() {
                assertAllFilesPresentByMetadata(this, "cfir/analysis-tests/testData/diagnostics/coverage/supertypes")
            }

            @TestMetadata("interfaceCannotInheritClassRich.cj")
            @Test
            fun testInterfaceCannotInheritClassRich() {
                runTest("cfir/analysis-tests/testData/diagnostics/coverage/supertypes/interfaceCannotInheritClassRich.cj")
            }

            @TestMetadata("multipleClassSupersRich.cj")
            @Test
            fun testMultipleClassSupersRich() {
                runTest("cfir/analysis-tests/testData/diagnostics/coverage/supertypes/multipleClassSupersRich.cj")
            }

            @TestMetadata("superSelfAndDuplicateRich.cj")
            @Test
            fun testSuperSelfAndDuplicateRich() {
                runTest("cfir/analysis-tests/testData/diagnostics/coverage/supertypes/superSelfAndDuplicateRich.cj")
            }
        }
    }

    @TestMetadata("enum")
    @TestDataPath("\$PROJECT_ROOT")
    @Nested
    inner class Enum : AbstractCfirLightTreeDiagnosticsTest() {
        @Test
        fun testAllFilesPresent() {
            assertAllFilesPresentByMetadata(this, "cfir/analysis-tests/testData/diagnostics/enum")
        }

        @TestMetadata("errorSimpleEnum.cj")
        @Test
        fun testErrorSimpleEnum() {
            runTest("cfir/analysis-tests/testData/diagnostics/enum/errorSimpleEnum.cj")
        }

        @TestMetadata("noErrorSimpleEnum.cj")
        @Test
        fun testNoErrorSimpleEnum() {
            runTest("cfir/analysis-tests/testData/diagnostics/enum/noErrorSimpleEnum.cj")
        }
    }

    @TestMetadata("function")
    @TestDataPath("\$PROJECT_ROOT")
    @Nested
    inner class Function : AbstractCfirLightTreeDiagnosticsTest() {
        @Test
        fun testAllFilesPresent() {
            assertAllFilesPresentByMetadata(this, "cfir/analysis-tests/testData/diagnostics/function")
        }

        @TestMetadata("funcArg.cj")
        @Test
        fun testFuncArg() {
            runTest("cfir/analysis-tests/testData/diagnostics/function/funcArg.cj")
        }
    }

    @TestMetadata("general")
    @TestDataPath("\$PROJECT_ROOT")
    @Nested
    inner class General : AbstractCfirLightTreeDiagnosticsTest() {
        @Test
        fun testAllFilesPresent() {
            assertAllFilesPresentByMetadata(this, "cfir/analysis-tests/testData/diagnostics/general")
        }

        @TestMetadata("extendInterfaceParentAndMemberInFile.cj")
        @Test
        fun testExtendInterfaceParentAndMemberInFile() {
            runTest("cfir/analysis-tests/testData/diagnostics/general/extendInterfaceParentAndMemberInFile.cj")
        }

        @TestMetadata("multipleDiagnostics.cj")
        @Test
        fun testMultipleDiagnostics() {
            runTest("cfir/analysis-tests/testData/diagnostics/general/multipleDiagnostics.cj")
        }

        @TestMetadata("noDiagnostics.cj")
        @Test
        fun testNoDiagnostics() {
            runTest("cfir/analysis-tests/testData/diagnostics/general/noDiagnostics.cj")
        }

        @TestMetadata("prefixedDiagnosticName.cj")
        @Test
        fun testPrefixedDiagnosticName() {
            runTest("cfir/analysis-tests/testData/diagnostics/general/prefixedDiagnosticName.cj")
        }

        @TestMetadata("simpleT.cj")
        @Test
        fun testSimpleT() {
            runTest("cfir/analysis-tests/testData/diagnostics/general/simpleT.cj")
        }

        @TestMetadata("toStringInterfaceParentType.cj")
        @Test
        fun testToStringInterfaceParentType() {
            runTest("cfir/analysis-tests/testData/diagnostics/general/toStringInterfaceParentType.cj")
        }

        @TestMetadata("toStringInterfaceParentTypeInFileExtend.cj")
        @Test
        fun testToStringInterfaceParentTypeInFileExtend() {
            runTest("cfir/analysis-tests/testData/diagnostics/general/toStringInterfaceParentTypeInFileExtend.cj")
        }
    }

    @TestMetadata("literal")
    @TestDataPath("\$PROJECT_ROOT")
    @Nested
    inner class Literal : AbstractCfirLightTreeDiagnosticsTest() {
        @Test
        fun testAllFilesPresent() {
            assertAllFilesPresentByMetadata(this, "cfir/analysis-tests/testData/diagnostics/literal")
        }

        @TestMetadata("literalNumericOverflow.cj")
        @Test
        fun testLiteralNumericOverflow() {
            runTest("cfir/analysis-tests/testData/diagnostics/literal/literalNumericOverflow.cj")
        }
    }

    @TestMetadata("operator")
    @TestDataPath("\$PROJECT_ROOT")
    @Nested
    inner class Operator : AbstractCfirLightTreeDiagnosticsTest() {
        @Test
        fun testAllFilesPresent() {
            assertAllFilesPresentByMetadata(this, "cfir/analysis-tests/testData/diagnostics/operator")
        }

        @TestMetadata("bitAnd.cj")
        @Test
        fun testBitAnd() {
            runTest("cfir/analysis-tests/testData/diagnostics/operator/bitAnd.cj")
        }

        @TestMetadata("bitOr.cj")
        @Test
        fun testBitOr() {
            runTest("cfir/analysis-tests/testData/diagnostics/operator/bitOr.cj")
        }

        @TestMetadata("bitXor.cj")
        @Test
        fun testBitXor() {
            runTest("cfir/analysis-tests/testData/diagnostics/operator/bitXor.cj")
        }

        @TestMetadata("divide.cj")
        @Test
        fun testDivide() {
            runTest("cfir/analysis-tests/testData/diagnostics/operator/divide.cj")
        }

        @TestMetadata("equals.cj")
        @Test
        fun testEquals() {
            runTest("cfir/analysis-tests/testData/diagnostics/operator/equals.cj")
        }

        @TestMetadata("greaterOrEqual.cj")
        @Test
        fun testGreaterOrEqual() {
            runTest("cfir/analysis-tests/testData/diagnostics/operator/greaterOrEqual.cj")
        }

        @TestMetadata("gt.cj")
        @Test
        fun testGt() {
            runTest("cfir/analysis-tests/testData/diagnostics/operator/gt.cj")
        }

        @TestMetadata("invoke.cj")
        @Test
        fun testInvoke() {
            runTest("cfir/analysis-tests/testData/diagnostics/operator/invoke.cj")
        }

        @TestMetadata("invokeEnum.cj")
        @Test
        fun testInvokeEnum() {
            runTest("cfir/analysis-tests/testData/diagnostics/operator/invokeEnum.cj")
        }

        @TestMetadata("invokeInheritance.cj")
        @Test
        fun testInvokeInheritance() {
            runTest("cfir/analysis-tests/testData/diagnostics/operator/invokeInheritance.cj")
        }

        @TestMetadata("invokeOverloads.cj")
        @Test
        fun testInvokeOverloads() {
            runTest("cfir/analysis-tests/testData/diagnostics/operator/invokeOverloads.cj")
        }

        @TestMetadata("invokeStruct.cj")
        @Test
        fun testInvokeStruct() {
            runTest("cfir/analysis-tests/testData/diagnostics/operator/invokeStruct.cj")
        }

        @TestMetadata("leftShift.cj")
        @Test
        fun testLeftShift() {
            runTest("cfir/analysis-tests/testData/diagnostics/operator/leftShift.cj")
        }

        @TestMetadata("lessOrEqual.cj")
        @Test
        fun testLessOrEqual() {
            runTest("cfir/analysis-tests/testData/diagnostics/operator/lessOrEqual.cj")
        }

        @TestMetadata("lt.cj")
        @Test
        fun testLt() {
            runTest("cfir/analysis-tests/testData/diagnostics/operator/lt.cj")
        }

        @TestMetadata("minus.cj")
        @Test
        fun testMinus() {
            runTest("cfir/analysis-tests/testData/diagnostics/operator/minus.cj")
        }

        @TestMetadata("notEquals.cj")
        @Test
        fun testNotEquals() {
            runTest("cfir/analysis-tests/testData/diagnostics/operator/notEquals.cj")
        }

        @TestMetadata("plus.cj")
        @Test
        fun testPlus() {
            runTest("cfir/analysis-tests/testData/diagnostics/operator/plus.cj")
        }

        @TestMetadata("power.cj")
        @Test
        fun testPower() {
            runTest("cfir/analysis-tests/testData/diagnostics/operator/power.cj")
        }

        @TestMetadata("remainder.cj")
        @Test
        fun testRemainder() {
            runTest("cfir/analysis-tests/testData/diagnostics/operator/remainder.cj")
        }

        @TestMetadata("rightShift.cj")
        @Test
        fun testRightShift() {
            runTest("cfir/analysis-tests/testData/diagnostics/operator/rightShift.cj")
        }

        @TestMetadata("subscriptGet.cj")
        @Test
        fun testSubscriptGet() {
            runTest("cfir/analysis-tests/testData/diagnostics/operator/subscriptGet.cj")
        }

        @TestMetadata("subscriptSet.cj")
        @Test
        fun testSubscriptSet() {
            runTest("cfir/analysis-tests/testData/diagnostics/operator/subscriptSet.cj")
        }

        @TestMetadata("times.cj")
        @Test
        fun testTimes() {
            runTest("cfir/analysis-tests/testData/diagnostics/operator/times.cj")
        }

        @TestMetadata("unaryMinus.cj")
        @Test
        fun testUnaryMinus() {
            runTest("cfir/analysis-tests/testData/diagnostics/operator/unaryMinus.cj")
        }

        @TestMetadata("unaryNot.cj")
        @Test
        fun testUnaryNot() {
            runTest("cfir/analysis-tests/testData/diagnostics/operator/unaryNot.cj")
        }
    }

    @TestMetadata("override")
    @TestDataPath("\$PROJECT_ROOT")
    @Nested
    inner class Override : AbstractCfirLightTreeDiagnosticsTest() {
        @Test
        fun testAllFilesPresent() {
            assertAllFilesPresentByMetadata(this, "cfir/analysis-tests/testData/diagnostics/override")
        }

        @TestMetadata("implemented.cj")
        @Test
        fun testImplemented() {
            runTest("cfir/analysis-tests/testData/diagnostics/override/implemented.cj")
        }
    }

    @TestMetadata("redeclaration")
    @TestDataPath("\$PROJECT_ROOT")
    @Nested
    inner class Redeclaration : AbstractCfirLightTreeDiagnosticsTest() {
        @Test
        fun testAllFilesPresent() {
            assertAllFilesPresentByMetadata(this, "cfir/analysis-tests/testData/diagnostics/redeclaration")
        }

        @TestMetadata("simple.cj")
        @Test
        fun testSimple() {
            runTest("cfir/analysis-tests/testData/diagnostics/redeclaration/simple.cj")
        }
    }

    @TestMetadata("type-mismatch")
    @TestDataPath("\$PROJECT_ROOT")
    @Nested
    inner class TypeMismatch : AbstractCfirLightTreeDiagnosticsTest() {
        @Test
        fun testAllFilesPresent() {
            assertAllFilesPresentByMetadata(this, "cfir/analysis-tests/testData/diagnostics/type-mismatch")
        }

        @TestMetadata("argumentTypeMismatch.cj")
        @Test
        fun testArgumentTypeMismatch() {
            runTest("cfir/analysis-tests/testData/diagnostics/type-mismatch/argumentTypeMismatch.cj")
        }

        @TestMetadata("assignmentTypeMismatch.cj")
        @Test
        fun testAssignmentTypeMismatch() {
            runTest("cfir/analysis-tests/testData/diagnostics/type-mismatch/assignmentTypeMismatch.cj")
        }

        @TestMetadata("conditionBoolOk.cj")
        @Test
        fun testConditionBoolOk() {
            runTest("cfir/analysis-tests/testData/diagnostics/type-mismatch/conditionBoolOk.cj")
        }

        @TestMetadata("conditionMustBeBool.cj")
        @Test
        fun testConditionMustBeBool() {
            runTest("cfir/analysis-tests/testData/diagnostics/type-mismatch/conditionMustBeBool.cj")
        }

        @TestMetadata("genericArgumentConstraintConflict.cj")
        @Test
        fun testGenericArgumentConstraintConflict() {
            runTest("cfir/analysis-tests/testData/diagnostics/type-mismatch/genericArgumentConstraintConflict.cj")
        }

        @TestMetadata("genericConstraintCascade.cj")
        @Test
        fun testGenericConstraintCascade() {
            runTest("cfir/analysis-tests/testData/diagnostics/type-mismatch/genericConstraintCascade.cj")
        }

        @TestMetadata("genericConstraintFromExpectedType.cj")
        @Test
        fun testGenericConstraintFromExpectedType() {
            runTest("cfir/analysis-tests/testData/diagnostics/type-mismatch/genericConstraintFromExpectedType.cj")
        }

        @TestMetadata("genericReturnTypeInference.cj")
        @Test
        fun testGenericReturnTypeInference() {
            runTest("cfir/analysis-tests/testData/diagnostics/type-mismatch/genericReturnTypeInference.cj")
        }

        @TestMetadata("ifBranchCommonType.cj")
        @Test
        fun testIfBranchCommonType() {
            runTest("cfir/analysis-tests/testData/diagnostics/type-mismatch/ifBranchCommonType.cj")
        }

        @TestMetadata("lambdaParameterInference.cj")
        @Test
        fun testLambdaParameterInference() {
            runTest("cfir/analysis-tests/testData/diagnostics/type-mismatch/lambdaParameterInference.cj")
        }

        @TestMetadata("lambdaReturnConstraintMismatch.cj")
        @Test
        fun testLambdaReturnConstraintMismatch() {
            runTest("cfir/analysis-tests/testData/diagnostics/type-mismatch/lambdaReturnConstraintMismatch.cj")
        }

        @TestMetadata("lambdaReturnConstraintMismatchAsArgumentFeature.cj")
        @Test
        fun testLambdaReturnConstraintMismatchAsArgumentFeature() {
            runTest("cfir/analysis-tests/testData/diagnostics/type-mismatch/lambdaReturnConstraintMismatchAsArgumentFeature.cj")
        }

        @TestMetadata("returnTypeMismatch.cj")
        @Test
        fun testReturnTypeMismatch() {
            runTest("cfir/analysis-tests/testData/diagnostics/type-mismatch/returnTypeMismatch.cj")
        }

        @TestMetadata("simple.cj")
        @Test
        fun testSimple() {
            runTest("cfir/analysis-tests/testData/diagnostics/type-mismatch/simple.cj")
        }

        @TestMetadata("whereMultipleUpperBounds.cj")
        @Test
        fun testWhereMultipleUpperBounds() {
            runTest("cfir/analysis-tests/testData/diagnostics/type-mismatch/whereMultipleUpperBounds.cj")
        }

        @TestMetadata("whereUpperBoundMemberAccess.cj")
        @Test
        fun testWhereUpperBoundMemberAccess() {
            runTest("cfir/analysis-tests/testData/diagnostics/type-mismatch/whereUpperBoundMemberAccess.cj")
        }

        @TestMetadata("whereUpperLowerConstraintFlow.cj")
        @Test
        fun testWhereUpperLowerConstraintFlow() {
            runTest("cfir/analysis-tests/testData/diagnostics/type-mismatch/whereUpperLowerConstraintFlow.cj")
        }
    }

    @TestMetadata("typealias")
    @TestDataPath("\$PROJECT_ROOT")
    @Nested
    inner class Typealias : AbstractCfirLightTreeDiagnosticsTest() {
        @Test
        fun testAllFilesPresent() {
            assertAllFilesPresentByMetadata(this, "cfir/analysis-tests/testData/diagnostics/typealias")
        }

        @TestMetadata("a.cj")
        @Test
        fun testA() {
            runTest("cfir/analysis-tests/testData/diagnostics/typealias/a.cj")
        }
    }

    @TestMetadata("unresolved")
    @TestDataPath("\$PROJECT_ROOT")
    @Nested
    inner class Unresolved : AbstractCfirLightTreeDiagnosticsTest() {
        @Test
        fun testAllFilesPresent() {
            assertAllFilesPresentByMetadata(this, "cfir/analysis-tests/testData/diagnostics/unresolved")
        }

        @TestMetadata("std.core.cj")
        @Test
        fun testStdCore() {
            runTest("cfir/analysis-tests/testData/diagnostics/unresolved/std.core.cj")
        }

        @TestMetadata("unresolvedNameCall.cj")
        @Test
        fun testUnresolvedNameCall() {
            runTest("cfir/analysis-tests/testData/diagnostics/unresolved/unresolvedNameCall.cj")
        }

        @TestMetadata("unresolvedReferenceName.cj")
        @Test
        fun testUnresolvedReferenceName() {
            runTest("cfir/analysis-tests/testData/diagnostics/unresolved/unresolvedReferenceName.cj")
        }

        @TestMetadata("unresolvedSymbolType.cj")
        @Test
        fun testUnresolvedSymbolType() {
            runTest("cfir/analysis-tests/testData/diagnostics/unresolved/unresolvedSymbolType.cj")
        }
    }

    @TestMetadata("visibility")
    @TestDataPath("\$PROJECT_ROOT")
    @Nested
    inner class Visibility : AbstractCfirLightTreeDiagnosticsTest() {
        @Test
        fun testAllFilesPresent() {
            assertAllFilesPresentByMetadata(this, "cfir/analysis-tests/testData/diagnostics/visibility")
        }

        @TestMetadata("privateMemberAccess.cj")
        @Test
        fun testPrivateMemberAccess() {
            runTest("cfir/analysis-tests/testData/diagnostics/visibility/privateMemberAccess.cj")
        }

        @TestMetadata("privateMemberAccessExplicitThis.cj")
        @Test
        fun testPrivateMemberAccessExplicitThis() {
            runTest("cfir/analysis-tests/testData/diagnostics/visibility/privateMemberAccessExplicitThis.cj")
        }

        @TestMetadata("privatePropertyAccess.cj")
        @Test
        fun testPrivatePropertyAccess() {
            runTest("cfir/analysis-tests/testData/diagnostics/visibility/privatePropertyAccess.cj")
        }
    }
}

private fun assertAllFilesPresentByMetadata(testInstance: Any, testDataRootRelativePath: String) {
    val testDataDir = resolveTestDataPath(testDataRootRelativePath)
    require(testDataDir.isDirectory) { "testData dir not found: ${testDataDir.path}" }

    val currentDir = currentClassTestDataDir(testInstance::class.java, testDataDir)
    val expected = currentDir.walkTopDown()
        .filter { it.isFile && it.extension == "cj" }
        .map { it.relativeTo(currentDir).invariantSeparatorsPath }
        .toSet()

    val covered = collectCoveredRelativePaths(testInstance::class.java, currentDir)
    val missing = expected - covered
    check(missing.isEmpty()) {
        "Missing generated tests for testData files in ${currentDir.path}: ${missing.sorted()}"
    }
}

private fun resolveTestDataPath(path: String): File {
    val direct = File(path)
    if (direct.isAbsolute) return direct
    if (direct.exists()) return direct

    var cursor = File(System.getProperty("user.dir", ".")).absoluteFile
    while (true) {
        val candidate = cursor.resolve(path)
        if (candidate.exists()) return candidate
        val parent = cursor.parentFile ?: break
        cursor = parent
    }
    return direct
}

private fun currentClassTestDataDir(testClass: Class<*>, rootTestDataDir: File): File {
    val classMetadata = testClass.getAnnotation(org.cangnova.cangjie.test.TestMetadata::class.java)
    if (classMetadata != null) {
        val metadataPath = classMetadata.value.replace('\\', '/')
        val candidate = File(metadataPath)
        if (candidate.isDirectory) return candidate
        val nestedCandidate = rootTestDataDir.resolve(metadataPath)
        if (nestedCandidate.isDirectory) return nestedCandidate
    }
    return rootTestDataDir
}

private fun collectCoveredRelativePaths(rootClass: Class<*>, testDataDir: File): Set<String> {
    val covered = linkedSetOf<String>()
    collectCoveredFromClass(rootClass, testDataDir, testDataDir, covered)
    return covered
}

private fun collectCoveredFromClass(
    klass: Class<*>,
    rootTestDataDir: File,
    inheritedDir: File,
    covered: MutableSet<String>,
) {
    val classScopedDir = classScopedDir(klass, rootTestDataDir, inheritedDir)
    for (method in klass.declaredMethods) {
        val metadata = method.getAnnotation(org.cangnova.cangjie.test.TestMetadata::class.java) ?: continue
        val metadataPath = metadata.value.replace('\\', '/')
        val candidate = classScopedDir.resolve(metadataPath)
        if (candidate.isFile && candidate.extension == "cj" && candidate.isUnder(rootTestDataDir)) {
            covered += candidate.relativeTo(rootTestDataDir).invariantSeparatorsPath
        }
    }
    for (nested in klass.declaredClasses) {
        collectCoveredFromClass(nested, rootTestDataDir, classScopedDir, covered)
    }
}

private fun classScopedDir(
    klass: Class<*>,
    rootTestDataDir: File,
    inheritedDir: File,
): File {
    val classMetadata = klass.getAnnotation(org.cangnova.cangjie.test.TestMetadata::class.java) ?: return inheritedDir
    val metadataPath = classMetadata.value.replace('\\', '/')
    val direct = resolveTestDataPath(metadataPath)
    if (direct.isDirectory) return direct
    val nested = rootTestDataDir.resolve(metadataPath)
    if (nested.isDirectory) return nested
    val inheritedNested = inheritedDir.resolve(metadataPath)
    if (inheritedNested.isDirectory) return inheritedNested
    return inheritedDir
}

private fun File.isUnder(parent: File): Boolean {
    val parentPath = parent.canonicalFile.toPath()
    val childPath = canonicalFile.toPath()
    return childPath.startsWith(parentPath)
}
