package org.cangnova.cangjie.cfir.analysis.tests

import com.intellij.testFramework.TestDataPath
import org.cangnova.cangjie.ObsoleteTestInfrastructure
import org.cangnova.cangjie.cfir.analysis.tests.runners.AbstractCfirLightTreeDiagnosticsWithoutAliasExpansionTest
import org.cangnova.cangjie.test.TestMetadata
import org.junit.jupiter.api.Test
import java.io.File
import org.cangnova.cangjie.cfir.analysis.tests.assertAllFilesPresentByMetadata

/** AUTO-GENERATED by TestGeneratorForCfirAnalysisTests. DO NOT EDIT MANUALLY. */
@TestMetadata("cfir/analysis-tests/testData/diagnostics")
@TestDataPath("${'$'}PROJECT_ROOT")
@OptIn(ObsoleteTestInfrastructure::class)
@ObsoleteTestInfrastructure
class CfirAnalysisDiagnosticsWithoutAliasExpansionTestGenerated : AbstractCfirLightTreeDiagnosticsWithoutAliasExpansionTest() {
    @Test
    fun testAllFilesPresent() {
        assertAllFilesPresentByMetadata(this, "cfir/analysis-tests/testData/diagnostics")
    }

    // Package: call -> CallGenerated

    // Package: const-eval -> ConstEvalGenerated

    // Package: constraints -> ConstraintsGenerated

    // Package: constructor -> ConstructorGenerated

    // Package: coverage -> CoverageGenerated

    // Package: effects -> EffectsGenerated

    // Package: enum -> EnumGenerated

    // Package: function -> FunctionGenerated

    // Package: general -> GeneralGenerated

    // Package: generic-access -> GenericAccessGenerated

    // Package: initialization -> InitializationGenerated

    // Package: interface -> InterfaceGenerated

    // Package: interop -> InteropGenerated

    // Package: jump -> JumpGenerated

    // Package: literal -> LiteralGenerated

    // Package: mut -> MutGenerated

    // Package: operator -> OperatorGenerated

    // Package: override -> OverrideGenerated

    // Package: pattern -> PatternGenerated

    // Package: redeclaration -> RedeclarationGenerated

    // Package: stdlib -> StdlibGenerated

    // Package: super -> SuperGenerated

    // Package: type-mismatch -> TypeMismatchGenerated

    // Package: typealias -> TypealiasGenerated

    // Package: unresolved -> UnresolvedGenerated

    // Package: varray -> VarrayGenerated

    // Package: visibility -> VisibilityGenerated
}

