package org.cangnova.cangjie.cfir.analysis.tests

import com.intellij.testFramework.TestDataPath
import org.cangnova.cangjie.ObsoleteTestInfrastructure
import org.cangnova.cangjie.cfir.analysis.tests.runners.AbstractCfirLightTreeDiagnosticsTest
import org.cangnova.cangjie.test.TestMetadata
import org.junit.jupiter.api.Nested
import org.junit.jupiter.api.Test
import java.io.File

/** AUTO-GENERATED by TestGeneratorForCfirAnalysisTests. DO NOT EDIT MANUALLY. */
@TestMetadata("cfir/analysis-tests/testData/diagnostics2")
@TestDataPath("\$PROJECT_ROOT")
@OptIn(ObsoleteTestInfrastructure::class)
@ObsoleteTestInfrastructure
class CfirAnalysisDiagnostics2TestGenerated : AbstractCfirLightTreeDiagnosticsTest() {
    @Test
    fun testAllFilesPresent() {
        assertAllFilesPresentByMetadata(this, "cfir/analysis-tests/testData/diagnostics2")
    }

    @TestMetadata("calls")
    @TestDataPath("\$PROJECT_ROOT")
    @Nested
    inner class Calls : AbstractCfirLightTreeDiagnosticsTest() {
        @Test
        fun testAllFilesPresent() {
            assertAllFilesPresentByMetadata(this, "cfir/analysis-tests/testData/diagnostics2/calls")
        }

        @TestMetadata("ambiguousFunctionCall.cj")
        @Test
        fun testAmbiguousFunctionCall() {
            runTest("cfir/analysis-tests/testData/diagnostics2/calls/ambiguousFunctionCall.cj")
        }

        @TestMetadata("functionReferenceAmbiguityPlaceholder.cj")
        @Test
        fun testFunctionReferenceAmbiguityPlaceholder() {
            runTest("cfir/analysis-tests/testData/diagnostics2/calls/functionReferenceAmbiguityPlaceholder.cj")
        }

        @TestMetadata("namedArgumentsAndArity.cj")
        @Test
        fun testNamedArgumentsAndArity() {
            runTest("cfir/analysis-tests/testData/diagnostics2/calls/namedArgumentsAndArity.cj")
        }
    }

    @TestMetadata("const-eval")
    @TestDataPath("\$PROJECT_ROOT")
    @Nested
    inner class ConstEval : AbstractCfirLightTreeDiagnosticsTest() {
        @Test
        fun testAllFilesPresent() {
            assertAllFilesPresentByMetadata(this, "cfir/analysis-tests/testData/diagnostics2/const-eval")
        }

        @TestMetadata("constEvalArithmeticOverflow.cj")
        @Test
        fun testConstEvalArithmeticOverflow() {
            runTest("cfir/analysis-tests/testData/diagnostics2/const-eval/constEvalArithmeticOverflow.cj")
        }

        @TestMetadata("constEvalDivideByZero.cj")
        @Test
        fun testConstEvalDivideByZero() {
            runTest("cfir/analysis-tests/testData/diagnostics2/const-eval/constEvalDivideByZero.cj")
        }

        @TestMetadata("constEvalShift.cj")
        @Test
        fun testConstEvalShift() {
            runTest("cfir/analysis-tests/testData/diagnostics2/const-eval/constEvalShift.cj")
        }
    }

    @TestMetadata("constructor")
    @TestDataPath("\$PROJECT_ROOT")
    @Nested
    inner class Constructor : AbstractCfirLightTreeDiagnosticsTest() {
        @Test
        fun testAllFilesPresent() {
            assertAllFilesPresentByMetadata(this, "cfir/analysis-tests/testData/diagnostics2/constructor")
        }

        @TestMetadata("noConstructorDirectConstruction.cj")
        @Test
        fun testNoConstructorDirectConstruction() {
            runTest("cfir/analysis-tests/testData/diagnostics2/constructor/noConstructorDirectConstruction.cj")
        }

        @TestMetadata("noConstructorThisAndSuper.cj")
        @Test
        fun testNoConstructorThisAndSuper() {
            runTest("cfir/analysis-tests/testData/diagnostics2/constructor/noConstructorThisAndSuper.cj")
        }
    }

    @TestMetadata("coverage")
    @TestDataPath("\$PROJECT_ROOT")
    @Nested
    inner class Coverage : AbstractCfirLightTreeDiagnosticsTest() {
        @Test
        fun testAllFilesPresent() {
            assertAllFilesPresentByMetadata(this, "cfir/analysis-tests/testData/diagnostics2/coverage")
        }

        @TestMetadata("match")
        @TestDataPath("\$PROJECT_ROOT")
        @Nested
        inner class Match : AbstractCfirLightTreeDiagnosticsTest() {
            @Test
            fun testAllFilesPresent() {
                assertAllFilesPresentByMetadata(this, "cfir/analysis-tests/testData/diagnostics2/coverage/match")
            }

            @TestMetadata("booleanExhaustiveness.cj")
            @Test
            fun testBooleanExhaustiveness() {
                runTest("cfir/analysis-tests/testData/diagnostics2/coverage/match/booleanExhaustiveness.cj")
            }

            @TestMetadata("nonExhaustiveMatch.cj")
            @Test
            fun testNonExhaustiveMatch() {
                runTest("cfir/analysis-tests/testData/diagnostics2/coverage/match/nonExhaustiveMatch.cj")
            }
        }
    }

    @TestMetadata("declaration-status")
    @TestDataPath("\$PROJECT_ROOT")
    @Nested
    inner class DeclarationStatus : AbstractCfirLightTreeDiagnosticsTest() {
        @Test
        fun testAllFilesPresent() {
            assertAllFilesPresentByMetadata(this, "cfir/analysis-tests/testData/diagnostics2/declaration-status")
        }

        @TestMetadata("deprecatedModifierContainingDeclaration.cj")
        @Test
        fun testDeprecatedModifierContainingDeclaration() {
            runTest("cfir/analysis-tests/testData/diagnostics2/declaration-status/deprecatedModifierContainingDeclaration.cj")
        }

        @TestMetadata("deprecatedModifierForTarget.cj")
        @Test
        fun testDeprecatedModifierForTarget() {
            runTest("cfir/analysis-tests/testData/diagnostics2/declaration-status/deprecatedModifierForTarget.cj")
        }

        @TestMetadata("deprecatedModifierPair.cj")
        @Test
        fun testDeprecatedModifierPair() {
            runTest("cfir/analysis-tests/testData/diagnostics2/declaration-status/deprecatedModifierPair.cj")
        }

        @TestMetadata("mutOnlyOnFunction.cj")
        @Test
        fun testMutOnlyOnFunction() {
            runTest("cfir/analysis-tests/testData/diagnostics2/declaration-status/mutOnlyOnFunction.cj")
        }

        @TestMetadata("staticCannotBeOpenAbstractOverride.cj")
        @Test
        fun testStaticCannotBeOpenAbstractOverride() {
            runTest("cfir/analysis-tests/testData/diagnostics2/declaration-status/staticCannotBeOpenAbstractOverride.cj")
        }
    }

    @TestMetadata("effects")
    @TestDataPath("\$PROJECT_ROOT")
    @Nested
    inner class Effects : AbstractCfirLightTreeDiagnosticsTest() {
        @Test
        fun testAllFilesPresent() {
            assertAllFilesPresentByMetadata(this, "cfir/analysis-tests/testData/diagnostics2/effects")
        }

        @TestMetadata("effectsSemantics.cj")
        @Test
        fun testEffectsSemantics() {
            runTest("cfir/analysis-tests/testData/diagnostics2/effects/effectsSemantics.cj")
        }

        @TestMetadata("handleBlockMismatch.cj")
        @Test
        fun testHandleBlockMismatch() {
            runTest("cfir/analysis-tests/testData/diagnostics2/effects/handleBlockMismatch.cj")
        }

        @TestMetadata("mismatchingHandleBlock.cj")
        @Test
        fun testMismatchingHandleBlock() {
            runTest("cfir/analysis-tests/testData/diagnostics2/effects/mismatchingHandleBlock.cj")
        }

        @TestMetadata("resumptionTypeMismatch.cj")
        @Test
        fun testResumptionTypeMismatch() {
            runTest("cfir/analysis-tests/testData/diagnostics2/effects/resumptionTypeMismatch.cj")
        }

        @TestMetadata("returnInsideHandlePlaceholder.cj")
        @Test
        fun testReturnInsideHandlePlaceholder() {
            runTest("cfir/analysis-tests/testData/diagnostics2/effects/returnInsideHandlePlaceholder.cj")
        }
    }

    @TestMetadata("generic-access")
    @TestDataPath("\$PROJECT_ROOT")
    @Nested
    inner class GenericAccess : AbstractCfirLightTreeDiagnosticsTest() {
        @Test
        fun testAllFilesPresent() {
            assertAllFilesPresentByMetadata(this, "cfir/analysis-tests/testData/diagnostics2/generic-access")
        }

        @TestMetadata("genericTypeWithoutTypeArgument.cj")
        @Test
        fun testGenericTypeWithoutTypeArgument() {
            runTest("cfir/analysis-tests/testData/diagnostics2/generic-access/genericTypeWithoutTypeArgument.cj")
        }

        @TestMetadata("upperBoundsMemberAndMethod.cj")
        @Test
        fun testUpperBoundsMemberAndMethod() {
            runTest("cfir/analysis-tests/testData/diagnostics2/generic-access/upperBoundsMemberAndMethod.cj")
        }
    }

    @TestMetadata("inference")
    @TestDataPath("\$PROJECT_ROOT")
    @Nested
    inner class Inference : AbstractCfirLightTreeDiagnosticsTest() {
        @Test
        fun testAllFilesPresent() {
            assertAllFilesPresentByMetadata(this, "cfir/analysis-tests/testData/diagnostics2/inference")
        }

        @TestMetadata("builderInferenceMultiLambdaRestriction.cj")
        @Test
        fun testBuilderInferenceMultiLambdaRestriction() {
            runTest("cfir/analysis-tests/testData/diagnostics2/inference/builderInferenceMultiLambdaRestriction.cj")
        }

        @TestMetadata("conflictingConstraintFamily.cj")
        @Test
        fun testConflictingConstraintFamily() {
            runTest("cfir/analysis-tests/testData/diagnostics2/inference/conflictingConstraintFamily.cj")
        }

        @TestMetadata("genericReturnTypeInferencePlaceholder.cj")
        @Test
        fun testGenericReturnTypeInferencePlaceholder() {
            runTest("cfir/analysis-tests/testData/diagnostics2/inference/genericReturnTypeInferencePlaceholder.cj")
        }

        @TestMetadata("inferencePlaceholder.cj")
        @Test
        fun testInferencePlaceholder() {
            runTest("cfir/analysis-tests/testData/diagnostics2/inference/inferencePlaceholder.cj")
        }

        @TestMetadata("intersectionCollapsePlaceholder.cj")
        @Test
        fun testIntersectionCollapsePlaceholder() {
            runTest("cfir/analysis-tests/testData/diagnostics2/inference/intersectionCollapsePlaceholder.cj")
        }

        @TestMetadata("lambdaInferencePlaceholder.cj")
        @Test
        fun testLambdaInferencePlaceholder() {
            runTest("cfir/analysis-tests/testData/diagnostics2/inference/lambdaInferencePlaceholder.cj")
        }

        @TestMetadata("newInferenceErrorConflict.cj")
        @Test
        fun testNewInferenceErrorConflict() {
            runTest("cfir/analysis-tests/testData/diagnostics2/inference/newInferenceErrorConflict.cj")
        }

        @TestMetadata("returnTypeInferenceMismatch.cj")
        @Test
        fun testReturnTypeInferenceMismatch() {
            runTest("cfir/analysis-tests/testData/diagnostics2/inference/returnTypeInferenceMismatch.cj")
        }
    }

    @TestMetadata("inheritance")
    @TestDataPath("\$PROJECT_ROOT")
    @Nested
    inner class Inheritance : AbstractCfirLightTreeDiagnosticsTest() {
        @Test
        fun testAllFilesPresent() {
            assertAllFilesPresentByMetadata(this, "cfir/analysis-tests/testData/diagnostics2/inheritance")
        }

        @TestMetadata("classAndInterfaceInheritanceBoundaries.cj")
        @Test
        fun testClassAndInterfaceInheritanceBoundaries() {
            runTest("cfir/analysis-tests/testData/diagnostics2/inheritance/classAndInterfaceInheritanceBoundaries.cj")
        }

        @TestMetadata("classNotOpenForInheritance.cj")
        @Test
        fun testClassNotOpenForInheritance() {
            runTest("cfir/analysis-tests/testData/diagnostics2/inheritance/classNotOpenForInheritance.cj")
        }

        @TestMetadata("classSuperCallAllowed.cj")
        @Test
        fun testClassSuperCallAllowed() {
            runTest("cfir/analysis-tests/testData/diagnostics2/inheritance/classSuperCallAllowed.cj")
        }

        @TestMetadata("illegalSuperInStructAndEnum.cj")
        @Test
        fun testIllegalSuperInStructAndEnum() {
            runTest("cfir/analysis-tests/testData/diagnostics2/inheritance/illegalSuperInStructAndEnum.cj")
        }

        @TestMetadata("interfaceCannotInheritClass.cj")
        @Test
        fun testInterfaceCannotInheritClass() {
            runTest("cfir/analysis-tests/testData/diagnostics2/inheritance/interfaceCannotInheritClass.cj")
        }

        @TestMetadata("multipleClassSupers.cj")
        @Test
        fun testMultipleClassSupers() {
            runTest("cfir/analysis-tests/testData/diagnostics2/inheritance/multipleClassSupers.cj")
        }

        @TestMetadata("nothingToOverride.cj")
        @Test
        fun testNothingToOverride() {
            runTest("cfir/analysis-tests/testData/diagnostics2/inheritance/nothingToOverride.cj")
        }

        @TestMetadata("overrideInvisibleAndNothingToOverride.cj")
        @Test
        fun testOverrideInvisibleAndNothingToOverride() {
            runTest("cfir/analysis-tests/testData/diagnostics2/inheritance/overrideInvisibleAndNothingToOverride.cj")
        }

        @TestMetadata("overrideInvisibleMember.cj")
        @Test
        fun testOverrideInvisibleMember() {
            runTest("cfir/analysis-tests/testData/diagnostics2/inheritance/overrideInvisibleMember.cj")
        }

        @TestMetadata("overrideParameterNameMismatch.cj")
        @Test
        fun testOverrideParameterNameMismatch() {
            runTest("cfir/analysis-tests/testData/diagnostics2/inheritance/overrideParameterNameMismatch.cj")
        }

        @TestMetadata("overrideReturnTypeCovariant.cj")
        @Test
        fun testOverrideReturnTypeCovariant() {
            runTest("cfir/analysis-tests/testData/diagnostics2/inheritance/overrideReturnTypeCovariant.cj")
        }

        @TestMetadata("overrideReturnTypeMismatch.cj")
        @Test
        fun testOverrideReturnTypeMismatch() {
            runTest("cfir/analysis-tests/testData/diagnostics2/inheritance/overrideReturnTypeMismatch.cj")
        }

        @TestMetadata("superSelfAndDuplicate.cj")
        @Test
        fun testSuperSelfAndDuplicate() {
            runTest("cfir/analysis-tests/testData/diagnostics2/inheritance/superSelfAndDuplicate.cj")
        }
    }

    @TestMetadata("initialization")
    @TestDataPath("\$PROJECT_ROOT")
    @Nested
    inner class Initialization : AbstractCfirLightTreeDiagnosticsTest() {
        @Test
        fun testAllFilesPresent() {
            assertAllFilesPresentByMetadata(this, "cfir/analysis-tests/testData/diagnostics2/initialization")
        }

        @TestMetadata("controlFlowInitialization.cj")
        @Test
        fun testControlFlowInitialization() {
            runTest("cfir/analysis-tests/testData/diagnostics2/initialization/controlFlowInitialization.cj")
        }

        @TestMetadata("usedBeforeInitialization.cj")
        @Test
        fun testUsedBeforeInitialization() {
            runTest("cfir/analysis-tests/testData/diagnostics2/initialization/usedBeforeInitialization.cj")
        }
    }

    @TestMetadata("inout")
    @TestDataPath("\$PROJECT_ROOT")
    @Nested
    inner class Inout : AbstractCfirLightTreeDiagnosticsTest() {
        @Test
        fun testAllFilesPresent() {
            assertAllFilesPresentByMetadata(this, "cfir/analysis-tests/testData/diagnostics2/inout")
        }

        @TestMetadata("inoutNonLValuePlaceholder.cj")
        @Test
        fun testInoutNonLValuePlaceholder() {
            runTest("cfir/analysis-tests/testData/diagnostics2/inout/inoutNonLValuePlaceholder.cj")
        }

        @TestMetadata("inoutPropertyAndDuplicatePlaceholder.cj")
        @Test
        fun testInoutPropertyAndDuplicatePlaceholder() {
            runTest("cfir/analysis-tests/testData/diagnostics2/inout/inoutPropertyAndDuplicatePlaceholder.cj")
        }

        @TestMetadata("inoutRequiresVarVariable.cj")
        @Test
        fun testInoutRequiresVarVariable() {
            runTest("cfir/analysis-tests/testData/diagnostics2/inout/inoutRequiresVarVariable.cj")
        }
    }

    @TestMetadata("interop")
    @TestDataPath("\$PROJECT_ROOT")
    @Nested
    inner class Interop : AbstractCfirLightTreeDiagnosticsTest() {
        @Test
        fun testAllFilesPresent() {
            assertAllFilesPresentByMetadata(this, "cfir/analysis-tests/testData/diagnostics2/interop")
        }

        @TestMetadata("callingConventionBoundaryPlaceholder.cj")
        @Test
        fun testCallingConventionBoundaryPlaceholder() {
            runTest("cfir/analysis-tests/testData/diagnostics2/interop/callingConventionBoundaryPlaceholder.cj")
        }

        @TestMetadata("foreignFunctionCFuncLegalityPlaceholder.cj")
        @Test
        fun testForeignFunctionCFuncLegalityPlaceholder() {
            runTest("cfir/analysis-tests/testData/diagnostics2/interop/foreignFunctionCFuncLegalityPlaceholder.cj")
        }

        @TestMetadata("foreignFunctionMixedSignatureLegality.cj")
        @Test
        fun testForeignFunctionMixedSignatureLegality() {
            runTest("cfir/analysis-tests/testData/diagnostics2/interop/foreignFunctionMixedSignatureLegality.cj")
        }

        @TestMetadata("foreignFunctionParameterTypePlaceholder.cj")
        @Test
        fun testForeignFunctionParameterTypePlaceholder() {
            runTest("cfir/analysis-tests/testData/diagnostics2/interop/foreignFunctionParameterTypePlaceholder.cj")
        }

        @TestMetadata("foreignFunctionReturnType.cj")
        @Test
        fun testForeignFunctionReturnType() {
            runTest("cfir/analysis-tests/testData/diagnostics2/interop/foreignFunctionReturnType.cj")
        }

        @TestMetadata("foreignFunctionTypeAliasExpansion.cj")
        @Test
        fun testForeignFunctionTypeAliasExpansion() {
            runTest("cfir/analysis-tests/testData/diagnostics2/interop/foreignFunctionTypeAliasExpansion.cj")
        }

        @TestMetadata("foreignNameLegalityPlaceholder.cj")
        @Test
        fun testForeignNameLegalityPlaceholder() {
            runTest("cfir/analysis-tests/testData/diagnostics2/interop/foreignNameLegalityPlaceholder.cj")
        }

        @TestMetadata("objcCJMappingBoundaryPlaceholder.cj")
        @Test
        fun testObjcCJMappingBoundaryPlaceholder() {
            runTest("cfir/analysis-tests/testData/diagnostics2/interop/objcCJMappingBoundaryPlaceholder.cj")
        }

        @TestMetadata("objcInitMethodBoundaryPlaceholder.cj")
        @Test
        fun testObjcInitMethodBoundaryPlaceholder() {
            runTest("cfir/analysis-tests/testData/diagnostics2/interop/objcInitMethodBoundaryPlaceholder.cj")
        }

        @TestMetadata("objcMirrorImplTypeBoundaryPlaceholder.cj")
        @Test
        fun testObjcMirrorImplTypeBoundaryPlaceholder() {
            runTest("cfir/analysis-tests/testData/diagnostics2/interop/objcMirrorImplTypeBoundaryPlaceholder.cj")
        }
    }

    @TestMetadata("invalid-declaration")
    @TestDataPath("\$PROJECT_ROOT")
    @Nested
    inner class InvalidDeclaration : AbstractCfirLightTreeDiagnosticsTest() {
        @Test
        fun testAllFilesPresent() {
            assertAllFilesPresentByMetadata(this, "cfir/analysis-tests/testData/diagnostics2/invalid-declaration")
        }

        @TestMetadata("ambiguousConstructorCall.cj")
        @Test
        fun testAmbiguousConstructorCall() {
            runTest("cfir/analysis-tests/testData/diagnostics2/invalid-declaration/ambiguousConstructorCall.cj")
        }

        @TestMetadata("constructorConflictMatrix.cj")
        @Test
        fun testConstructorConflictMatrix() {
            runTest("cfir/analysis-tests/testData/diagnostics2/invalid-declaration/constructorConflictMatrix.cj")
        }

        @TestMetadata("constructorDelegationMatrix.cj")
        @Test
        fun testConstructorDelegationMatrix() {
            runTest("cfir/analysis-tests/testData/diagnostics2/invalid-declaration/constructorDelegationMatrix.cj")
        }

        @TestMetadata("explicitSuperCallRequired.cj")
        @Test
        fun testExplicitSuperCallRequired() {
            runTest("cfir/analysis-tests/testData/diagnostics2/invalid-declaration/explicitSuperCallRequired.cj")
        }

        @TestMetadata("illegalDelegationPlacement.cj")
        @Test
        fun testIllegalDelegationPlacement() {
            runTest("cfir/analysis-tests/testData/diagnostics2/invalid-declaration/illegalDelegationPlacement.cj")
        }

        @TestMetadata("illegalSuperCallInMember.cj")
        @Test
        fun testIllegalSuperCallInMember() {
            runTest("cfir/analysis-tests/testData/diagnostics2/invalid-declaration/illegalSuperCallInMember.cj")
        }

        @TestMetadata("illegalThisCallInMember.cj")
        @Test
        fun testIllegalThisCallInMember() {
            runTest("cfir/analysis-tests/testData/diagnostics2/invalid-declaration/illegalThisCallInMember.cj")
        }

        @TestMetadata("noConstructorMatrix.cj")
        @Test
        fun testNoConstructorMatrix() {
            runTest("cfir/analysis-tests/testData/diagnostics2/invalid-declaration/noConstructorMatrix.cj")
        }

        @TestMetadata("recursiveConstructorCall.cj")
        @Test
        fun testRecursiveConstructorCall() {
            runTest("cfir/analysis-tests/testData/diagnostics2/invalid-declaration/recursiveConstructorCall.cj")
        }

        @TestMetadata("redeclarationMatrix.cj")
        @Test
        fun testRedeclarationMatrix() {
            runTest("cfir/analysis-tests/testData/diagnostics2/invalid-declaration/redeclarationMatrix.cj")
        }
    }

    @TestMetadata("jump")
    @TestDataPath("\$PROJECT_ROOT")
    @Nested
    inner class Jump : AbstractCfirLightTreeDiagnosticsTest() {
        @Test
        fun testAllFilesPresent() {
            assertAllFilesPresentByMetadata(this, "cfir/analysis-tests/testData/diagnostics2/jump")
        }

        @TestMetadata("invalidLoopControl.cj")
        @Test
        fun testInvalidLoopControl() {
            runTest("cfir/analysis-tests/testData/diagnostics2/jump/invalidLoopControl.cj")
        }

        @TestMetadata("invalidLoopControlTrailingLambda.cj")
        @Test
        fun testInvalidLoopControlTrailingLambda() {
            runTest("cfir/analysis-tests/testData/diagnostics2/jump/invalidLoopControlTrailingLambda.cj")
        }
    }

    @TestMetadata("match")
    @TestDataPath("\$PROJECT_ROOT")
    @Nested
    inner class Match : AbstractCfirLightTreeDiagnosticsTest() {
        @Test
        fun testAllFilesPresent() {
            assertAllFilesPresentByMetadata(this, "cfir/analysis-tests/testData/diagnostics2/match")
        }

        @TestMetadata("matchCaseHasNoType.cj")
        @Test
        fun testMatchCaseHasNoType() {
            runTest("cfir/analysis-tests/testData/diagnostics2/match/matchCaseHasNoType.cj")
        }

        @TestMetadata("notOverloadInMatch.cj")
        @Test
        fun testNotOverloadInMatch() {
            runTest("cfir/analysis-tests/testData/diagnostics2/match/notOverloadInMatch.cj")
        }
    }

    @TestMetadata("mut")
    @TestDataPath("\$PROJECT_ROOT")
    @Nested
    inner class Mut : AbstractCfirLightTreeDiagnosticsTest() {
        @Test
        fun testAllFilesPresent() {
            assertAllFilesPresentByMetadata(this, "cfir/analysis-tests/testData/diagnostics2/mut")
        }

        @TestMetadata("immutableFunctionRestrictions.cj")
        @Test
        fun testImmutableFunctionRestrictions() {
            runTest("cfir/analysis-tests/testData/diagnostics2/mut/immutableFunctionRestrictions.cj")
        }
    }

    @TestMetadata("pattern")
    @TestDataPath("\$PROJECT_ROOT")
    @Nested
    inner class Pattern : AbstractCfirLightTreeDiagnosticsTest() {
        @Test
        fun testAllFilesPresent() {
            assertAllFilesPresentByMetadata(this, "cfir/analysis-tests/testData/diagnostics2/pattern")
        }

        @TestMetadata("patternLegality.cj")
        @Test
        fun testPatternLegality() {
            runTest("cfir/analysis-tests/testData/diagnostics2/pattern/patternLegality.cj")
        }
    }

    @TestMetadata("range")
    @TestDataPath("\$PROJECT_ROOT")
    @Nested
    inner class Range : AbstractCfirLightTreeDiagnosticsTest() {
        @Test
        fun testAllFilesPresent() {
            assertAllFilesPresentByMetadata(this, "cfir/analysis-tests/testData/diagnostics2/range")
        }

        @TestMetadata("rangeDirectionPlaceholder.cj")
        @Test
        fun testRangeDirectionPlaceholder() {
            runTest("cfir/analysis-tests/testData/diagnostics2/range/rangeDirectionPlaceholder.cj")
        }

        @TestMetadata("rangeEndpointTypeMismatch.cj")
        @Test
        fun testRangeEndpointTypeMismatch() {
            runTest("cfir/analysis-tests/testData/diagnostics2/range/rangeEndpointTypeMismatch.cj")
        }

        @TestMetadata("rangeOneSidedAndStepMatrix.cj")
        @Test
        fun testRangeOneSidedAndStepMatrix() {
            runTest("cfir/analysis-tests/testData/diagnostics2/range/rangeOneSidedAndStepMatrix.cj")
        }

        @TestMetadata("rangeSingleEndpointInference.cj")
        @Test
        fun testRangeSingleEndpointInference() {
            runTest("cfir/analysis-tests/testData/diagnostics2/range/rangeSingleEndpointInference.cj")
        }

        @TestMetadata("rangeStepTypeMustBeInt64.cj")
        @Test
        fun testRangeStepTypeMustBeInt64() {
            runTest("cfir/analysis-tests/testData/diagnostics2/range/rangeStepTypeMustBeInt64.cj")
        }

        @TestMetadata("rangeStepZeroPlaceholder.cj")
        @Test
        fun testRangeStepZeroPlaceholder() {
            runTest("cfir/analysis-tests/testData/diagnostics2/range/rangeStepZeroPlaceholder.cj")
        }

        @TestMetadata("rangeTargetTypeMismatch.cj")
        @Test
        fun testRangeTargetTypeMismatch() {
            runTest("cfir/analysis-tests/testData/diagnostics2/range/rangeTargetTypeMismatch.cj")
        }
    }

    @TestMetadata("throw")
    @TestDataPath("\$PROJECT_ROOT")
    @Nested
    inner class Throw : AbstractCfirLightTreeDiagnosticsTest() {
        @Test
        fun testAllFilesPresent() {
            assertAllFilesPresentByMetadata(this, "cfir/analysis-tests/testData/diagnostics2/throw")
        }

        @TestMetadata("legalAndIllegalThrowPlaceholder.cj")
        @Test
        fun testLegalAndIllegalThrowPlaceholder() {
            runTest("cfir/analysis-tests/testData/diagnostics2/throw/legalAndIllegalThrowPlaceholder.cj")
        }

        @TestMetadata("throwAllowsErrorSubtypeAndRejectsOtherClasses.cj")
        @Test
        fun testThrowAllowsErrorSubtypeAndRejectsOtherClasses() {
            runTest("cfir/analysis-tests/testData/diagnostics2/throw/throwAllowsErrorSubtypeAndRejectsOtherClasses.cj")
        }

        @TestMetadata("throwCatchCombinedFlow.cj")
        @Test
        fun testThrowCatchCombinedFlow() {
            runTest("cfir/analysis-tests/testData/diagnostics2/throw/throwCatchCombinedFlow.cj")
        }

        @TestMetadata("throwGenericUpperBound.cj")
        @Test
        fun testThrowGenericUpperBound() {
            runTest("cfir/analysis-tests/testData/diagnostics2/throw/throwGenericUpperBound.cj")
        }

        @TestMetadata("throwHierarchyBoundary.cj")
        @Test
        fun testThrowHierarchyBoundary() {
            runTest("cfir/analysis-tests/testData/diagnostics2/throw/throwHierarchyBoundary.cj")
        }

        @TestMetadata("throwNothingAndErrorFamily.cj")
        @Test
        fun testThrowNothingAndErrorFamily() {
            runTest("cfir/analysis-tests/testData/diagnostics2/throw/throwNothingAndErrorFamily.cj")
        }

        @TestMetadata("throwScalarAndEnumPlaceholder.cj")
        @Test
        fun testThrowScalarAndEnumPlaceholder() {
            runTest("cfir/analysis-tests/testData/diagnostics2/throw/throwScalarAndEnumPlaceholder.cj")
        }

        @TestMetadata("throwTypePlaceholder.cj")
        @Test
        fun testThrowTypePlaceholder() {
            runTest("cfir/analysis-tests/testData/diagnostics2/throw/throwTypePlaceholder.cj")
        }
    }

    @TestMetadata("try")
    @TestDataPath("\$PROJECT_ROOT")
    @Nested
    inner class Try : AbstractCfirLightTreeDiagnosticsTest() {
        @Test
        fun testAllFilesPresent() {
            assertAllFilesPresentByMetadata(this, "cfir/analysis-tests/testData/diagnostics2/try")
        }

        @TestMetadata("catchOrderingAndDuplicate.cj")
        @Test
        fun testCatchOrderingAndDuplicate() {
            runTest("cfir/analysis-tests/testData/diagnostics2/try/catchOrderingAndDuplicate.cj")
        }

        @TestMetadata("catchTypeMustExtendException.cj")
        @Test
        fun testCatchTypeMustExtendException() {
            runTest("cfir/analysis-tests/testData/diagnostics2/try/catchTypeMustExtendException.cj")
        }

        @TestMetadata("duplicateCatchPlaceholder.cj")
        @Test
        fun testDuplicateCatchPlaceholder() {
            runTest("cfir/analysis-tests/testData/diagnostics2/try/duplicateCatchPlaceholder.cj")
        }

        @TestMetadata("finallyFlowPlaceholder.cj")
        @Test
        fun testFinallyFlowPlaceholder() {
            runTest("cfir/analysis-tests/testData/diagnostics2/try/finallyFlowPlaceholder.cj")
        }

        @TestMetadata("multiCatchJoinMismatch.cj")
        @Test
        fun testMultiCatchJoinMismatch() {
            runTest("cfir/analysis-tests/testData/diagnostics2/try/multiCatchJoinMismatch.cj")
        }

        @TestMetadata("tryCatchBranchTypeMismatch.cj")
        @Test
        fun testTryCatchBranchTypeMismatch() {
            runTest("cfir/analysis-tests/testData/diagnostics2/try/tryCatchBranchTypeMismatch.cj")
        }

        @TestMetadata("tryMultipleCatchJoinMatrix.cj")
        @Test
        fun testTryMultipleCatchJoinMatrix() {
            runTest("cfir/analysis-tests/testData/diagnostics2/try/tryMultipleCatchJoinMatrix.cj")
        }

        @TestMetadata("tryWithResourcesMultipleSpecs.cj")
        @Test
        fun testTryWithResourcesMultipleSpecs() {
            runTest("cfir/analysis-tests/testData/diagnostics2/try/tryWithResourcesMultipleSpecs.cj")
        }

        @TestMetadata("tryWithResourcesRequiresResource.cj")
        @Test
        fun testTryWithResourcesRequiresResource() {
            runTest("cfir/analysis-tests/testData/diagnostics2/try/tryWithResourcesRequiresResource.cj")
        }

        @TestMetadata("unreachableCatchPlaceholder.cj")
        @Test
        fun testUnreachableCatchPlaceholder() {
            runTest("cfir/analysis-tests/testData/diagnostics2/try/unreachableCatchPlaceholder.cj")
        }
    }

    @TestMetadata("visibility")
    @TestDataPath("\$PROJECT_ROOT")
    @Nested
    inner class Visibility : AbstractCfirLightTreeDiagnosticsTest() {
        @Test
        fun testAllFilesPresent() {
            assertAllFilesPresentByMetadata(this, "cfir/analysis-tests/testData/diagnostics2/visibility")
        }

        @TestMetadata("inheritedMemberAccess.cj")
        @Test
        fun testInheritedMemberAccess() {
            runTest("cfir/analysis-tests/testData/diagnostics2/visibility/inheritedMemberAccess.cj")
        }

        @TestMetadata("invisibleReferenceAndMember.cj")
        @Test
        fun testInvisibleReferenceAndMember() {
            runTest("cfir/analysis-tests/testData/diagnostics2/visibility/invisibleReferenceAndMember.cj")
        }

        @TestMetadata("privateMemberAccess.cj")
        @Test
        fun testPrivateMemberAccess() {
            runTest("cfir/analysis-tests/testData/diagnostics2/visibility/privateMemberAccess.cj")
        }

        @TestMetadata("privateMemberAccessExplicitThis.cj")
        @Test
        fun testPrivateMemberAccessExplicitThis() {
            runTest("cfir/analysis-tests/testData/diagnostics2/visibility/privateMemberAccessExplicitThis.cj")
        }

        @TestMetadata("privateMemberAndPropertyAccess.cj")
        @Test
        fun testPrivateMemberAndPropertyAccess() {
            runTest("cfir/analysis-tests/testData/diagnostics2/visibility/privateMemberAndPropertyAccess.cj")
        }

        @TestMetadata("privatePropertyAccess.cj")
        @Test
        fun testPrivatePropertyAccess() {
            runTest("cfir/analysis-tests/testData/diagnostics2/visibility/privatePropertyAccess.cj")
        }

        @TestMetadata("protectedAndInternalMatrix.cj")
        @Test
        fun testProtectedAndInternalMatrix() {
            runTest("cfir/analysis-tests/testData/diagnostics2/visibility/protectedAndInternalMatrix.cj")
        }
    }
}

private fun assertAllFilesPresentByMetadata(testInstance: Any, testDataRootRelativePath: String) {
    val testDataDir = resolveTestDataPath(testDataRootRelativePath)
    require(testDataDir.isDirectory) { "testData dir not found: ${testDataDir.path}" }

    val currentDir = currentClassTestDataDir(testInstance::class.java, testDataDir)
    val expected = currentDir.walkTopDown()
        .filter { it.isFile && it.extension == "cj" }
        .map { it.relativeTo(currentDir).invariantSeparatorsPath }
        .toSet()

    val covered = collectCoveredRelativePaths(testInstance::class.java, currentDir)
    val missing = expected - covered
    check(missing.isEmpty()) {
        "Missing generated tests for testData files in ${currentDir.path}: ${missing.sorted()}"
    }
}

private fun resolveTestDataPath(path: String): File {
    val direct = File(path)
    if (direct.isAbsolute) return direct
    if (direct.exists()) return direct

    var cursor = File(System.getProperty("user.dir", ".")).absoluteFile
    while (true) {
        val candidate = cursor.resolve(path)
        if (candidate.exists()) return candidate
        val parent = cursor.parentFile ?: break
        cursor = parent
    }
    return direct
}

private fun currentClassTestDataDir(testClass: Class<*>, rootTestDataDir: File): File {
    val classMetadata = testClass.getAnnotation(org.cangnova.cangjie.test.TestMetadata::class.java)
    if (classMetadata != null) {
        val metadataPath = classMetadata.value.replace('\\', '/')
        val candidate = File(metadataPath)
        if (candidate.isDirectory) return candidate
        val nestedCandidate = rootTestDataDir.resolve(metadataPath)
        if (nestedCandidate.isDirectory) return nestedCandidate
    }
    return rootTestDataDir
}

private fun collectCoveredRelativePaths(rootClass: Class<*>, testDataDir: File): Set<String> {
    val covered = linkedSetOf<String>()
    collectCoveredFromClass(rootClass, testDataDir, testDataDir, covered)
    return covered
}

private fun collectCoveredFromClass(
    klass: Class<*>,
    rootTestDataDir: File,
    inheritedDir: File,
    covered: MutableSet<String>,
) {
    val classScopedDir = classScopedDir(klass, rootTestDataDir, inheritedDir)
    for (method in klass.declaredMethods) {
        val metadata = method.getAnnotation(org.cangnova.cangjie.test.TestMetadata::class.java) ?: continue
        val metadataPath = metadata.value.replace('\\', '/')
        val candidate = classScopedDir.resolve(metadataPath)
        if (candidate.isFile && candidate.extension == "cj" && candidate.isUnder(rootTestDataDir)) {
            covered += candidate.relativeTo(rootTestDataDir).invariantSeparatorsPath
        }
    }
    for (nested in klass.declaredClasses) {
        collectCoveredFromClass(nested, rootTestDataDir, classScopedDir, covered)
    }
}

private fun classScopedDir(
    klass: Class<*>,
    rootTestDataDir: File,
    inheritedDir: File,
): File {
    val classMetadata = klass.getAnnotation(org.cangnova.cangjie.test.TestMetadata::class.java) ?: return inheritedDir
    val metadataPath = classMetadata.value.replace('\\', '/')
    val direct = resolveTestDataPath(metadataPath)
    if (direct.isDirectory) return direct
    val nested = rootTestDataDir.resolve(metadataPath)
    if (nested.isDirectory) return nested
    val inheritedNested = inheritedDir.resolve(metadataPath)
    if (inheritedNested.isDirectory) return inheritedNested
    return inheritedDir
}

private fun File.isUnder(parent: File): Boolean {
    val parentPath = parent.canonicalFile.toPath()
    val childPath = canonicalFile.toPath()
    return childPath.startsWith(parentPath)
}
