package org.cangnova.cangjie.codegen.parity

import java.io.File

object TestGeneratorForCodegenParity {
    @JvmStatic
    fun main(args: Array<String>) {
        val projectRoot = if (args.isNotEmpty()) File(args[0]) else File(System.getProperty("user.dir"))
        val modelRelativePath = "compiler/codegen/testData/chirParity"
        val testDataRoot = projectRoot.resolve(modelRelativePath)
        require(testDataRoot.exists()) { "testData root not found: ${testDataRoot.path}" }

        val outputFile = projectRoot.resolve(
            "compiler/codegen/tests-gen/org/cangnova/cangjie/codegen/parity/CodegenParityTestGenerated.kt",
        )
        outputFile.parentFile.mkdirs()
        outputFile.writeText(render(projectRoot, testDataRoot, modelRelativePath), Charsets.UTF_8)
        println("Generated: ${outputFile.path}")
    }

    private fun render(projectRoot: File, testDataRoot: File, rootRelativePath: String): String {
        val methods = mutableListOf<String>()
        val usedNames = linkedSetOf<String>()

        testDataRoot.walkTopDown()
            .filter { it.isFile && it.name.endsWith(".chir.json") }
            .sortedBy { projectRoot.toPath().relativize(it.toPath()).toString().replace('\\', '/') }
            .forEach { file ->
                val relativePath = projectRoot.toPath().relativize(file.toPath()).toString().replace('\\', '/')
                val stem = testDataRoot.toPath().relativize(file.toPath()).toString().replace('\\', '/').removeSuffix(".chir.json")
                val methodBase = "test" + stem
                    .split(Regex("[^A-Za-z0-9]+"))
                    .filter { it.isNotBlank() }
                    .joinToString("") { it.replaceFirstChar { c -> c.uppercaseChar() } }
                val methodName = uniqueMethodName(methodBase, usedNames)
                methods += """
                    fun $methodName() {
                        runTest("$relativePath")
                    }
                """.trimIndent()
            }

        return buildString {
            appendLine("package org.cangnova.cangjie.codegen.parity")
            appendLine()
            appendLine("/** AUTO-GENERATED by TestGeneratorForCodegenParity. DO NOT EDIT MANUALLY. */")
            appendLine("class CodegenParityTestGenerated : AbstractCodegenParityTestCase() {")
            appendLine("    fun testAllFilesPresentInChirParity() {")
            appendLine("        assertAllFilesPresentByMetadata(\"$rootRelativePath\")")
            appendLine("    }")
            appendLine()
            methods.forEach { method ->
                method.lineSequence().forEach { appendLine("    $it") }
                appendLine()
            }
            appendLine("}")
        }
    }

    private fun uniqueMethodName(base: String, usedNames: MutableSet<String>): String {
        if (usedNames.add(base)) return base
        var index = 2
        while (true) {
            val candidate = "${base}_$index"
            if (usedNames.add(candidate)) return candidate
            index++
        }
    }
}
