package org.cangnova.cangjie.cfir.analysis.tests.CfirAnalysisLLTPsiTest.llt.nonExhaustiveEnum.bad

import com.intellij.testFramework.TestDataPath
import org.cangnova.cangjie.ObsoleteTestInfrastructure
import org.cangnova.cangjie.cfir.analysis.tests.runners.AbstractCfirPsiLlTDiagnosticsTest
import org.cangnova.cangjie.test.TestMetadata
import org.junit.jupiter.api.Test
import java.io.File
import org.cangnova.cangjie.cfir.analysis.tests.assertAllFilesPresentByMetadata

/** AUTO-GENERATED by TestGeneratorForCfirAnalysisTests. DO NOT EDIT MANUALLY. */
@TestMetadata("cfir/analysis-tests/testData/llt/nonExhaustiveEnum/bad")
@TestDataPath("${'$'}PROJECT_ROOT")
@OptIn(ObsoleteTestInfrastructure::class)
@ObsoleteTestInfrastructure
class BadGenerated : AbstractCfirPsiLlTDiagnosticsTest() {
    @Test
    fun testAllFilesPresent() {
        assertAllFilesPresentByMetadata(this, "cfir/analysis-tests/testData/llt/nonExhaustiveEnum/bad")
    }

    @TestMetadata("missingEllipse.cj")
    @Test
    fun testMissingEllipse() {
        runTest("cfir/analysis-tests/testData/llt/nonExhaustiveEnum/bad/missingEllipse.cj")
    }

    @TestMetadata("missingEllipse_generic.cj")
    @Test
    fun testMissingEllipseGeneric() {
        runTest("cfir/analysis-tests/testData/llt/nonExhaustiveEnum/bad/missingEllipse_generic.cj")
    }

    @TestMetadata("missingEllipse_imported.cj")
    @Test
    fun testMissingEllipseImported() {
        runTest("cfir/analysis-tests/testData/llt/nonExhaustiveEnum/bad/missingEllipse_imported.cj")
    }

    @TestMetadata("nested_match.cj")
    @Test
    fun testNestedMatch() {
        runTest("cfir/analysis-tests/testData/llt/nonExhaustiveEnum/bad/nested_match.cj")
    }

    @TestMetadata("nested_match_guard.cj")
    @Test
    fun testNestedMatchGuard() {
        runTest("cfir/analysis-tests/testData/llt/nonExhaustiveEnum/bad/nested_match_guard.cj")
    }
}

