package org.cangnova.cangjie.chir.core.expression

object ChirOperationSets {
    val unaryOperators: Set<String> = setOf(
        "neg",
        "ineg",
        "fneg",
        "not",
        "bitnot",
        "logical_not",
        "lnot",
        "copy",
        "mov",
        "identity",
    )

    val binaryOperators: Set<String> = setOf(
        "add",
        "+",
        "plus",
        "sub",
        "-",
        "minus",
        "mul",
        "*",
        "times",
        "div",
        "/",
        "udiv",
        "rem",
        "%",
        "urem",
        "and",
        "or",
        "xor",
        "shl",
        "ashr",
        "lshr",
        "eq",
        "==",
        "ne",
        "!=",
        "lt",
        "<",
        "slt",
        "le",
        "<=",
        "sle",
        "gt",
        ">",
        "sgt",
        "ge",
        ">=",
        "sge",
        "ult",
        "ule",
        "ugt",
        "uge",
        "feq",
        "fne",
        "flt",
        "fle",
        "fgt",
        "fge",
    )

    val memoryOperations: Set<String> = setOf(
        "load",
        "store",
        "alloca",
        "gep",
        "getelementptr",
        "getelementptr.inbounds",
        "getelementptr inbounds",
    )

    val otherOperations: Set<String> = setOf(
        "select",
        "bitcast",
        "ptrtoint",
        "inttoptr",
        "trunc",
        "zext",
        "sext",
        "fptrunc",
        "fpext",
        "sitofp",
        "uitofp",
        "fptosi",
        "fptoui",
        "phi",
        "jvm.new",
        "jvm.getfield",
        "jvm.putfield",
        "jvm.getstatic",
        "jvm.putstatic",
        "jvm.newarray",
        "jvm.arrayload",
        "jvm.arraystore",
        "jvm.arraylength",
        "jvm.checkcast",
        "jvm.instanceof",
    )
}
