package org.cangnova.cangjie.cfir.analysis.tests.CfirAnalysisLLTTest.llt.record.static_init

import com.intellij.testFramework.TestDataPath
import org.cangnova.cangjie.ObsoleteTestInfrastructure
import org.cangnova.cangjie.cfir.analysis.tests.runners.AbstractCfirLightTreeLlTDiagnosticsTest
import org.cangnova.cangjie.test.TestMetadata
import org.junit.jupiter.api.Test
import java.io.File
import org.cangnova.cangjie.cfir.analysis.tests.assertAllFilesPresentByMetadata

/** AUTO-GENERATED by TestGeneratorForCfirAnalysisTests. DO NOT EDIT MANUALLY. */
@TestMetadata("cfir/analysis-tests/testData/llt/record/static_init")
@TestDataPath("${'$'}PROJECT_ROOT")
@OptIn(ObsoleteTestInfrastructure::class)
@ObsoleteTestInfrastructure
class StaticInitGenerated : AbstractCfirLightTreeLlTDiagnosticsTest() {
    @Test
    fun testAllFilesPresent() {
        assertAllFilesPresentByMetadata(this, "cfir/analysis-tests/testData/llt/record/static_init")
    }

    @TestMetadata("static_init_01.cj")
    @Test
    fun testStaticInit01() {
        runTest("cfir/analysis-tests/testData/llt/record/static_init/static_init_01.cj")
    }

    @TestMetadata("static_init_02.cj")
    @Test
    fun testStaticInit02() {
        runTest("cfir/analysis-tests/testData/llt/record/static_init/static_init_02.cj")
    }

    @TestMetadata("static_init_03.cj")
    @Test
    fun testStaticInit03() {
        runTest("cfir/analysis-tests/testData/llt/record/static_init/static_init_03.cj")
    }
}

