package org.cangnova.cangjie.cfir.analysis.tests.CfirAnalysisLLTPsiTest.llt.lambda.trailing_closure

import com.intellij.testFramework.TestDataPath
import org.cangnova.cangjie.ObsoleteTestInfrastructure
import org.cangnova.cangjie.cfir.analysis.tests.runners.AbstractCfirPsiLlTDiagnosticsTest
import org.cangnova.cangjie.test.TestMetadata
import org.junit.jupiter.api.Test
import java.io.File
import org.cangnova.cangjie.cfir.analysis.tests.assertAllFilesPresentByMetadata

/** AUTO-GENERATED by TestGeneratorForCfirAnalysisTests. DO NOT EDIT MANUALLY. */
@TestMetadata("cfir/analysis-tests/testData/llt/lambda/trailing_closure")
@TestDataPath("${'$'}PROJECT_ROOT")
@OptIn(ObsoleteTestInfrastructure::class)
@ObsoleteTestInfrastructure
class TrailingClosureGenerated : AbstractCfirPsiLlTDiagnosticsTest() {
    @Test
    fun testAllFilesPresent() {
        assertAllFilesPresentByMetadata(this, "cfir/analysis-tests/testData/llt/lambda/trailing_closure")
    }

    @TestMetadata("trailing_closure01.cj")
    @Test
    fun testTrailingClosure01() {
        runTest("cfir/analysis-tests/testData/llt/lambda/trailing_closure/trailing_closure01.cj")
    }

    @TestMetadata("trailing_closure02.cj")
    @Test
    fun testTrailingClosure02() {
        runTest("cfir/analysis-tests/testData/llt/lambda/trailing_closure/trailing_closure02.cj")
    }

    @TestMetadata("trailing_closure03.cj")
    @Test
    fun testTrailingClosure03() {
        runTest("cfir/analysis-tests/testData/llt/lambda/trailing_closure/trailing_closure03.cj")
    }

    @TestMetadata("trailing_closure04.cj")
    @Test
    fun testTrailingClosure04() {
        runTest("cfir/analysis-tests/testData/llt/lambda/trailing_closure/trailing_closure04.cj")
    }

    @TestMetadata("trailing_closure06.cj")
    @Test
    fun testTrailingClosure06() {
        runTest("cfir/analysis-tests/testData/llt/lambda/trailing_closure/trailing_closure06.cj")
    }

    @TestMetadata("trailing_closure07.cj")
    @Test
    fun testTrailingClosure07() {
        runTest("cfir/analysis-tests/testData/llt/lambda/trailing_closure/trailing_closure07.cj")
    }

    @TestMetadata("trailing_closure09.cj")
    @Test
    fun testTrailingClosure09() {
        runTest("cfir/analysis-tests/testData/llt/lambda/trailing_closure/trailing_closure09.cj")
    }

    @TestMetadata("trailing_closure13.cj")
    @Test
    fun testTrailingClosure13() {
        runTest("cfir/analysis-tests/testData/llt/lambda/trailing_closure/trailing_closure13.cj")
    }

    @TestMetadata("trailing_closure14.cj")
    @Test
    fun testTrailingClosure14() {
        runTest("cfir/analysis-tests/testData/llt/lambda/trailing_closure/trailing_closure14.cj")
    }

    @TestMetadata("trailing_closure15.cj")
    @Test
    fun testTrailingClosure15() {
        runTest("cfir/analysis-tests/testData/llt/lambda/trailing_closure/trailing_closure15.cj")
    }

    @TestMetadata("trailing_closure16.cj")
    @Test
    fun testTrailingClosure16() {
        runTest("cfir/analysis-tests/testData/llt/lambda/trailing_closure/trailing_closure16.cj")
    }

    @TestMetadata("trailing_closure_generic_upper.cj")
    @Test
    fun testTrailingClosureGenericUpper() {
        runTest("cfir/analysis-tests/testData/llt/lambda/trailing_closure/trailing_closure_generic_upper.cj")
    }

    @TestMetadata("trailing_closure_named_args_01.cj")
    @Test
    fun testTrailingClosureNamedArgs01() {
        runTest("cfir/analysis-tests/testData/llt/lambda/trailing_closure/trailing_closure_named_args_01.cj")
    }

    @TestMetadata("trailing_closure_named_args_02.cj")
    @Test
    fun testTrailingClosureNamedArgs02() {
        runTest("cfir/analysis-tests/testData/llt/lambda/trailing_closure/trailing_closure_named_args_02.cj")
    }

    @TestMetadata("trailing_closure_nesting_01.cj")
    @Test
    fun testTrailingClosureNesting01() {
        runTest("cfir/analysis-tests/testData/llt/lambda/trailing_closure/trailing_closure_nesting_01.cj")
    }

    @TestMetadata("trailing_closure_type_mismatch_01.cj")
    @Test
    fun testTrailingClosureTypeMismatch01() {
        runTest("cfir/analysis-tests/testData/llt/lambda/trailing_closure/trailing_closure_type_mismatch_01.cj")
    }

    @TestMetadata("trailing_closure_type_mismatch_02.cj")
    @Test
    fun testTrailingClosureTypeMismatch02() {
        runTest("cfir/analysis-tests/testData/llt/lambda/trailing_closure/trailing_closure_type_mismatch_02.cj")
    }
}

