package org.cangnova.cangjie.cfir.analysis.tests.CfirAnalysisLLTTest.llt.generics.pkgs0024_ClassTypeArgs

import com.intellij.testFramework.TestDataPath
import org.cangnova.cangjie.ObsoleteTestInfrastructure
import org.cangnova.cangjie.cfir.analysis.tests.runners.AbstractCfirLightTreeLlTDiagnosticsTest
import org.cangnova.cangjie.test.TestMetadata
import org.junit.jupiter.api.Test
import java.io.File
import org.cangnova.cangjie.cfir.analysis.tests.assertAllFilesPresentByMetadata

/** AUTO-GENERATED by TestGeneratorForCfirAnalysisTests. DO NOT EDIT MANUALLY. */
@TestMetadata("cfir/analysis-tests/testData/llt/generics/pkgs0024_ClassTypeArgs")
@TestDataPath("${'$'}PROJECT_ROOT")
@OptIn(ObsoleteTestInfrastructure::class)
@ObsoleteTestInfrastructure
class Pkgs0024ClassTypeArgsGenerated : AbstractCfirLightTreeLlTDiagnosticsTest() {
    @Test
    fun testAllFilesPresent() {
        assertAllFilesPresentByMetadata(this, "cfir/analysis-tests/testData/llt/generics/pkgs0024_ClassTypeArgs")
    }

    @TestMetadata("pkgs0024_ClassTypeArgs.cj")
    @Test
    fun testPkgs0024ClassTypeArgs() {
        runTest("cfir/analysis-tests/testData/llt/generics/pkgs0024_ClassTypeArgs/pkgs0024_ClassTypeArgs.cj")
    }
}

