<!sema_missing_entry!>/<!>/ Copyright (c) Huawei Technologies Co., Ltd. 2025. All rights reserved.
// This source file is part of the Cangjie project, licensed under Apache-2.0
// with Runtime Library Exception.
//
// See https://cangjie-lang.cn/pages/LICENSE for license information.


func b(bo!: (<!sema_undeclared_type_name!>R<!>esult, <!sema_generic_type_without_type_argument!>R<!>ange) -> Bool): Unit {}
