

func F(a: Int64): Int64 {
    return a
}

main() {
    let a: Int64 = 1
    // 40 F
    var b = F(
        F(
            F(
                F(
                    F(
                        F(
                            F(
                                F(
                                    F(
                                        F(
                                            F(
                                                F(
                                                    F(
                                                        F(
                                                            F(
                                                                F(
                                                                    F(
                                                                        F(
                                                                            F(
                                                                                F(
                                                                                    F(
                                                                                        F(
                                                                                            F(
                                                                                                F(
                                                                                                    F(
                                                                                                        F(
                                                                                                            F(
                                                                                                                F(
                                                                                                                    F(
                                                                                                                        F(
                                                                                                                            F(
                                                                                                                                F(
                                                                                                                                    F(
                                                                                                                                        F(
                                                                                                                                            F(
                                                                                                                                                F(
                                                                                                                                                    F(
                                                                                                                                                        F(
                                                                                                                                                            F(
                                                                                                                                                                F(
                                                                                                                                                                    F(
                                                                                                                                                                        F(
                                                                                                                                                                            a))))))))))))))))))))))))))))))))))))))))))
    println(b)
    0
}
