package org.cangnova.cangjie.cfir.analysis.tests.CfirAnalysisDiagnostics2Test.diagnostics2.inout

import com.intellij.testFramework.TestDataPath
import org.cangnova.cangjie.ObsoleteTestInfrastructure
import org.cangnova.cangjie.cfir.analysis.tests.runners.AbstractCfirLightTreeDiagnosticsTest
import org.cangnova.cangjie.test.TestMetadata
import org.junit.jupiter.api.Test
import java.io.File
import org.cangnova.cangjie.cfir.analysis.tests.assertAllFilesPresentByMetadata

/** AUTO-GENERATED by TestGeneratorForCfirAnalysisTests. DO NOT EDIT MANUALLY. */
@TestMetadata("cfir/analysis-tests/testData/diagnostics2/inout")
@TestDataPath("${'$'}PROJECT_ROOT")
@OptIn(ObsoleteTestInfrastructure::class)
@ObsoleteTestInfrastructure
class InoutGenerated : AbstractCfirLightTreeDiagnosticsTest() {
    @Test
    fun testAllFilesPresent() {
        assertAllFilesPresentByMetadata(this, "cfir/analysis-tests/testData/diagnostics2/inout")
    }

    @TestMetadata("inoutNonLValuePlaceholder.cj")
    @Test
    fun testInoutNonLValuePlaceholder() {
        runTest("cfir/analysis-tests/testData/diagnostics2/inout/inoutNonLValuePlaceholder.cj")
    }

    @TestMetadata("inoutPropertyAndDuplicatePlaceholder.cj")
    @Test
    fun testInoutPropertyAndDuplicatePlaceholder() {
        runTest("cfir/analysis-tests/testData/diagnostics2/inout/inoutPropertyAndDuplicatePlaceholder.cj")
    }

    @TestMetadata("inoutRequiresVarVariable.cj")
    @Test
    fun testInoutRequiresVarVariable() {
        runTest("cfir/analysis-tests/testData/diagnostics2/inout/inoutRequiresVarVariable.cj")
    }
}

