package org.cangnova.cangjie.cfir.analysis.tests.CfirAnalysisLLTPsiTest.llt.assign.multipleAssignExpr

import com.intellij.testFramework.TestDataPath
import org.cangnova.cangjie.ObsoleteTestInfrastructure
import org.cangnova.cangjie.cfir.analysis.tests.runners.AbstractCfirPsiLlTDiagnosticsTest
import org.cangnova.cangjie.test.TestMetadata
import org.junit.jupiter.api.Test
import java.io.File
import org.cangnova.cangjie.cfir.analysis.tests.assertAllFilesPresentByMetadata

/** AUTO-GENERATED by TestGeneratorForCfirAnalysisTests. DO NOT EDIT MANUALLY. */
@TestMetadata("cfir/analysis-tests/testData/llt/assign/multipleAssignExpr")
@TestDataPath("${'$'}PROJECT_ROOT")
@OptIn(ObsoleteTestInfrastructure::class)
@ObsoleteTestInfrastructure
class MultipleAssignExprGenerated : AbstractCfirPsiLlTDiagnosticsTest() {
    @Test
    fun testAllFilesPresent() {
        assertAllFilesPresentByMetadata(this, "cfir/analysis-tests/testData/llt/assign/multipleAssignExpr")
    }

    @TestMetadata("case01.cj")
    @Test
    fun testCase01() {
        runTest("cfir/analysis-tests/testData/llt/assign/multipleAssignExpr/case01.cj")
    }

    @TestMetadata("case02.cj")
    @Test
    fun testCase02() {
        runTest("cfir/analysis-tests/testData/llt/assign/multipleAssignExpr/case02.cj")
    }

    @TestMetadata("case03.cj")
    @Test
    fun testCase03() {
        runTest("cfir/analysis-tests/testData/llt/assign/multipleAssignExpr/case03.cj")
    }

    @TestMetadata("case04.cj")
    @Test
    fun testCase04() {
        runTest("cfir/analysis-tests/testData/llt/assign/multipleAssignExpr/case04.cj")
    }

    @TestMetadata("case05.cj")
    @Test
    fun testCase05() {
        runTest("cfir/analysis-tests/testData/llt/assign/multipleAssignExpr/case05.cj")
    }

    @TestMetadata("case06.cj")
    @Test
    fun testCase06() {
        runTest("cfir/analysis-tests/testData/llt/assign/multipleAssignExpr/case06.cj")
    }

    @TestMetadata("case07.cj")
    @Test
    fun testCase07() {
        runTest("cfir/analysis-tests/testData/llt/assign/multipleAssignExpr/case07.cj")
    }

    @TestMetadata("case08.cj")
    @Test
    fun testCase08() {
        runTest("cfir/analysis-tests/testData/llt/assign/multipleAssignExpr/case08.cj")
    }

    @TestMetadata("err_optional_chain_00.cj")
    @Test
    fun testErrOptionalChain00() {
        runTest("cfir/analysis-tests/testData/llt/assign/multipleAssignExpr/err_optional_chain_00.cj")
    }
}

