package org.cangnova.cangjie.cfir.analysis.tests.CfirAnalysisLLTTest.llt.generics.generic_member

import com.intellij.testFramework.TestDataPath
import org.cangnova.cangjie.ObsoleteTestInfrastructure
import org.cangnova.cangjie.cfir.analysis.tests.runners.AbstractCfirLightTreeLlTDiagnosticsTest
import org.cangnova.cangjie.test.TestMetadata
import org.junit.jupiter.api.Test
import java.io.File
import org.cangnova.cangjie.cfir.analysis.tests.assertAllFilesPresentByMetadata

/** AUTO-GENERATED by TestGeneratorForCfirAnalysisTests. DO NOT EDIT MANUALLY. */
@TestMetadata("cfir/analysis-tests/testData/llt/generics/generic_member")
@TestDataPath("${'$'}PROJECT_ROOT")
@OptIn(ObsoleteTestInfrastructure::class)
@ObsoleteTestInfrastructure
class GenericMemberGenerated : AbstractCfirLightTreeLlTDiagnosticsTest() {
    @Test
    fun testAllFilesPresent() {
        assertAllFilesPresentByMetadata(this, "cfir/analysis-tests/testData/llt/generics/generic_member")
    }

    @TestMetadata("generic_member_func_01.cj")
    @Test
    fun testGenericMemberFunc01() {
        runTest("cfir/analysis-tests/testData/llt/generics/generic_member/generic_member_func_01.cj")
    }

    @TestMetadata("generic_member_func_02.cj")
    @Test
    fun testGenericMemberFunc02() {
        runTest("cfir/analysis-tests/testData/llt/generics/generic_member/generic_member_func_02.cj")
    }

    @TestMetadata("generic_member_func_03.cj")
    @Test
    fun testGenericMemberFunc03() {
        runTest("cfir/analysis-tests/testData/llt/generics/generic_member/generic_member_func_03.cj")
    }

    @TestMetadata("generic_member_func_04.cj")
    @Test
    fun testGenericMemberFunc04() {
        runTest("cfir/analysis-tests/testData/llt/generics/generic_member/generic_member_func_04.cj")
    }

    @TestMetadata("generic_member_func_05.cj")
    @Test
    fun testGenericMemberFunc05() {
        runTest("cfir/analysis-tests/testData/llt/generics/generic_member/generic_member_func_05.cj")
    }
}

