package org.cangnova.cangjie.codegen.parity

/** AUTO-GENERATED by TestGeneratorForCodegenParity. DO NOT EDIT MANUALLY. */
class CodegenParityTestGenerated : AbstractCodegenParityTestCase() {
    fun testAllFilesPresentInChirParity() {
        assertAllFilesPresentByMetadata("compiler/codegen/testData/chirParity")
    }

    fun testAdvancedBitwiseShiftChain() {
        runTest("compiler/codegen/testData/chirParity/advanced/bitwiseShiftChain.chir.json")
    }

    fun testAdvancedBranchPhi() {
        runTest("compiler/codegen/testData/chirParity/advanced/branchPhi.chir.json")
    }

    fun testAdvancedCastChain() {
        runTest("compiler/codegen/testData/chirParity/advanced/castChain.chir.json")
    }

    fun testAdvancedFloatCastChain() {
        runTest("compiler/codegen/testData/chirParity/advanced/floatCastChain.chir.json")
    }

    fun testAdvancedFloatCompare() {
        runTest("compiler/codegen/testData/chirParity/advanced/floatCompare.chir.json")
    }

    fun testAdvancedGepSpacedInbounds() {
        runTest("compiler/codegen/testData/chirParity/advanced/gepSpacedInbounds.chir.json")
    }

    fun testAdvancedImportedCall() {
        runTest("compiler/codegen/testData/chirParity/advanced/importedCall.chir.json")
    }

    fun testAdvancedMemoryGepAlign() {
        runTest("compiler/codegen/testData/chirParity/advanced/memoryGepAlign.chir.json")
    }

    fun testAdvancedOperationMatrix() {
        runTest("compiler/codegen/testData/chirParity/advanced/operationMatrix.chir.json")
    }

    fun testAdvancedPtrIntCastChain() {
        runTest("compiler/codegen/testData/chirParity/advanced/ptrIntCastChain.chir.json")
    }

    fun testAdvancedRuntimeGlobals() {
        runTest("compiler/codegen/testData/chirParity/advanced/runtimeGlobals.chir.json")
    }

    fun testAdvancedSelectI32() {
        runTest("compiler/codegen/testData/chirParity/advanced/selectI32.chir.json")
    }

    fun testAdvancedTailCallCc() {
        runTest("compiler/codegen/testData/chirParity/advanced/tailCallCc.chir.json")
    }

    fun testAdvancedThrowUnwind() {
        runTest("compiler/codegen/testData/chirParity/advanced/throwUnwind.chir.json")
    }

    fun testAdvancedUnaryAlias() {
        runTest("compiler/codegen/testData/chirParity/advanced/unaryAlias.chir.json")
    }

    fun testAdvancedUnaryLogicNot() {
        runTest("compiler/codegen/testData/chirParity/advanced/unaryLogicNot.chir.json")
    }

    fun testAdvancedUnaryMisc() {
        runTest("compiler/codegen/testData/chirParity/advanced/unaryMisc.chir.json")
    }

    fun testAdvancedUnsignedChain() {
        runTest("compiler/codegen/testData/chirParity/advanced/unsignedChain.chir.json")
    }

    fun testAdvancedVoidCall() {
        runTest("compiler/codegen/testData/chirParity/advanced/voidCall.chir.json")
    }

    fun testBasicReturnFortyTwo() {
        runTest("compiler/codegen/testData/chirParity/basic/returnFortyTwo.chir.json")
    }

    fun testBasicReturnIntMax() {
        runTest("compiler/codegen/testData/chirParity/basic/returnIntMax.chir.json")
    }

    fun testBasicReturnIntMin() {
        runTest("compiler/codegen/testData/chirParity/basic/returnIntMin.chir.json")
    }

    fun testBasicReturnIntMinPlusOne() {
        runTest("compiler/codegen/testData/chirParity/basic/returnIntMinPlusOne.chir.json")
    }

    fun testBasicReturnLargeNegative() {
        runTest("compiler/codegen/testData/chirParity/basic/returnLargeNegative.chir.json")
    }

    fun testBasicReturnLargePositive() {
        runTest("compiler/codegen/testData/chirParity/basic/returnLargePositive.chir.json")
    }

    fun testBasicReturnNegOne() {
        runTest("compiler/codegen/testData/chirParity/basic/returnNegOne.chir.json")
    }

    fun testBasicReturnNegSeven() {
        runTest("compiler/codegen/testData/chirParity/basic/returnNegSeven.chir.json")
    }

    fun testBasicReturnOne() {
        runTest("compiler/codegen/testData/chirParity/basic/returnOne.chir.json")
    }

    fun testBasicReturnSeven() {
        runTest("compiler/codegen/testData/chirParity/basic/returnSeven.chir.json")
    }

    fun testBasicReturnTwo() {
        runTest("compiler/codegen/testData/chirParity/basic/returnTwo.chir.json")
    }

    fun testBasicReturnZero() {
        runTest("compiler/codegen/testData/chirParity/basic/returnZero.chir.json")
    }

    fun testBasicSimpleReturn() {
        runTest("compiler/codegen/testData/chirParity/basic/simpleReturn.chir.json")
    }

}
