package org.cangnova.cangjie.cfir.analysis.tests.CfirAnalysisLLTTest.llt.redefinition.private_func._04_diff_file_extend

import com.intellij.testFramework.TestDataPath
import org.cangnova.cangjie.ObsoleteTestInfrastructure
import org.cangnova.cangjie.cfir.analysis.tests.runners.AbstractCfirLightTreeLlTDiagnosticsTest
import org.cangnova.cangjie.test.TestMetadata
import org.junit.jupiter.api.Test
import java.io.File
import org.cangnova.cangjie.cfir.analysis.tests.assertAllFilesPresentByMetadata

/** AUTO-GENERATED by TestGeneratorForCfirAnalysisTests. DO NOT EDIT MANUALLY. */
@TestMetadata("cfir/analysis-tests/testData/llt/redefinition/private_func/04_diff_file_extend")
@TestDataPath("${'$'}PROJECT_ROOT")
@OptIn(ObsoleteTestInfrastructure::class)
@ObsoleteTestInfrastructure
class _04DiffFileExtendGenerated : AbstractCfirLightTreeLlTDiagnosticsTest() {
    @Test
    fun testAllFilesPresent() {
        assertAllFilesPresentByMetadata(this, "cfir/analysis-tests/testData/llt/redefinition/private_func/04_diff_file_extend")
    }

    @TestMetadata("1.cj")
    @Test
    fun test1() {
        runTest("cfir/analysis-tests/testData/llt/redefinition/private_func/04_diff_file_extend/1.cj")
    }

    @TestMetadata("2.cj")
    @Test
    fun test2() {
        runTest("cfir/analysis-tests/testData/llt/redefinition/private_func/04_diff_file_extend/2.cj")
    }
}

