package org.cangnova.cangjie.cfir.analysis.tests.CfirAnalysisDiagnostics2WithoutAliasExpansionTest.diagnostics2.match

import com.intellij.testFramework.TestDataPath
import org.cangnova.cangjie.ObsoleteTestInfrastructure
import org.cangnova.cangjie.cfir.analysis.tests.runners.AbstractCfirLightTreeDiagnosticsWithoutAliasExpansionTest
import org.cangnova.cangjie.test.TestMetadata
import org.junit.jupiter.api.Test
import java.io.File
import org.cangnova.cangjie.cfir.analysis.tests.assertAllFilesPresentByMetadata

/** AUTO-GENERATED by TestGeneratorForCfirAnalysisTests. DO NOT EDIT MANUALLY. */
@TestMetadata("cfir/analysis-tests/testData/diagnostics2/match")
@TestDataPath("${'$'}PROJECT_ROOT")
@OptIn(ObsoleteTestInfrastructure::class)
@ObsoleteTestInfrastructure
class MatchGenerated : AbstractCfirLightTreeDiagnosticsWithoutAliasExpansionTest() {
    @Test
    fun testAllFilesPresent() {
        assertAllFilesPresentByMetadata(this, "cfir/analysis-tests/testData/diagnostics2/match")
    }

    @TestMetadata("matchCaseHasNoType.cj")
    @Test
    fun testMatchCaseHasNoType() {
        runTest("cfir/analysis-tests/testData/diagnostics2/match/matchCaseHasNoType.cj")
    }

    @TestMetadata("notOverloadInMatch.cj")
    @Test
    fun testNotOverloadInMatch() {
        runTest("cfir/analysis-tests/testData/diagnostics2/match/notOverloadInMatch.cj")
    }
}

