package org.cangnova.cangjie.cfir.analysis.tests.CfirAnalysisDiagnosticsPsiTest.diagnostics.unresolved

import com.intellij.testFramework.TestDataPath
import org.cangnova.cangjie.ObsoleteTestInfrastructure
import org.cangnova.cangjie.cfir.analysis.tests.runners.AbstractCfirPsiDiagnosticTest
import org.cangnova.cangjie.test.TestMetadata
import org.junit.jupiter.api.Test
import java.io.File
import org.cangnova.cangjie.cfir.analysis.tests.assertAllFilesPresentByMetadata

/** AUTO-GENERATED by TestGeneratorForCfirAnalysisTests. DO NOT EDIT MANUALLY. */
@TestMetadata("cfir/analysis-tests/testData/diagnostics/unresolved")
@TestDataPath("${'$'}PROJECT_ROOT")
@OptIn(ObsoleteTestInfrastructure::class)
@ObsoleteTestInfrastructure
class UnresolvedGenerated : AbstractCfirPsiDiagnosticTest() {
    @Test
    fun testAllFilesPresent() {
        assertAllFilesPresentByMetadata(this, "cfir/analysis-tests/testData/diagnostics/unresolved")
    }

    @TestMetadata("std.core.cj")
    @Test
    fun testStdCore() {
        runTest("cfir/analysis-tests/testData/diagnostics/unresolved/std.core.cj")
    }

    @TestMetadata("unresolvedNameCall.cj")
    @Test
    fun testUnresolvedNameCall() {
        runTest("cfir/analysis-tests/testData/diagnostics/unresolved/unresolvedNameCall.cj")
    }

    @TestMetadata("unresolvedReferenceName.cj")
    @Test
    fun testUnresolvedReferenceName() {
        runTest("cfir/analysis-tests/testData/diagnostics/unresolved/unresolvedReferenceName.cj")
    }

    @TestMetadata("unresolvedSymbolType.cj")
    @Test
    fun testUnresolvedSymbolType() {
        runTest("cfir/analysis-tests/testData/diagnostics/unresolved/unresolvedSymbolType.cj")
    }
}

