package org.cangnova.cangjie.cfir.analysis.tests.CfirAnalysisLLTTest.llt.while_let_expr

import com.intellij.testFramework.TestDataPath
import org.cangnova.cangjie.ObsoleteTestInfrastructure
import org.cangnova.cangjie.cfir.analysis.tests.runners.AbstractCfirLightTreeLlTDiagnosticsTest
import org.cangnova.cangjie.test.TestMetadata
import org.junit.jupiter.api.Test
import java.io.File
import org.cangnova.cangjie.cfir.analysis.tests.assertAllFilesPresentByMetadata

/** AUTO-GENERATED by TestGeneratorForCfirAnalysisTests. DO NOT EDIT MANUALLY. */
@TestMetadata("cfir/analysis-tests/testData/llt/while-let-expr")
@TestDataPath("${'$'}PROJECT_ROOT")
@OptIn(ObsoleteTestInfrastructure::class)
@ObsoleteTestInfrastructure
class WhileLetExprGenerated : AbstractCfirLightTreeLlTDiagnosticsTest() {
    @Test
    fun testAllFilesPresent() {
        assertAllFilesPresentByMetadata(this, "cfir/analysis-tests/testData/llt/while-let-expr")
    }

    @TestMetadata("ok_scope_00.cj")
    @Test
    fun testOkScope00() {
        runTest("cfir/analysis-tests/testData/llt/while-let-expr/ok_scope_00.cj")
    }

    @TestMetadata("while_let1.cj")
    @Test
    fun testWhileLet1() {
        runTest("cfir/analysis-tests/testData/llt/while-let-expr/while_let1.cj")
    }

    @TestMetadata("while_let2.cj")
    @Test
    fun testWhileLet2() {
        runTest("cfir/analysis-tests/testData/llt/while-let-expr/while_let2.cj")
    }

    @TestMetadata("while_let3.cj")
    @Test
    fun testWhileLet3() {
        runTest("cfir/analysis-tests/testData/llt/while-let-expr/while_let3.cj")
    }

    @TestMetadata("while_let4.cj")
    @Test
    fun testWhileLet4() {
        runTest("cfir/analysis-tests/testData/llt/while-let-expr/while_let4.cj")
    }

    @TestMetadata("while_let5.cj")
    @Test
    fun testWhileLet5() {
        runTest("cfir/analysis-tests/testData/llt/while-let-expr/while_let5.cj")
    }

    @TestMetadata("while_let6.cj")
    @Test
    fun testWhileLet6() {
        runTest("cfir/analysis-tests/testData/llt/while-let-expr/while_let6.cj")
    }

    @TestMetadata("while_let7.cj")
    @Test
    fun testWhileLet7() {
        runTest("cfir/analysis-tests/testData/llt/while-let-expr/while_let7.cj")
    }

    @TestMetadata("while_let8.cj")
    @Test
    fun testWhileLet8() {
        runTest("cfir/analysis-tests/testData/llt/while-let-expr/while_let8.cj")
    }

    @TestMetadata("while_let9.cj")
    @Test
    fun testWhileLet9() {
        runTest("cfir/analysis-tests/testData/llt/while-let-expr/while_let9.cj")
    }
}

