// Copyright (c) Huawei Technologies Co., Ltd. 2025. All rights reserved.
// This source file is part of the Cangjie project, licensed under Apache-2.0
// with Runtime Library Exception.
//
// See https://cangjie-lang.cn/pages/LICENSE for license information.

// The tests are defined in composition9_1.cj

func g(): Bool {
    false
}

func g(x: Int64): Int64 {
    x
}

func f(x: Int64): Int64 {
    -x
}
