
// Was ICE, should quit normally
import ast<!parse_expected_character!>..<!>

public macro <!parse_expected_macro_decl_define_in_macro_package!>test<!>(input:Tokens):Tokens{
    quote(.)
}

main() {}

// Copyright (c) Huawei Technologies Co., Ltd. 2025. All rights reserved.
// This source file is part of the Cangjie project, licensed under Apache-2.0
// with Runtime Library Exception.
//
// See https://cangjie-lang.cn/pages/LICENSE for license information.
