[versions]
kotlin = "2.2.0"
guava = "33.4.0-jre"
junit4 = "4.13.2"
junit-jupiter = "5.10.2"
junit-platform-launcher = "1.10.2"
vavr = "0.10.4"
jansi = "2.4.1"

[libraries]
junit4 = { module = "junit:junit", version.ref = "junit4" }
junit-jupiter = { module = "org.junit.jupiter:junit-jupiter", version.ref = "junit-jupiter" }
junit-platform-launcher = { module = "org.junit.platform:junit-platform-launcher", version.ref = "junit-platform-launcher" }
junit-vintage-engine = { module = "org.junit.vintage:junit-vintage-engine", version.ref = "junit-jupiter" }
vavr = { module = "io.vavr:vavr", version.ref = "vavr" }
jansi = { module = "org.fusesource.jansi:jansi", version.ref = "jansi" }
guava = { module = "com.google.guava:guava", version.ref = "guava" }

[plugins]
kotlinJvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
