package org.cangnova.cangjie.cfir.analysis.tests.CfirAnalysisLLTPsiTest.llt.overload

import com.intellij.testFramework.TestDataPath
import org.cangnova.cangjie.ObsoleteTestInfrastructure
import org.cangnova.cangjie.cfir.analysis.tests.runners.AbstractCfirPsiLlTDiagnosticsTest
import org.cangnova.cangjie.test.TestMetadata
import org.junit.jupiter.api.Test
import java.io.File
import org.cangnova.cangjie.cfir.analysis.tests.assertAllFilesPresentByMetadata

/** AUTO-GENERATED by TestGeneratorForCfirAnalysisTests. DO NOT EDIT MANUALLY. */
@TestMetadata("cfir/analysis-tests/testData/llt/overload")
@TestDataPath("${'$'}PROJECT_ROOT")
@OptIn(ObsoleteTestInfrastructure::class)
@ObsoleteTestInfrastructure
class OverloadGenerated : AbstractCfirPsiLlTDiagnosticsTest() {
    @Test
    fun testAllFilesPresent() {
        assertAllFilesPresentByMetadata(this, "cfir/analysis-tests/testData/llt/overload")
    }

    @TestMetadata("class_extends_class1.cj")
    @Test
    fun testClassExtendsClass1() {
        runTest("cfir/analysis-tests/testData/llt/overload/class_extends_class1.cj")
    }

    @TestMetadata("class_extends_class2.cj")
    @Test
    fun testClassExtendsClass2() {
        runTest("cfir/analysis-tests/testData/llt/overload/class_extends_class2.cj")
    }

    @TestMetadata("class_extends_class4.cj")
    @Test
    fun testClassExtendsClass4() {
        runTest("cfir/analysis-tests/testData/llt/overload/class_extends_class4.cj")
    }

    @TestMetadata("class_extends_class5.cj")
    @Test
    fun testClassExtendsClass5() {
        runTest("cfir/analysis-tests/testData/llt/overload/class_extends_class5.cj")
    }

    @TestMetadata("class_impl_interface1.cj")
    @Test
    fun testClassImplInterface1() {
        runTest("cfir/analysis-tests/testData/llt/overload/class_impl_interface1.cj")
    }

    @TestMetadata("class_impl_interface2.cj")
    @Test
    fun testClassImplInterface2() {
        runTest("cfir/analysis-tests/testData/llt/overload/class_impl_interface2.cj")
    }

    @TestMetadata("class_impl_interface3.cj")
    @Test
    fun testClassImplInterface3() {
        runTest("cfir/analysis-tests/testData/llt/overload/class_impl_interface3.cj")
    }

    @TestMetadata("class_impl_interface4.cj")
    @Test
    fun testClassImplInterface4() {
        runTest("cfir/analysis-tests/testData/llt/overload/class_impl_interface4.cj")
    }

    @TestMetadata("overload_resolution_1.cj")
    @Test
    fun testOverloadResolution1() {
        runTest("cfir/analysis-tests/testData/llt/overload/overload_resolution_1.cj")
    }

    @TestMetadata("overload_resolution_2.cj")
    @Test
    fun testOverloadResolution2() {
        runTest("cfir/analysis-tests/testData/llt/overload/overload_resolution_2.cj")
    }

    @TestMetadata("overload_resolution_3.cj")
    @Test
    fun testOverloadResolution3() {
        runTest("cfir/analysis-tests/testData/llt/overload/overload_resolution_3.cj")
    }

    @TestMetadata("overload_resolution_4.cj")
    @Test
    fun testOverloadResolution4() {
        runTest("cfir/analysis-tests/testData/llt/overload/overload_resolution_4.cj")
    }

    @TestMetadata("overload_resolution_5.cj")
    @Test
    fun testOverloadResolution5() {
        runTest("cfir/analysis-tests/testData/llt/overload/overload_resolution_5.cj")
    }
}

