package org.cangnova.cangjie.cfir.analysis.tests.CfirAnalysisLLTTest.llt.PatternMatching.Sealed.pkg_class

import com.intellij.testFramework.TestDataPath
import org.cangnova.cangjie.ObsoleteTestInfrastructure
import org.cangnova.cangjie.cfir.analysis.tests.runners.AbstractCfirLightTreeLlTDiagnosticsTest
import org.cangnova.cangjie.test.TestMetadata
import org.junit.jupiter.api.Test
import java.io.File
import org.cangnova.cangjie.cfir.analysis.tests.assertAllFilesPresentByMetadata

/** AUTO-GENERATED by TestGeneratorForCfirAnalysisTests. DO NOT EDIT MANUALLY. */
@TestMetadata("cfir/analysis-tests/testData/llt/PatternMatching/Sealed/pkg_class")
@TestDataPath("${'$'}PROJECT_ROOT")
@OptIn(ObsoleteTestInfrastructure::class)
@ObsoleteTestInfrastructure
class PkgClassGenerated : AbstractCfirLightTreeLlTDiagnosticsTest() {
    @Test
    fun testAllFilesPresent() {
        assertAllFilesPresentByMetadata(this, "cfir/analysis-tests/testData/llt/PatternMatching/Sealed/pkg_class")
    }

    @TestMetadata("fail.cj")
    @Test
    fun testFail() {
        runTest("cfir/analysis-tests/testData/llt/PatternMatching/Sealed/pkg_class/fail.cj")
    }

    @TestMetadata("pass.cj")
    @Test
    fun testPass() {
        runTest("cfir/analysis-tests/testData/llt/PatternMatching/Sealed/pkg_class/pass.cj")
    }
}

