package org.cangnova.cangjie.cfir.resolve.dfa.cfg

abstract class ControlFlowGraphVisitorVoid : ControlFlowGraphVisitor<Unit, Nothing?>() {
    abstract fun visitNode(node: CFGNode<*>)

    open fun visitFunctionEnterNode(node: FunctionEnterNode) = visitNode(node)
    open fun visitFunctionExitNode(node: FunctionExitNode) = visitNode(node)
    open fun visitLocalFunctionDeclarationNode(node: LocalFunctionDeclarationNode) = visitNode(node)

    open fun visitEnterValueParameterNode(node: EnterValueParameterNode) = visitNode(node)
    open fun visitEnterDefaultArgumentsNode(node: EnterDefaultArgumentsNode) = visitNode(node)
    open fun visitExitDefaultArgumentsNode(node: ExitDefaultArgumentsNode) = visitNode(node)
    open fun visitExitValueParameterNode(node: ExitValueParameterNode) = visitNode(node)

    open fun visitSplitPostponedLambdasNode(node: SplitPostponedLambdasNode) = visitNode(node)
    open fun visitPostponedLambdaExitNode(node: PostponedLambdaExitNode) = visitNode(node)
    open fun visitMergePostponedLambdaExitsNode(node: MergePostponedLambdaExitsNode) = visitNode(node)
    open fun visitAnonymousFunctionCaptureNode(node: AnonymousFunctionCaptureNode) = visitNode(node)
    open fun visitAnonymousFunctionExpressionNode(node: AnonymousFunctionExpressionNode) = visitNode(node)

    open fun visitFileEnterNode(node: FileEnterNode) = visitNode(node)
    open fun visitFileExitNode(node: FileExitNode) = visitNode(node)
    open fun visitClassEnterNode(node: ClassEnterNode) = visitNode(node)
    open fun visitClassExitNode(node: ClassExitNode) = visitNode(node)
    open fun visitLocalClassExitNode(node: LocalClassExitNode) = visitNode(node)
    open fun visitCodeFragmentEnterNode(node: CodeFragmentEnterNode) = visitNode(node)
    open fun visitCodeFragmentExitNode(node: CodeFragmentExitNode) = visitNode(node)

    open fun visitFieldInitializerEnterNode(node: FieldInitializerEnterNode) = visitNode(node)
    open fun visitFieldInitializerExitNode(node: FieldInitializerExitNode) = visitNode(node)

    open fun visitSpawnExpressionNode(node: SpawnExpressionNode) = visitNode(node)
    open fun visitSynchronizedEnterNode(node: SynchronizedEnterNode) = visitNode(node)
    open fun visitSynchronizedExitNode(node: SynchronizedExitNode) = visitNode(node)
    open fun visitUnsafeEnterNode(node: UnsafeEnterNode) = visitNode(node)
    open fun visitUnsafeExitNode(node: UnsafeExitNode) = visitNode(node)
    open fun visitBlockEnterNode(node: BlockEnterNode) = visitNode(node)
    open fun visitBlockExitNode(node: BlockExitNode) = visitNode(node)

    open fun visitMatchEnterNode(node: MatchEnterNode) = visitNode(node)
    open fun visitMatchExitNode(node: MatchExitNode) = visitNode(node)
    open fun visitMatchBranchConditionEnterNode(node: MatchBranchConditionEnterNode) = visitNode(node)
    open fun visitMatchBranchConditionExitNode(node: MatchBranchConditionExitNode) = visitNode(node)
    open fun visitMatchBranchResultEnterNode(node: MatchBranchResultEnterNode) = visitNode(node)
    open fun visitMatchBranchResultExitNode(node: MatchBranchResultExitNode) = visitNode(node)
    open fun visitMatchSyntheticElseBranchNode(node: MatchSyntheticElseBranchNode) = visitNode(node)
    open fun visitIfEnterNode(node: IfEnterNode) = visitNode(node)
    open fun visitIfExitNode(node: IfExitNode) = visitNode(node)

    open fun visitLoopEnterNode(node: LoopEnterNode) = visitNode(node)
    open fun visitLoopBlockEnterNode(node: LoopBlockEnterNode) = visitNode(node)
    open fun visitLoopBlockExitNode(node: LoopBlockExitNode) = visitNode(node)
    open fun visitLoopConditionEnterNode(node: LoopConditionEnterNode) = visitNode(node)
    open fun visitLoopConditionExitNode(node: LoopConditionExitNode) = visitNode(node)
    open fun visitLoopExitNode(node: LoopExitNode) = visitNode(node)

    open fun visitTryExpressionEnterNode(node: TryExpressionEnterNode) = visitNode(node)
    open fun visitTryMainBlockEnterNode(node: TryMainBlockEnterNode) = visitNode(node)
    open fun visitTryMainBlockExitNode(node: TryMainBlockExitNode) = visitNode(node)
    open fun visitCatchClauseEnterNode(node: CatchClauseEnterNode) = visitNode(node)
    open fun visitCatchClauseExitNode(node: CatchClauseExitNode) = visitNode(node)
    open fun visitFinallyBlockEnterNode(node: FinallyBlockEnterNode) = visitNode(node)
    open fun visitFinallyBlockExitNode(node: FinallyBlockExitNode) = visitNode(node)
    open fun visitTryExpressionExitNode(node: TryExpressionExitNode) = visitNode(node)

    open fun visitBooleanOperatorEnterNode(node: BooleanOperatorEnterNode) = visitNode(node)
    open fun visitBooleanOperatorExitLeftOperandNode(node: BooleanOperatorExitLeftOperandNode) = visitNode(node)
    open fun visitBooleanOperatorEnterRightOperandNode(node: BooleanOperatorEnterRightOperandNode) = visitNode(node)
    open fun visitBooleanOperatorExitNode(node: BooleanOperatorExitNode) = visitNode(node)
    open fun visitTypeOperatorCallNode(node: TypeOperatorCallNode) = visitNode(node)
    open fun visitComparisonExpressionNode(node: ComparisonExpressionNode) = visitNode(node)
    open fun visitJumpNode(node: JumpNode) = visitNode(node)
    open fun visitLiteralExpressionNode(node: LiteralExpressionNode) = visitNode(node)
    open fun visitQualifiedAccessNode(node: QualifiedAccessNode) = visitNode(node)
    open fun visitFunctionCallArgumentsEnterNode(node: FunctionCallArgumentsEnterNode) = visitNode(node)
    open fun visitFunctionCallArgumentsExitNode(node: FunctionCallArgumentsExitNode) = visitNode(node)
    open fun visitFunctionCallEnterNode(node: FunctionCallEnterNode) = visitNode(node)
    open fun visitFunctionCallExitNode(node: FunctionCallExitNode) = visitNode(node)
    open fun visitThrowExceptionNode(node: ThrowExceptionNode) = visitNode(node)
    open fun visitVariableDeclarationEnterNode(node: VariableDeclarationEnterNode) = visitNode(node)
    open fun visitVariableDeclarationExitNode(node: VariableDeclarationExitNode) = visitNode(node)
    open fun visitVariableAssignmentNode(node: VariableAssignmentNode) = visitNode(node)
    open fun visitEnterOptionalChainNode(node: EnterOptionalChainNode) = visitNode(node)
    open fun visitExitOptionalChainNode(node: ExitOptionalChainNode) = visitNode(node)
    open fun visitWrappedExpressionNode(node: WrappedExpressionNode) = visitNode(node)
    open fun visitStubNode(node: StubNode) = visitNode(node)

    final override fun visitNode(node: CFGNode<*>, data: Nothing?) {
        visitNode(node)
    }

    final override fun visitFunctionEnterNode(node: FunctionEnterNode, data: Nothing?) = visitFunctionEnterNode(node)
    final override fun visitFunctionExitNode(node: FunctionExitNode, data: Nothing?) = visitFunctionExitNode(node)
    final override fun visitLocalFunctionDeclarationNode(node: LocalFunctionDeclarationNode, data: Nothing?) = visitLocalFunctionDeclarationNode(node)
    final override fun visitEnterValueParameterNode(node: EnterValueParameterNode, data: Nothing?) = visitEnterValueParameterNode(node)
    final override fun visitEnterDefaultArgumentsNode(node: EnterDefaultArgumentsNode, data: Nothing?) = visitEnterDefaultArgumentsNode(node)
    final override fun visitExitDefaultArgumentsNode(node: ExitDefaultArgumentsNode, data: Nothing?) = visitExitDefaultArgumentsNode(node)
    final override fun visitExitValueParameterNode(node: ExitValueParameterNode, data: Nothing?) = visitExitValueParameterNode(node)
    final override fun visitSplitPostponedLambdasNode(node: SplitPostponedLambdasNode, data: Nothing?) = visitSplitPostponedLambdasNode(node)
    final override fun visitPostponedLambdaExitNode(node: PostponedLambdaExitNode, data: Nothing?) = visitPostponedLambdaExitNode(node)
    final override fun visitMergePostponedLambdaExitsNode(node: MergePostponedLambdaExitsNode, data: Nothing?) = visitMergePostponedLambdaExitsNode(node)
    final override fun visitAnonymousFunctionCaptureNode(node: AnonymousFunctionCaptureNode, data: Nothing?) = visitAnonymousFunctionCaptureNode(node)
    final override fun visitAnonymousFunctionExpressionNode(node: AnonymousFunctionExpressionNode, data: Nothing?) = visitAnonymousFunctionExpressionNode(node)
    final override fun visitFileEnterNode(node: FileEnterNode, data: Nothing?) = visitFileEnterNode(node)
    final override fun visitFileExitNode(node: FileExitNode, data: Nothing?) = visitFileExitNode(node)
    final override fun visitClassEnterNode(node: ClassEnterNode, data: Nothing?) = visitClassEnterNode(node)
    final override fun visitClassExitNode(node: ClassExitNode, data: Nothing?) = visitClassExitNode(node)
    final override fun visitLocalClassExitNode(node: LocalClassExitNode, data: Nothing?) = visitLocalClassExitNode(node)
    final override fun visitCodeFragmentEnterNode(node: CodeFragmentEnterNode, data: Nothing?) = visitCodeFragmentEnterNode(node)
    final override fun visitCodeFragmentExitNode(node: CodeFragmentExitNode, data: Nothing?) = visitCodeFragmentExitNode(node)

    final override fun visitFieldInitializerEnterNode(node: FieldInitializerEnterNode, data: Nothing?) = visitFieldInitializerEnterNode(node)
    final override fun visitFieldInitializerExitNode(node: FieldInitializerExitNode, data: Nothing?) = visitFieldInitializerExitNode(node)

    final override fun visitSpawnExpressionNode(node: SpawnExpressionNode, data: Nothing?) = visitSpawnExpressionNode(node)
    final override fun visitSynchronizedEnterNode(node: SynchronizedEnterNode, data: Nothing?) = visitSynchronizedEnterNode(node)
    final override fun visitSynchronizedExitNode(node: SynchronizedExitNode, data: Nothing?) = visitSynchronizedExitNode(node)
    final override fun visitUnsafeEnterNode(node: UnsafeEnterNode, data: Nothing?) = visitUnsafeEnterNode(node)
    final override fun visitUnsafeExitNode(node: UnsafeExitNode, data: Nothing?) = visitUnsafeExitNode(node)
    final override fun visitBlockEnterNode(node: BlockEnterNode, data: Nothing?) = visitBlockEnterNode(node)
    final override fun visitBlockExitNode(node: BlockExitNode, data: Nothing?) = visitBlockExitNode(node)
    final override fun visitMatchEnterNode(node: MatchEnterNode, data: Nothing?) = visitMatchEnterNode(node)
    final override fun visitMatchExitNode(node: MatchExitNode, data: Nothing?) = visitMatchExitNode(node)
    final override fun visitMatchBranchConditionEnterNode(node: MatchBranchConditionEnterNode, data: Nothing?) = visitMatchBranchConditionEnterNode(node)
    final override fun visitMatchBranchConditionExitNode(node: MatchBranchConditionExitNode, data: Nothing?) = visitMatchBranchConditionExitNode(node)
    final override fun visitMatchBranchResultEnterNode(node: MatchBranchResultEnterNode, data: Nothing?) = visitMatchBranchResultEnterNode(node)
    final override fun visitMatchBranchResultExitNode(node: MatchBranchResultExitNode, data: Nothing?) = visitMatchBranchResultExitNode(node)
    final override fun visitMatchSyntheticElseBranchNode(node: MatchSyntheticElseBranchNode, data: Nothing?) = visitMatchSyntheticElseBranchNode(node)
    final override fun visitIfEnterNode(node: IfEnterNode, data: Nothing?) = visitIfEnterNode(node)
    final override fun visitIfExitNode(node: IfExitNode, data: Nothing?) = visitIfExitNode(node)
    final override fun visitLoopEnterNode(node: LoopEnterNode, data: Nothing?) = visitLoopEnterNode(node)
    final override fun visitLoopBlockEnterNode(node: LoopBlockEnterNode, data: Nothing?) = visitLoopBlockEnterNode(node)
    final override fun visitLoopBlockExitNode(node: LoopBlockExitNode, data: Nothing?) = visitLoopBlockExitNode(node)
    final override fun visitLoopConditionEnterNode(node: LoopConditionEnterNode, data: Nothing?) = visitLoopConditionEnterNode(node)
    final override fun visitLoopConditionExitNode(node: LoopConditionExitNode, data: Nothing?) = visitLoopConditionExitNode(node)
    final override fun visitLoopExitNode(node: LoopExitNode, data: Nothing?) = visitLoopExitNode(node)
    final override fun visitTryExpressionEnterNode(node: TryExpressionEnterNode, data: Nothing?) = visitTryExpressionEnterNode(node)
    final override fun visitTryMainBlockEnterNode(node: TryMainBlockEnterNode, data: Nothing?) = visitTryMainBlockEnterNode(node)
    final override fun visitTryMainBlockExitNode(node: TryMainBlockExitNode, data: Nothing?) = visitTryMainBlockExitNode(node)
    final override fun visitCatchClauseEnterNode(node: CatchClauseEnterNode, data: Nothing?) = visitCatchClauseEnterNode(node)
    final override fun visitCatchClauseExitNode(node: CatchClauseExitNode, data: Nothing?) = visitCatchClauseExitNode(node)
    final override fun visitFinallyBlockEnterNode(node: FinallyBlockEnterNode, data: Nothing?) = visitFinallyBlockEnterNode(node)
    final override fun visitFinallyBlockExitNode(node: FinallyBlockExitNode, data: Nothing?) = visitFinallyBlockExitNode(node)
    final override fun visitTryExpressionExitNode(node: TryExpressionExitNode, data: Nothing?) = visitTryExpressionExitNode(node)
    final override fun visitBooleanOperatorEnterNode(node: BooleanOperatorEnterNode, data: Nothing?) = visitBooleanOperatorEnterNode(node)
    final override fun visitBooleanOperatorExitLeftOperandNode(node: BooleanOperatorExitLeftOperandNode, data: Nothing?) = visitBooleanOperatorExitLeftOperandNode(node)
    final override fun visitBooleanOperatorEnterRightOperandNode(node: BooleanOperatorEnterRightOperandNode, data: Nothing?) = visitBooleanOperatorEnterRightOperandNode(node)
    final override fun visitBooleanOperatorExitNode(node: BooleanOperatorExitNode, data: Nothing?) = visitBooleanOperatorExitNode(node)
    final override fun visitTypeOperatorCallNode(node: TypeOperatorCallNode, data: Nothing?) = visitTypeOperatorCallNode(node)
    final override fun visitComparisonExpressionNode(node: ComparisonExpressionNode, data: Nothing?) = visitComparisonExpressionNode(node)
    final override fun visitJumpNode(node: JumpNode, data: Nothing?) = visitJumpNode(node)
    final override fun visitLiteralExpressionNode(node: LiteralExpressionNode, data: Nothing?) = visitLiteralExpressionNode(node)
    final override fun visitQualifiedAccessNode(node: QualifiedAccessNode, data: Nothing?) = visitQualifiedAccessNode(node)
    final override fun visitFunctionCallArgumentsEnterNode(node: FunctionCallArgumentsEnterNode, data: Nothing?) = visitFunctionCallArgumentsEnterNode(node)
    final override fun visitFunctionCallArgumentsExitNode(node: FunctionCallArgumentsExitNode, data: Nothing?) = visitFunctionCallArgumentsExitNode(node)
    final override fun visitFunctionCallEnterNode(node: FunctionCallEnterNode, data: Nothing?) = visitFunctionCallEnterNode(node)
    final override fun visitFunctionCallExitNode(node: FunctionCallExitNode, data: Nothing?) = visitFunctionCallExitNode(node)
    final override fun visitThrowExceptionNode(node: ThrowExceptionNode, data: Nothing?) = visitThrowExceptionNode(node)
    final override fun visitVariableDeclarationEnterNode(node: VariableDeclarationEnterNode, data: Nothing?) = visitVariableDeclarationEnterNode(node)
    final override fun visitVariableDeclarationExitNode(node: VariableDeclarationExitNode, data: Nothing?) = visitVariableDeclarationExitNode(node)
    final override fun visitVariableAssignmentNode(node: VariableAssignmentNode, data: Nothing?) = visitVariableAssignmentNode(node)
    final override fun visitEnterOptionalChainNode(node: EnterOptionalChainNode, data: Nothing?) = visitEnterOptionalChainNode(node)
    final override fun visitExitOptionalChainNode(node: ExitOptionalChainNode, data: Nothing?) = visitExitOptionalChainNode(node)
    final override fun visitWrappedExpressionNode(node: WrappedExpressionNode, data: Nothing?) = visitWrappedExpressionNode(node)
    final override fun visitStubNode(node: StubNode, data: Nothing?) = visitStubNode(node)
}
