// Copyright (c) Huawei Technologies Co., Ltd. 2025. All rights reserved.
// This source file is part of the Cangjie project, licensed under Apache-2.0
// with Runtime Library Exception.
//
// See https://cangjie-lang.cn/pages/LICENSE for license information.

// DEPENDENCE: unused012pkga.cj

import <!UNUSED_IMPORT!>pkga.test<!>
import pkga.test as testanew
main(): Int64 {
    testanew()
    return 0
}
