package org.cangnova.cangjie.cfir.analysis.tests.CfirAnalysisLLTPsiTest.llt.forin

import com.intellij.testFramework.TestDataPath
import org.cangnova.cangjie.ObsoleteTestInfrastructure
import org.cangnova.cangjie.cfir.analysis.tests.runners.AbstractCfirPsiLlTDiagnosticsTest
import org.cangnova.cangjie.test.TestMetadata
import org.junit.jupiter.api.Test
import java.io.File
import org.cangnova.cangjie.cfir.analysis.tests.assertAllFilesPresentByMetadata

/** AUTO-GENERATED by TestGeneratorForCfirAnalysisTests. DO NOT EDIT MANUALLY. */
@TestMetadata("cfir/analysis-tests/testData/llt/forin")
@TestDataPath("${'$'}PROJECT_ROOT")
@OptIn(ObsoleteTestInfrastructure::class)
@ObsoleteTestInfrastructure
class ForinGenerated : AbstractCfirPsiLlTDiagnosticsTest() {
    @Test
    fun testAllFilesPresent() {
        assertAllFilesPresentByMetadata(this, "cfir/analysis-tests/testData/llt/forin")
    }

    @TestMetadata("closedrange_ovf.cj")
    @Test
    fun testClosedrangeOvf() {
        runTest("cfir/analysis-tests/testData/llt/forin/closedrange_ovf.cj")
    }

    @TestMetadata("closedrange_ovf2.cj")
    @Test
    fun testClosedrangeOvf2() {
        runTest("cfir/analysis-tests/testData/llt/forin/closedrange_ovf2.cj")
    }

    @TestMetadata("closedrange_rune.cj")
    @Test
    fun testClosedrangeRune() {
        runTest("cfir/analysis-tests/testData/llt/forin/closedrange_rune.cj")
    }

    @TestMetadata("forin.cj")
    @Test
    fun testForin() {
        runTest("cfir/analysis-tests/testData/llt/forin/forin.cj")
    }

    @TestMetadata("forin10.cj")
    @Test
    fun testForin10() {
        runTest("cfir/analysis-tests/testData/llt/forin/forin10.cj")
    }

    @TestMetadata("forin11.cj")
    @Test
    fun testForin11() {
        runTest("cfir/analysis-tests/testData/llt/forin/forin11.cj")
    }

    @TestMetadata("forin12.cj")
    @Test
    fun testForin12() {
        runTest("cfir/analysis-tests/testData/llt/forin/forin12.cj")
    }

    @TestMetadata("forin13.cj")
    @Test
    fun testForin13() {
        runTest("cfir/analysis-tests/testData/llt/forin/forin13.cj")
    }

    @TestMetadata("forin14.cj")
    @Test
    fun testForin14() {
        runTest("cfir/analysis-tests/testData/llt/forin/forin14.cj")
    }

    @TestMetadata("forin15.cj")
    @Test
    fun testForin15() {
        runTest("cfir/analysis-tests/testData/llt/forin/forin15.cj")
    }

    @TestMetadata("forin16.cj")
    @Test
    fun testForin16() {
        runTest("cfir/analysis-tests/testData/llt/forin/forin16.cj")
    }

    @TestMetadata("forin2.cj")
    @Test
    fun testForin2() {
        runTest("cfir/analysis-tests/testData/llt/forin/forin2.cj")
    }

    @TestMetadata("forin3.cj")
    @Test
    fun testForin3() {
        runTest("cfir/analysis-tests/testData/llt/forin/forin3.cj")
    }

    @TestMetadata("forin4.cj")
    @Test
    fun testForin4() {
        runTest("cfir/analysis-tests/testData/llt/forin/forin4.cj")
    }

    @TestMetadata("forin5.cj")
    @Test
    fun testForin5() {
        runTest("cfir/analysis-tests/testData/llt/forin/forin5.cj")
    }

    @TestMetadata("forin6.cj")
    @Test
    fun testForin6() {
        runTest("cfir/analysis-tests/testData/llt/forin/forin6.cj")
    }

    @TestMetadata("forin7.cj")
    @Test
    fun testForin7() {
        runTest("cfir/analysis-tests/testData/llt/forin/forin7.cj")
    }

    @TestMetadata("forin8.cj")
    @Test
    fun testForin8() {
        runTest("cfir/analysis-tests/testData/llt/forin/forin8.cj")
    }

    @TestMetadata("forin9.cj")
    @Test
    fun testForin9() {
        runTest("cfir/analysis-tests/testData/llt/forin/forin9.cj")
    }

    @TestMetadata("forin_desugar.cj")
    @Test
    fun testForinDesugar() {
        runTest("cfir/analysis-tests/testData/llt/forin/forin_desugar.cj")
    }

    @TestMetadata("forin_expr_not_implement_iterator.cj")
    @Test
    fun testForinExprNotImplementIterator() {
        runTest("cfir/analysis-tests/testData/llt/forin/forin_expr_not_implement_iterator.cj")
    }

    @TestMetadata("forin_generic.cj")
    @Test
    fun testForinGeneric() {
        runTest("cfir/analysis-tests/testData/llt/forin/forin_generic.cj")
    }

    @TestMetadata("forin_generic_upperbound.cj")
    @Test
    fun testForinGenericUpperbound() {
        runTest("cfir/analysis-tests/testData/llt/forin/forin_generic_upperbound.cj")
    }

    @TestMetadata("forin_in_match_expr.cj")
    @Test
    fun testForinInMatchExpr() {
        runTest("cfir/analysis-tests/testData/llt/forin/forin_in_match_expr.cj")
    }

    @TestMetadata("imported_forinrange.cj")
    @Test
    fun testImportedForinrange() {
        runTest("cfir/analysis-tests/testData/llt/forin/imported_forinrange.cj")
    }

    @TestMetadata("imported_forinrange.lib.cj")
    @Test
    fun testImportedForinrangeLib() {
        runTest("cfir/analysis-tests/testData/llt/forin/imported_forinrange.lib.cj")
    }
}

