package org.cangnova.cangjie.cfir.analysis.tests.CfirAnalysisLLTTest.llt.lambda

import com.intellij.testFramework.TestDataPath
import org.cangnova.cangjie.ObsoleteTestInfrastructure
import org.cangnova.cangjie.cfir.analysis.tests.runners.AbstractCfirLightTreeLlTDiagnosticsTest
import org.cangnova.cangjie.test.TestMetadata
import org.junit.jupiter.api.Test
import java.io.File
import org.cangnova.cangjie.cfir.analysis.tests.assertAllFilesPresentByMetadata

/** AUTO-GENERATED by TestGeneratorForCfirAnalysisTests. DO NOT EDIT MANUALLY. */
@TestMetadata("cfir/analysis-tests/testData/llt/lambda")
@TestDataPath("${'$'}PROJECT_ROOT")
@OptIn(ObsoleteTestInfrastructure::class)
@ObsoleteTestInfrastructure
class LambdaGenerated : AbstractCfirLightTreeLlTDiagnosticsTest() {
    @Test
    fun testAllFilesPresent() {
        assertAllFilesPresentByMetadata(this, "cfir/analysis-tests/testData/llt/lambda")
    }

    @TestMetadata("err_capture_var.cj")
    @Test
    fun testErrCaptureVar() {
        runTest("cfir/analysis-tests/testData/llt/lambda/err_capture_var.cj")
    }

    @TestMetadata("lambda01.cj")
    @Test
    fun testLambda01() {
        runTest("cfir/analysis-tests/testData/llt/lambda/lambda01.cj")
    }

    @TestMetadata("lambda02.cj")
    @Test
    fun testLambda02() {
        runTest("cfir/analysis-tests/testData/llt/lambda/lambda02.cj")
    }

    @TestMetadata("lambda03.cj")
    @Test
    fun testLambda03() {
        runTest("cfir/analysis-tests/testData/llt/lambda/lambda03.cj")
    }

    @TestMetadata("lambda04.cj")
    @Test
    fun testLambda04() {
        runTest("cfir/analysis-tests/testData/llt/lambda/lambda04.cj")
    }

    @TestMetadata("lambda05.cj")
    @Test
    fun testLambda05() {
        runTest("cfir/analysis-tests/testData/llt/lambda/lambda05.cj")
    }

    @TestMetadata("lambda06.cj")
    @Test
    fun testLambda06() {
        runTest("cfir/analysis-tests/testData/llt/lambda/lambda06.cj")
    }

    @TestMetadata("lambda07.cj")
    @Test
    fun testLambda07() {
        runTest("cfir/analysis-tests/testData/llt/lambda/lambda07.cj")
    }

    @TestMetadata("lambda08.cj")
    @Test
    fun testLambda08() {
        runTest("cfir/analysis-tests/testData/llt/lambda/lambda08.cj")
    }

    @TestMetadata("lambda09.cj")
    @Test
    fun testLambda09() {
        runTest("cfir/analysis-tests/testData/llt/lambda/lambda09.cj")
    }

    @TestMetadata("lambda10.cj")
    @Test
    fun testLambda10() {
        runTest("cfir/analysis-tests/testData/llt/lambda/lambda10.cj")
    }

    @TestMetadata("lambda11.cj")
    @Test
    fun testLambda11() {
        runTest("cfir/analysis-tests/testData/llt/lambda/lambda11.cj")
    }

    @TestMetadata("lambda12.cj")
    @Test
    fun testLambda12() {
        runTest("cfir/analysis-tests/testData/llt/lambda/lambda12.cj")
    }

    @TestMetadata("lambda13.cj")
    @Test
    fun testLambda13() {
        runTest("cfir/analysis-tests/testData/llt/lambda/lambda13.cj")
    }

    @TestMetadata("lambda14.cj")
    @Test
    fun testLambda14() {
        runTest("cfir/analysis-tests/testData/llt/lambda/lambda14.cj")
    }

    @TestMetadata("lambda15.cj")
    @Test
    fun testLambda15() {
        runTest("cfir/analysis-tests/testData/llt/lambda/lambda15.cj")
    }

    @TestMetadata("lambda16.cj")
    @Test
    fun testLambda16() {
        runTest("cfir/analysis-tests/testData/llt/lambda/lambda16.cj")
    }

    @TestMetadata("lambda17.cj")
    @Test
    fun testLambda17() {
        runTest("cfir/analysis-tests/testData/llt/lambda/lambda17.cj")
    }

    @TestMetadata("lambda20.cj")
    @Test
    fun testLambda20() {
        runTest("cfir/analysis-tests/testData/llt/lambda/lambda20.cj")
    }

    @TestMetadata("lambda21.cj")
    @Test
    fun testLambda21() {
        runTest("cfir/analysis-tests/testData/llt/lambda/lambda21.cj")
    }

    @TestMetadata("lambda_any.cj")
    @Test
    fun testLambdaAny() {
        runTest("cfir/analysis-tests/testData/llt/lambda/lambda_any.cj")
    }

    @TestMetadata("lambda_in_if_cond.cj")
    @Test
    fun testLambdaInIfCond() {
        runTest("cfir/analysis-tests/testData/llt/lambda/lambda_in_if_cond.cj")
    }

    @TestMetadata("lambda_in_record.cj")
    @Test
    fun testLambdaInRecord() {
        runTest("cfir/analysis-tests/testData/llt/lambda/lambda_in_record.cj")
    }

    @TestMetadata("lambda_nest_error.cj")
    @Test
    fun testLambdaNestError() {
        runTest("cfir/analysis-tests/testData/llt/lambda/lambda_nest_error.cj")
    }

    @TestMetadata("lambda_nest_generic.cj")
    @Test
    fun testLambdaNestGeneric() {
        runTest("cfir/analysis-tests/testData/llt/lambda/lambda_nest_generic.cj")
    }

    @TestMetadata("lambda_param_infer01.cj")
    @Test
    fun testLambdaParamInfer01() {
        runTest("cfir/analysis-tests/testData/llt/lambda/lambda_param_infer01.cj")
    }

    @TestMetadata("lambda_param_infer02.cj")
    @Test
    fun testLambdaParamInfer02() {
        runTest("cfir/analysis-tests/testData/llt/lambda/lambda_param_infer02.cj")
    }

    @TestMetadata("lambda_param_infer03.cj")
    @Test
    fun testLambdaParamInfer03() {
        runTest("cfir/analysis-tests/testData/llt/lambda/lambda_param_infer03.cj")
    }

    @TestMetadata("lambda_param_infer04.cj")
    @Test
    fun testLambdaParamInfer04() {
        runTest("cfir/analysis-tests/testData/llt/lambda/lambda_param_infer04.cj")
    }

    @TestMetadata("lambda_spawn.cj")
    @Test
    fun testLambdaSpawn() {
        runTest("cfir/analysis-tests/testData/llt/lambda/lambda_spawn.cj")
    }

    @TestMetadata("test_fold.cj")
    @Test
    fun testTestFold() {
        runTest("cfir/analysis-tests/testData/llt/lambda/test_fold.cj")
    }
}

