package org.cangnova.cangjie.cfir.analysis.tests.CfirAnalysisLLTTest.llt.OptionalModifiers

import com.intellij.testFramework.TestDataPath
import org.cangnova.cangjie.ObsoleteTestInfrastructure
import org.cangnova.cangjie.cfir.analysis.tests.runners.AbstractCfirLightTreeLlTDiagnosticsTest
import org.cangnova.cangjie.test.TestMetadata
import org.junit.jupiter.api.Test
import java.io.File
import org.cangnova.cangjie.cfir.analysis.tests.assertAllFilesPresentByMetadata

/** AUTO-GENERATED by TestGeneratorForCfirAnalysisTests. DO NOT EDIT MANUALLY. */
@TestMetadata("cfir/analysis-tests/testData/llt/OptionalModifiers")
@TestDataPath("${'$'}PROJECT_ROOT")
@OptIn(ObsoleteTestInfrastructure::class)
@ObsoleteTestInfrastructure
class OptionalModifiersGenerated : AbstractCfirLightTreeLlTDiagnosticsTest() {
    @Test
    fun testAllFilesPresent() {
        assertAllFilesPresentByMetadata(this, "cfir/analysis-tests/testData/llt/OptionalModifiers")
    }

    @TestMetadata("optionalModifiers01.cj")
    @Test
    fun testOptionalModifiers01() {
        runTest("cfir/analysis-tests/testData/llt/OptionalModifiers/optionalModifiers01.cj")
    }

    @TestMetadata("optionalModifiers02_1.cj")
    @Test
    fun testOptionalModifiers021() {
        runTest("cfir/analysis-tests/testData/llt/OptionalModifiers/optionalModifiers02_1.cj")
    }

    @TestMetadata("optionalModifiers02_2.cj")
    @Test
    fun testOptionalModifiers022() {
        runTest("cfir/analysis-tests/testData/llt/OptionalModifiers/optionalModifiers02_2.cj")
    }

    @TestMetadata("optionalModifiers03_1.cj")
    @Test
    fun testOptionalModifiers031() {
        runTest("cfir/analysis-tests/testData/llt/OptionalModifiers/optionalModifiers03_1.cj")
    }

    @TestMetadata("optionalModifiers03_2.cj")
    @Test
    fun testOptionalModifiers032() {
        runTest("cfir/analysis-tests/testData/llt/OptionalModifiers/optionalModifiers03_2.cj")
    }

    @TestMetadata("optionalModifiers04.cj")
    @Test
    fun testOptionalModifiers04() {
        runTest("cfir/analysis-tests/testData/llt/OptionalModifiers/optionalModifiers04.cj")
    }

    @TestMetadata("optionalModifiers05.cj")
    @Test
    fun testOptionalModifiers05() {
        runTest("cfir/analysis-tests/testData/llt/OptionalModifiers/optionalModifiers05.cj")
    }

    @TestMetadata("optionalModifiers06.cj")
    @Test
    fun testOptionalModifiers06() {
        runTest("cfir/analysis-tests/testData/llt/OptionalModifiers/optionalModifiers06.cj")
    }

    @TestMetadata("optionalModifiers07.cj")
    @Test
    fun testOptionalModifiers07() {
        runTest("cfir/analysis-tests/testData/llt/OptionalModifiers/optionalModifiers07.cj")
    }

    @TestMetadata("optionalModifiers08.cj")
    @Test
    fun testOptionalModifiers08() {
        runTest("cfir/analysis-tests/testData/llt/OptionalModifiers/optionalModifiers08.cj")
    }
}

