package org.cangnova.cangjie.cfir.analysis.tests.CfirAnalysisLLTPsiTest.llt.Extend.property

import com.intellij.testFramework.TestDataPath
import org.cangnova.cangjie.ObsoleteTestInfrastructure
import org.cangnova.cangjie.cfir.analysis.tests.runners.AbstractCfirPsiLlTDiagnosticsTest
import org.cangnova.cangjie.test.TestMetadata
import org.junit.jupiter.api.Test
import java.io.File
import org.cangnova.cangjie.cfir.analysis.tests.assertAllFilesPresentByMetadata

/** AUTO-GENERATED by TestGeneratorForCfirAnalysisTests. DO NOT EDIT MANUALLY. */
@TestMetadata("cfir/analysis-tests/testData/llt/Extend/property")
@TestDataPath("${'$'}PROJECT_ROOT")
@OptIn(ObsoleteTestInfrastructure::class)
@ObsoleteTestInfrastructure
class PropertyGenerated : AbstractCfirPsiLlTDiagnosticsTest() {
    @Test
    fun testAllFilesPresent() {
        assertAllFilesPresentByMetadata(this, "cfir/analysis-tests/testData/llt/Extend/property")
    }

    @TestMetadata("extend_property1.cj")
    @Test
    fun testExtendProperty1() {
        runTest("cfir/analysis-tests/testData/llt/Extend/property/extend_property1.cj")
    }

    @TestMetadata("extend_property12.cj")
    @Test
    fun testExtendProperty12() {
        runTest("cfir/analysis-tests/testData/llt/Extend/property/extend_property12.cj")
    }

    @TestMetadata("extend_property13.cj")
    @Test
    fun testExtendProperty13() {
        runTest("cfir/analysis-tests/testData/llt/Extend/property/extend_property13.cj")
    }

    @TestMetadata("extend_property14.cj")
    @Test
    fun testExtendProperty14() {
        runTest("cfir/analysis-tests/testData/llt/Extend/property/extend_property14.cj")
    }

    @TestMetadata("extend_property15.cj")
    @Test
    fun testExtendProperty15() {
        runTest("cfir/analysis-tests/testData/llt/Extend/property/extend_property15.cj")
    }

    @TestMetadata("extend_property16.cj")
    @Test
    fun testExtendProperty16() {
        runTest("cfir/analysis-tests/testData/llt/Extend/property/extend_property16.cj")
    }

    @TestMetadata("extend_property2.cj")
    @Test
    fun testExtendProperty2() {
        runTest("cfir/analysis-tests/testData/llt/Extend/property/extend_property2.cj")
    }

    @TestMetadata("extend_property4.cj")
    @Test
    fun testExtendProperty4() {
        runTest("cfir/analysis-tests/testData/llt/Extend/property/extend_property4.cj")
    }

    @TestMetadata("extend_property5.cj")
    @Test
    fun testExtendProperty5() {
        runTest("cfir/analysis-tests/testData/llt/Extend/property/extend_property5.cj")
    }

    @TestMetadata("extend_property6.cj")
    @Test
    fun testExtendProperty6() {
        runTest("cfir/analysis-tests/testData/llt/Extend/property/extend_property6.cj")
    }

    @TestMetadata("extend_property7.cj")
    @Test
    fun testExtendProperty7() {
        runTest("cfir/analysis-tests/testData/llt/Extend/property/extend_property7.cj")
    }

    @TestMetadata("extend_property8.cj")
    @Test
    fun testExtendProperty8() {
        runTest("cfir/analysis-tests/testData/llt/Extend/property/extend_property8.cj")
    }

    @TestMetadata("extend_property9.cj")
    @Test
    fun testExtendProperty9() {
        runTest("cfir/analysis-tests/testData/llt/Extend/property/extend_property9.cj")
    }

    @TestMetadata("extend_property_override.cj")
    @Test
    fun testExtendPropertyOverride() {
        runTest("cfir/analysis-tests/testData/llt/Extend/property/extend_property_override.cj")
    }

    @TestMetadata("prop_look_up.cj")
    @Test
    fun testPropLookUp() {
        runTest("cfir/analysis-tests/testData/llt/Extend/property/prop_look_up.cj")
    }

    @TestMetadata("prop_look_up_n.cj")
    @Test
    fun testPropLookUpN() {
        runTest("cfir/analysis-tests/testData/llt/Extend/property/prop_look_up_n.cj")
    }

    @TestMetadata("property_mut_immut_mismatch.cj")
    @Test
    fun testPropertyMutImmutMismatch() {
        runTest("cfir/analysis-tests/testData/llt/Extend/property/property_mut_immut_mismatch.cj")
    }
}

