package org.cangnova.cangjie.cfir.analysis.tests.CfirAnalysisLLTTest.llt.generics.generic_constraint_inheritance

import com.intellij.testFramework.TestDataPath
import org.cangnova.cangjie.ObsoleteTestInfrastructure
import org.cangnova.cangjie.cfir.analysis.tests.runners.AbstractCfirLightTreeLlTDiagnosticsTest
import org.cangnova.cangjie.test.TestMetadata
import org.junit.jupiter.api.Test
import java.io.File
import org.cangnova.cangjie.cfir.analysis.tests.assertAllFilesPresentByMetadata

/** AUTO-GENERATED by TestGeneratorForCfirAnalysisTests. DO NOT EDIT MANUALLY. */
@TestMetadata("cfir/analysis-tests/testData/llt/generics/generic_constraint_inheritance")
@TestDataPath("${'$'}PROJECT_ROOT")
@OptIn(ObsoleteTestInfrastructure::class)
@ObsoleteTestInfrastructure
class GenericConstraintInheritanceGenerated : AbstractCfirLightTreeLlTDiagnosticsTest() {
    @Test
    fun testAllFilesPresent() {
        assertAllFilesPresentByMetadata(this, "cfir/analysis-tests/testData/llt/generics/generic_constraint_inheritance")
    }

    @TestMetadata("generic_constraint_inheritance_01.cj")
    @Test
    fun testGenericConstraintInheritance01() {
        runTest("cfir/analysis-tests/testData/llt/generics/generic_constraint_inheritance/generic_constraint_inheritance_01.cj")
    }

    @TestMetadata("generic_constraint_inheritance_02.cj")
    @Test
    fun testGenericConstraintInheritance02() {
        runTest("cfir/analysis-tests/testData/llt/generics/generic_constraint_inheritance/generic_constraint_inheritance_02.cj")
    }

    @TestMetadata("generic_constraint_inheritance_03.cj")
    @Test
    fun testGenericConstraintInheritance03() {
        runTest("cfir/analysis-tests/testData/llt/generics/generic_constraint_inheritance/generic_constraint_inheritance_03.cj")
    }

    @TestMetadata("generic_constraint_inheritance_04.cj")
    @Test
    fun testGenericConstraintInheritance04() {
        runTest("cfir/analysis-tests/testData/llt/generics/generic_constraint_inheritance/generic_constraint_inheritance_04.cj")
    }

    @TestMetadata("generic_constraint_inheritance_05.cj")
    @Test
    fun testGenericConstraintInheritance05() {
        runTest("cfir/analysis-tests/testData/llt/generics/generic_constraint_inheritance/generic_constraint_inheritance_05.cj")
    }

    @TestMetadata("generic_constraint_inheritance_06.cj")
    @Test
    fun testGenericConstraintInheritance06() {
        runTest("cfir/analysis-tests/testData/llt/generics/generic_constraint_inheritance/generic_constraint_inheritance_06.cj")
    }

    @TestMetadata("generic_constraint_inheritance_07.cj")
    @Test
    fun testGenericConstraintInheritance07() {
        runTest("cfir/analysis-tests/testData/llt/generics/generic_constraint_inheritance/generic_constraint_inheritance_07.cj")
    }

    @TestMetadata("generic_constraint_inheritance_08.cj")
    @Test
    fun testGenericConstraintInheritance08() {
        runTest("cfir/analysis-tests/testData/llt/generics/generic_constraint_inheritance/generic_constraint_inheritance_08.cj")
    }

    @TestMetadata("generic_upper_constraint_inheritance_01.cj")
    @Test
    fun testGenericUpperConstraintInheritance01() {
        runTest("cfir/analysis-tests/testData/llt/generics/generic_constraint_inheritance/generic_upper_constraint_inheritance_01.cj")
    }

    @TestMetadata("generic_upper_constraint_inheritance_02.cj")
    @Test
    fun testGenericUpperConstraintInheritance02() {
        runTest("cfir/analysis-tests/testData/llt/generics/generic_constraint_inheritance/generic_upper_constraint_inheritance_02.cj")
    }

    @TestMetadata("generic_upper_constraint_inheritance_03.cj")
    @Test
    fun testGenericUpperConstraintInheritance03() {
        runTest("cfir/analysis-tests/testData/llt/generics/generic_constraint_inheritance/generic_upper_constraint_inheritance_03.cj")
    }

    @TestMetadata("generic_upper_constraint_inheritance_04.cj")
    @Test
    fun testGenericUpperConstraintInheritance04() {
        runTest("cfir/analysis-tests/testData/llt/generics/generic_constraint_inheritance/generic_upper_constraint_inheritance_04.cj")
    }

    @TestMetadata("generic_upper_constraint_inheritance_05.cj")
    @Test
    fun testGenericUpperConstraintInheritance05() {
        runTest("cfir/analysis-tests/testData/llt/generics/generic_constraint_inheritance/generic_upper_constraint_inheritance_05.cj")
    }

    @TestMetadata("generic_upper_constraint_inheritance_06.cj")
    @Test
    fun testGenericUpperConstraintInheritance06() {
        runTest("cfir/analysis-tests/testData/llt/generics/generic_constraint_inheritance/generic_upper_constraint_inheritance_06.cj")
    }

    @TestMetadata("generic_upper_constraint_inheritance_07.cj")
    @Test
    fun testGenericUpperConstraintInheritance07() {
        runTest("cfir/analysis-tests/testData/llt/generics/generic_constraint_inheritance/generic_upper_constraint_inheritance_07.cj")
    }

    @TestMetadata("generic_upper_constraint_inheritance_08.cj")
    @Test
    fun testGenericUpperConstraintInheritance08() {
        runTest("cfir/analysis-tests/testData/llt/generics/generic_constraint_inheritance/generic_upper_constraint_inheritance_08.cj")
    }

    @TestMetadata("generic_upper_constraint_inheritance_09.cj")
    @Test
    fun testGenericUpperConstraintInheritance09() {
        runTest("cfir/analysis-tests/testData/llt/generics/generic_constraint_inheritance/generic_upper_constraint_inheritance_09.cj")
    }

    @TestMetadata("generic_upper_constraint_inheritance_10.cj")
    @Test
    fun testGenericUpperConstraintInheritance10() {
        runTest("cfir/analysis-tests/testData/llt/generics/generic_constraint_inheritance/generic_upper_constraint_inheritance_10.cj")
    }

    @TestMetadata("generic_upper_constraint_inheritance_11.cj")
    @Test
    fun testGenericUpperConstraintInheritance11() {
        runTest("cfir/analysis-tests/testData/llt/generics/generic_constraint_inheritance/generic_upper_constraint_inheritance_11.cj")
    }
}

