package org.cangnova.cangjie.cfir.analysis.tests.CfirAnalysisLLTTest.llt.CompoundAssign

import com.intellij.testFramework.TestDataPath
import org.cangnova.cangjie.ObsoleteTestInfrastructure
import org.cangnova.cangjie.cfir.analysis.tests.runners.AbstractCfirLightTreeLlTDiagnosticsTest
import org.cangnova.cangjie.test.TestMetadata
import org.junit.jupiter.api.Test
import java.io.File
import org.cangnova.cangjie.cfir.analysis.tests.assertAllFilesPresentByMetadata

/** AUTO-GENERATED by TestGeneratorForCfirAnalysisTests. DO NOT EDIT MANUALLY. */
@TestMetadata("cfir/analysis-tests/testData/llt/CompoundAssign")
@TestDataPath("${'$'}PROJECT_ROOT")
@OptIn(ObsoleteTestInfrastructure::class)
@ObsoleteTestInfrastructure
class CompoundAssignGenerated : AbstractCfirLightTreeLlTDiagnosticsTest() {
    @Test
    fun testAllFilesPresent() {
        assertAllFilesPresentByMetadata(this, "cfir/analysis-tests/testData/llt/CompoundAssign")
    }

    @TestMetadata("overflow_01.cj")
    @Test
    fun testOverflow01() {
        runTest("cfir/analysis-tests/testData/llt/CompoundAssign/overflow_01.cj")
    }

    @TestMetadata("overflow_02.cj")
    @Test
    fun testOverflow02() {
        runTest("cfir/analysis-tests/testData/llt/CompoundAssign/overflow_02.cj")
    }

    @TestMetadata("overshift_01.cj")
    @Test
    fun testOvershift01() {
        runTest("cfir/analysis-tests/testData/llt/CompoundAssign/overshift_01.cj")
    }

    @TestMetadata("overshift_02.cj")
    @Test
    fun testOvershift02() {
        runTest("cfir/analysis-tests/testData/llt/CompoundAssign/overshift_02.cj")
    }
}

