package org.cangnova.cangjie.cfir.analysis.tests.CfirAnalysisLLTTest.llt.record.member_variable

import com.intellij.testFramework.TestDataPath
import org.cangnova.cangjie.ObsoleteTestInfrastructure
import org.cangnova.cangjie.cfir.analysis.tests.runners.AbstractCfirLightTreeLlTDiagnosticsTest
import org.cangnova.cangjie.test.TestMetadata
import org.junit.jupiter.api.Test
import java.io.File
import org.cangnova.cangjie.cfir.analysis.tests.assertAllFilesPresentByMetadata

/** AUTO-GENERATED by TestGeneratorForCfirAnalysisTests. DO NOT EDIT MANUALLY. */
@TestMetadata("cfir/analysis-tests/testData/llt/record/member_variable")
@TestDataPath("${'$'}PROJECT_ROOT")
@OptIn(ObsoleteTestInfrastructure::class)
@ObsoleteTestInfrastructure
class MemberVariableGenerated : AbstractCfirLightTreeLlTDiagnosticsTest() {
    @Test
    fun testAllFilesPresent() {
        assertAllFilesPresentByMetadata(this, "cfir/analysis-tests/testData/llt/record/member_variable")
    }

    @TestMetadata("record_member_variable_init01.cj")
    @Test
    fun testRecordMemberVariableInit01() {
        runTest("cfir/analysis-tests/testData/llt/record/member_variable/record_member_variable_init01.cj")
    }

    @TestMetadata("record_member_variable_init02.cj")
    @Test
    fun testRecordMemberVariableInit02() {
        runTest("cfir/analysis-tests/testData/llt/record/member_variable/record_member_variable_init02.cj")
    }

    @TestMetadata("record_member_variable_init03.cj")
    @Test
    fun testRecordMemberVariableInit03() {
        runTest("cfir/analysis-tests/testData/llt/record/member_variable/record_member_variable_init03.cj")
    }

    @TestMetadata("record_member_variable_init04.cj")
    @Test
    fun testRecordMemberVariableInit04() {
        runTest("cfir/analysis-tests/testData/llt/record/member_variable/record_member_variable_init04.cj")
    }
}

