// Copyright (c) Huawei Technologies Co., Ltd. 2025. All rights reserved.
// This source file is part of the Cangjie project, licensed under Apache-2.0
// with Runtime Library Exception.
//
// See https://cangjie-lang.cn/pages/LICENSE for license information.


@C
foreign func get_cptr6(cb2: CFunc<(CPointer<Int8CPointer<Int8>>)<!parse_expected_right_delimiter!>:<!> CPointer<Int8><!parse_expected_character!><<!>(CPointer<Int8>)->CPointer<Int8>>): CPointer<Int8>

unsafe main():Int64 {
    return 0
}
