package org.cangnova.cangjie.cfir.analysis.tests.CfirAnalysisLLTPsiTest.llt._interface.use_interface_default_impl_01

import com.intellij.testFramework.TestDataPath
import org.cangnova.cangjie.ObsoleteTestInfrastructure
import org.cangnova.cangjie.cfir.analysis.tests.runners.AbstractCfirPsiLlTDiagnosticsTest
import org.cangnova.cangjie.test.TestMetadata
import org.junit.jupiter.api.Test
import java.io.File
import org.cangnova.cangjie.cfir.analysis.tests.assertAllFilesPresentByMetadata

/** AUTO-GENERATED by TestGeneratorForCfirAnalysisTests. DO NOT EDIT MANUALLY. */
@TestMetadata("cfir/analysis-tests/testData/llt/interface/use_interface_default_impl_01")
@TestDataPath("${'$'}PROJECT_ROOT")
@OptIn(ObsoleteTestInfrastructure::class)
@ObsoleteTestInfrastructure
class UseInterfaceDefaultImpl01Generated : AbstractCfirPsiLlTDiagnosticsTest() {
    @Test
    fun testAllFilesPresent() {
        assertAllFilesPresentByMetadata(this, "cfir/analysis-tests/testData/llt/interface/use_interface_default_impl_01")
    }

    @TestMetadata("use_interface_def_imple_005.cj")
    @Test
    fun testUseInterfaceDefImple005() {
        runTest("cfir/analysis-tests/testData/llt/interface/use_interface_default_impl_01/use_interface_def_imple_005.cj")
    }
}

