package org.cangnova.cangjie.cfir.analysis.tests.CfirAnalysisLLTTest.llt._this

import com.intellij.testFramework.TestDataPath
import org.cangnova.cangjie.ObsoleteTestInfrastructure
import org.cangnova.cangjie.cfir.analysis.tests.runners.AbstractCfirLightTreeLlTDiagnosticsTest
import org.cangnova.cangjie.test.TestMetadata
import org.junit.jupiter.api.Test
import java.io.File
import org.cangnova.cangjie.cfir.analysis.tests.assertAllFilesPresentByMetadata

/** AUTO-GENERATED by TestGeneratorForCfirAnalysisTests. DO NOT EDIT MANUALLY. */
@TestMetadata("cfir/analysis-tests/testData/llt/this")
@TestDataPath("${'$'}PROJECT_ROOT")
@OptIn(ObsoleteTestInfrastructure::class)
@ObsoleteTestInfrastructure
class ThisGenerated : AbstractCfirLightTreeLlTDiagnosticsTest() {
    @Test
    fun testAllFilesPresent() {
        assertAllFilesPresentByMetadata(this, "cfir/analysis-tests/testData/llt/this")
    }

    @TestMetadata("callthisop.cj")
    @Test
    fun testCallthisop() {
        runTest("cfir/analysis-tests/testData/llt/this/callthisop.cj")
    }

    @TestMetadata("chkmatch.cj")
    @Test
    fun testChkmatch() {
        runTest("cfir/analysis-tests/testData/llt/this/chkmatch.cj")
    }

    @TestMetadata("err_capture_00.cj")
    @Test
    fun testErrCapture00() {
        runTest("cfir/analysis-tests/testData/llt/this/err_capture_00.cj")
    }

    @TestMetadata("instanceFuncReturningThis.cj")
    @Test
    fun testInstanceFuncReturningThis() {
        runTest("cfir/analysis-tests/testData/llt/this/instanceFuncReturningThis.cj")
    }

    @TestMetadata("synif.cj")
    @Test
    fun testSynif() {
        runTest("cfir/analysis-tests/testData/llt/this/synif.cj")
    }

    @TestMetadata("synmatch.cj")
    @Test
    fun testSynmatch() {
        runTest("cfir/analysis-tests/testData/llt/this/synmatch.cj")
    }

    @TestMetadata("this3.cj")
    @Test
    fun testThis3() {
        runTest("cfir/analysis-tests/testData/llt/this/this3.cj")
    }

    @TestMetadata("this_chain.cj")
    @Test
    fun testThisChain() {
        runTest("cfir/analysis-tests/testData/llt/this/this_chain.cj")
    }

    @TestMetadata("this_initializer.cj")
    @Test
    fun testThisInitializer() {
        runTest("cfir/analysis-tests/testData/llt/this/this_initializer.cj")
    }

    @TestMetadata("thisfuncchain.cj")
    @Test
    fun testThisfuncchain() {
        runTest("cfir/analysis-tests/testData/llt/this/thisfuncchain.cj")
    }

    @TestMetadata("unsafe.cj")
    @Test
    fun testUnsafe() {
        runTest("cfir/analysis-tests/testData/llt/this/unsafe.cj")
    }
}

