package org.cangnova.cangjie.cfir.analysis.tests.CfirAnalysisDiagnosticsWithoutAliasExpansionTest.diagnostics.generic_access

import com.intellij.testFramework.TestDataPath
import org.cangnova.cangjie.ObsoleteTestInfrastructure
import org.cangnova.cangjie.cfir.analysis.tests.runners.AbstractCfirLightTreeDiagnosticsWithoutAliasExpansionTest
import org.cangnova.cangjie.test.TestMetadata
import org.junit.jupiter.api.Test
import java.io.File
import org.cangnova.cangjie.cfir.analysis.tests.assertAllFilesPresentByMetadata

/** AUTO-GENERATED by TestGeneratorForCfirAnalysisTests. DO NOT EDIT MANUALLY. */
@TestMetadata("cfir/analysis-tests/testData/diagnostics/generic-access")
@TestDataPath("${'$'}PROJECT_ROOT")
@OptIn(ObsoleteTestInfrastructure::class)
@ObsoleteTestInfrastructure
class GenericAccessGenerated : AbstractCfirLightTreeDiagnosticsWithoutAliasExpansionTest() {
    @Test
    fun testAllFilesPresent() {
        assertAllFilesPresentByMetadata(this, "cfir/analysis-tests/testData/diagnostics/generic-access")
    }

    @TestMetadata("genericTypeWithoutTypeArgumentRich.cj")
    @Test
    fun testGenericTypeWithoutTypeArgumentRich() {
        runTest("cfir/analysis-tests/testData/diagnostics/generic-access/genericTypeWithoutTypeArgumentRich.cj")
    }

    @TestMetadata("upperBoundsMemberAndMethodRich.cj")
    @Test
    fun testUpperBoundsMemberAndMethodRich() {
        runTest("cfir/analysis-tests/testData/diagnostics/generic-access/upperBoundsMemberAndMethodRich.cj")
    }
}

