package org.cangnova.cangjie.cfir.analysis.tests.CfirAnalysisDiagnostics2WithoutAliasExpansionTest.diagnostics2.initialization

import com.intellij.testFramework.TestDataPath
import org.cangnova.cangjie.ObsoleteTestInfrastructure
import org.cangnova.cangjie.cfir.analysis.tests.runners.AbstractCfirLightTreeDiagnosticsWithoutAliasExpansionTest
import org.cangnova.cangjie.test.TestMetadata
import org.junit.jupiter.api.Test
import java.io.File
import org.cangnova.cangjie.cfir.analysis.tests.assertAllFilesPresentByMetadata

/** AUTO-GENERATED by TestGeneratorForCfirAnalysisTests. DO NOT EDIT MANUALLY. */
@TestMetadata("cfir/analysis-tests/testData/diagnostics2/initialization")
@TestDataPath("${'$'}PROJECT_ROOT")
@OptIn(ObsoleteTestInfrastructure::class)
@ObsoleteTestInfrastructure
class InitializationGenerated : AbstractCfirLightTreeDiagnosticsWithoutAliasExpansionTest() {
    @Test
    fun testAllFilesPresent() {
        assertAllFilesPresentByMetadata(this, "cfir/analysis-tests/testData/diagnostics2/initialization")
    }

    @TestMetadata("controlFlowInitialization.cj")
    @Test
    fun testControlFlowInitialization() {
        runTest("cfir/analysis-tests/testData/diagnostics2/initialization/controlFlowInitialization.cj")
    }

    @TestMetadata("usedBeforeInitialization.cj")
    @Test
    fun testUsedBeforeInitialization() {
        runTest("cfir/analysis-tests/testData/diagnostics2/initialization/usedBeforeInitialization.cj")
    }
}

