package org.cangnova.cangjie.cfir.analysis.tests.CfirAnalysisDiagnosticsTest.diagnostics.pattern

import com.intellij.testFramework.TestDataPath
import org.cangnova.cangjie.ObsoleteTestInfrastructure
import org.cangnova.cangjie.cfir.analysis.tests.runners.AbstractCfirLightTreeDiagnosticsTest
import org.cangnova.cangjie.test.TestMetadata
import org.junit.jupiter.api.Test
import java.io.File
import org.cangnova.cangjie.cfir.analysis.tests.assertAllFilesPresentByMetadata

/** AUTO-GENERATED by TestGeneratorForCfirAnalysisTests. DO NOT EDIT MANUALLY. */
@TestMetadata("cfir/analysis-tests/testData/diagnostics/pattern")
@TestDataPath("${'$'}PROJECT_ROOT")
@OptIn(ObsoleteTestInfrastructure::class)
@ObsoleteTestInfrastructure
class PatternGenerated : AbstractCfirLightTreeDiagnosticsTest() {
    @Test
    fun testAllFilesPresent() {
        assertAllFilesPresentByMetadata(this, "cfir/analysis-tests/testData/diagnostics/pattern")
    }

    @TestMetadata("matchCaseHasNoTypeRich.cj")
    @Test
    fun testMatchCaseHasNoTypeRich() {
        runTest("cfir/analysis-tests/testData/diagnostics/pattern/matchCaseHasNoTypeRich.cj")
    }

    @TestMetadata("notOverloadInMatchRich.cj")
    @Test
    fun testNotOverloadInMatchRich() {
        runTest("cfir/analysis-tests/testData/diagnostics/pattern/notOverloadInMatchRich.cj")
    }

    @TestMetadata("patternLegalityRich.cj")
    @Test
    fun testPatternLegalityRich() {
        runTest("cfir/analysis-tests/testData/diagnostics/pattern/patternLegalityRich.cj")
    }
}

