package org.cangnova.cangjie.cfir.analysis.tests.CfirAnalysisLLTTest.llt.operator.bitwise_operator.shift

import com.intellij.testFramework.TestDataPath
import org.cangnova.cangjie.ObsoleteTestInfrastructure
import org.cangnova.cangjie.cfir.analysis.tests.runners.AbstractCfirLightTreeLlTDiagnosticsTest
import org.cangnova.cangjie.test.TestMetadata
import org.junit.jupiter.api.Test
import java.io.File
import org.cangnova.cangjie.cfir.analysis.tests.assertAllFilesPresentByMetadata

/** AUTO-GENERATED by TestGeneratorForCfirAnalysisTests. DO NOT EDIT MANUALLY. */
@TestMetadata("cfir/analysis-tests/testData/llt/operator/bitwise_operator/shift")
@TestDataPath("${'$'}PROJECT_ROOT")
@OptIn(ObsoleteTestInfrastructure::class)
@ObsoleteTestInfrastructure
class ShiftGenerated : AbstractCfirLightTreeLlTDiagnosticsTest() {
    @Test
    fun testAllFilesPresent() {
        assertAllFilesPresentByMetadata(this, "cfir/analysis-tests/testData/llt/operator/bitwise_operator/shift")
    }

    @TestMetadata("normal_shift.cj")
    @Test
    fun testNormalShift() {
        runTest("cfir/analysis-tests/testData/llt/operator/bitwise_operator/shift/normal_shift.cj")
    }

    @TestMetadata("shift_var_ty.cj")
    @Test
    fun testShiftVarTy() {
        runTest("cfir/analysis-tests/testData/llt/operator/bitwise_operator/shift/shift_var_ty.cj")
    }
}

