package org.cangnova.cangjie.cfir.analysis.tests.CfirAnalysisMacroTest.macro.llt.varray.varray_cffi

import com.intellij.testFramework.TestDataPath
import org.cangnova.cangjie.ObsoleteTestInfrastructure
import org.cangnova.cangjie.cfir.analysis.tests.runners.AbstractCfirLightTreeMacroDiagnosticsTest
import org.cangnova.cangjie.test.TestMetadata
import org.junit.jupiter.api.Test
import java.io.File
import org.cangnova.cangjie.cfir.analysis.tests.assertAllFilesPresentByMetadata

/** AUTO-GENERATED by TestGeneratorForCfirAnalysisTests. DO NOT EDIT MANUALLY. */
@TestMetadata("cfir/analysis-tests/testData/macro/llt/varray/varray_cffi")
@TestDataPath("${'$'}PROJECT_ROOT")
@OptIn(ObsoleteTestInfrastructure::class)
@ObsoleteTestInfrastructure
class VarrayCffiGenerated : AbstractCfirLightTreeMacroDiagnosticsTest() {
    @Test
    fun testAllFilesPresent() {
        assertAllFilesPresentByMetadata(this, "cfir/analysis-tests/testData/macro/llt/varray/varray_cffi")
    }

    @TestMetadata("varray_cstruct01.cj")
    @Test
    fun testVarrayCstruct01() {
        runTest("cfir/analysis-tests/testData/macro/llt/varray/varray_cffi/varray_cstruct01.cj")
    }

    @TestMetadata("varray_cstruct02.cj")
    @Test
    fun testVarrayCstruct02() {
        runTest("cfir/analysis-tests/testData/macro/llt/varray/varray_cffi/varray_cstruct02.cj")
    }

    @TestMetadata("varray_cstruct03.cj")
    @Test
    fun testVarrayCstruct03() {
        runTest("cfir/analysis-tests/testData/macro/llt/varray/varray_cffi/varray_cstruct03.cj")
    }

    @TestMetadata("varray_cstruct04.cj")
    @Test
    fun testVarrayCstruct04() {
        runTest("cfir/analysis-tests/testData/macro/llt/varray/varray_cffi/varray_cstruct04.cj")
    }

    @TestMetadata("varray_cstruct05.cj")
    @Test
    fun testVarrayCstruct05() {
        runTest("cfir/analysis-tests/testData/macro/llt/varray/varray_cffi/varray_cstruct05.cj")
    }

    @TestMetadata("varray_ctype01.cj")
    @Test
    fun testVarrayCtype01() {
        runTest("cfir/analysis-tests/testData/macro/llt/varray/varray_cffi/varray_ctype01.cj")
    }

    @TestMetadata("varray_ctype02.cj")
    @Test
    fun testVarrayCtype02() {
        runTest("cfir/analysis-tests/testData/macro/llt/varray/varray_cffi/varray_ctype02.cj")
    }

    @TestMetadata("varray_ctype03.cj")
    @Test
    fun testVarrayCtype03() {
        runTest("cfir/analysis-tests/testData/macro/llt/varray/varray_cffi/varray_ctype03.cj")
    }

    @TestMetadata("varray_inout.cj")
    @Test
    fun testVarrayInout() {
        runTest("cfir/analysis-tests/testData/macro/llt/varray/varray_cffi/varray_inout.cj")
    }

    @TestMetadata("varray_inout02.cj")
    @Test
    fun testVarrayInout02() {
        runTest("cfir/analysis-tests/testData/macro/llt/varray/varray_cffi/varray_inout02.cj")
    }

    @TestMetadata("varray_inout03.cj")
    @Test
    fun testVarrayInout03() {
        runTest("cfir/analysis-tests/testData/macro/llt/varray/varray_cffi/varray_inout03.cj")
    }

    @TestMetadata("varray_inout04.cj")
    @Test
    fun testVarrayInout04() {
        runTest("cfir/analysis-tests/testData/macro/llt/varray/varray_cffi/varray_inout04.cj")
    }

    @TestMetadata("varray_inout05.cj")
    @Test
    fun testVarrayInout05() {
        runTest("cfir/analysis-tests/testData/macro/llt/varray/varray_cffi/varray_inout05.cj")
    }
}

