package org.cangnova.cangjie.cfir.analysis.tests.CfirAnalysisLLTTest.llt.unusedImport.unusedImport002.unused017

import com.intellij.testFramework.TestDataPath
import org.cangnova.cangjie.ObsoleteTestInfrastructure
import org.cangnova.cangjie.cfir.analysis.tests.runners.AbstractCfirLightTreeLlTDiagnosticsTest
import org.cangnova.cangjie.test.TestMetadata
import org.junit.jupiter.api.Test
import java.io.File
import org.cangnova.cangjie.cfir.analysis.tests.assertAllFilesPresentByMetadata

/** AUTO-GENERATED by TestGeneratorForCfirAnalysisTests. DO NOT EDIT MANUALLY. */
@TestMetadata("cfir/analysis-tests/testData/llt/unusedImport/unusedImport002/unused017")
@TestDataPath("${'$'}PROJECT_ROOT")
@OptIn(ObsoleteTestInfrastructure::class)
@ObsoleteTestInfrastructure
class Unused017Generated : AbstractCfirLightTreeLlTDiagnosticsTest() {
    @Test
    fun testAllFilesPresent() {
        assertAllFilesPresentByMetadata(this, "cfir/analysis-tests/testData/llt/unusedImport/unusedImport002/unused017")
    }

    @TestMetadata("unused017.cj")
    @Test
    fun testUnused017() {
        runTest("cfir/analysis-tests/testData/llt/unusedImport/unusedImport002/unused017/unused017.cj")
    }
}

