package org.cangnova.cangjie.cfir.analysis.tests.CfirAnalysisLLTTest.llt.blockexpr

import com.intellij.testFramework.TestDataPath
import org.cangnova.cangjie.ObsoleteTestInfrastructure
import org.cangnova.cangjie.cfir.analysis.tests.runners.AbstractCfirLightTreeLlTDiagnosticsTest
import org.cangnova.cangjie.test.TestMetadata
import org.junit.jupiter.api.Test
import java.io.File
import org.cangnova.cangjie.cfir.analysis.tests.assertAllFilesPresentByMetadata

/** AUTO-GENERATED by TestGeneratorForCfirAnalysisTests. DO NOT EDIT MANUALLY. */
@TestMetadata("cfir/analysis-tests/testData/llt/blockexpr")
@TestDataPath("${'$'}PROJECT_ROOT")
@OptIn(ObsoleteTestInfrastructure::class)
@ObsoleteTestInfrastructure
class BlockexprGenerated : AbstractCfirLightTreeLlTDiagnosticsTest() {
    @Test
    fun testAllFilesPresent() {
        assertAllFilesPresentByMetadata(this, "cfir/analysis-tests/testData/llt/blockexpr")
    }

    @TestMetadata("blockexpr1.cj")
    @Test
    fun testBlockexpr1() {
        runTest("cfir/analysis-tests/testData/llt/blockexpr/blockexpr1.cj")
    }

    @TestMetadata("blockexpr2.cj")
    @Test
    fun testBlockexpr2() {
        runTest("cfir/analysis-tests/testData/llt/blockexpr/blockexpr2.cj")
    }

    @TestMetadata("blockexpr3.cj")
    @Test
    fun testBlockexpr3() {
        runTest("cfir/analysis-tests/testData/llt/blockexpr/blockexpr3.cj")
    }

    @TestMetadata("blockexpr4.cj")
    @Test
    fun testBlockexpr4() {
        runTest("cfir/analysis-tests/testData/llt/blockexpr/blockexpr4.cj")
    }

    @TestMetadata("blockexpr5.cj")
    @Test
    fun testBlockexpr5() {
        runTest("cfir/analysis-tests/testData/llt/blockexpr/blockexpr5.cj")
    }

    @TestMetadata("blockexpr6.cj")
    @Test
    fun testBlockexpr6() {
        runTest("cfir/analysis-tests/testData/llt/blockexpr/blockexpr6.cj")
    }

    @TestMetadata("err_block_00.cj")
    @Test
    fun testErrBlock00() {
        runTest("cfir/analysis-tests/testData/llt/blockexpr/err_block_00.cj")
    }

    @TestMetadata("err_block_01.cj")
    @Test
    fun testErrBlock01() {
        runTest("cfir/analysis-tests/testData/llt/blockexpr/err_block_01.cj")
    }

    @TestMetadata("err_block_02.cj")
    @Test
    fun testErrBlock02() {
        runTest("cfir/analysis-tests/testData/llt/blockexpr/err_block_02.cj")
    }

    @TestMetadata("err_block_03.cj")
    @Test
    fun testErrBlock03() {
        runTest("cfir/analysis-tests/testData/llt/blockexpr/err_block_03.cj")
    }
}

