// Copyright (c) Huawei Technologies Co., Ltd. 2025. All rights reserved.
// This source file is part of the Cangjie project, licensed under Apache-2.0
// with Runtime Library Exception.
//
// See https://cangjie-lang.cn/pages/LICENSE for license information.

package ohos.dep

import ohos.labels.*

@!Hide[isChecked: true]
@!APILevel[since: "21"]
public open class A {
}

@!APILevel[since: "21"]
@!Hide[isChecked: true]
public open class B {
}
