

package org.cangnova.cangjie.analysis.low.level.api.cfir.resolve;

import com.intellij.testFramework.TestDataPath;
import org.cangnova.cangjie.test.util.CjTestUtil;
import org.cangnova.cangjie.test.TestMetadata;
import org.junit.jupiter.api.Test;

import java.io.File;
import java.util.regex.Pattern;

/** This class is generated by {@link org.cangnova.cangjie.analysis.low.level.api.cfir.TestGeneratorKt}. DO NOT MODIFY MANUALLY */
@SuppressWarnings("all")
@TestMetadata("analysis/low-level-api-cfir/testData/cjmpMatching")
@TestDataPath("$PROJECT_ROOT")
public class CfirCjmpMatchingTestGenerated extends AbstractCfirCjmpMatchingTest {
  private void run(String fileName) {
    runTest("analysis/low-level-api-cfir/testData/cjmpMatching/" + fileName);
  }

  @Test
  public void testAllFilesPresentInCjmpMatching() {
    CjTestUtil.assertAllTestsPresentByMetadataWithExcluded(this.getClass(), new File("analysis/low-level-api-cfir/testData/cjmpMatching"), Pattern.compile("^(.+)\\.cj$"), null, true);
  }

  @Test
  @TestMetadata("firstFitCandidateDiagnostic.cj")
  public void testFirstFitCandidateDiagnostic() {
    run("firstFitCandidateDiagnostic.cj");
  }

  @Test
  @TestMetadata("memberFirstMatch.cj")
  public void testMemberFirstMatch() {
    run("memberFirstMatch.cj");
  }

  @Test
  @TestMetadata("modeNoneDoesNotMatch.cj")
  public void testModeNoneDoesNotMatch() {
    run("modeNoneDoesNotMatch.cj");
  }

  @Test
  @TestMetadata("parallelTopLevelSpecificFirstMatch.cj")
  public void testParallelTopLevelSpecificFirstMatch() {
    run("parallelTopLevelSpecificFirstMatch.cj");
  }

  @Test
  @TestMetadata("specificMemberMatchesCommon.cj")
  public void testSpecificMemberMatchesCommon() {
    run("specificMemberMatchesCommon.cj");
  }

  @Test
  @TestMetadata("topLevelSpecificFirstMatch.cj")
  public void testTopLevelSpecificFirstMatch() {
    run("topLevelSpecificFirstMatch.cj");
  }
}
