

package org.cangnova.cangjie.analysis.low.level.api.cfir.resolve;

import com.intellij.testFramework.TestDataPath;
import org.cangnova.cangjie.test.util.CjTestUtil;
import org.cangnova.cangjie.test.TestMetadata;
import org.junit.jupiter.api.Test;

import java.io.File;
import java.util.regex.Pattern;

/** This class is generated by {@link org.cangnova.cangjie.analysis.low.level.api.cfir.TestGeneratorKt}. DO NOT MODIFY MANUALLY */
@SuppressWarnings("all")
@TestMetadata("analysis/low-level-api-cfir/testData/deprecationsResolve")
@TestDataPath("$PROJECT_ROOT")
public class DeprecationsResolveTestGenerated extends AbstractDeprecationsResolveTest {
  private void run(String fileName) {
    runTest("analysis/low-level-api-cfir/testData/deprecationsResolve/" + fileName);
  }

  @Test
  public void testAllFilesPresentInDeprecationsResolve() {
    CjTestUtil.assertAllTestsPresentByMetadataWithExcluded(this.getClass(), new File("analysis/low-level-api-cfir/testData/deprecationsResolve"), Pattern.compile("^(.+)\\.cj$"), null, true);
  }

  @Test
  @TestMetadata("deprecatedFunction.cj")
  public void testDeprecatedFunction() {
    run("deprecatedFunction.cj");
  }
}
