package org.cangnova.cangjie.cfir.analysis.tests.CfirAnalysisDiagnostics2Test.diagnostics2.modifier

import com.intellij.testFramework.TestDataPath
import org.cangnova.cangjie.ObsoleteTestInfrastructure
import org.cangnova.cangjie.cfir.analysis.tests.runners.AbstractCfirLightTreeDiagnosticsTest
import org.cangnova.cangjie.test.TestMetadata
import org.junit.jupiter.api.Test
import java.io.File
import org.cangnova.cangjie.cfir.analysis.tests.assertAllFilesPresentByMetadata

/** AUTO-GENERATED by TestGeneratorForCfirAnalysisTests. DO NOT EDIT MANUALLY. */
@TestMetadata("cfir/analysis-tests/testData/diagnostics2/modifier")
@TestDataPath("${'$'}PROJECT_ROOT")
@OptIn(ObsoleteTestInfrastructure::class)
@ObsoleteTestInfrastructure
class ModifierGenerated : AbstractCfirLightTreeDiagnosticsTest() {
    @Test
    fun testAllFilesPresent() {
        assertAllFilesPresentByMetadata(this, "cfir/analysis-tests/testData/diagnostics2/modifier")
    }

    @TestMetadata("internal.cj")
    @Test
    fun testInternal() {
        runTest("cfir/analysis-tests/testData/diagnostics2/modifier/internal.cj")
    }

    @TestMetadata("private.cj")
    @Test
    fun testPrivate() {
        runTest("cfir/analysis-tests/testData/diagnostics2/modifier/private.cj")
    }

    @TestMetadata("protected.cj")
    @Test
    fun testProtected() {
        runTest("cfir/analysis-tests/testData/diagnostics2/modifier/protected.cj")
    }

    @TestMetadata("public.cj")
    @Test
    fun testPublic() {
        runTest("cfir/analysis-tests/testData/diagnostics2/modifier/public.cj")
    }
}

