package org.cangnova.cangjie.cfir.analysis.tests.CfirAnalysisLLTTest.llt._class.class_property

import com.intellij.testFramework.TestDataPath
import org.cangnova.cangjie.ObsoleteTestInfrastructure
import org.cangnova.cangjie.cfir.analysis.tests.runners.AbstractCfirLightTreeLlTDiagnosticsTest
import org.cangnova.cangjie.test.TestMetadata
import org.junit.jupiter.api.Test
import java.io.File
import org.cangnova.cangjie.cfir.analysis.tests.assertAllFilesPresentByMetadata

/** AUTO-GENERATED by TestGeneratorForCfirAnalysisTests. DO NOT EDIT MANUALLY. */
@TestMetadata("cfir/analysis-tests/testData/llt/class/class_property")
@TestDataPath("${'$'}PROJECT_ROOT")
@OptIn(ObsoleteTestInfrastructure::class)
@ObsoleteTestInfrastructure
class ClassPropertyGenerated : AbstractCfirLightTreeLlTDiagnosticsTest() {
    @Test
    fun testAllFilesPresent() {
        assertAllFilesPresentByMetadata(this, "cfir/analysis-tests/testData/llt/class/class_property")
    }

    @TestMetadata("property1.cj")
    @Test
    fun testProperty1() {
        runTest("cfir/analysis-tests/testData/llt/class/class_property/property1.cj")
    }

    @TestMetadata("property10.cj")
    @Test
    fun testProperty10() {
        runTest("cfir/analysis-tests/testData/llt/class/class_property/property10.cj")
    }

    @TestMetadata("property11.cj")
    @Test
    fun testProperty11() {
        runTest("cfir/analysis-tests/testData/llt/class/class_property/property11.cj")
    }

    @TestMetadata("property12.cj")
    @Test
    fun testProperty12() {
        runTest("cfir/analysis-tests/testData/llt/class/class_property/property12.cj")
    }

    @TestMetadata("property13.cj")
    @Test
    fun testProperty13() {
        runTest("cfir/analysis-tests/testData/llt/class/class_property/property13.cj")
    }

    @TestMetadata("property14.cj")
    @Test
    fun testProperty14() {
        runTest("cfir/analysis-tests/testData/llt/class/class_property/property14.cj")
    }

    @TestMetadata("property15.cj")
    @Test
    fun testProperty15() {
        runTest("cfir/analysis-tests/testData/llt/class/class_property/property15.cj")
    }

    @TestMetadata("property16.cj")
    @Test
    fun testProperty16() {
        runTest("cfir/analysis-tests/testData/llt/class/class_property/property16.cj")
    }

    @TestMetadata("property18.cj")
    @Test
    fun testProperty18() {
        runTest("cfir/analysis-tests/testData/llt/class/class_property/property18.cj")
    }

    @TestMetadata("property19.cj")
    @Test
    fun testProperty19() {
        runTest("cfir/analysis-tests/testData/llt/class/class_property/property19.cj")
    }

    @TestMetadata("property2.cj")
    @Test
    fun testProperty2() {
        runTest("cfir/analysis-tests/testData/llt/class/class_property/property2.cj")
    }

    @TestMetadata("property20.cj")
    @Test
    fun testProperty20() {
        runTest("cfir/analysis-tests/testData/llt/class/class_property/property20.cj")
    }

    @TestMetadata("property21.cj")
    @Test
    fun testProperty21() {
        runTest("cfir/analysis-tests/testData/llt/class/class_property/property21.cj")
    }

    @TestMetadata("property22.cj")
    @Test
    fun testProperty22() {
        runTest("cfir/analysis-tests/testData/llt/class/class_property/property22.cj")
    }

    @TestMetadata("property23.cj")
    @Test
    fun testProperty23() {
        runTest("cfir/analysis-tests/testData/llt/class/class_property/property23.cj")
    }

    @TestMetadata("property24.cj")
    @Test
    fun testProperty24() {
        runTest("cfir/analysis-tests/testData/llt/class/class_property/property24.cj")
    }

    @TestMetadata("property25.cj")
    @Test
    fun testProperty25() {
        runTest("cfir/analysis-tests/testData/llt/class/class_property/property25.cj")
    }

    @TestMetadata("property26.cj")
    @Test
    fun testProperty26() {
        runTest("cfir/analysis-tests/testData/llt/class/class_property/property26.cj")
    }

    @TestMetadata("property27.cj")
    @Test
    fun testProperty27() {
        runTest("cfir/analysis-tests/testData/llt/class/class_property/property27.cj")
    }

    @TestMetadata("property28.cj")
    @Test
    fun testProperty28() {
        runTest("cfir/analysis-tests/testData/llt/class/class_property/property28.cj")
    }

    @TestMetadata("property29.cj")
    @Test
    fun testProperty29() {
        runTest("cfir/analysis-tests/testData/llt/class/class_property/property29.cj")
    }

    @TestMetadata("property3.cj")
    @Test
    fun testProperty3() {
        runTest("cfir/analysis-tests/testData/llt/class/class_property/property3.cj")
    }

    @TestMetadata("property30.cj")
    @Test
    fun testProperty30() {
        runTest("cfir/analysis-tests/testData/llt/class/class_property/property30.cj")
    }

    @TestMetadata("property4.cj")
    @Test
    fun testProperty4() {
        runTest("cfir/analysis-tests/testData/llt/class/class_property/property4.cj")
    }

    @TestMetadata("property5.cj")
    @Test
    fun testProperty5() {
        runTest("cfir/analysis-tests/testData/llt/class/class_property/property5.cj")
    }

    @TestMetadata("property6.cj")
    @Test
    fun testProperty6() {
        runTest("cfir/analysis-tests/testData/llt/class/class_property/property6.cj")
    }

    @TestMetadata("property7.cj")
    @Test
    fun testProperty7() {
        runTest("cfir/analysis-tests/testData/llt/class/class_property/property7.cj")
    }

    @TestMetadata("property8.cj")
    @Test
    fun testProperty8() {
        runTest("cfir/analysis-tests/testData/llt/class/class_property/property8.cj")
    }

    @TestMetadata("property9.cj")
    @Test
    fun testProperty9() {
        runTest("cfir/analysis-tests/testData/llt/class/class_property/property9.cj")
    }
}

