package org.cangnova.cangjie.cfir.analysis.tests.CfirAnalysisLLTTest.llt.type

import com.intellij.testFramework.TestDataPath
import org.cangnova.cangjie.ObsoleteTestInfrastructure
import org.cangnova.cangjie.cfir.analysis.tests.runners.AbstractCfirLightTreeLlTDiagnosticsTest
import org.cangnova.cangjie.test.TestMetadata
import org.junit.jupiter.api.Test
import java.io.File
import org.cangnova.cangjie.cfir.analysis.tests.assertAllFilesPresentByMetadata

/** AUTO-GENERATED by TestGeneratorForCfirAnalysisTests. DO NOT EDIT MANUALLY. */
@TestMetadata("cfir/analysis-tests/testData/llt/type")
@TestDataPath("${'$'}PROJECT_ROOT")
@OptIn(ObsoleteTestInfrastructure::class)
@ObsoleteTestInfrastructure
class TypeGenerated : AbstractCfirLightTreeLlTDiagnosticsTest() {
    @Test
    fun testAllFilesPresent() {
        assertAllFilesPresentByMetadata(this, "cfir/analysis-tests/testData/llt/type")
    }

    @TestMetadata("Int_UInt.cj")
    @Test
    fun testIntUInt() {
        runTest("cfir/analysis-tests/testData/llt/type/Int_UInt.cj")
    }

    @TestMetadata("err_recursive_func_00.cj")
    @Test
    fun testErrRecursiveFunc00() {
        runTest("cfir/analysis-tests/testData/llt/type/err_recursive_func_00.cj")
    }

    @TestMetadata("err_recursive_func_01.cj")
    @Test
    fun testErrRecursiveFunc01() {
        runTest("cfir/analysis-tests/testData/llt/type/err_recursive_func_01.cj")
    }

    @TestMetadata("err_recursive_func_02.cj")
    @Test
    fun testErrRecursiveFunc02() {
        runTest("cfir/analysis-tests/testData/llt/type/err_recursive_func_02.cj")
    }

    @TestMetadata("int64max.cj")
    @Test
    fun testInt64max() {
        runTest("cfir/analysis-tests/testData/llt/type/int64max.cj")
    }

    @TestMetadata("numeric_type_conv.cj")
    @Test
    fun testNumericTypeConv() {
        runTest("cfir/analysis-tests/testData/llt/type/numeric_type_conv.cj")
    }

    @TestMetadata("numeric_type_conv_2.cj")
    @Test
    fun testNumericTypeConv2() {
        runTest("cfir/analysis-tests/testData/llt/type/numeric_type_conv_2.cj")
    }

    @TestMetadata("ok_float.cj")
    @Test
    fun testOkFloat() {
        runTest("cfir/analysis-tests/testData/llt/type/ok_float.cj")
    }

    @TestMetadata("paren_type_with_generic_type.cj")
    @Test
    fun testParenTypeWithGenericType() {
        runTest("cfir/analysis-tests/testData/llt/type/paren_type_with_generic_type.cj")
    }

    @TestMetadata("subtype_00.cj")
    @Test
    fun testSubtype00() {
        runTest("cfir/analysis-tests/testData/llt/type/subtype_00.cj")
    }

    @TestMetadata("subtype_01.cj")
    @Test
    fun testSubtype01() {
        runTest("cfir/analysis-tests/testData/llt/type/subtype_01.cj")
    }

    @TestMetadata("subtype_02.cj")
    @Test
    fun testSubtype02() {
        runTest("cfir/analysis-tests/testData/llt/type/subtype_02.cj")
    }

    @TestMetadata("subtype_03.cj")
    @Test
    fun testSubtype03() {
        runTest("cfir/analysis-tests/testData/llt/type/subtype_03.cj")
    }

    @TestMetadata("unit.cj")
    @Test
    fun testUnit() {
        runTest("cfir/analysis-tests/testData/llt/type/unit.cj")
    }

    @TestMetadata("unit2.cj")
    @Test
    fun testUnit2() {
        runTest("cfir/analysis-tests/testData/llt/type/unit2.cj")
    }
}

