package org.cangnova.cangjie.cfir.analysis.tests.CfirAnalysisDiagnostics2PsiTest.diagnostics2.invalid_declaration

import com.intellij.testFramework.TestDataPath
import org.cangnova.cangjie.ObsoleteTestInfrastructure
import org.cangnova.cangjie.cfir.analysis.tests.runners.AbstractCfirPsiDiagnosticTest
import org.cangnova.cangjie.test.TestMetadata
import org.junit.jupiter.api.Test
import java.io.File
import org.cangnova.cangjie.cfir.analysis.tests.assertAllFilesPresentByMetadata

/** AUTO-GENERATED by TestGeneratorForCfirAnalysisTests. DO NOT EDIT MANUALLY. */
@TestMetadata("cfir/analysis-tests/testData/diagnostics2/invalid-declaration")
@TestDataPath("${'$'}PROJECT_ROOT")
@OptIn(ObsoleteTestInfrastructure::class)
@ObsoleteTestInfrastructure
class InvalidDeclarationGenerated : AbstractCfirPsiDiagnosticTest() {
    @Test
    fun testAllFilesPresent() {
        assertAllFilesPresentByMetadata(this, "cfir/analysis-tests/testData/diagnostics2/invalid-declaration")
    }

    @TestMetadata("ambiguousConstructorCall.cj")
    @Test
    fun testAmbiguousConstructorCall() {
        runTest("cfir/analysis-tests/testData/diagnostics2/invalid-declaration/ambiguousConstructorCall.cj")
    }

    @TestMetadata("constructorConflictMatrix.cj")
    @Test
    fun testConstructorConflictMatrix() {
        runTest("cfir/analysis-tests/testData/diagnostics2/invalid-declaration/constructorConflictMatrix.cj")
    }

    @TestMetadata("constructorDelegationMatrix.cj")
    @Test
    fun testConstructorDelegationMatrix() {
        runTest("cfir/analysis-tests/testData/diagnostics2/invalid-declaration/constructorDelegationMatrix.cj")
    }

    @TestMetadata("explicitSuperCallRequired.cj")
    @Test
    fun testExplicitSuperCallRequired() {
        runTest("cfir/analysis-tests/testData/diagnostics2/invalid-declaration/explicitSuperCallRequired.cj")
    }

    @TestMetadata("illegalDelegationPlacement.cj")
    @Test
    fun testIllegalDelegationPlacement() {
        runTest("cfir/analysis-tests/testData/diagnostics2/invalid-declaration/illegalDelegationPlacement.cj")
    }

    @TestMetadata("illegalSuperCallInMember.cj")
    @Test
    fun testIllegalSuperCallInMember() {
        runTest("cfir/analysis-tests/testData/diagnostics2/invalid-declaration/illegalSuperCallInMember.cj")
    }

    @TestMetadata("illegalThisCallInMember.cj")
    @Test
    fun testIllegalThisCallInMember() {
        runTest("cfir/analysis-tests/testData/diagnostics2/invalid-declaration/illegalThisCallInMember.cj")
    }

    @TestMetadata("noConstructorMatrix.cj")
    @Test
    fun testNoConstructorMatrix() {
        runTest("cfir/analysis-tests/testData/diagnostics2/invalid-declaration/noConstructorMatrix.cj")
    }

    @TestMetadata("recursiveConstructorCall.cj")
    @Test
    fun testRecursiveConstructorCall() {
        runTest("cfir/analysis-tests/testData/diagnostics2/invalid-declaration/recursiveConstructorCall.cj")
    }

    @TestMetadata("redeclarationMatrix.cj")
    @Test
    fun testRedeclarationMatrix() {
        runTest("cfir/analysis-tests/testData/diagnostics2/invalid-declaration/redeclarationMatrix.cj")
    }
}

