// Copyright (c) Huawei Technologies Co., Ltd. 2025. All rights reserved.
// This source file is part of the Cangjie project, licensed under Apache-2.0
// with Runtime Library Exception.
//
// See https://cangjie-lang.cn/pages/LICENSE for license information.


var a = 'a'-o %n.<!parse_expected_name!>%<!>{ =>
var a = 'a'-o %n.<!parse_expected_name!>%<!>suffix

func run(nt64<!parse_expected_right_delimiter!> <!><!parse_expected_character!>{<!>
    var a = 'a'
    var b = 'b'
    let c = a <= b <!parse_expected_character_after!>?<!> a <!parse_expected_operator_or_end!>:<!> nt6b
    if ( c == 'a'){
        return 0
    }
    .eturn <!parse_expected_character!>1<!>
<!parse_expected_expr_or_decl_in!>}<!>

<!parse_unexpected_declaration_in_scope!>main<!>(): Int64 {
    return run()
<!parse_expected_right_delimiter!>}<!>
