package org.cangnova.cangjie.cfir.analysis.tests.CfirAnalysisLLTTest.llt.if_let_expr

import com.intellij.testFramework.TestDataPath
import org.cangnova.cangjie.ObsoleteTestInfrastructure
import org.cangnova.cangjie.cfir.analysis.tests.runners.AbstractCfirLightTreeLlTDiagnosticsTest
import org.cangnova.cangjie.test.TestMetadata
import org.junit.jupiter.api.Test
import java.io.File
import org.cangnova.cangjie.cfir.analysis.tests.assertAllFilesPresentByMetadata

/** AUTO-GENERATED by TestGeneratorForCfirAnalysisTests. DO NOT EDIT MANUALLY. */
@TestMetadata("cfir/analysis-tests/testData/llt/if-let-expr")
@TestDataPath("${'$'}PROJECT_ROOT")
@OptIn(ObsoleteTestInfrastructure::class)
@ObsoleteTestInfrastructure
class IfLetExprGenerated : AbstractCfirLightTreeLlTDiagnosticsTest() {
    @Test
    fun testAllFilesPresent() {
        assertAllFilesPresentByMetadata(this, "cfir/analysis-tests/testData/llt/if-let-expr")
    }

    @TestMetadata("bugfix1.cj")
    @Test
    fun testBugfix1() {
        runTest("cfir/analysis-tests/testData/llt/if-let-expr/bugfix1.cj")
    }

    @TestMetadata("bugfix2.cj")
    @Test
    fun testBugfix2() {
        runTest("cfir/analysis-tests/testData/llt/if-let-expr/bugfix2.cj")
    }

    @TestMetadata("bugfix3.cj")
    @Test
    fun testBugfix3() {
        runTest("cfir/analysis-tests/testData/llt/if-let-expr/bugfix3.cj")
    }

    @TestMetadata("bugfix4.cj")
    @Test
    fun testBugfix4() {
        runTest("cfir/analysis-tests/testData/llt/if-let-expr/bugfix4.cj")
    }

    @TestMetadata("iflet1.cj")
    @Test
    fun testIflet1() {
        runTest("cfir/analysis-tests/testData/llt/if-let-expr/iflet1.cj")
    }

    @TestMetadata("iflet2.cj")
    @Test
    fun testIflet2() {
        runTest("cfir/analysis-tests/testData/llt/if-let-expr/iflet2.cj")
    }

    @TestMetadata("iflet3.cj")
    @Test
    fun testIflet3() {
        runTest("cfir/analysis-tests/testData/llt/if-let-expr/iflet3.cj")
    }

    @TestMetadata("iflet4.cj")
    @Test
    fun testIflet4() {
        runTest("cfir/analysis-tests/testData/llt/if-let-expr/iflet4.cj")
    }

    @TestMetadata("iflet_enum.cj")
    @Test
    fun testIfletEnum() {
        runTest("cfir/analysis-tests/testData/llt/if-let-expr/iflet_enum.cj")
    }

    @TestMetadata("iflet_enum_02.cj")
    @Test
    fun testIfletEnum02() {
        runTest("cfir/analysis-tests/testData/llt/if-let-expr/iflet_enum_02.cj")
    }

    @TestMetadata("iflet_rebind.cj")
    @Test
    fun testIfletRebind() {
        runTest("cfir/analysis-tests/testData/llt/if-let-expr/iflet_rebind.cj")
    }

    @TestMetadata("iflet_unit.cj")
    @Test
    fun testIfletUnit() {
        runTest("cfir/analysis-tests/testData/llt/if-let-expr/iflet_unit.cj")
    }

    @TestMetadata("ok_scope_00.cj")
    @Test
    fun testOkScope00() {
        runTest("cfir/analysis-tests/testData/llt/if-let-expr/ok_scope_00.cj")
    }

    @TestMetadata("scope.cj")
    @Test
    fun testScope() {
        runTest("cfir/analysis-tests/testData/llt/if-let-expr/scope.cj")
    }
}

