// Copyright (c) Huawei Technologies Co., Ltd. 2025. All rights reserved.
// This source file is part of the Cangjie project, licensed under Apache-2.0
// with Runtime Library Exception.
//
// See https://cangjie-lang.cn/pages/LICENSE for license information.


<!VALUE_TYPE_RECURSIVE!>p<!>ublic struct Record10 {
    public let var69: (Record10, Rune) = (<!RECURSIVE_CONSTRUCTOR_CALL!>Record10<!>(), r'd');
}

main(): Int64 {
    return 0;
}
