package org.cangnova.cangjie.cfir.analysis.tests.CfirAnalysisLLTPsiTest.llt.concurrency

import com.intellij.testFramework.TestDataPath
import org.cangnova.cangjie.ObsoleteTestInfrastructure
import org.cangnova.cangjie.cfir.analysis.tests.runners.AbstractCfirPsiLlTDiagnosticsTest
import org.cangnova.cangjie.test.TestMetadata
import org.junit.jupiter.api.Test
import java.io.File
import org.cangnova.cangjie.cfir.analysis.tests.assertAllFilesPresentByMetadata

/** AUTO-GENERATED by TestGeneratorForCfirAnalysisTests. DO NOT EDIT MANUALLY. */
@TestMetadata("cfir/analysis-tests/testData/llt/concurrency")
@TestDataPath("${'$'}PROJECT_ROOT")
@OptIn(ObsoleteTestInfrastructure::class)
@ObsoleteTestInfrastructure
class ConcurrencyGenerated : AbstractCfirPsiLlTDiagnosticsTest() {
    @Test
    fun testAllFilesPresent() {
        assertAllFilesPresentByMetadata(this, "cfir/analysis-tests/testData/llt/concurrency")
    }

    @TestMetadata("spawn1.cj")
    @Test
    fun testSpawn1() {
        runTest("cfir/analysis-tests/testData/llt/concurrency/spawn1.cj")
    }

    @TestMetadata("spawn10.cj")
    @Test
    fun testSpawn10() {
        runTest("cfir/analysis-tests/testData/llt/concurrency/spawn10.cj")
    }

    @TestMetadata("spawn2.cj")
    @Test
    fun testSpawn2() {
        runTest("cfir/analysis-tests/testData/llt/concurrency/spawn2.cj")
    }

    @TestMetadata("spawn3.cj")
    @Test
    fun testSpawn3() {
        runTest("cfir/analysis-tests/testData/llt/concurrency/spawn3.cj")
    }

    @TestMetadata("spawn4.cj")
    @Test
    fun testSpawn4() {
        runTest("cfir/analysis-tests/testData/llt/concurrency/spawn4.cj")
    }

    @TestMetadata("spawn5.cj")
    @Test
    fun testSpawn5() {
        runTest("cfir/analysis-tests/testData/llt/concurrency/spawn5.cj")
    }

    @TestMetadata("spawn6.cj")
    @Test
    fun testSpawn6() {
        runTest("cfir/analysis-tests/testData/llt/concurrency/spawn6.cj")
    }

    @TestMetadata("spawn8.cj")
    @Test
    fun testSpawn8() {
        runTest("cfir/analysis-tests/testData/llt/concurrency/spawn8.cj")
    }

    @TestMetadata("spawn9.cj")
    @Test
    fun testSpawn9() {
        runTest("cfir/analysis-tests/testData/llt/concurrency/spawn9.cj")
    }
}

