package org.cangnova.cangjie.cfir.analysis.tests.CfirAnalysisLLTTest.llt.generics.pkgs006.pkgs006001a

import com.intellij.testFramework.TestDataPath
import org.cangnova.cangjie.ObsoleteTestInfrastructure
import org.cangnova.cangjie.cfir.analysis.tests.runners.AbstractCfirLightTreeLlTDiagnosticsTest
import org.cangnova.cangjie.test.TestMetadata
import org.junit.jupiter.api.Test
import java.io.File
import org.cangnova.cangjie.cfir.analysis.tests.assertAllFilesPresentByMetadata

/** AUTO-GENERATED by TestGeneratorForCfirAnalysisTests. DO NOT EDIT MANUALLY. */
@TestMetadata("cfir/analysis-tests/testData/llt/generics/pkgs006/pkgs006001a")
@TestDataPath("${'$'}PROJECT_ROOT")
@OptIn(ObsoleteTestInfrastructure::class)
@ObsoleteTestInfrastructure
class Pkgs006001aGenerated : AbstractCfirLightTreeLlTDiagnosticsTest() {
    @Test
    fun testAllFilesPresent() {
        assertAllFilesPresentByMetadata(this, "cfir/analysis-tests/testData/llt/generics/pkgs006/pkgs006001a")
    }

    @TestMetadata("pkgs006001a.cj")
    @Test
    fun testPkgs006001a() {
        runTest("cfir/analysis-tests/testData/llt/generics/pkgs006/pkgs006001a/pkgs006001a.cj")
    }

    @TestMetadata("pkgs006002a.cj")
    @Test
    fun testPkgs006002a() {
        runTest("cfir/analysis-tests/testData/llt/generics/pkgs006/pkgs006001a/pkgs006002a.cj")
    }
}

