package org.cangnova.cangjie.cfir.analysis.tests.CfirAnalysisLLTTest.llt._class.import_static_function.no_generic_class

import com.intellij.testFramework.TestDataPath
import org.cangnova.cangjie.ObsoleteTestInfrastructure
import org.cangnova.cangjie.cfir.analysis.tests.runners.AbstractCfirLightTreeLlTDiagnosticsTest
import org.cangnova.cangjie.test.TestMetadata
import org.junit.jupiter.api.Test
import java.io.File
import org.cangnova.cangjie.cfir.analysis.tests.assertAllFilesPresentByMetadata

/** AUTO-GENERATED by TestGeneratorForCfirAnalysisTests. DO NOT EDIT MANUALLY. */
@TestMetadata("cfir/analysis-tests/testData/llt/class/import_static_function/no_generic_class")
@TestDataPath("${'$'}PROJECT_ROOT")
@OptIn(ObsoleteTestInfrastructure::class)
@ObsoleteTestInfrastructure
class NoGenericClassGenerated : AbstractCfirLightTreeLlTDiagnosticsTest() {
    @Test
    fun testAllFilesPresent() {
        assertAllFilesPresentByMetadata(this, "cfir/analysis-tests/testData/llt/class/import_static_function/no_generic_class")
    }

    @TestMetadata("main.cj")
    @Test
    fun testMain() {
        runTest("cfir/analysis-tests/testData/llt/class/import_static_function/no_generic_class/main.cj")
    }
}

