package org.cangnova.cangjie.cfir.analysis.tests.CfirAnalysisLLTTest.llt.toplevel

import com.intellij.testFramework.TestDataPath
import org.cangnova.cangjie.ObsoleteTestInfrastructure
import org.cangnova.cangjie.cfir.analysis.tests.runners.AbstractCfirLightTreeLlTDiagnosticsTest
import org.cangnova.cangjie.test.TestMetadata
import org.junit.jupiter.api.Test
import java.io.File
import org.cangnova.cangjie.cfir.analysis.tests.assertAllFilesPresentByMetadata

/** AUTO-GENERATED by TestGeneratorForCfirAnalysisTests. DO NOT EDIT MANUALLY. */
@TestMetadata("cfir/analysis-tests/testData/llt/toplevel")
@TestDataPath("${'$'}PROJECT_ROOT")
@OptIn(ObsoleteTestInfrastructure::class)
@ObsoleteTestInfrastructure
class ToplevelGenerated : AbstractCfirLightTreeLlTDiagnosticsTest() {
    @Test
    fun testAllFilesPresent() {
        assertAllFilesPresentByMetadata(this, "cfir/analysis-tests/testData/llt/toplevel")
    }

    @TestMetadata("binaryexpr.cj")
    @Test
    fun testBinaryexpr() {
        runTest("cfir/analysis-tests/testData/llt/toplevel/binaryexpr.cj")
    }

    @TestMetadata("call1.cj")
    @Test
    fun testCall1() {
        runTest("cfir/analysis-tests/testData/llt/toplevel/call1.cj")
    }

    @TestMetadata("dowhile1.cj")
    @Test
    fun testDowhile1() {
        runTest("cfir/analysis-tests/testData/llt/toplevel/dowhile1.cj")
    }

    @TestMetadata("funcdecl1.cj")
    @Test
    fun testFuncdecl1() {
        runTest("cfir/analysis-tests/testData/llt/toplevel/funcdecl1.cj")
    }

    @TestMetadata("refexpr1.cj")
    @Test
    fun testRefexpr1() {
        runTest("cfir/analysis-tests/testData/llt/toplevel/refexpr1.cj")
    }

    @TestMetadata("vardecl1.cj")
    @Test
    fun testVardecl1() {
        runTest("cfir/analysis-tests/testData/llt/toplevel/vardecl1.cj")
    }

    @TestMetadata("while1.cj")
    @Test
    fun testWhile1() {
        runTest("cfir/analysis-tests/testData/llt/toplevel/while1.cj")
    }
}

