package org.cangnova.cangjie.cfir.analysis.tests.CfirAnalysisLLTTest.llt._class.constructor.primaryConstructor

import com.intellij.testFramework.TestDataPath
import org.cangnova.cangjie.ObsoleteTestInfrastructure
import org.cangnova.cangjie.cfir.analysis.tests.runners.AbstractCfirLightTreeLlTDiagnosticsTest
import org.cangnova.cangjie.test.TestMetadata
import org.junit.jupiter.api.Test
import java.io.File
import org.cangnova.cangjie.cfir.analysis.tests.assertAllFilesPresentByMetadata

/** AUTO-GENERATED by TestGeneratorForCfirAnalysisTests. DO NOT EDIT MANUALLY. */
@TestMetadata("cfir/analysis-tests/testData/llt/class/constructor/primaryConstructor")
@TestDataPath("${'$'}PROJECT_ROOT")
@OptIn(ObsoleteTestInfrastructure::class)
@ObsoleteTestInfrastructure
class PrimaryConstructorGenerated : AbstractCfirLightTreeLlTDiagnosticsTest() {
    @Test
    fun testAllFilesPresent() {
        assertAllFilesPresentByMetadata(this, "cfir/analysis-tests/testData/llt/class/constructor/primaryConstructor")
    }

    @TestMetadata("primaryConstructor1.cj")
    @Test
    fun testPrimaryConstructor1() {
        runTest("cfir/analysis-tests/testData/llt/class/constructor/primaryConstructor/primaryConstructor1.cj")
    }

    @TestMetadata("primaryConstructor10.cj")
    @Test
    fun testPrimaryConstructor10() {
        runTest("cfir/analysis-tests/testData/llt/class/constructor/primaryConstructor/primaryConstructor10.cj")
    }

    @TestMetadata("primaryConstructor11.cj")
    @Test
    fun testPrimaryConstructor11() {
        runTest("cfir/analysis-tests/testData/llt/class/constructor/primaryConstructor/primaryConstructor11.cj")
    }

    @TestMetadata("primaryConstructor2.cj")
    @Test
    fun testPrimaryConstructor2() {
        runTest("cfir/analysis-tests/testData/llt/class/constructor/primaryConstructor/primaryConstructor2.cj")
    }

    @TestMetadata("primaryConstructor3.cj")
    @Test
    fun testPrimaryConstructor3() {
        runTest("cfir/analysis-tests/testData/llt/class/constructor/primaryConstructor/primaryConstructor3.cj")
    }

    @TestMetadata("primaryConstructor4.cj")
    @Test
    fun testPrimaryConstructor4() {
        runTest("cfir/analysis-tests/testData/llt/class/constructor/primaryConstructor/primaryConstructor4.cj")
    }

    @TestMetadata("primaryConstructor6.cj")
    @Test
    fun testPrimaryConstructor6() {
        runTest("cfir/analysis-tests/testData/llt/class/constructor/primaryConstructor/primaryConstructor6.cj")
    }

    @TestMetadata("primaryConstructor7.cj")
    @Test
    fun testPrimaryConstructor7() {
        runTest("cfir/analysis-tests/testData/llt/class/constructor/primaryConstructor/primaryConstructor7.cj")
    }

    @TestMetadata("primaryConstructor8.cj")
    @Test
    fun testPrimaryConstructor8() {
        runTest("cfir/analysis-tests/testData/llt/class/constructor/primaryConstructor/primaryConstructor8.cj")
    }

    @TestMetadata("primaryConstructor9.cj")
    @Test
    fun testPrimaryConstructor9() {
        runTest("cfir/analysis-tests/testData/llt/class/constructor/primaryConstructor/primaryConstructor9.cj")
    }
}

