package org.cangnova.cangjie.cfir.analysis.tests.CfirAnalysisLLTTest.llt._if

import com.intellij.testFramework.TestDataPath
import org.cangnova.cangjie.ObsoleteTestInfrastructure
import org.cangnova.cangjie.cfir.analysis.tests.runners.AbstractCfirLightTreeLlTDiagnosticsTest
import org.cangnova.cangjie.test.TestMetadata
import org.junit.jupiter.api.Test
import java.io.File
import org.cangnova.cangjie.cfir.analysis.tests.assertAllFilesPresentByMetadata

/** AUTO-GENERATED by TestGeneratorForCfirAnalysisTests. DO NOT EDIT MANUALLY. */
@TestMetadata("cfir/analysis-tests/testData/llt/if")
@TestDataPath("${'$'}PROJECT_ROOT")
@OptIn(ObsoleteTestInfrastructure::class)
@ObsoleteTestInfrastructure
class IfGenerated : AbstractCfirLightTreeLlTDiagnosticsTest() {
    @Test
    fun testAllFilesPresent() {
        assertAllFilesPresentByMetadata(this, "cfir/analysis-tests/testData/llt/if")
    }

    @TestMetadata("err_if_undeclared.cj")
    @Test
    fun testErrIfUndeclared() {
        runTest("cfir/analysis-tests/testData/llt/if/err_if_undeclared.cj")
    }

    @TestMetadata("err_scope_00.cj")
    @Test
    fun testErrScope00() {
        runTest("cfir/analysis-tests/testData/llt/if/err_scope_00.cj")
    }

    @TestMetadata("if1.cj")
    @Test
    fun testIf1() {
        runTest("cfir/analysis-tests/testData/llt/if/if1.cj")
    }

    @TestMetadata("if12.cj")
    @Test
    fun testIf12() {
        runTest("cfir/analysis-tests/testData/llt/if/if12.cj")
    }

    @TestMetadata("if13.cj")
    @Test
    fun testIf13() {
        runTest("cfir/analysis-tests/testData/llt/if/if13.cj")
    }

    @TestMetadata("if14.cj")
    @Test
    fun testIf14() {
        runTest("cfir/analysis-tests/testData/llt/if/if14.cj")
    }

    @TestMetadata("if15.cj")
    @Test
    fun testIf15() {
        runTest("cfir/analysis-tests/testData/llt/if/if15.cj")
    }

    @TestMetadata("if16.cj")
    @Test
    fun testIf16() {
        runTest("cfir/analysis-tests/testData/llt/if/if16.cj")
    }

    @TestMetadata("if17.cj")
    @Test
    fun testIf17() {
        runTest("cfir/analysis-tests/testData/llt/if/if17.cj")
    }

    @TestMetadata("if3.cj")
    @Test
    fun testIf3() {
        runTest("cfir/analysis-tests/testData/llt/if/if3.cj")
    }

    @TestMetadata("if4.cj")
    @Test
    fun testIf4() {
        runTest("cfir/analysis-tests/testData/llt/if/if4.cj")
    }

    @TestMetadata("if5.cj")
    @Test
    fun testIf5() {
        runTest("cfir/analysis-tests/testData/llt/if/if5.cj")
    }

    @TestMetadata("if6.cj")
    @Test
    fun testIf6() {
        runTest("cfir/analysis-tests/testData/llt/if/if6.cj")
    }

    @TestMetadata("if7.cj")
    @Test
    fun testIf7() {
        runTest("cfir/analysis-tests/testData/llt/if/if7.cj")
    }

    @TestMetadata("if8.cj")
    @Test
    fun testIf8() {
        runTest("cfir/analysis-tests/testData/llt/if/if8.cj")
    }

    @TestMetadata("if9.cj")
    @Test
    fun testIf9() {
        runTest("cfir/analysis-tests/testData/llt/if/if9.cj")
    }

    @TestMetadata("if_check_type.cj")
    @Test
    fun testIfCheckType() {
        runTest("cfir/analysis-tests/testData/llt/if/if_check_type.cj")
    }

    @TestMetadata("if_check_type2.cj")
    @Test
    fun testIfCheckType2() {
        runTest("cfir/analysis-tests/testData/llt/if/if_check_type2.cj")
    }

    @TestMetadata("if_check_type3.cj")
    @Test
    fun testIfCheckType3() {
        runTest("cfir/analysis-tests/testData/llt/if/if_check_type3.cj")
    }

    @TestMetadata("if_check_type4.cj")
    @Test
    fun testIfCheckType4() {
        runTest("cfir/analysis-tests/testData/llt/if/if_check_type4.cj")
    }

    @TestMetadata("if_check_type5.cj")
    @Test
    fun testIfCheckType5() {
        runTest("cfir/analysis-tests/testData/llt/if/if_check_type5.cj")
    }

    @TestMetadata("if_check_type6.cj")
    @Test
    fun testIfCheckType6() {
        runTest("cfir/analysis-tests/testData/llt/if/if_check_type6.cj")
    }

    @TestMetadata("if_check_type7.cj")
    @Test
    fun testIfCheckType7() {
        runTest("cfir/analysis-tests/testData/llt/if/if_check_type7.cj")
    }

    @TestMetadata("if_check_type8.cj")
    @Test
    fun testIfCheckType8() {
        runTest("cfir/analysis-tests/testData/llt/if/if_check_type8.cj")
    }

    @TestMetadata("target_typed_tail_contexts.cj")
    @Test
    fun testTargetTypedTailContexts() {
        runTest("cfir/analysis-tests/testData/llt/if/target_typed_tail_contexts.cj")
    }
}

