package org.cangnova.cangjie.cfir.analysis.tests.CfirAnalysisLLTTest.llt.Extend.extend_export.direct_extend.extend_generic01

import com.intellij.testFramework.TestDataPath
import org.cangnova.cangjie.ObsoleteTestInfrastructure
import org.cangnova.cangjie.cfir.analysis.tests.runners.AbstractCfirLightTreeLlTDiagnosticsTest
import org.cangnova.cangjie.test.TestMetadata
import org.junit.jupiter.api.Test
import java.io.File
import org.cangnova.cangjie.cfir.analysis.tests.assertAllFilesPresentByMetadata

/** AUTO-GENERATED by TestGeneratorForCfirAnalysisTests. DO NOT EDIT MANUALLY. */
@TestMetadata("cfir/analysis-tests/testData/llt/Extend/extend_export/direct_extend/extend_generic01")
@TestDataPath("${'$'}PROJECT_ROOT")
@OptIn(ObsoleteTestInfrastructure::class)
@ObsoleteTestInfrastructure
class ExtendGeneric01Generated : AbstractCfirLightTreeLlTDiagnosticsTest() {
    @Test
    fun testAllFilesPresent() {
        assertAllFilesPresentByMetadata(this, "cfir/analysis-tests/testData/llt/Extend/extend_export/direct_extend/extend_generic01")
    }

    @TestMetadata("failed01.cj")
    @Test
    fun testFailed01() {
        runTest("cfir/analysis-tests/testData/llt/Extend/extend_export/direct_extend/extend_generic01/failed01.cj")
    }

    @TestMetadata("failed02.cj")
    @Test
    fun testFailed02() {
        runTest("cfir/analysis-tests/testData/llt/Extend/extend_export/direct_extend/extend_generic01/failed02.cj")
    }

    @TestMetadata("pass01.cj")
    @Test
    fun testPass01() {
        runTest("cfir/analysis-tests/testData/llt/Extend/extend_export/direct_extend/extend_generic01/pass01.cj")
    }

    @TestMetadata("pass02.cj")
    @Test
    fun testPass02() {
        runTest("cfir/analysis-tests/testData/llt/Extend/extend_export/direct_extend/extend_generic01/pass02.cj")
    }
}

