[versions]
intellijPlatform = "2.10.5"
kotlin = "2.2.20"
jackson = "2.15.2"
lsp4j = "0.21.0"
protobuf = "3.24.4"
vavr = "0.10.4"
jansi = "2.4.1"
toml4j = "0.7.3"
okio = "3.9.0"

[libraries]
jackson-dataformat-toml = { module = "com.fasterxml.jackson.dataformat:jackson-dataformat-toml", version.ref = "jackson" }
jackson-module-kotlin = { module = "com.fasterxml.jackson.module:jackson-module-kotlin", version.ref = "jackson" }
lsp4j-debug = { module = "org.eclipse.lsp4j:org.eclipse.lsp4j.debug", version.ref = "lsp4j" }
protobuf-java = { module = "com.google.protobuf:protobuf-java", version.ref = "protobuf" }
protobuf-kotlin = { module = "com.google.protobuf:protobuf-kotlin", version.ref = "protobuf" }
vavr = { module = "io.vavr:vavr", version.ref = "vavr" }
jansi = { module = "org.fusesource.jansi:jansi", version.ref = "jansi" }
toml4j = { module = "io.hotmoka:toml4j", version.ref = "toml4j" }
okio = { module = "com.squareup.okio:okio", version.ref = "okio" }

[plugins]
intellijPlatform = { id = "org.jetbrains.intellij.platform", version.ref = "intellijPlatform" }
kotlin = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }

[bundles]
jackson = ["jackson-dataformat-toml", "jackson-module-kotlin"]
protobuf = ["protobuf-java", "protobuf-kotlin"]
