package org.cangnova.cangjie.cfir.builder

import com.intellij.testFramework.TestDataPath
import org.cangnova.cangjie.ObsoleteTestInfrastructure
import org.cangnova.cangjie.test.TestMetadata
import org.cangnova.cangjie.test.JUnit3RunnerWithInners
import java.io.File
import org.junit.runner.RunWith

/** AUTO-GENERATED by TestGeneratorForPsi2Cfir. DO NOT EDIT MANUALLY. */
@TestMetadata("cfir/raw-cfir/psi2cfir/testData/sourceElementMapping")
@TestDataPath("\$PROJECT_ROOT")
@RunWith(JUnit3RunnerWithInners::class)
@OptIn(ObsoleteTestInfrastructure::class)
@ObsoleteTestInfrastructure
class RawCfirBuilderSourceElementMappingTestGenerated : AbstractRawCfirBuilderSourceElementMappingTestCase() {
    fun testSmoke() {
        // Container class for nested generated suites.
    }

    fun testAllFilesPresentInTestData() {
        assertAllFilesPresentByMetadata("cfir/raw-cfir/psi2cfir/testData/sourceElementMapping")
    }

    @TestMetadata("binaryExpr.cj")
    fun testBinaryExpr() {
        runTest("cfir/raw-cfir/psi2cfir/testData/sourceElementMapping/binaryExpr.cj")
    }

    @TestMetadata("callArgExpr.cj")
    fun testCallArgExpr() {
        runTest("cfir/raw-cfir/psi2cfir/testData/sourceElementMapping/callArgExpr.cj")
    }

    @TestMetadata("ifExpr.cj")
    fun testIfExpr() {
        runTest("cfir/raw-cfir/psi2cfir/testData/sourceElementMapping/ifExpr.cj")
    }

    @TestMetadata("indexExpr.cj")
    fun testIndexExpr() {
        runTest("cfir/raw-cfir/psi2cfir/testData/sourceElementMapping/indexExpr.cj")
    }

    @TestMetadata("lambdaExpr.cj")
    fun testLambdaExpr() {
        runTest("cfir/raw-cfir/psi2cfir/testData/sourceElementMapping/lambdaExpr.cj")
    }

    @TestMetadata("memberLikeAccessExpr.cj")
    fun testMemberLikeAccessExpr() {
        runTest("cfir/raw-cfir/psi2cfir/testData/sourceElementMapping/memberLikeAccessExpr.cj")
    }

    @TestMetadata("simpleExpr.cj")
    fun testSimpleExpr() {
        runTest("cfir/raw-cfir/psi2cfir/testData/sourceElementMapping/simpleExpr.cj")
    }

    @TestMetadata("stringTemplate.cj")
    fun testStringTemplate() {
        runTest("cfir/raw-cfir/psi2cfir/testData/sourceElementMapping/stringTemplate.cj")
    }

}
