package org.cangnova.cangjie.cfir.analysis.tests.CfirAnalysisLLTTest.llt.if_let_expr.enhancedcondition.patterns

import com.intellij.testFramework.TestDataPath
import org.cangnova.cangjie.ObsoleteTestInfrastructure
import org.cangnova.cangjie.cfir.analysis.tests.runners.AbstractCfirLightTreeLlTDiagnosticsTest
import org.cangnova.cangjie.test.TestMetadata
import org.junit.jupiter.api.Test
import java.io.File
import org.cangnova.cangjie.cfir.analysis.tests.assertAllFilesPresentByMetadata

/** AUTO-GENERATED by TestGeneratorForCfirAnalysisTests. DO NOT EDIT MANUALLY. */
@TestMetadata("cfir/analysis-tests/testData/llt/if-let-expr/enhancedcondition/patterns")
@TestDataPath("${'$'}PROJECT_ROOT")
@OptIn(ObsoleteTestInfrastructure::class)
@ObsoleteTestInfrastructure
class PatternsGenerated : AbstractCfirLightTreeLlTDiagnosticsTest() {
    @Test
    fun testAllFilesPresent() {
        assertAllFilesPresentByMetadata(this, "cfir/analysis-tests/testData/llt/if-let-expr/enhancedcondition/patterns")
    }

    @TestMetadata("and.cj")
    @Test
    fun testAnd() {
        runTest("cfir/analysis-tests/testData/llt/if-let-expr/enhancedcondition/patterns/and.cj")
    }

    @TestMetadata("and2.cj")
    @Test
    fun testAnd2() {
        runTest("cfir/analysis-tests/testData/llt/if-let-expr/enhancedcondition/patterns/and2.cj")
    }

    @TestMetadata("constpattern.cj")
    @Test
    fun testConstpattern() {
        runTest("cfir/analysis-tests/testData/llt/if-let-expr/enhancedcondition/patterns/constpattern.cj")
    }

    @TestMetadata("en.cj")
    @Test
    fun testEn() {
        runTest("cfir/analysis-tests/testData/llt/if-let-expr/enhancedcondition/patterns/en.cj")
    }

    @TestMetadata("enumorwildcard.cj")
    @Test
    fun testEnumorwildcard() {
        runTest("cfir/analysis-tests/testData/llt/if-let-expr/enhancedcondition/patterns/enumorwildcard.cj")
    }

    @TestMetadata("or.cj")
    @Test
    fun testOr() {
        runTest("cfir/analysis-tests/testData/llt/if-let-expr/enhancedcondition/patterns/or.cj")
    }

    @TestMetadata("paren.cj")
    @Test
    fun testParen() {
        runTest("cfir/analysis-tests/testData/llt/if-let-expr/enhancedcondition/patterns/paren.cj")
    }

    @TestMetadata("tuple.cj")
    @Test
    fun testTuple() {
        runTest("cfir/analysis-tests/testData/llt/if-let-expr/enhancedcondition/patterns/tuple.cj")
    }
}

