package org.cangnova.cangjie.cfir.analysis.tests.CfirAnalysisLLTPsiTest.llt.if_let_expr.enhancedcondition.parse

import com.intellij.testFramework.TestDataPath
import org.cangnova.cangjie.ObsoleteTestInfrastructure
import org.cangnova.cangjie.cfir.analysis.tests.runners.AbstractCfirPsiLlTDiagnosticsTest
import org.cangnova.cangjie.test.TestMetadata
import org.junit.jupiter.api.Test
import java.io.File
import org.cangnova.cangjie.cfir.analysis.tests.assertAllFilesPresentByMetadata

/** AUTO-GENERATED by TestGeneratorForCfirAnalysisTests. DO NOT EDIT MANUALLY. */
@TestMetadata("cfir/analysis-tests/testData/llt/if-let-expr/enhancedcondition/parse")
@TestDataPath("${'$'}PROJECT_ROOT")
@OptIn(ObsoleteTestInfrastructure::class)
@ObsoleteTestInfrastructure
class ParseGenerated : AbstractCfirPsiLlTDiagnosticsTest() {
    @Test
    fun testAllFilesPresent() {
        assertAllFilesPresentByMetadata(this, "cfir/analysis-tests/testData/llt/if-let-expr/enhancedcondition/parse")
    }

    @TestMetadata("missing_rparen.cj")
    @Test
    fun testMissingRparen() {
        runTest("cfir/analysis-tests/testData/llt/if-let-expr/enhancedcondition/parse/missing_rparen.cj")
    }

    @TestMetadata("or_and_var.cj")
    @Test
    fun testOrAndVar() {
        runTest("cfir/analysis-tests/testData/llt/if-let-expr/enhancedcondition/parse/or_and_var.cj")
    }
}

