package org.cangjie.cfir.builder

import java.io.File

/**
 * 生成 RawCfirBuilderTestCaseGenerated（对齐 Kotlin TestGeneratorForPsi2Fir 风格）。
 */
object TestGeneratorForPsi2Cfir {
    @JvmStatic
    fun main(args: Array<String>) {
        val projectRoot = if (args.isNotEmpty()) File(args[0]) else File(System.getProperty("user.dir"))
        generateSuite(
            projectRoot = projectRoot,
            modelRelativePath = "cfir/raw-cfir/psi2cfir/testData/rawBuilder",
            generatedClassName = "RawCfirBuilderTestCaseGenerated",
            baseClassName = "AbstractRawCfirBuilderTestCase",
        )

        generateSuite(
            projectRoot = projectRoot,
            modelRelativePath = "cfir/raw-cfir/psi2cfir/testData/rawBuilder",
            generatedClassName = "RawCfirBuilderLazyBodiesByAstTestGenerated",
            baseClassName = "AbstractRawCfirBuilderLazyBodiesByAstTest",
        )

        generateSuite(
            projectRoot = projectRoot,
            modelRelativePath = "cfir/raw-cfir/psi2cfir/testData/rawBuilder",
            generatedClassName = "RawCfirBuilderLazyBodiesByStubTestGenerated",
            baseClassName = "AbstractRawCfirBuilderLazyBodiesByStubTest",
        )

        generateSuite(
            projectRoot = projectRoot,
            modelRelativePath = "cfir/raw-cfir/psi2cfir/testData/sourceElementMapping",
            generatedClassName = "RawCfirBuilderSourceElementMappingTestGenerated",
            baseClassName = "AbstractRawCfirBuilderSourceElementMappingTestCase",
        )
    }

    private fun generateSuite(
        projectRoot: File,
        modelRelativePath: String,
        generatedClassName: String,
        baseClassName: String,
    ) {
        val testDataRoot = projectRoot.resolve(modelRelativePath)
        require(testDataRoot.exists()) { "testData root not found: ${testDataRoot.path}" }

        val outputFile = projectRoot.resolve(
            "cfir/raw-cfir/psi2cfir/tests-gen/org/cangjie/cfir/builder/$generatedClassName.kt"
        )
        outputFile.parentFile.mkdirs()
        outputFile.writeText(render(testDataRoot, projectRoot, generatedClassName, baseClassName), Charsets.UTF_8)
        println("Generated: ${outputFile.path}")
    }

    private fun render(
        testDataRoot: File,
        projectRoot: File,
        generatedClassName: String,
        baseClassName: String,
    ): String {
        val sb = StringBuilder()
        sb.appendLine("package org.cangjie.cfir.builder")
        sb.appendLine()
        sb.appendLine("import com.intellij.testFramework.TestDataPath")
        sb.appendLine("import org.cangjie.ObsoleteTestInfrastructure")
        sb.appendLine("import org.cangjie.test.TestMetadata")
        sb.appendLine("import org.cangjie.test.JUnit3RunnerWithInners")
        sb.appendLine("import java.io.File")
        sb.appendLine("import org.junit.runner.RunWith")
        sb.appendLine()
        sb.appendLine("/** AUTO-GENERATED by TestGeneratorForPsi2Cfir. DO NOT EDIT MANUALLY. */")
        val rootRel = projectRoot.toPath().relativize(testDataRoot.toPath()).toString().replace('\\', '/')
        sb.appendLine("@TestMetadata(\"$rootRel\")")
        sb.appendLine("@TestDataPath(\"\\\$PROJECT_ROOT\")")
        sb.appendLine("@RunWith(JUnit3RunnerWithInners::class)")
        sb.appendLine("@OptIn(ObsoleteTestInfrastructure::class)")
        sb.appendLine("@ObsoleteTestInfrastructure")
        sb.appendLine("class $generatedClassName : $baseClassName() {")
        sb.appendLine("    fun testSmoke() {")
        sb.appendLine("        // Container class for nested generated suites.")
        sb.appendLine("    }")
        sb.appendLine()
        sb.appendLine("    fun testAllFilesPresentInTestData() {")
        sb.appendLine("        assertAllFilesPresentByMetadata(\"$rootRel\")")
        sb.appendLine("    }")
        sb.appendLine()

        val children = testDataRoot.listFiles().orEmpty().sortedBy { it.name }
        children.filter { it.isDirectory }.forEach { dir ->
            renderDirectoryClass(sb, dir, projectRoot, baseClassName, 1)
        }

        val filesInRoot = testDataRoot.listFiles().orEmpty().filter { it.isFile && it.extension == "cj" }.sortedBy { it.name }
        filesInRoot.forEach { file ->
            val testName = toTestMethodName(file.nameWithoutExtension)
            val rel = projectRoot.toPath().relativize(file.toPath()).toString().replace('\\', '/')
            sb.appendLine("    @TestMetadata(\"${file.name}\")")
            sb.appendLine("    fun $testName() {")
            sb.appendLine("        runTest(\"$rel\")")
            sb.appendLine("    }")
            sb.appendLine()
        }

        sb.appendLine("}")
        return sb.toString()
    }

    private fun renderDirectoryClass(
        sb: StringBuilder,
        dir: File,
        projectRoot: File,
        baseClassName: String,
        level: Int,
    ) {
        val indent = "    ".repeat(level)
        val className = toClassName(dir.name)
        val relDir = projectRoot.toPath().relativize(dir.toPath()).toString().replace('\\', '/')

        sb.appendLine("${indent}@TestMetadata(\"$relDir\")")
        sb.appendLine("${indent}@TestDataPath(\"\\\$PROJECT_ROOT\")")
        sb.appendLine("${indent}@RunWith(JUnit3RunnerWithInners::class)")
        sb.appendLine("${indent}class $className : $baseClassName() {")
        sb.appendLine("${indent}    fun testAllFilesPresentIn${className}() {")
        sb.appendLine("${indent}        assertAllFilesPresentByMetadata(\"$relDir\")")
        sb.appendLine("${indent}    }")
        sb.appendLine()

        val files = dir.listFiles().orEmpty().filter { it.isFile && it.extension == "cj" }.sortedBy { it.name }
        files.forEach { file ->
            val testName = toTestMethodName(file.nameWithoutExtension)
            val rel = projectRoot.toPath().relativize(file.toPath()).toString().replace('\\', '/')
            sb.appendLine("${indent}    @TestMetadata(\"${file.name}\")")
            sb.appendLine("${indent}    fun $testName() {")
            sb.appendLine("${indent}        runTest(\"$rel\")")
            sb.appendLine("${indent}    }")
            sb.appendLine()
        }

        val subdirs = dir.listFiles().orEmpty().filter { it.isDirectory }.sortedBy { it.name }
        subdirs.forEach { child ->
            renderDirectoryClass(sb, child, projectRoot, baseClassName, level + 1)
        }

        sb.appendLine("${indent}}")
        sb.appendLine()
    }

    private fun toClassName(name: String): String {
        return name
            .split(Regex("[^A-Za-z0-9]+"))
            .filter { it.isNotBlank() }
            .joinToString("") { it.replaceFirstChar { ch -> ch.uppercaseChar() } }
    }

    private fun toTestMethodName(base: String): String {
        val raw = toClassName(base)
        return "test$raw"
    }

}
