// Copyright (c) Huawei Technologies Co., Ltd. 2025. All rights reserved.
// This source file is part of the Cangjie project, licensed under Apache-2.0
// with Runtime Library Exception.
//
// See https://cangjie-lang.cn/pages/LICENSE for license information.


class Data
    public var a : Int32  = 100
    public var b :)Float32
    public init()  {
        b = 3<!lex_unknown_suffix!>var<!> a : Int32  c run(): Int64 {
    var value : Data = Data();
    if ((value.a == 100) && (value.b == 3.0)) {        return 0
    }
    else {
        return 1
    }
}

main(): Int64 {
    return run()
}
