


// API_LEVEL: 11

import std.argopt.*
import std.ast.*
import std.binary.*
import std.collection.*
import std.collection.concurrent.*
import std.console.*
import std.convert.*
import std.core.*
import std.crypto.cipher.*
import std.crypto.digest.*
import std.database.sql.*
import std.deriving.*
import std.env.*
import std.fs.*
import std.io.*
import std.math.*
import std.math.numeric.*
import std.net.*
import std.objectpool.*
import std.overflow.*
import std.posix.*
import std.process.*
import std.random.*
import std.ref.*
import std.reflect.*
import std.regex.*
import std.runtime.*
import std.sort.*
import std.sync.*
import std.time.*
import std.unicode.*
import std.unittest.*
import std.unittest.common.*
import std.unittest.diff.*
import std.unittest.mock.*
import std.unittest.mock.mockmacro.*
import std.unittest.prop_test.*
import std.unittest.testmacro.*

main() {
    <!APILEVEL_REF_HIGHER!>ArgOpt()<!>
    0
}
