


// API_LEVEL: 11

import std.argopt.*
import <!UNUSED_IMPORT!>std.ast.*<!>
import <!UNUSED_IMPORT!>std.binary.*<!>
import <!UNUSED_IMPORT!>std.collection.*<!>
import <!UNUSED_IMPORT!>std.collection.concurrent.*<!>
import <!UNUSED_IMPORT!>std.console.*<!>
import <!UNUSED_IMPORT!>std.convert.*<!>
import <!UNUSED_IMPORT!>std.core.*<!>
import <!UNUSED_IMPORT!>std.crypto.cipher.*<!>
import <!UNUSED_IMPORT!>std.crypto.digest.*<!>
import <!UNUSED_IMPORT!>std.database.sql.*<!>
import <!UNUSED_IMPORT!>std.deriving.*<!>
import <!UNUSED_IMPORT!>std.env.*<!>
import <!UNUSED_IMPORT!>std.fs.*<!>
import <!UNUSED_IMPORT!>std.io.*<!>
import <!UNUSED_IMPORT!>std.math.*<!>
import <!UNUSED_IMPORT!>std.math.numeric.*<!>
import <!UNUSED_IMPORT!>std.net.*<!>
import <!UNUSED_IMPORT!>std.objectpool.*<!>
import <!UNUSED_IMPORT!>std.overflow.*<!>
import <!UNUSED_IMPORT!>std.posix.*<!>
import <!UNUSED_IMPORT!>std.process.*<!>
import <!UNUSED_IMPORT!>std.random.*<!>
import <!UNUSED_IMPORT!>std.ref.*<!>
import <!UNUSED_IMPORT!>std.reflect.*<!>
import <!UNUSED_IMPORT!>std.regex.*<!>
import <!UNUSED_IMPORT!>std.runtime.*<!>
import <!UNUSED_IMPORT!>std.sort.*<!>
import <!UNUSED_IMPORT!>std.sync.*<!>
import <!UNUSED_IMPORT!>std.time.*<!>
import <!UNUSED_IMPORT!>std.unicode.*<!>
import <!UNUSED_IMPORT!>std.unittest.*<!>
import <!UNUSED_IMPORT!>std.unittest.common.*<!>
import <!UNUSED_IMPORT!>std.unittest.diff.*<!>
import <!UNUSED_IMPORT!>std.unittest.mock.*<!>
import <!UNUSED_IMPORT!>std.unittest.mock.mockmacro.*<!>
import <!UNUSED_IMPORT!>std.unittest.prop_test.*<!>
import <!UNUSED_IMPORT!>std.unittest.testmacro.*<!>

main() {
    <!APILEVEL_REF_HIGHER!><!DEPRECATED_WARNING!>ArgOpt<!>()<!>
    0
}
