package org.cangnova.cangjie.cfir.analysis.tests.CfirAnalysisDiagnosticsPsiTest.diagnostics.type_mismatch

import com.intellij.testFramework.TestDataPath
import org.cangnova.cangjie.ObsoleteTestInfrastructure
import org.cangnova.cangjie.cfir.analysis.tests.runners.AbstractCfirPsiDiagnosticTest
import org.cangnova.cangjie.test.TestMetadata
import org.junit.jupiter.api.Test
import java.io.File
import org.cangnova.cangjie.cfir.analysis.tests.assertAllFilesPresentByMetadata

/** AUTO-GENERATED by TestGeneratorForCfirAnalysisTests. DO NOT EDIT MANUALLY. */
@TestMetadata("cfir/analysis-tests/testData/diagnostics/type-mismatch")
@TestDataPath("${'$'}PROJECT_ROOT")
@OptIn(ObsoleteTestInfrastructure::class)
@ObsoleteTestInfrastructure
class TypeMismatchGenerated : AbstractCfirPsiDiagnosticTest() {
    @Test
    fun testAllFilesPresent() {
        assertAllFilesPresentByMetadata(this, "cfir/analysis-tests/testData/diagnostics/type-mismatch")
    }

    @TestMetadata("argumentTypeMismatch.cj")
    @Test
    fun testArgumentTypeMismatch() {
        runTest("cfir/analysis-tests/testData/diagnostics/type-mismatch/argumentTypeMismatch.cj")
    }

    @TestMetadata("assignmentTypeMismatch.cj")
    @Test
    fun testAssignmentTypeMismatch() {
        runTest("cfir/analysis-tests/testData/diagnostics/type-mismatch/assignmentTypeMismatch.cj")
    }

    @TestMetadata("conditionBoolOk.cj")
    @Test
    fun testConditionBoolOk() {
        runTest("cfir/analysis-tests/testData/diagnostics/type-mismatch/conditionBoolOk.cj")
    }

    @TestMetadata("conditionMustBeBool.cj")
    @Test
    fun testConditionMustBeBool() {
        runTest("cfir/analysis-tests/testData/diagnostics/type-mismatch/conditionMustBeBool.cj")
    }

    @TestMetadata("genericArgumentConstraintConflict.cj")
    @Test
    fun testGenericArgumentConstraintConflict() {
        runTest("cfir/analysis-tests/testData/diagnostics/type-mismatch/genericArgumentConstraintConflict.cj")
    }

    @TestMetadata("genericConstraintCascade.cj")
    @Test
    fun testGenericConstraintCascade() {
        runTest("cfir/analysis-tests/testData/diagnostics/type-mismatch/genericConstraintCascade.cj")
    }

    @TestMetadata("genericConstraintFromExpectedType.cj")
    @Test
    fun testGenericConstraintFromExpectedType() {
        runTest("cfir/analysis-tests/testData/diagnostics/type-mismatch/genericConstraintFromExpectedType.cj")
    }

    @TestMetadata("genericReturnTypeInference.cj")
    @Test
    fun testGenericReturnTypeInference() {
        runTest("cfir/analysis-tests/testData/diagnostics/type-mismatch/genericReturnTypeInference.cj")
    }

    @TestMetadata("ifBranchCommonType.cj")
    @Test
    fun testIfBranchCommonType() {
        runTest("cfir/analysis-tests/testData/diagnostics/type-mismatch/ifBranchCommonType.cj")
    }

    @TestMetadata("lambdaParameterInference.cj")
    @Test
    fun testLambdaParameterInference() {
        runTest("cfir/analysis-tests/testData/diagnostics/type-mismatch/lambdaParameterInference.cj")
    }

    @TestMetadata("lambdaReturnConstraintMismatch.cj")
    @Test
    fun testLambdaReturnConstraintMismatch() {
        runTest("cfir/analysis-tests/testData/diagnostics/type-mismatch/lambdaReturnConstraintMismatch.cj")
    }

    @TestMetadata("lambdaReturnConstraintMismatchAsArgumentFeature.cj")
    @Test
    fun testLambdaReturnConstraintMismatchAsArgumentFeature() {
        runTest("cfir/analysis-tests/testData/diagnostics/type-mismatch/lambdaReturnConstraintMismatchAsArgumentFeature.cj")
    }

    @TestMetadata("returnTypeMismatch.cj")
    @Test
    fun testReturnTypeMismatch() {
        runTest("cfir/analysis-tests/testData/diagnostics/type-mismatch/returnTypeMismatch.cj")
    }

    @TestMetadata("simple.cj")
    @Test
    fun testSimple() {
        runTest("cfir/analysis-tests/testData/diagnostics/type-mismatch/simple.cj")
    }

    @TestMetadata("whereMultipleUpperBounds.cj")
    @Test
    fun testWhereMultipleUpperBounds() {
        runTest("cfir/analysis-tests/testData/diagnostics/type-mismatch/whereMultipleUpperBounds.cj")
    }

    @TestMetadata("whereUpperBoundMemberAccess.cj")
    @Test
    fun testWhereUpperBoundMemberAccess() {
        runTest("cfir/analysis-tests/testData/diagnostics/type-mismatch/whereUpperBoundMemberAccess.cj")
    }

    @TestMetadata("whereUpperLowerConstraintFlow.cj")
    @Test
    fun testWhereUpperLowerConstraintFlow() {
        runTest("cfir/analysis-tests/testData/diagnostics/type-mismatch/whereUpperLowerConstraintFlow.cj")
    }
}

