package org.cangnova.cangjie.cfir.analysis.tests.CfirAnalysisMacroPsiTest.macro.llt.unusedImport.unusedImport001.unused014

import com.intellij.testFramework.TestDataPath
import org.cangnova.cangjie.ObsoleteTestInfrastructure
import org.cangnova.cangjie.cfir.analysis.tests.runners.AbstractCfirPsiMacroDiagnosticsTest
import org.cangnova.cangjie.test.TestMetadata
import org.junit.jupiter.api.Test
import java.io.File
import org.cangnova.cangjie.cfir.analysis.tests.assertAllFilesPresentByMetadata

/** AUTO-GENERATED by TestGeneratorForCfirAnalysisTests. DO NOT EDIT MANUALLY. */
@TestMetadata("cfir/analysis-tests/testData/macro/llt/unusedImport/unusedImport001/unused014")
@TestDataPath("${'$'}PROJECT_ROOT")
@OptIn(ObsoleteTestInfrastructure::class)
@ObsoleteTestInfrastructure
class Unused014Generated : AbstractCfirPsiMacroDiagnosticsTest() {
    @Test
    fun testAllFilesPresent() {
        assertAllFilesPresentByMetadata(this, "cfir/analysis-tests/testData/macro/llt/unusedImport/unusedImport001/unused014")
    }

    @TestMetadata("unused.cj")
    @Test
    fun testUnused() {
        runTest("cfir/analysis-tests/testData/macro/llt/unusedImport/unusedImport001/unused014/unused.cj")
    }
}

