package org.cangnova.cangjie.cfir.analysis.tests.CfirAnalysisLLTPsiTest.llt.linkage

import com.intellij.testFramework.TestDataPath
import org.cangnova.cangjie.ObsoleteTestInfrastructure
import org.cangnova.cangjie.cfir.analysis.tests.runners.AbstractCfirPsiLlTDiagnosticsTest
import org.cangnova.cangjie.test.TestMetadata
import org.junit.jupiter.api.Test
import java.io.File
import org.cangnova.cangjie.cfir.analysis.tests.assertAllFilesPresentByMetadata

/** AUTO-GENERATED by TestGeneratorForCfirAnalysisTests. DO NOT EDIT MANUALLY. */
@TestMetadata("cfir/analysis-tests/testData/llt/linkage")
@TestDataPath("${'$'}PROJECT_ROOT")
@OptIn(ObsoleteTestInfrastructure::class)
@ObsoleteTestInfrastructure
class LinkageGenerated : AbstractCfirPsiLlTDiagnosticsTest() {
    @Test
    fun testAllFilesPresent() {
        assertAllFilesPresentByMetadata(this, "cfir/analysis-tests/testData/llt/linkage")
    }

    @TestMetadata("access01.cj")
    @Test
    fun testAccess01() {
        runTest("cfir/analysis-tests/testData/llt/linkage/access01.cj")
    }

    @TestMetadata("access02.cj")
    @Test
    fun testAccess02() {
        runTest("cfir/analysis-tests/testData/llt/linkage/access02.cj")
    }

    @TestMetadata("access_err.cj")
    @Test
    fun testAccessErr() {
        runTest("cfir/analysis-tests/testData/llt/linkage/access_err.cj")
    }

    @TestMetadata("base01.cj")
    @Test
    fun testBase01() {
        runTest("cfir/analysis-tests/testData/llt/linkage/base01.cj")
    }

    @TestMetadata("base02.cj")
    @Test
    fun testBase02() {
        runTest("cfir/analysis-tests/testData/llt/linkage/base02.cj")
    }
}

