package org.cangnova.cangjie.cfir.analysis.tests.CfirAnalysisLLTPsiTest.llt.operator.bitwise_operator

import com.intellij.testFramework.TestDataPath
import org.cangnova.cangjie.ObsoleteTestInfrastructure
import org.cangnova.cangjie.cfir.analysis.tests.runners.AbstractCfirPsiLlTDiagnosticsTest
import org.cangnova.cangjie.test.TestMetadata
import org.junit.jupiter.api.Test
import java.io.File
import org.cangnova.cangjie.cfir.analysis.tests.assertAllFilesPresentByMetadata

/** AUTO-GENERATED by TestGeneratorForCfirAnalysisTests. DO NOT EDIT MANUALLY. */
@TestMetadata("cfir/analysis-tests/testData/llt/operator/bitwise_operator")
@TestDataPath("${'$'}PROJECT_ROOT")
@OptIn(ObsoleteTestInfrastructure::class)
@ObsoleteTestInfrastructure
class BitwiseOperatorGenerated : AbstractCfirPsiLlTDiagnosticsTest() {
    @Test
    fun testAllFilesPresent() {
        assertAllFilesPresentByMetadata(this, "cfir/analysis-tests/testData/llt/operator/bitwise_operator")
    }

    @TestMetadata("bitwise_priority.cj")
    @Test
    fun testBitwisePriority() {
        runTest("cfir/analysis-tests/testData/llt/operator/bitwise_operator/bitwise_priority.cj")
    }

    @TestMetadata("bitwise_typematch.cj")
    @Test
    fun testBitwiseTypematch() {
        runTest("cfir/analysis-tests/testData/llt/operator/bitwise_operator/bitwise_typematch.cj")
    }

    @TestMetadata("bitwise_typeunmatch.cj")
    @Test
    fun testBitwiseTypeunmatch() {
        runTest("cfir/analysis-tests/testData/llt/operator/bitwise_operator/bitwise_typeunmatch.cj")
    }

    @TestMetadata("compound_assign.cj")
    @Test
    fun testCompoundAssign() {
        runTest("cfir/analysis-tests/testData/llt/operator/bitwise_operator/compound_assign.cj")
    }
}

