package org.cangnova.cangjie.cfir.analysis.tests.CfirAnalysisMacroTest.macro.diagnostics.annotation

import com.intellij.testFramework.TestDataPath
import org.cangnova.cangjie.ObsoleteTestInfrastructure
import org.cangnova.cangjie.cfir.analysis.tests.runners.AbstractCfirLightTreeMacroDiagnosticsTest
import org.cangnova.cangjie.test.TestMetadata
import org.junit.jupiter.api.Test
import java.io.File
import org.cangnova.cangjie.cfir.analysis.tests.assertAllFilesPresentByMetadata

/** AUTO-GENERATED by TestGeneratorForCfirAnalysisTests. DO NOT EDIT MANUALLY. */
@TestMetadata("cfir/analysis-tests/testData/macro/diagnostics/annotation")
@TestDataPath("${'$'}PROJECT_ROOT")
@OptIn(ObsoleteTestInfrastructure::class)
@ObsoleteTestInfrastructure
class AnnotationGenerated : AbstractCfirLightTreeMacroDiagnosticsTest() {
    @Test
    fun testAllFilesPresent() {
        assertAllFilesPresentByMetadata(this, "cfir/analysis-tests/testData/macro/diagnostics/annotation")
    }

    @TestMetadata("annotationNoConstInitRich.cj")
    @Test
    fun testAnnotationNoConstInitRich() {
        runTest("cfir/analysis-tests/testData/macro/diagnostics/annotation/annotationNoConstInitRich.cj")
    }
}

