package org.cangnova.cangjie.cfir.analysis.tests.CfirAnalysisMacroPsiTest.macro.llt.if_let_expr.enhancedcondition.libast

import com.intellij.testFramework.TestDataPath
import org.cangnova.cangjie.ObsoleteTestInfrastructure
import org.cangnova.cangjie.cfir.analysis.tests.runners.AbstractCfirPsiMacroDiagnosticsTest
import org.cangnova.cangjie.test.TestMetadata
import org.junit.jupiter.api.Test
import java.io.File
import org.cangnova.cangjie.cfir.analysis.tests.assertAllFilesPresentByMetadata

/** AUTO-GENERATED by TestGeneratorForCfirAnalysisTests. DO NOT EDIT MANUALLY. */
@TestMetadata("cfir/analysis-tests/testData/macro/llt/if-let-expr/enhancedcondition/libast")
@TestDataPath("${'$'}PROJECT_ROOT")
@OptIn(ObsoleteTestInfrastructure::class)
@ObsoleteTestInfrastructure
class LibastGenerated : AbstractCfirPsiMacroDiagnosticsTest() {
    @Test
    fun testAllFilesPresent() {
        assertAllFilesPresentByMetadata(this, "cfir/analysis-tests/testData/macro/llt/if-let-expr/enhancedcondition/libast")
    }

    @TestMetadata("letcond.cj")
    @Test
    fun testLetcond() {
        runTest("cfir/analysis-tests/testData/macro/llt/if-let-expr/enhancedcondition/libast/letcond.cj")
    }
}

