package org.cangnova.cangjie.cfir.analysis.tests.CfirAnalysisLLTTest.llt._return

import com.intellij.testFramework.TestDataPath
import org.cangnova.cangjie.ObsoleteTestInfrastructure
import org.cangnova.cangjie.cfir.analysis.tests.runners.AbstractCfirLightTreeLlTDiagnosticsTest
import org.cangnova.cangjie.test.TestMetadata
import org.junit.jupiter.api.Test
import java.io.File
import org.cangnova.cangjie.cfir.analysis.tests.assertAllFilesPresentByMetadata

/** AUTO-GENERATED by TestGeneratorForCfirAnalysisTests. DO NOT EDIT MANUALLY. */
@TestMetadata("cfir/analysis-tests/testData/llt/return")
@TestDataPath("${'$'}PROJECT_ROOT")
@OptIn(ObsoleteTestInfrastructure::class)
@ObsoleteTestInfrastructure
class ReturnGenerated : AbstractCfirLightTreeLlTDiagnosticsTest() {
    @Test
    fun testAllFilesPresent() {
        assertAllFilesPresentByMetadata(this, "cfir/analysis-tests/testData/llt/return")
    }

    @TestMetadata("return1.cj")
    @Test
    fun testReturn1() {
        runTest("cfir/analysis-tests/testData/llt/return/return1.cj")
    }

    @TestMetadata("return10.cj")
    @Test
    fun testReturn10() {
        runTest("cfir/analysis-tests/testData/llt/return/return10.cj")
    }

    @TestMetadata("return2.cj")
    @Test
    fun testReturn2() {
        runTest("cfir/analysis-tests/testData/llt/return/return2.cj")
    }

    @TestMetadata("return5.cj")
    @Test
    fun testReturn5() {
        runTest("cfir/analysis-tests/testData/llt/return/return5.cj")
    }

    @TestMetadata("return6.cj")
    @Test
    fun testReturn6() {
        runTest("cfir/analysis-tests/testData/llt/return/return6.cj")
    }

    @TestMetadata("return7.cj")
    @Test
    fun testReturn7() {
        runTest("cfir/analysis-tests/testData/llt/return/return7.cj")
    }

    @TestMetadata("return8.cj")
    @Test
    fun testReturn8() {
        runTest("cfir/analysis-tests/testData/llt/return/return8.cj")
    }

    @TestMetadata("return9.cj")
    @Test
    fun testReturn9() {
        runTest("cfir/analysis-tests/testData/llt/return/return9.cj")
    }
}

