package org.cangnova.cangjie.cfir.analysis.tests.CfirAnalysisLLTTest.llt.CompoundAssign.Logic

import com.intellij.testFramework.TestDataPath
import org.cangnova.cangjie.ObsoleteTestInfrastructure
import org.cangnova.cangjie.cfir.analysis.tests.runners.AbstractCfirLightTreeLlTDiagnosticsTest
import org.cangnova.cangjie.test.TestMetadata
import org.junit.jupiter.api.Test
import java.io.File
import org.cangnova.cangjie.cfir.analysis.tests.assertAllFilesPresentByMetadata

/** AUTO-GENERATED by TestGeneratorForCfirAnalysisTests. DO NOT EDIT MANUALLY. */
@TestMetadata("cfir/analysis-tests/testData/llt/CompoundAssign/Logic")
@TestDataPath("${'$'}PROJECT_ROOT")
@OptIn(ObsoleteTestInfrastructure::class)
@ObsoleteTestInfrastructure
class LogicGenerated : AbstractCfirLightTreeLlTDiagnosticsTest() {
    @Test
    fun testAllFilesPresent() {
        assertAllFilesPresentByMetadata(this, "cfir/analysis-tests/testData/llt/CompoundAssign/Logic")
    }

    @TestMetadata("logic01.cj")
    @Test
    fun testLogic01() {
        runTest("cfir/analysis-tests/testData/llt/CompoundAssign/Logic/logic01.cj")
    }

    @TestMetadata("logic02.cj")
    @Test
    fun testLogic02() {
        runTest("cfir/analysis-tests/testData/llt/CompoundAssign/Logic/logic02.cj")
    }

    @TestMetadata("logic03.cj")
    @Test
    fun testLogic03() {
        runTest("cfir/analysis-tests/testData/llt/CompoundAssign/Logic/logic03.cj")
    }
}

