package org.cangnova.cangjie.cfir.analysis.tests.CfirAnalysisDiagnosticsWithoutAliasExpansionTest.diagnostics.jump

import com.intellij.testFramework.TestDataPath
import org.cangnova.cangjie.ObsoleteTestInfrastructure
import org.cangnova.cangjie.cfir.analysis.tests.runners.AbstractCfirLightTreeDiagnosticsWithoutAliasExpansionTest
import org.cangnova.cangjie.test.TestMetadata
import org.junit.jupiter.api.Test
import java.io.File
import org.cangnova.cangjie.cfir.analysis.tests.assertAllFilesPresentByMetadata

/** AUTO-GENERATED by TestGeneratorForCfirAnalysisTests. DO NOT EDIT MANUALLY. */
@TestMetadata("cfir/analysis-tests/testData/diagnostics/jump")
@TestDataPath("${'$'}PROJECT_ROOT")
@OptIn(ObsoleteTestInfrastructure::class)
@ObsoleteTestInfrastructure
class JumpGenerated : AbstractCfirLightTreeDiagnosticsWithoutAliasExpansionTest() {
    @Test
    fun testAllFilesPresent() {
        assertAllFilesPresentByMetadata(this, "cfir/analysis-tests/testData/diagnostics/jump")
    }

    @TestMetadata("invalidLoopControlRich.cj")
    @Test
    fun testInvalidLoopControlRich() {
        runTest("cfir/analysis-tests/testData/diagnostics/jump/invalidLoopControlRich.cj")
    }

    @TestMetadata("invalidLoopControlTrailingLambdaRich.cj")
    @Test
    fun testInvalidLoopControlTrailingLambdaRich() {
        runTest("cfir/analysis-tests/testData/diagnostics/jump/invalidLoopControlTrailingLambdaRich.cj")
    }
}

