package org.cangnova.cangjie.analysis.api.impl.base.test

import org.cangnova.cangjie.analysis.test.framework.test.configurators.AnalysisApiMode
import org.cangnova.cangjie.analysis.test.framework.test.configurators.AnalysisApiTestConfiguratorFactoryData
import org.cangnova.cangjie.analysis.test.framework.test.configurators.AnalysisSessionMode
import org.cangnova.cangjie.analysis.test.framework.test.configurators.CaCfirAnalysisApiTestConfiguratorFactory
import org.cangnova.cangjie.analysis.test.framework.test.configurators.FrontendKind
import org.cangnova.cangjie.analysis.test.framework.test.configurators.TestModuleKind
import java.io.File

/**
 * Analysis API generated tests 生成器。
 *
 * 生成器本身只负责：
 * 1. 遍历 testData 目录；
 * 2. 将注册表中的矩阵展开成具体 runner；
 * 3. 输出到 `analysis-api-cfir/tests-gen`。
 *
 * 模型矩阵、模块种类和 configurator 可用性判定都交给注册表维护。
 */
object TestGeneratorForAnalysisApi {
    private const val generatedPackage = "org.cangnova.cangjie.analysis.api.cfir.test.cases.generated"
    const val generatedOutputRoot =
        "analysis/analysis-api-cfir/tests-gen/org/cangnova/cangjie/analysis/api/cfir/test/cases/generated"

    @JvmStatic
    fun main(args: Array<String>) {
        val projectRoot = if (args.isNotEmpty()) File(args[0]) else File(System.getProperty("user.dir"))
        generatedSuites(projectRoot).forEach { generatedFile ->
            generatedFile.outputFile.parentFile.mkdirs()
            generatedFile.outputFile.writeText(generatedFile.content, Charsets.UTF_8)
            println("Generated: ${generatedFile.outputFile.path}")
        }
    }

    /**
     * 生成当前注册表对应的全部 runner 文件快照。
     *
     * 该入口同时服务于代码生成与一致性校验任务，避免两套逻辑漂移。
     */
    fun generatedSuites(projectRoot: File): List<GeneratedAnalysisApiSuiteFile> {
        return buildList {
            GeneratedAnalysisApiTestRegistry.models.forEach { model ->
                model.supportedModuleKinds.forEach { moduleKind ->
                    GeneratedAnalysisApiTestRegistry.supportedVariantsFor(moduleKind).forEach { variant ->
                        add(buildSuite(projectRoot, model, moduleKind, variant))
                    }
                }
            }
        }
    }

    private fun buildSuite(
        projectRoot: File,
        model: GeneratedAnalysisApiModel,
        moduleKind: TestModuleKind,
        variant: GeneratedAnalysisApiVariant,
    ): GeneratedAnalysisApiSuiteFile {
        val testDataRoot = projectRoot.resolve(model.modelRelativePath)
        require(testDataRoot.isDirectory) { "testData root not found: ${testDataRoot.path}" }

        val generatedClassName = variant.generatedClassName(moduleKind, model.baseName)
        val outputFile = projectRoot.resolve("$generatedOutputRoot/$generatedClassName.kt")
        return GeneratedAnalysisApiSuiteFile(
            outputFile = outputFile,
            content = render(model, moduleKind, variant, testDataRoot, projectRoot, generatedClassName),
        )
    }

    private fun render(
        model: GeneratedAnalysisApiModel,
        moduleKind: TestModuleKind,
        variant: GeneratedAnalysisApiVariant,
        testDataRoot: File,
        projectRoot: File,
        generatedClassName: String,
    ): String = buildString {
        val abstractClassSimpleName = model.abstractClassQualifiedName.substringAfterLast('.')
        val patternLiteral = model.includedFilePattern(moduleKind).replace("\\", "\\\\")

        appendLine("package $generatedPackage")
        appendLine()
        appendLine("import org.cangnova.cangjie.analysis.test.framework.test.configurators.AnalysisApiMode")
        appendLine("import org.cangnova.cangjie.analysis.test.framework.test.configurators.AnalysisApiTestConfiguratorFactoryData")
        appendLine("import org.cangnova.cangjie.analysis.test.framework.test.configurators.AnalysisSessionMode")
        appendLine("import org.cangnova.cangjie.analysis.test.framework.test.configurators.CaCfirAnalysisApiTestConfiguratorFactory")
        appendLine("import org.cangnova.cangjie.analysis.test.framework.test.configurators.FrontendKind")
        appendLine("import org.cangnova.cangjie.analysis.test.framework.test.configurators.TestModuleKind")
        appendLine("import org.cangnova.cangjie.test.TestMetadata")
        appendLine("import org.cangnova.cangjie.test.util.CjTestUtil")
        appendLine("import org.junit.jupiter.api.Nested")
        appendLine("import org.junit.jupiter.api.Test")
        appendLine("import java.io.File")
        appendLine("import java.util.regex.Pattern")
        appendLine("import ${model.abstractClassQualifiedName}")
        appendLine()
        appendLine("/** AUTO-GENERATED by TestGeneratorForAnalysisApi. DO NOT EDIT MANUALLY. */")
        appendLine("@TestMetadata(\"${model.modelRelativePath}\")")
        appendLine("class $generatedClassName : $abstractClassSimpleName() {")
        appendLine("    override val configurator = CaCfirAnalysisApiTestConfiguratorFactory.createConfigurator(")
        appendLine("        AnalysisApiTestConfiguratorFactoryData(")
        appendLine("            frontend = FrontendKind.${variant.frontend.name},")
        appendLine("            moduleKind = TestModuleKind.${moduleKind.name},")
        appendLine("            analysisSessionMode = AnalysisSessionMode.${variant.analysisSessionMode.name},")
        appendLine("            analysisApiMode = AnalysisApiMode.${variant.analysisApiMode.name},")
        appendLine("        ),")
        appendLine("    )")
        appendLine()
        appendLine("    @Test")
        appendLine("    fun testAllFilesPresentInModel() {")
        appendLine("        CjTestUtil.assertAllTestsPresentByMetadata(")
        appendLine("            this::class.java,")
        appendLine("            File(\"${model.modelRelativePath}\"),")
        appendLine("            Pattern.compile(\"$patternLiteral\"),")
        appendLine("            true,")
        appendLine("        )")
        appendLine("    }")

        renderDirectoryContent(
            builder = this,
            directory = testDataRoot,
            projectRoot = projectRoot,
            variant = variant,
            model = model,
            moduleKind = moduleKind,
            abstractClassSimpleName = abstractClassSimpleName,
            includedFileRegex = Regex(model.includedFilePattern(moduleKind)),
            includePatternLiteral = patternLiteral,
            indent = "    ",
        )

        appendLine("}")
    }

    private fun renderDirectoryContent(
        builder: StringBuilder,
        directory: File,
        projectRoot: File,
        variant: GeneratedAnalysisApiVariant,
        model: GeneratedAnalysisApiModel,
        moduleKind: TestModuleKind,
        abstractClassSimpleName: String,
        includedFileRegex: Regex,
        includePatternLiteral: String,
        indent: String,
    ) {
        val files = directory.listFiles().orEmpty()
            .filter { it.isFile && includedFileRegex.matches(it.name) }
            .sortedBy { it.name }
        val directories = directory.listFiles().orEmpty()
            .filter { file -> file.isDirectory && directoryContainsIncludedFiles(file, includedFileRegex) }
            .sortedBy { it.name }

        files.forEach { file ->
            val testName = "test" + sanitizeIdentifier(
                file.relativeTo(directory).path.substringBeforeLast('.').replace('\\', '_').replace('/', '_'),
            )
            val relativePath = projectRoot.toPath().relativize(file.toPath()).toString().replace('\\', '/')
            builder.appendLine()
            builder.appendLine("${indent}@TestMetadata(\"${file.name}\")")
            builder.appendLine("${indent}@Test")
            builder.appendLine("${indent}fun $testName() {")
            builder.appendLine("${indent}    runTest(\"$relativePath\")")
            builder.appendLine("${indent}}")
        }

        directories.forEach { subdirectory ->
            val nestedClassName = sanitizeIdentifier(subdirectory.name)
            val relativeDirectoryPath = projectRoot.toPath().relativize(subdirectory.toPath()).toString().replace('\\', '/')
            builder.appendLine()
            builder.appendLine("${indent}@TestMetadata(\"$relativeDirectoryPath\")")
            builder.appendLine("${indent}@Nested")
            builder.appendLine("${indent}inner class $nestedClassName : $abstractClassSimpleName() {")
            builder.appendLine("${indent}    override val configurator = CaCfirAnalysisApiTestConfiguratorFactory.createConfigurator(")
            builder.appendLine("${indent}        AnalysisApiTestConfiguratorFactoryData(")
            builder.appendLine("${indent}            frontend = FrontendKind.${variant.frontend.name},")
            builder.appendLine("${indent}            moduleKind = TestModuleKind.${moduleKind.name},")
            builder.appendLine("${indent}            analysisSessionMode = AnalysisSessionMode.${variant.analysisSessionMode.name},")
            builder.appendLine("${indent}            analysisApiMode = AnalysisApiMode.${variant.analysisApiMode.name},")
            builder.appendLine("${indent}        ),")
            builder.appendLine("${indent}    )")
            builder.appendLine()
            builder.appendLine("${indent}    @Test")
            builder.appendLine("${indent}    fun testAllFilesPresentIn$nestedClassName() {")
            builder.appendLine("${indent}        CjTestUtil.assertAllTestsPresentByMetadata(")
            builder.appendLine("${indent}            this::class.java,")
            builder.appendLine("${indent}            File(\"$relativeDirectoryPath\"),")
            builder.appendLine("${indent}            Pattern.compile(\"$includePatternLiteral\"),")
            builder.appendLine("${indent}            true,")
            builder.appendLine("${indent}        )")
            builder.appendLine("${indent}    }")

            renderDirectoryContent(
                builder = builder,
                directory = subdirectory,
                projectRoot = projectRoot,
                variant = variant,
                model = model,
                moduleKind = moduleKind,
                abstractClassSimpleName = abstractClassSimpleName,
                includedFileRegex = includedFileRegex,
                includePatternLiteral = includePatternLiteral,
                indent = "$indent    ",
            )

            builder.appendLine("${indent}}")
        }
    }

    private fun sanitizeIdentifier(raw: String): String {
        val pascal = raw
            .split(Regex("[^A-Za-z0-9]+"))
            .filter { it.isNotBlank() }
            .joinToString("") { token -> token.replaceFirstChar { ch -> ch.uppercaseChar() } }
        return pascal.ifBlank { "Generated" }
    }

    private fun directoryContainsIncludedFiles(directory: File, includedFileRegex: Regex): Boolean {
        return directory.walkTopDown().any { file -> file.isFile && includedFileRegex.matches(file.name) }
    }
}

/**
 * generated test runner 的期望产物快照。
 */
data class GeneratedAnalysisApiSuiteFile(
    val outputFile: File,
    val content: String,
)
