// Copyright (c) Huawei Technologies Co., Ltd. 2025. All rights reserved.
// This source file is part of the Cangjie project, licensed under Apache-2.0
// with Runtime Library Exception.
//
// See https://cangjie-lang.cn/pages/LICENSE for license information.

func function44(): Unit {
    {
        =>
        func foo() {}
        ((), 32);
    }()[0];
}

main(): Int64 {
    function44()
    return 0;
}
