package org.cangnova.cangjie.cfir.analysis.tests.CfirAnalysisLLTPsiTest.llt.Extend.generic_param_decl_call_in_member_func

import com.intellij.testFramework.TestDataPath
import org.cangnova.cangjie.ObsoleteTestInfrastructure
import org.cangnova.cangjie.cfir.analysis.tests.runners.AbstractCfirPsiLlTDiagnosticsTest
import org.cangnova.cangjie.test.TestMetadata
import org.junit.jupiter.api.Test
import java.io.File
import org.cangnova.cangjie.cfir.analysis.tests.assertAllFilesPresentByMetadata

/** AUTO-GENERATED by TestGeneratorForCfirAnalysisTests. DO NOT EDIT MANUALLY. */
@TestMetadata("cfir/analysis-tests/testData/llt/Extend/generic_param_decl_call_in_member_func")
@TestDataPath("${'$'}PROJECT_ROOT")
@OptIn(ObsoleteTestInfrastructure::class)
@ObsoleteTestInfrastructure
class GenericParamDeclCallInMemberFuncGenerated : AbstractCfirPsiLlTDiagnosticsTest() {
    @Test
    fun testAllFilesPresent() {
        assertAllFilesPresentByMetadata(this, "cfir/analysis-tests/testData/llt/Extend/generic_param_decl_call_in_member_func")
    }

    @TestMetadata("generics_00012.cj")
    @Test
    fun testGenerics00012() {
        runTest("cfir/analysis-tests/testData/llt/Extend/generic_param_decl_call_in_member_func/generics_00012.cj")
    }

    @TestMetadata("generics_00035.cj")
    @Test
    fun testGenerics00035() {
        runTest("cfir/analysis-tests/testData/llt/Extend/generic_param_decl_call_in_member_func/generics_00035.cj")
    }

    @TestMetadata("generics_00038.cj")
    @Test
    fun testGenerics00038() {
        runTest("cfir/analysis-tests/testData/llt/Extend/generic_param_decl_call_in_member_func/generics_00038.cj")
    }

    @TestMetadata("generics_00051.cj")
    @Test
    fun testGenerics00051() {
        runTest("cfir/analysis-tests/testData/llt/Extend/generic_param_decl_call_in_member_func/generics_00051.cj")
    }

    @TestMetadata("generics_00065.cj")
    @Test
    fun testGenerics00065() {
        runTest("cfir/analysis-tests/testData/llt/Extend/generic_param_decl_call_in_member_func/generics_00065.cj")
    }

    @TestMetadata("generics_00100.cj")
    @Test
    fun testGenerics00100() {
        runTest("cfir/analysis-tests/testData/llt/Extend/generic_param_decl_call_in_member_func/generics_00100.cj")
    }

    @TestMetadata("same_sign_default_in_multi_extend_impl01.cj")
    @Test
    fun testSameSignDefaultInMultiExtendImpl01() {
        runTest("cfir/analysis-tests/testData/llt/Extend/generic_param_decl_call_in_member_func/same_sign_default_in_multi_extend_impl01.cj")
    }

    @TestMetadata("same_sign_default_in_multi_extend_impl02.cj")
    @Test
    fun testSameSignDefaultInMultiExtendImpl02() {
        runTest("cfir/analysis-tests/testData/llt/Extend/generic_param_decl_call_in_member_func/same_sign_default_in_multi_extend_impl02.cj")
    }
}

