package org.cangnova.cangjie.cfir.analysis.tests.CfirAnalysisLLTPsiTest.llt.main.mod_files_main_06_1_c

import com.intellij.testFramework.TestDataPath
import org.cangnova.cangjie.ObsoleteTestInfrastructure
import org.cangnova.cangjie.cfir.analysis.tests.runners.AbstractCfirPsiLlTDiagnosticsTest
import org.cangnova.cangjie.test.TestMetadata
import org.junit.jupiter.api.Test
import java.io.File
import org.cangnova.cangjie.cfir.analysis.tests.assertAllFilesPresentByMetadata

/** AUTO-GENERATED by TestGeneratorForCfirAnalysisTests. DO NOT EDIT MANUALLY. */
@TestMetadata("cfir/analysis-tests/testData/llt/main/mod_files_main_06_1_c")
@TestDataPath("${'$'}PROJECT_ROOT")
@OptIn(ObsoleteTestInfrastructure::class)
@ObsoleteTestInfrastructure
class ModFilesMain061CGenerated : AbstractCfirPsiLlTDiagnosticsTest() {
    @Test
    fun testAllFilesPresent() {
        assertAllFilesPresentByMetadata(this, "cfir/analysis-tests/testData/llt/main/mod_files_main_06_1_c")
    }
}

