package org.cangnova.cangjie.cfir.analysis.tests.CfirAnalysisLLTPsiTest.llt._class.static_init

import com.intellij.testFramework.TestDataPath
import org.cangnova.cangjie.ObsoleteTestInfrastructure
import org.cangnova.cangjie.cfir.analysis.tests.runners.AbstractCfirPsiLlTDiagnosticsTest
import org.cangnova.cangjie.test.TestMetadata
import org.junit.jupiter.api.Test
import java.io.File
import org.cangnova.cangjie.cfir.analysis.tests.assertAllFilesPresentByMetadata

/** AUTO-GENERATED by TestGeneratorForCfirAnalysisTests. DO NOT EDIT MANUALLY. */
@TestMetadata("cfir/analysis-tests/testData/llt/class/static_init")
@TestDataPath("${'$'}PROJECT_ROOT")
@OptIn(ObsoleteTestInfrastructure::class)
@ObsoleteTestInfrastructure
class StaticInitGenerated : AbstractCfirPsiLlTDiagnosticsTest() {
    @Test
    fun testAllFilesPresent() {
        assertAllFilesPresentByMetadata(this, "cfir/analysis-tests/testData/llt/class/static_init")
    }

    @TestMetadata("static_init_01.cj")
    @Test
    fun testStaticInit01() {
        runTest("cfir/analysis-tests/testData/llt/class/static_init/static_init_01.cj")
    }

    @TestMetadata("static_init_01_O2.cj")
    @Test
    fun testStaticInit01O2() {
        runTest("cfir/analysis-tests/testData/llt/class/static_init/static_init_01_O2.cj")
    }

    @TestMetadata("static_init_02.cj")
    @Test
    fun testStaticInit02() {
        runTest("cfir/analysis-tests/testData/llt/class/static_init/static_init_02.cj")
    }

    @TestMetadata("static_init_03.cj")
    @Test
    fun testStaticInit03() {
        runTest("cfir/analysis-tests/testData/llt/class/static_init/static_init_03.cj")
    }

    @TestMetadata("static_init_04.cj")
    @Test
    fun testStaticInit04() {
        runTest("cfir/analysis-tests/testData/llt/class/static_init/static_init_04.cj")
    }

    @TestMetadata("static_init_05.cj")
    @Test
    fun testStaticInit05() {
        runTest("cfir/analysis-tests/testData/llt/class/static_init/static_init_05.cj")
    }
}

