package org.cangnova.cangjie.cfir.analysis.tests.CfirAnalysisDiagnosticsWithoutAliasExpansionTest.diagnostics.initialization

import com.intellij.testFramework.TestDataPath
import org.cangnova.cangjie.ObsoleteTestInfrastructure
import org.cangnova.cangjie.cfir.analysis.tests.runners.AbstractCfirLightTreeDiagnosticsWithoutAliasExpansionTest
import org.cangnova.cangjie.test.TestMetadata
import org.junit.jupiter.api.Test
import java.io.File
import org.cangnova.cangjie.cfir.analysis.tests.assertAllFilesPresentByMetadata

/** AUTO-GENERATED by TestGeneratorForCfirAnalysisTests. DO NOT EDIT MANUALLY. */
@TestMetadata("cfir/analysis-tests/testData/diagnostics/initialization")
@TestDataPath("${'$'}PROJECT_ROOT")
@OptIn(ObsoleteTestInfrastructure::class)
@ObsoleteTestInfrastructure
class InitializationGenerated : AbstractCfirLightTreeDiagnosticsWithoutAliasExpansionTest() {
    @Test
    fun testAllFilesPresent() {
        assertAllFilesPresentByMetadata(this, "cfir/analysis-tests/testData/diagnostics/initialization")
    }

    @TestMetadata("classUninitializedFieldRich.cj")
    @Test
    fun testClassUninitializedFieldRich() {
        runTest("cfir/analysis-tests/testData/diagnostics/initialization/classUninitializedFieldRich.cj")
    }

    @TestMetadata("controlFlowInitializationRich.cj")
    @Test
    fun testControlFlowInitializationRich() {
        runTest("cfir/analysis-tests/testData/diagnostics/initialization/controlFlowInitializationRich.cj")
    }

    @TestMetadata("tryCatchInitializationSmoke.cj")
    @Test
    fun testTryCatchInitializationSmoke() {
        runTest("cfir/analysis-tests/testData/diagnostics/initialization/tryCatchInitializationSmoke.cj")
    }

    @TestMetadata("usedBeforeInitializationRich.cj")
    @Test
    fun testUsedBeforeInitializationRich() {
        runTest("cfir/analysis-tests/testData/diagnostics/initialization/usedBeforeInitializationRich.cj")
    }
}

