package org.cangnova.cangjie.cfir.analysis.tests.CfirAnalysisLLTTest.llt.Extend.visibility.default_other_pkg_child_class

import com.intellij.testFramework.TestDataPath
import org.cangnova.cangjie.ObsoleteTestInfrastructure
import org.cangnova.cangjie.cfir.analysis.tests.runners.AbstractCfirLightTreeLlTDiagnosticsTest
import org.cangnova.cangjie.test.TestMetadata
import org.junit.jupiter.api.Test
import java.io.File
import org.cangnova.cangjie.cfir.analysis.tests.assertAllFilesPresentByMetadata

/** AUTO-GENERATED by TestGeneratorForCfirAnalysisTests. DO NOT EDIT MANUALLY. */
@TestMetadata("cfir/analysis-tests/testData/llt/Extend/visibility/default_other_pkg_child_class")
@TestDataPath("${'$'}PROJECT_ROOT")
@OptIn(ObsoleteTestInfrastructure::class)
@ObsoleteTestInfrastructure
class DefaultOtherPkgChildClassGenerated : AbstractCfirLightTreeLlTDiagnosticsTest() {
    @Test
    fun testAllFilesPresent() {
        assertAllFilesPresentByMetadata(this, "cfir/analysis-tests/testData/llt/Extend/visibility/default_other_pkg_child_class")
    }

    @TestMetadata("main.cj")
    @Test
    fun testMain() {
        runTest("cfir/analysis-tests/testData/llt/Extend/visibility/default_other_pkg_child_class/main.cj")
    }
}

