package org.cangnova.cangjie.cfir.analysis.tests.CfirAnalysisLLTPsiTest.llt.record.constructor.call_other_init

import com.intellij.testFramework.TestDataPath
import org.cangnova.cangjie.ObsoleteTestInfrastructure
import org.cangnova.cangjie.cfir.analysis.tests.runners.AbstractCfirPsiLlTDiagnosticsTest
import org.cangnova.cangjie.test.TestMetadata
import org.junit.jupiter.api.Test
import java.io.File
import org.cangnova.cangjie.cfir.analysis.tests.assertAllFilesPresentByMetadata

/** AUTO-GENERATED by TestGeneratorForCfirAnalysisTests. DO NOT EDIT MANUALLY. */
@TestMetadata("cfir/analysis-tests/testData/llt/record/constructor/call_other_init")
@TestDataPath("${'$'}PROJECT_ROOT")
@OptIn(ObsoleteTestInfrastructure::class)
@ObsoleteTestInfrastructure
class CallOtherInitGenerated : AbstractCfirPsiLlTDiagnosticsTest() {
    @Test
    fun testAllFilesPresent() {
        assertAllFilesPresentByMetadata(this, "cfir/analysis-tests/testData/llt/record/constructor/call_other_init")
    }

    @TestMetadata("record_constructor_call_other_init01.cj")
    @Test
    fun testRecordConstructorCallOtherInit01() {
        runTest("cfir/analysis-tests/testData/llt/record/constructor/call_other_init/record_constructor_call_other_init01.cj")
    }

    @TestMetadata("record_constructor_call_other_init02.cj")
    @Test
    fun testRecordConstructorCallOtherInit02() {
        runTest("cfir/analysis-tests/testData/llt/record/constructor/call_other_init/record_constructor_call_other_init02.cj")
    }
}

