package org.cangnova.cangjie.cfir.analysis.tests.CfirAnalysisDiagnostics2WithoutAliasExpansionTest.diagnostics2.enum

import com.intellij.testFramework.TestDataPath
import org.cangnova.cangjie.ObsoleteTestInfrastructure
import org.cangnova.cangjie.cfir.analysis.tests.runners.AbstractCfirLightTreeDiagnosticsWithoutAliasExpansionTest
import org.cangnova.cangjie.test.TestMetadata
import org.junit.jupiter.api.Test
import java.io.File
import org.cangnova.cangjie.cfir.analysis.tests.assertAllFilesPresentByMetadata

/** AUTO-GENERATED by TestGeneratorForCfirAnalysisTests. DO NOT EDIT MANUALLY. */
@TestMetadata("cfir/analysis-tests/testData/diagnostics2/enum")
@TestDataPath("${'$'}PROJECT_ROOT")
@OptIn(ObsoleteTestInfrastructure::class)
@ObsoleteTestInfrastructure
class EnumGenerated : AbstractCfirLightTreeDiagnosticsWithoutAliasExpansionTest() {
    @Test
    fun testAllFilesPresent() {
        assertAllFilesPresentByMetadata(this, "cfir/analysis-tests/testData/diagnostics2/enum")
    }

    @TestMetadata("errorSimpleEnum.cj")
    @Test
    fun testErrorSimpleEnum() {
        runTest("cfir/analysis-tests/testData/diagnostics2/enum/errorSimpleEnum.cj")
    }

    @TestMetadata("noErrorSimpleEnum.cj")
    @Test
    fun testNoErrorSimpleEnum() {
        runTest("cfir/analysis-tests/testData/diagnostics2/enum/noErrorSimpleEnum.cj")
    }
}

