package org.cangnova.cangjie.cfir.analysis.tests.CfirAnalysisLLTPsiTest.llt.functionlinkage

import com.intellij.testFramework.TestDataPath
import org.cangnova.cangjie.ObsoleteTestInfrastructure
import org.cangnova.cangjie.cfir.analysis.tests.runners.AbstractCfirPsiLlTDiagnosticsTest
import org.cangnova.cangjie.test.TestMetadata
import org.junit.jupiter.api.Test
import java.io.File
import org.cangnova.cangjie.cfir.analysis.tests.assertAllFilesPresentByMetadata

/** AUTO-GENERATED by TestGeneratorForCfirAnalysisTests. DO NOT EDIT MANUALLY. */
@TestMetadata("cfir/analysis-tests/testData/llt/functionlinkage")
@TestDataPath("${'$'}PROJECT_ROOT")
@OptIn(ObsoleteTestInfrastructure::class)
@ObsoleteTestInfrastructure
class FunctionlinkageGenerated : AbstractCfirPsiLlTDiagnosticsTest() {
    @Test
    fun testAllFilesPresent() {
        assertAllFilesPresentByMetadata(this, "cfir/analysis-tests/testData/llt/functionlinkage")
    }

    @TestMetadata("internal_inline.cj")
    @Test
    fun testInternalInline() {
        runTest("cfir/analysis-tests/testData/llt/functionlinkage/internal_inline.cj")
    }

    @TestMetadata("member_used_internal.cj")
    @Test
    fun testMemberUsedInternal() {
        runTest("cfir/analysis-tests/testData/llt/functionlinkage/member_used_internal.cj")
    }

    @TestMetadata("ok_no_sub_pkg_00.cj")
    @Test
    fun testOkNoSubPkg00() {
        runTest("cfir/analysis-tests/testData/llt/functionlinkage/ok_no_sub_pkg_00.cj")
    }
}

